export const wordsLesson254 = [
  [
    {
      id: 1,
      word: 'fall apart',
      transcription: 'fɔːl əˈpɑːt',
      translation: 'развалиться',
    },
    {
      id: 2,
      word: 'hold back',
      transcription: 'həʊld bæk',
      translation: 'сдерживать',
    },
    {
      id: 3,
      word: 'hack into',
      transcription: 'hæk ˈɪntuː',
      translation: 'взломать',
    },
    {
      id: 4,
      word: 'speed up',
      transcription: 'spiːd ʌp',
      translation: 'ускорить',
    },
    {
      id: 5,
      word: 'stick to',
      transcription: 'stɪk tuː',
      translation: 'придерживаться',
    },
    {
      id: 6,
      word: 'hold on',
      transcription: 'həʊld ɒn',
      translation: 'ждать',
    },
    {
      id: 7,
      word: 'polish up',
      transcription: 'ˈpɒlɪʃ ʌp',
      translation: 'усовершенствовать',
    },
    {
      id: 8,
      word: 'go over',
      transcription: 'ɡəʊ ˈəʊvə',
      translation: 'повторить, пройти',
    },
    {
      id: 9,
      word: 'settle down',
      transcription: 'ˈsɛtl daʊn',
      translation: 'остепениться',
    },
    {
      id: 10,
      word: 'anticipation',
      transcription: 'ænˌtɪsɪˈpeɪʃᵊn',
      translation: 'предвкушение',
    },
    {
      id: 11,
      word: 'central',
      transcription: 'ˈsɛntrəl',
      translation: 'центральный',
    },
    {
      id: 12,
      word: 'database',
      transcription: 'ˈdeɪtəˌbeɪs',
      translation: 'база данных',
    },
    {
      id: 13,
      word: 'gang',
      transcription: 'ɡæŋ',
      translation: 'банда',
    },
    {
      id: 14,
      word: 'junction',
      transcription: 'ˈʤʌŋkʃᵊn',
      translation: 'перекресток',
    },
    {
      id: 15,
      word: 'preference',
      transcription: 'ˈprɛfərəns',
      translation: 'предпочтение',
    },
    {
      id: 16,
      word: 'registration',
      transcription: 'ˌrɛʤɪsˈtreɪʃᵊn',
      translation: 'регистрация',
    },
    {
      id: 17,
      word: 'sunshine',
      transcription: 'ˈsʌnʃaɪn',
      translation: 'солнечный свет',
    },
    {
      id: 18,
      word: 'unlimited',
      transcription: 'ʌnˈlɪmɪtɪd',
      translation: 'неограниченный',
    },
    {
      id: 19,
      word: 'unprofitable',
      transcription: 'ʌnˈprɒfɪtəbᵊl',
      translation: 'убыточный, неприбыльный',
    },
    {
      id: 20,
      word: 'willpower',
      transcription: 'ˈwɪlˌpaʊə',
      translation: 'сила воли',
    },
  ],
];
