export const wordsLesson212 = [
  [
    {
      id: 1,
      word: 'benefit',
      transcription: 'ˈbɛnɪfɪt',
      translation: 'выгода',
    },
    {
      id: 2,
      word: 'beware',
      transcription: 'bɪˈweə',
      translation: 'остерегаться',
    },
    {
      id: 3,
      word: 'ceaseless',
      transcription: 'ˈsiːslɪs',
      translation: 'непрестанный',
    },
    {
      id: 4,
      word: 'confidential',
      transcription: 'ˌkɒnfɪˈdɛnʃəl',
      translation: 'конфиденциальный',
    },
    {
      id: 5,
      word: 'creativity',
      transcription: 'ˌkriːeɪˈtɪvɪti',
      translation: 'креативность',
    },
    {
      id: 6,
      word: 'depth',
      transcription: 'dɛpθ',
      translation: 'глубина',
    },
    {
      id: 7,
      word: 'erudition',
      transcription: 'ˌɛru(ː)ˈdɪʃᵊn',
      translation: 'эрудиция',
    },
    {
      id: 8,
      word: 'fragrance',
      transcription: 'ˈfreɪɡrəns',
      translation: 'аромат',
    },
    {
      id: 9,
      word: 'garlic',
      transcription: 'ˈɡɑːlɪk',
      translation: 'чеснок',
    },
    {
      id: 10,
      word: 'hasty',
      transcription: 'ˈheɪsti',
      translation: 'поспешный',
    },
    {
      id: 11,
      word: 'impressed',
      transcription: 'ɪmˈprɛst',
      translation: 'впечатлен',
    },
    {
      id: 12,
      word: 'incredibly',
      transcription: 'ɪnˈkrɛdəbli',
      translation: 'невероятный',
    },
    {
      id: 13,
      word: 'panoramic',
      transcription: 'ˌpænəˈræmɪk',
      translation: 'панорамный',
    },
    {
      id: 14,
      word: 'perfume',
      transcription: 'ˈpɜːfjuːm',
      translation: 'парфюм',
    },
    {
      id: 15,
      word: 'protect',
      transcription: 'prəˈtɛkt',
      translation: 'защищать',
    },
    {
      id: 16,
      word: 'raspberry',
      transcription: 'ˈrɑːzbəri',
      translation: 'малина',
    },
    {
      id: 17,
      word: 'slippery',
      transcription: 'ˈslɪpəri',
      translation: 'скользкий',
    },
    {
      id: 18,
      word: 'strength',
      transcription: 'strɛŋθ',
      translation: 'сила',
    },
    {
      id: 19,
      word: 'truly',
      transcription: 'ˈtruːli',
      translation: 'действительно',
    },
  ],
];
