export const wordsLesson10 = [
  [
    {
      id: 1,
      word: 'actor',
      transcription: 'ˈæktə',
      translation: 'актер',
    },
    {
      id: 2,
      word: 'actress',
      transcription: 'ˈæktrɪs',
      translation: 'актриса',
    },
    {
      id: 3,
      word: 'change',
      transcription: 'ʧeɪnʤ',
      translation: 'менять',
    },
    {
      id: 4,
      word: 'cheap',
      transcription: 'ʧiːp',
      translation: 'дешевый',
    },
    {
      id: 5,
      word: 'discuss',
      transcription: 'dɪsˈkʌs',
      translation: 'обсуждать',
    },
    {
      id: 6,
      word: 'expensive',
      transcription: 'ɪksˈpɛnsɪv',
      translation: 'дорогой',
    },
    {
      id: 7,
      word: 'five',
      transcription: 'faɪv',
      translation: 'пять',
    },
    {
      id: 8,
      word: 'forty',
      transcription: 'ˈfɔːti',
      translation: 'сорок',
    },
    {
      id: 9,
      word: 'from',
      transcription: 'frɒm',
      translation: 'от, из',
    },
    {
      id: 10,
      word: 'one hundred',
      transcription: 'wʌn ˈhʌndrəd',
      translation: 'сто',
    },
    {
      id: 11,
      word: 'important',
      transcription: 'ɪmˈpɔːtənt',
      translation: 'важный',
    },
    {
      id: 12,
      word: 'listen to',
      transcription: 'ˈlɪsn tʊ',
      translation: 'слушать',
    },
    {
      id: 13,
      word: 'look',
      transcription: 'lʊk',
      translation: 'смотреть',
    },
    {
      id: 14,
      word: 'method',
      transcription: 'ˈmɛθəd',
      translation: 'метод',
    },
    {
      id: 15,
      word: 'phone',
      transcription: 'fəʊn',
      translation: 'телефон',
    },
    {
      id: 16,
      word: 'seem',
      transcription: 'siːm',
      translation: 'казаться',
    },
    {
      id: 17,
      word: 'seven',
      transcription: 'ˈsɛvn',
      translation: 'семь',
    },
    {
      id: 18,
      word: 'strange',
      transcription: 'streɪnʤ',
      translation: 'странный',
    },
    {
      id: 19,
      word: 'than',
      transcription: 'ðæn',
      translation: 'чем',
    },
    {
      id: 20,
      word: 'thirty',
      transcription: 'ˈθɜːti',
      translation: 'тридцать',
    },
    {
      id: 21,
      word: 'thousand',
      transcription: 'ˈθaʊzənd',
      translation: 'тысяча',
    },
  ],
];
