export const wordsLesson5 = [
  [
    { id: 1, word: 'be', transcription: 'biː', translation: 'быть', },
    {
      id: 2,
      word: 'become',
      transcription: 'bɪˈkʌm',
      translation: 'становиться',
    },
    {
      id: 3,
      word: 'businessman',
      transcription: 'ˈbɪznɪsmən',
      translation: 'бизнесмен',
    },
    {
      id: 4,
      word: 'correctly',
      transcription: 'kəˈrɛktli',
      translation: 'правильно',
    },
    {
      id: 5,
      word: 'designer',
      transcription: 'dɪˈzaɪnə',
      translation: 'дизайнер',
    },
    {
      id: 6,
      word: 'doctor',
      transcription: 'ˈdɒktə',
      translation: 'доктор',
    },
    {
      id: 7,
      word: 'fluently',
      transcription: 'ˈflu(ː)əntli',
      translation: 'бегло',
    },
    {
      id: 8,
      word: 'happy',
      transcription: 'ˈhæpi',
      translation: 'счастливый',
    },
    { id: 9, word: 'her', transcription: 'hɜː', translation: 'ей' },
    {
      id: 10,
      word: 'him',
      transcription: 'hɪm',
      translation: 'ему',
    },
    {
      id: 11,
      word: 'manager',
      transcription: 'ˈmænɪʤə',
      translation: 'менеджер',
    },
    {
      id: 12,
      word: 'new',
      transcription: 'njuː',
      translation: 'новый',
    },
    {
      id: 13,
      word: 'now',
      transcription: 'naʊ',
      translation: 'сейчас',
    },
    {
      id: 14,
      word: 'programmer',
      transcription: 'ˈprəʊgræmə',
      translation: 'программист',
    },
    {
      id: 15,
      word: 'them',
      transcription: 'ðɛm',
      translation: 'их, им',
    },
    {
      id: 16,
      word: 'visit',
      transcription: 'ˈvɪzɪt',
      translation: 'посещать',
    },
    {
      id: 17,
      word: 'without',
      transcription: 'wɪˈðaʊt',
      translation: 'без',
    },
    {
      id: 18,
      word: 'would',
      transcription: 'wʊd',
      translation: 'бы',
    },
    {
      id: 19,
      word: 'abroad',
      transcription: 'əˈbrɔːd',
      translation: 'за границей',
    },
    {
      id: 20,
      word: 'China',
      transcription: 'ˈʧaɪnə',
      translation: 'Китай',
    },
    {
      id: 21,
      word: 'England',
      transcription: 'ˈɪŋglənd',
      translation: 'Англия',
    },
    {
      id: 22,
      word: 'father',
      transcription: 'ˈfɑːðə',
      translation: 'отец',
    },
    {
      id: 23,
      word: 'Germany',
      transcription: 'ˈʤɜːməni',
      translation: 'Германия',
    },
    {
      id: 24,
      word: 'his',
      transcription: 'hɪz',
      translation: 'его',
    },
    {
      id: 25,
      word: 'Italy',
      transcription: 'ˈɪtəli',
      translation: 'Италия',
    },
    {
      id: 26,
      word: 'Japan',
      transcription: 'ʤəˈpæn',
      translation: 'Япония',
    },
    {
      id: 27,
      word: 'month',
      transcription: 'mʌnθ',
      translation: 'месяц',
    },
    {
      id: 28,
      word: 'mother',
      transcription: 'ˈmʌðə',
      translation: 'мама',
    },
    {
      id: 29,
      word: 'next',
      transcription: 'nɛkst',
      translation: 'следующий',
    },
    {
      id: 30,
      word: 'the United States',
      transcription: 'ðə jʊˈnaɪtɪd steɪts',
      translation: 'Соединенные Штаты',
    },
    {
      id: 31,
      word: 'their',
      transcription: 'ðeə',
      translation: 'их',
    },
    {
      id: 32,
      word: 'week',
      transcription: 'wiːk',
      translation: 'неделя',
    },
  ],
];
