export const wordsLesson91 = [
  [
    {
      id: 1,
      word: 'accidentally',
      transcription: 'ˌæksɪˈdɛntəli',
      translation: 'случайно',
    },
    {
      id: 2,
      word: 'across',
      transcription: 'əˈkrɒs',
      translation: 'через',
    },
    {
      id: 3,
      word: 'arm',
      transcription: 'ɑːm',
      translation: 'рука',
    },
    {
      id: 4,
      word: 'beside',
      transcription: 'bɪˈsaɪd',
      translation: 'рядом, возле',
    },
    {
      id: 5,
      word: 'bravely',
      transcription: 'ˈbreɪvli',
      translation: 'смело',
    },
    {
      id: 6,
      word: 'courageously',
      transcription: 'kəˈreɪʤəsli',
      translation: 'отважно',
    },
    {
      id: 7,
      word: 'deal',
      transcription: 'diːl',
      translation: 'иметь дело, сделка',
    },
    {
      id: 8,
      word: 'fight',
      transcription: 'faɪt',
      translation: 'сражаться, борьба',
    },
    {
      id: 9,
      word: 'forgive',
      transcription: 'fəˈgɪv',
      translation: 'прощать',
    },
    {
      id: 10,
      word: 'freedom',
      transcription: 'ˈfriːdəm',
      translation: 'свобода',
    },
    {
      id: 11,
      word: 'heroically',
      transcription: 'hɪˈrəʊɪk(ə)li',
      translation: 'героически',
    },
    {
      id: 12,
      word: 'hurt',
      transcription: 'hɜːt',
      translation: 'повредить, ранить',
    },
    {
      id: 13,
      word: 'independence',
      transcription: 'ˌɪndɪˈpɛndəns',
      translation: 'независимость',
    },
    {
      id: 14,
      word: 'knee',
      transcription: 'niː',
      translation: 'колено',
    },
    {
      id: 15,
      word: 'leg',
      transcription: 'lɛg',
      translation: 'нога',
    },
    {
      id: 16,
      word: 'masterpiece',
      transcription: 'ˈmɑːstəpiːs',
      translation: 'шедевр',
    },
    {
      id: 17,
      word: 'piece',
      transcription: 'piːs',
      translation: 'кусок',
    },
    {
      id: 18,
      word: 'plate',
      transcription: 'pleɪt',
      translation: 'тарелка',
    },
    {
      id: 19,
      word: 'pond',
      transcription: 'pɒnd',
      translation: 'пруд',
    },
    {
      id: 20,
      word: 'pony',
      transcription: 'pəʊni',
      translation: 'пони',
    },
    {
      id: 21,
      word: 'soldier',
      transcription: 'ˈsəʊlʤə',
      translation: 'солдат',
    },
    {
      id: 22,
      word: 'supplier',
      transcription: 'səˈplaɪə',
      translation: 'поставщик',
    },
  ],
];
