export const wordsLesson188 = [
  [
    {
      id: 1,
      word: 'acceptable',
      transcription: 'əkˈsɛptəbl',
      translation: 'приемлемый',
    },
    {
      id: 2,
      word: 'available',
      transcription: 'əˈveɪləbl',
      translation: 'доступный',
    },
    {
      id: 3,
      word: 'bunch',
      transcription: 'bʌnʧ',
      translation: 'букет',
    },
    {
      id: 4,
      word: 'clinical',
      transcription: 'ˈklɪnɪkəl',
      translation: 'клинический',
    },
    {
      id: 5,
      word: 'enormous',
      transcription: 'ɪˈnɔːməs',
      translation: 'огромный',
    },
    {
      id: 6,
      word: 'horrible',
      transcription: 'ˈhɒrəbl',
      translation: 'ужасный',
    },
    {
      id: 7,
      word: 'legal',
      transcription: 'ˈliːgəl',
      translation: 'законный',
    },
    {
      id: 8,
      word: 'metre',
      transcription: 'ˈmiːtə',
      translation: 'метр',
    },
    {
      id: 9,
      word: 'naive',
      transcription: 'nɑːˈiːv',
      translation: 'наивный',
    },
    {
      id: 10,
      word: 'objective',
      transcription: 'əbˈʤɛktɪv',
      translation: 'объективный',
    },
    {
      id: 11,
      word: 'overtime',
      transcription: 'ˈəʊvətaɪm',
      translation: 'сверхурочно',
    },
    {
      id: 12,
      word: 'pale',
      transcription: 'peɪl',
      translation: 'бледный',
    },
    {
      id: 13,
      word: 'philosophical',
      transcription: 'ˌfɪləˈsɒfɪkəl',
      translation: 'философский',
    },
    {
      id: 14,
      word: 'rose',
      transcription: 'rəʊz',
      translation: 'роза',
    },
    {
      id: 15,
      word: 'row',
      transcription: 'rəʊ',
      translation: 'ряд',
    },
    {
      id: 16,
      word: 'square',
      transcription: 'skweə',
      translation: 'квадрат, квадратный',
    },
    {
      id: 17,
      word: 'state',
      transcription: 'steɪt',
      translation: 'штат',
    },
    {
      id: 18,
      word: 'waist',
      transcription: 'weɪst',
      translation: 'талия',
    },
  ],
];
