export const wordsLesson293 = [
  [
    {
      id: 1,
      word: 'admission',
      transcription: 'ədˈmɪʃᵊn',
      translation: 'вход, вступительный',
    },
    {
      id: 2,
      word: 'cheerful',
      transcription: 'ˈʧɪəfʊl',
      translation: 'жизнерадостный',
    },
    {
      id: 3,
      word: 'complicate',
      transcription: 'ˈkɒmplɪkeɪt',
      translation: 'усложнять',
    },
    {
      id: 4,
      word: 'dispute',
      transcription: 'dɪsˈpjuːt',
      translation: 'спор, диспут',
    },
    {
      id: 5,
      word: 'foundation',
      transcription: 'faʊnˈdeɪʃᵊn',
      translation: 'основание',
    },
    {
      id: 6,
      word: 'importantly',
      transcription: 'ɪmˈpɔːtəntli',
      translation: 'важно',
    },
    {
      id: 7,
      word: 'increasingly',
      transcription: 'ɪnˈkriːsɪŋli',
      translation: 'все более',
    },
    {
      id: 8,
      word: 'junior',
      transcription: 'ˈʤuːniə',
      translation: 'юношеский, юниорский',
    },
    {
      id: 9,
      word: 'lab',
      transcription: 'læb',
      translation: 'лаборатория',
    },
    {
      id: 10,
      word: 'largely',
      transcription: 'ˈlɑːʤli',
      translation: 'в основном',
    },
    {
      id: 11,
      word: 'minority',
      transcription: 'maɪˈnɒrəti',
      translation: 'меньшинство',
    },
    {
      id: 12,
      word: 'notwithstanding',
      transcription: 'ˌnɒtwɪθˈstændɪŋ',
      translation: 'несмотря на',
    },
    {
      id: 13,
      word: 'odd',
      transcription: 'ɒd',
      translation: 'странный',
    },
    {
      id: 14,
      word: 'peak',
      transcription: 'piːk',
      translation: 'вершина, пик',
    },
    {
      id: 15,
      word: 'permanent',
      transcription: 'ˈpɜːmənənt',
      translation: 'постоянный',
    },
    {
      id: 16,
      word: 'regrettably',
      transcription: 'rɪˈɡrɛtəbᵊli',
      translation: 'к сожалению',
    },
    {
      id: 17,
      word: 'remarkable',
      transcription: 'rɪˈmɑːkəbᵊl',
      translation: 'удивительный',
    },
    {
      id: 18,
      word: 'revolutionise',
      transcription: 'ˌrɛvəˈluːʃnaɪz',
      translation: 'произвести революцию',
    },
    {
      id: 19,
      word: 'similarly',
      transcription: 'ˈsɪmɪləli',
      translation: 'сходство',
    },
    {
      id: 20,
      word: 'ultimately',
      transcription: 'ˈʌltɪmɪtli',
      translation: 'в конечном итоге',
    },
    {
      id: 21,
      word: 'undermine',
      transcription: 'ˌʌndəˈmaɪn',
      translation: 'подрывать',
    },
    {
      id: 22,
      word: 'undetermined',
      transcription: 'ˌʌndɪˈtɜːmɪnd',
      translation: 'нерешительный',
    },
  ],
];
