export const wordsLesson206 = [
  [
    {
      id: 1,
      word: 'annoy',
      transcription: 'əˈnɔɪ',
      translation: 'раздражать',
    },
    {
      id: 2,
      word: 'competitor',
      transcription: 'kəmˈpɛtɪtə',
      translation: 'конкурент',
    },
    {
      id: 3,
      word: 'corporation',
      transcription: 'ˌkɔːpəˈreɪʃən',
      translation: 'корпорация',
    },
    {
      id: 4,
      word: 'objectively',
      transcription: 'əbˈʤɛktɪvli',
      translation: 'объективно',
    },
    {
      id: 5,
      word: 'dress down',
      transcription: 'drɛs daʊn',
      translation: 'одеваться неформально',
    },
    {
      id: 6,
      word: 'calm down',
      transcription: 'kɑːm daʊn',
      translation: 'успокоиться',
    },
    {
      id: 7,
      word: 'cool down',
      transcription: 'kuːl daʊn',
      translation: 'остыть',
    },
    {
      id: 8,
      word: 'check in',
      transcription: 'ʧɛk ɪn',
      translation: 'зарегистрироваться',
    },
    {
      id: 9,
      word: 'check out',
      transcription: 'ʧɛk aʊt',
      translation: 'выселяться',
    },
    {
      id: 10,
      word: 'dress up',
      transcription: 'drɛs ʌp',
      translation: 'наряжаться, одеваться формально',
    },
    {
      id: 11,
      word: 'put down',
      transcription: 'pʊt daʊn',
      translation: 'записывать, критиковать',
    },
    {
      id: 12,
      word: 'back up',
      transcription: 'bæk ʌp',
      translation: 'поддерживать, сохранять',
    },
    {
      id: 13,
      word: 'deal with',
      transcription: 'diːl wɪð',
      translation: 'иметь дело с',
    },
    {
      id: 14,
      word: 'take over',
      transcription: 'teɪk ˈəʊvə',
      translation: 'поглотить',
    },
    {
      id: 15,
      word: 'put aside',
      transcription: 'pʊt əˈsaɪd',
      translation: 'откладывать',
    },
    {
      id: 16,
      word: 'put away',
      transcription: 'pʊt əˈweɪ',
      translation: 'убирать',
    },
    {
      id: 17,
      word: 'give back',
      transcription: 'gɪv bæk',
      translation: 'возвращать',
    },
    {
      id: 18,
      word: 'move forward',
      transcription: 'muːv ˈfɔːwəd',
      translation: 'двигаться вперед',
    },
    {
      id: 19,
      word: 'call for',
      transcription: 'kɔːl fɔː',
      translation: 'требовать',
    },
    {
      id: 20,
      word: 'close down',
      transcription: 'kləʊs daʊn',
      translation: 'закрываться',
    },
    {
      id: 21,
      word: 'come along',
      transcription: 'kʌm əˈlɒŋ',
      translation: 'идти вместе',
    },
    {
      id: 22,
      word: 'break out',
      transcription: 'breɪk aʊt',
      translation: 'разразиться',
    },
    {
      id: 23,
      word: 'bring down',
      transcription: 'brɪŋ daʊn',
      translation: 'снижать',
    },
  ],
];
