export const wordsLesson75 = [
  [
    {
      id: 1,
      word: 'broaden',
      transcription: 'ˈbrɔːdn',
      translation: 'расширять',
    },
    {
      id: 2,
      word: 'care',
      transcription: 'keə',
      translation: 'волновать, заботиться',
    },
    {
      id: 3,
      word: 'conversation',
      transcription: 'ˌkɒnvəˈseɪʃən',
      translation: 'разговор',
    },
    {
      id: 4,
      word: 'discussion',
      transcription: 'dɪsˈkʌʃən',
      translation: 'обсуждение',
    },
    {
      id: 5,
      word: 'fun',
      transcription: 'fʌn',
      translation: 'веселье',
    },
    {
      id: 6,
      word: 'horizon',
      transcription: 'həˈraɪzn',
      translation: 'горизонт',
    },
    {
      id: 7,
      word: 'innocent',
      transcription: 'ˈɪnəsənt',
      translation: 'невинный',
    },
    {
      id: 8,
      word: 'luck',
      transcription: 'lʌk',
      translation: 'удача',
    },
    {
      id: 9,
      word: 'outdoors',
      transcription: 'ˌaʊtˈdɔːz',
      translation: 'на свежем воздухе',
    },
    {
      id: 10,
      word: 'partly',
      transcription: 'ˈpɑːtli',
      translation: 'частично',
    },
    {
      id: 11,
      word: 'poverty',
      transcription: 'ˈpɒvəti',
      translation: 'бедность',
    },
    {
      id: 12,
      word: 'private',
      transcription: 'ˈpraɪvɪt',
      translation: 'частный',
   },
    {
      id: 13,
      word: 'pronunciation',
      transcription: 'prəˌnʌnsɪˈeɪʃən',
      translation: 'произношение',
    },
    {
      id: 14,
      word: 'reach',
      transcription: 'riːʧ',
      translation: 'достигать',
    },
    {
      id: 15,
      word: 'record',
      transcription: 'ˈrɛkɔːd',
      translation: 'записывать, запись',
    },
    {
      id: 16,
      word: 'seldom',
      transcription: 'ˈsɛldəm',
      translation: 'редко',
    },
    {
      id: 17,
      word: 'sight',
      transcription: 'saɪt',
      translation: 'зрение',
    },
    {
      id: 18,
      word: 'soft',
      transcription: 'sɒft',
      translation: 'мягкий',
    },
    {
      id: 19,
      word: 'suppose',
      transcription: 'səˈpəʊz',
      translation: 'предполагать',
    },
    {
      id: 20,
      word: 'thoroughly',
      transcription: 'ˈθʌrəli',
      translation: 'тщательно',
    },
    {
      id: 21,
      word: 'touch',
      transcription: 'tʌʧ',
      translation: 'трогать, прикасаться',
    },
    {
      id: 22,
      word: 'wish',
      transcription: 'wɪʃ',
      translation: 'желать, желание',
    },
  ],
];
