export const wordsLesson292 = [
  [
    {
      id: 1,
      word: 'amazingly',
      transcription: 'əˈmeɪzɪŋli',
      translation: 'удивительно',
    },
    {
      id: 2,
      word: 'apparently',
      transcription: 'əˈpærəntli',
      translation: 'видимо',
    },
    {
      id: 3,
      word: 'claim',
      transcription: 'kleɪm',
      translation: 'требовать, претендовать',
    },
    {
      id: 4,
      word: 'crown',
      transcription: 'kraʊn',
      translation: 'завершать, корона',
    },
    {
      id: 5,
      word: 'curriculum',
      transcription: 'kəˈrɪkjələm',
      translation: 'учебная программа',
    },
    {
      id: 6,
      word: 'decade',
      transcription: 'ˈdɛkeɪd',
      translation: 'десятилетие',
    },
    {
      id: 7,
      word: 'entrance',
      transcription: 'ˈɛntrəns',
      translation: 'вход, вступительный',
    },
    {
      id: 8,
      word: 'evidently',
      transcription: 'ˈɛvɪdəntli',
      translation: 'очевидно',
    },
    {
      id: 9,
      word: 'lifelong',
      transcription: 'ˈlaɪflɒŋ',
      translation: 'пожизненный',
    },
    {
      id: 10,
      word: 'likelihood',
      transcription: 'ˈlaɪklɪhʊd',
      translation: 'вероятность',
    },
    {
      id: 11,
      word: 'omit',
      transcription: 'əˈmɪt',
      translation: 'пропускать, не включать',
    },
    {
      id: 12,
      word: 'perform',
      transcription: 'pəˈfɔːm',
      translation: 'выполнять',
    },
    {
      id: 13,
      word: 'pilgrim',
      transcription: 'ˈpɪlɡrɪm',
      translation: 'паломник',
    },
    {
      id: 14,
      word: 'poisonous',
      transcription: 'ˈpɔɪznəs',
      translation: 'ядовитый',
    },
    {
      id: 15,
      word: 'predictably',
      transcription: 'prɪˈdɪk.tə.bli',
      translation: 'предсказуемо',
    },
    {
      id: 16,
      word: 'presumably',
      transcription: 'prɪˈzjuːməbli',
      translation: 'предположительно',
    },
    {
      id: 17,
      word: 'prosper',
      transcription: 'ˈprɒspə',
      translation: 'процветать',
    },
    {
      id: 18,
      word: 'reveal',
      transcription: 'rɪˈviːl',
      translation: 'выявлять, раскрывать',
    },
    {
      id: 19,
      word: 'theoretical',
      transcription: 'θɪəˈrɛtɪkᵊl',
      translation: 'теоретический',
    },
    {
      id: 20,
      word: 'tourism',
      transcription: 'ˈtʊərɪzᵊm',
      translation: 'туризм',
    },
    {
      id: 21,
      word: 'trained',
      transcription: 'treɪnd',
      translation: 'тренированный',
    },
  ],
];
