export const wordsLesson284 = [
  [
    {
      id: 1,
      word: 'appealing',
      transcription: 'əˈpiːlɪŋ',
      translation: 'привлекательный',
    },
    {
      id: 2,
      word: 'assessment',
      transcription: 'əˈsɛsmənt',
      translation: 'оценка',
    },
    {
      id: 3,
      word: 'assume',
      transcription: 'əˈsjuːm',
      translation: 'предполагать',
    },
    {
      id: 4,
      word: 'awkward',
      transcription: 'ˈɔːkwəd',
      translation: 'неловкий',
    },
    {
      id: 5,
      word: 'compulsory',
      transcription: 'kəmˈpʌlsəri',
      translation: 'принудительный, обязательный',
    },
    {
      id: 6,
      word: 'discrimination',
      transcription: 'dɪsˌkrɪmɪˈneɪʃᵊn',
      translation: 'дискриминация',
    },
    {
      id: 7,
      word: 'disregard',
      transcription: 'ˌdɪsrɪˈɡɑːd',
      translation: 'пренебрежение, пренебрегать',
    },
    {
      id: 8,
      word: 'drastically',
      transcription: 'ˈdræstɪkᵊli',
      translation: 'резко, радикально',
    },
    {
      id: 9,
      word: 'real estate',
      transcription: 'rɪəl ɪsˈteɪt',
      translation: 'недвижимость',
    },
    {
      id: 10,
      word: 'exploitation',
      transcription: 'ˌɛksplɔɪˈteɪʃᵊn',
      translation: 'эксплуатация',
    },
    {
      id: 11,
      word: 'gender',
      transcription: 'ˈʤɛndə',
      translation: 'пол',
    },
    {
      id: 12,
      word: 'genuineness',
      transcription: 'ˈʤɛnjuɪnəs',
      translation: 'подлинность',
    },
    {
      id: 13,
      word: 'insulting',
      transcription: 'ɪnˈsʌltɪŋ',
      translation: 'оскорбительный',
    },
    {
      id: 14,
      word: 'labour',
      transcription: 'ˈleɪbə',
      translation: 'рабочая сила',
    },
    {
      id: 15,
      word: 'overpriced',
      transcription: 'ˌəʊvəˈpraɪst',
      translation: 'переоцененный',
    },
    {
      id: 16,
      word: 'pleasantly',
      transcription: 'ˈplɛzntli',
      translation: 'приятно',
    },
    {
      id: 17,
      word: 'presume',
      transcription: 'prɪˈzjuːm',
      translation: 'предполагать',
    },
    {
      id: 18,
      word: 'responsibly',
      transcription: 'rɪsˈpɒnsəbᵊli',
      translation: 'ответственно',
    },
    {
      id: 19,
      word: 'rhetorical',
      transcription: 'rɪˈtɒrɪkəl',
      translation: 'риторический',
    },
    {
      id: 20,
      word: 'ruthless',
      transcription: 'ˈruːθləs',
      translation: 'безжалостный',
    },
    {
      id: 21,
      word: 'subjective',
      transcription: 'səbˈʤɛktɪv',
      translation: 'субъективный',
    },
    {
      id: 22,
      word: 'surpass',
      transcription: 'sɜːˈpɑːs',
      translation: 'превзойти',
    },
    {
      id: 23,
      word: 'unavoidable',
      transcription: 'ˌʌnəˈvɔɪdəbᵊl',
      translation: 'неизбежный',
    },
    {
      id: 24,
      word: 'underline',
      transcription: 'ˈʌndəlaɪn',
      translation: 'подчеркнуть',
    },
  ],
];
