export const wordsLesson2 = [
  [
    {
      id: 1,
      word: 'absolutely',
      transcription: 'ˈæbsəluːtli',
      translation: 'абсолютно, полностью',
    },
    {
      id: 2,
      word: 'agree',
      transcription: 'əˈgriː',
      translation: 'соглашаться',
    },
    {
      id: 3,
      word: 'better',
      transcription: 'ˈbɛtə',
      translation: 'лучше',
    },
    {
      id: 4,
      word: 'cost',
      transcription: 'kɒst',
      translation: 'стоить',
    },
    {
      id: 5,
      word: 'dollar',
      transcription: 'ˈdɒlə',
      translation: 'доллар',
    },
    {
      id: 6,
      word: 'euro',
      transcription: 'ˈjʊərəʊ',
      translation: 'евро',
    },
    {
      id: 7,
      word: 'far',
      transcription: 'fɑː',
      translation: 'далеко',
    },
    {
      id: 8,
      word: 'feel',
      transcription: 'fiːl',
      translation: 'чувствовать себя',
    },
    {
      id: 9,
      word: 'fifty',
      transcription: 'ˈfɪfti',
      translation: 'пятьдесят',
    },
    {
      id: 10,
      word: 'he',
      transcription: 'hiː',
      translation: 'он',
    },
    {
      id: 11,
      word: 'less',
      transcription: 'lɛs',
      translation: 'меньше',
    },
    {
      id: 12,
      word: 'make',
      transcription: 'meɪk',
      translation: 'делать',
    },
    {
      id: 13,
      word: 'mistake',
      transcription: 'mɪsˈteɪk',
      translation: 'ошибка',
    },
    {
      id: 14,
      word: 'much',
      transcription: 'mʌʧ',
      translation: 'много',
    },
    {
      id: 15,
      word: 'near',
      transcription: 'nɪə',
      translation: 'рядом, около',
    },
    {
      id: 16,
      word: 'pound',
      transcription: 'paʊnd',
      translation: 'фунт',
    },
    {
      id: 17,
      word: 'problem',
      transcription: 'ˈprɒbləm',
      translation: 'проблема',
    },
    {
      id: 18,
      word: 'she',
      transcription: 'ʃiː',
      translation: 'она',
    },
    {
      id: 19,
      word: 'ten',
      transcription: 'tɛn',
      translation: 'десять',
    },
    {
      id: 20,
      word: 'that',
      transcription: 'ðæt',
      translation: 'тот',
    },
    {
      id: 21,
      word: 'ticket',
      transcription: 'ˈtɪkɪt',
      translation: 'билет',
    },
    {
      id: 22,
      word: 'together',
      transcription: 'təˈgɛðə',
      translation: 'вместе',
    },
    {
      id: 23,
      word: 'twenty',
      transcription: 'ˈtwɛnti',
      translation: 'двадцать',
    },
    {
      id: 24,
      word: 'with',
      transcription: 'wɪð',
      translation: 'с',
    },
    {
      id: 25,
      word: 'call',
      transcription: 'kɔːl',
      translation: 'звонить, звонок',
    },
    {
      id: 26,
      word: 'happen',
      transcription: 'ˈhæpən',
      translation: 'случаться, происходить',
    },
    {
      id: 27,
      word: 'hear',
      transcription: 'hɪə',
      translation: 'слышать',
    },
    {
      id: 28,
      word: 'how',
      transcription: 'haʊ',
      translation: 'как',
    },
    {
      id: 29,
      word: 'idea',
      transcription: 'aɪˈdɪə',
      translation: 'идея',
    },
    {
      id: 30,
      word: 'little',
      transcription: 'ˈlɪtl',
      translation: 'мало',
    },
    {
      id: 31,
      word: 'a lot',
      transcription: 'ə lɒt',
      translation: 'много',
    },
    {
      id: 32,
      word: 'on',
      transcription: 'ɒn',
      translation: 'на',
    },
    {
      id: 33,
      word: 'people',
      transcription: 'ˈpiːpl',
      translation: 'люди',
    },
    {
      id: 34,
      word: 'person',
      transcription: 'ˈpɜːsn',
      translation: 'человек',
    },
    {
      id: 35,
      word: 'say',
      transcription: 'seɪ',
      translation: 'говорить',
    },
    {
      id: 36,
      word: 'tell',
      transcription: 'tɛl',
      translation: 'сказать, рассказывать',
    },
    {
      id: 37,
      word: 'too',
      transcription: 'tuː',
      translation: 'слишком, также',
    },
    {
      id: 38,
      word: 'TV',
      transcription: 'ˌtiːˈviː',
      translation: 'телевизор',
    },
    {
      id: 39,
      word: 'us',
      transcription: 'ʌs',
      translation: 'нам, нас',
    },
    {
      id: 40,
      word: 'watch',
      transcription: 'wɒʧ',
      translation: 'смотреть',
    },
    {
      id: 41,
      word: 'why',
      transcription: 'waɪ',
      translation: 'зачем',
    },
  ],
];
