export const wordsLesson134 = [
  [
    {
      id: 1,
      word: 'accusation',
      transcription: 'ˌækju(ː)ˈzeɪʃ(ə)n',
      translation: 'обвинение',
    },
    {
      id: 2,
      word: 'afford',
      transcription: 'əˈfɔːd',
      translation: 'позволить себе',
    },
    {
      id: 3,
      word: 'angrily',
      transcription: 'ˈæŋgrɪli',
      translation: 'сердито',
    },
    {
      id: 4,
      word: 'appear',
      transcription: 'əˈpɪə',
      translation: 'появляться',
    },
    {
      id: 5,
      word: 'beard',
      transcription: 'bɪəd',
      translation: 'борода',
    },
    {
      id: 6,
      word: 'both',
      transcription: 'bəʊθ',
      translation: 'оба',
    },
    {
      id: 7,
      word: 'concern',
      transcription: 'kənˈsɜːn',
      translation: 'касаться',
    },
    {
      id: 8,
      word: 'deny',
      transcription: 'dɪˈnaɪ',
      translation: 'отрицать',
    },
    { id: 9, word: 'gas', transcription: 'gæs', translation: 'газ', },
    {
      id: 10,
      word: 'guilt',
      transcription: 'gɪlt',
      translation: 'вина',
    },
    {
      id: 11,
      word: 'hunt',
      transcription: 'hʌnt',
      translation: 'охотиться',
    },
    {
      id: 12,
      word: 'influence',
      transcription: 'ˈɪnflʊəns',
      translation: 'влиять',
    },
    {
      id: 13,
      word: 'moustache',
      transcription: 'məsˈtɑːʃ',
      translation: 'усы',
    },
    {
      id: 14,
      word: 'oil',
      transcription: 'ɔɪl',
      translation: 'нефть, масло',
    },
    {
      id: 15,
      word: 'shave',
      transcription: 'ʃeɪv',
      translation: 'бриться',
    },
    {
      id: 16,
      word: 'spell',
      transcription: 'spɛl',
      translation: 'писать или произносить по буквам',
    },
    {
      id: 17,
      word: 'strongly',
      transcription: 'ˈstrɒŋli',
      translation: 'сильно',
    },
    {
      id: 18,
      word: 'suburbs',
      transcription: 'ˈsʌbɜːbz',
      translation: 'пригород',
    },
    {
      id: 19,
      word: 'supply',
      transcription: 'səˈplaɪ',
      translation: 'поставлять',
    },
    {
      id: 20,
      word: 'trouble',
      transcription: 'ˈtrʌbl',
      translation: 'беда',
    },
    {
      id: 21,
      word: 'universe',
      transcription: 'ˈjuːnɪvɜːs',
      translation: 'Вселенная',
    },
    {
      id: 22,
      word: 'warn',
      transcription: 'wɔːn',
      translation: 'предупреждать',
    },
    {
      id: 23,
      word: 'wire',
      transcription: 'ˈwaɪə',
      translation: 'провод',
    },
  ],
];
