export const wordsLesson4 = [
  [
    {
      id: 1,
      word: 'airport',
      transcription: 'ˈeəpɔːt',
      translation: 'аэропорт',
    },
    {
      id: 2,
      word: 'apartment',
      transcription: 'əˈpɑːtmənt',
      translation: 'квартира',
    },
    {
      id: 3,
      word: 'cake',
      transcription: 'keɪk',
      translation: 'торт, пирожное',
    },
    {
      id: 4,
      word: 'child',
      transcription: 'ʧaɪld',
      translation: 'ребенок',
    },
    {
      id: 5,
      word: 'children',
      transcription: 'ˈʧɪldrən',
      translation: 'дети',
    },
    {
      id: 6,
      word: 'chocolate',
      transcription: 'ˈʧɒkəlɪt',
      translation: 'шоколад',
    },
    {
      id: 7,
      word: 'daughter',
      transcription: 'ˈdɔːtə',
      translation: 'дочь',
    },
    {
      id: 8,
      word: 'four',
      transcription: 'fɔː',
      translation: 'четыре',
    },
    {
      id: 9,
      word: 'German',
      transcription: 'ˈʤɜːmən',
      translation: 'немецкий',
    },
    {
      id: 10,
      word: 'meat',
      transcription: 'miːt',
      translation: 'мясо',
    },
    {
      id: 11,
      word: 'men',
      transcription: 'mɛn',
      translation: 'мужчины',
    },
    {
      id: 12,
      word: 'seafood',
      transcription: 'ˈsiːfuːd',
      translation: 'морепродукты',
    },
    {
      id: 13,
      word: 'son',
      transcription: 'sʌn',
      translation: 'сын',
    },
    {
      id: 14,
      word: 'Spanish',
      transcription: 'ˈspænɪʃ',
      translation: 'испанский',
    },
    {
      id: 15,
      word: 'three',
      transcription: 'θriː',
      translation: 'три',
    },
    {
      id: 16,
      word: 'women',
      transcription: 'ˈwɪmɪn',
      translation: 'женщины',
    },
    {
      id: 17,
      word: 'boyfriend',
      transcription: 'bɔɪfrɛnd',
      translation: 'парень',
    },
    {
      id: 18,
      word: 'ice cream',
      transcription: 'aɪs kriːm',
      translation: 'мороженое',
    },
    {
      id: 19,
      word: 'foreign',
      transcription: 'ˈfɒrɪn',
      translation: 'иностранный',
    },
    {
      id: 20,
      word: 'girlfriend',
      transcription: 'gɜːlfrɛnd',
      translation: 'девушка',
    },
    {
      id: 21,
      word: 'hospital',
      transcription: 'ˈhɒspɪtl',
      translation: 'больница',
    },
    {
      id: 22,
      word: 'pizza',
      transcription: 'ˈpiːtsə',
      translation: 'пицца',
    },
    {
      id: 23,
      word: 'swimming',
      transcription: 'ˈswɪmɪŋ',
      translation: 'плавание',
    },
  ],
];
