export const wordsLesson296 = [
  [
    {
      id: 1,
      word: 'absurdly',
      transcription: 'əbˈsɜːdli',
      translation: 'абсурдно',
    },
    {
      id: 2,
      word: 'academy',
      transcription: 'əˈkædəmi',
      translation: 'академия',
    },
    {
      id: 3,
      word: 'altogether',
      transcription: 'ˌɔːltəˈɡɛðə',
      translation: 'совсем, совершенно',
    },
    {
      id: 4,
      word: 'clarity',
      transcription: 'ˈklærəti',
      translation: 'ясность',
    },
    {
      id: 5,
      word: 'clumsiness',
      transcription: 'ˈklʌmzɪnəs',
      translation: 'неуклюжесть',
    },
    {
      id: 6,
      word: 'coherence',
      transcription: 'kəʊˈhɪərəns',
      translation: 'последовательность',
    },
    {
      id: 7,
      word: 'cohesion',
      transcription: 'kəʊˈhiːʒən',
      translation: 'связность',
    },
    {
      id: 8,
      word: 'colloquial',
      transcription: 'kəˈləʊkwiəl',
      translation: 'разговорный',
    },
    {
      id: 9,
      word: 'colourless',
      transcription: 'ˈkʌlələs',
      translation: 'бесцветный',
    },
    {
      id: 10,
      word: 'disappointing',
      transcription: 'ˌdɪsəˈpɔɪntɪŋ',
      translation: 'разочаровывающий',
    },
    {
      id: 11,
      word: 'fanaticism',
      transcription: 'fəˈnætɪsɪzᵊm',
      translation: 'фанатизм',
    },
    {
      id: 12,
      word: 'honorary',
      transcription: 'ˈɒnərəri',
      translation: 'почетный',
    },
    {
      id: 13,
      word: 'inclination',
      transcription: 'ˌɪnklɪˈneɪʃᵊn',
      translation: 'желание',
    },
    {
      id: 14,
      word: 'incomplete',
      transcription: 'ˌɪnkəmˈpliːt',
      translation: 'неполный',
    },
    {
      id: 15,
      word: 'innumerable',
      transcription: 'ɪˈnjuːmərəbᵊl',
      translation: 'бесчисленный',
    },
    {
      id: 16,
      word: 'irreparable',
      transcription: 'ɪˈrɛpərəbᵊl',
      translation: 'непоправимый',
    },
    {
      id: 17,
      word: 'outweigh',
      transcription: 'aʊtˈweɪ',
      translation: 'перевешивать',
    },
    {
      id: 18,
      word: 'overshadow',
      transcription: 'ˌəʊvəˈʃædəʊ',
      translation: 'затмевать',
    },
    {
      id: 19,
      word: 'overstep',
      transcription: 'ˌəʊvəˈstɛp',
      translation: 'переступать',
    },
    {
      id: 20,
      word: 'phrasal',
      transcription: 'ˈfreɪzᵊl',
      translation: 'фразовый',
    },
    {
      id: 21,
      word: 'preferable',
      transcription: 'ˈprɛfərəbᵊl',
      translation: 'предпочтительный',
    },
    {
      id: 22,
      word: 'prepay',
      transcription: 'priːˈpeɪ',
      translation: 'платить вперед',
    },
    {
      id: 23,
      word: 'protective',
      transcription: 'prəˈtɛktɪv',
      translation: 'защитный',
    },
    {
      id: 24,
      word: 'recession',
      transcription: 'rɪˈsɛʃᵊn',
      translation: 'спад, рецессия',
    },
    {
      id: 25,
      word: 'renewable',
      transcription: 'rɪˈnjuːəbᵊl',
      translation: 'возобновляемый',
    },
    {
      id: 26,
      word: 'researcher',
      transcription: 'rɪˈsɜːʧə',
      translation: 'исследователь',
    },
    {
      id: 27,
      word: 'revival',
      transcription: 'rɪˈvaɪvəl',
      translation: 'оживление',
    },
    {
      id: 28,
      word: 'revive',
      transcription: 'rɪˈvaɪv',
      translation: 'оживать',
    },
    {
      id: 29,
      word: 'scrupulously',
      transcription: 'ˈskruːpjələsli',
      translation: 'скрупулезно',
    },
    {
      id: 30,
      word: 'stagnation',
      transcription: 'stæɡˈneɪʃᵊn',
      translation: 'стагнация',
    },
    {
      id: 31,
      word: 'storyteller',
      transcription: 'ˈstɔːrɪˌtɛlə',
      translation: 'рассказчик',
    },
    {
      id: 32,
      word: 'straighten',
      transcription: 'ˈstreɪtn',
      translation: 'выпрямлять',
    },
    {
      id: 33,
      word: 'supplementary',
      transcription: 'ˌsʌplɪˈmɛntəri',
      translation: 'дополнительный',
    },
    {
      id: 34,
      word: 'trade',
      transcription: 'treɪd',
      translation: 'торговля',
    },
    {
      id: 35,
      word: 'tranquil',
      transcription: 'ˈtræŋkwɪl',
      translation: 'спокойный',
    },
    {
      id: 36,
      word: 'unfit',
      transcription: 'ʌnˈfɪt',
      translation: 'непригодный, нездоровый',
    },
    {
      id: 37,
      word: 'unhealthy',
      transcription: 'ʌnˈhɛlθi',
      translation: 'нездоровый',
    },
    {
      id: 38,
      word: 'unprotected',
      transcription: 'ˌʌnprəˈtɛktɪd',
      translation: 'незащищенный',
    },
    {
      id: 39,
      word: 'unsafe',
      transcription: 'ʌnˈseɪf',
      translation: 'небезопасный',
    },
  ],
];
