export const contentLesson150 = [
  [
    {
      title: 'Урок 150. Важные грамматические конструкции',
    },
    [
      {
        id: 1,
        expression: 'Он никогда не ходит туда',
        transcription: 'hi ˈnɛvə gəʊz ðeə',
        translation: 'He never goes there',
      },
      {
        id: 2,
        expression: 'Я никогда не поеду туда',
        transcription: 'aɪl ˈnɛvə gəʊ ðeə',
        translation: "I'll never go there",
      },
      {
        id: 3,
        expression: 'Кто-то знает это',
        transcription: 'ˈsʌmbədi (ˈsʌmwʌn) nəʊz ɪt',
        translation: 'Somebody (someone) knows it',
      },
      {
        id: 4,
        expression: 'Всё здесь',
        transcription: 'ˈɛvrɪθɪŋ z hɪə',
        translation: 'Everything is here',
      },
      {
        id: 5,
        expression: 'Что-то неправильно',
        transcription: 'ˈsʌmθɪŋ z rɒŋ',
        translation: 'Something is wrong',
      },
      {
        id: 6,
        expression: 'Он может говорить как по-английски, так и по-испански',
        transcription: 'hi kən spiːk bəʊθ ˈɪŋglɪʃ ənd ˈspænɪʃ',
        translation: 'He can speak both English and Spanish',
      },
      {
        id: 7,
        expression: 'Его ничего не интересует',
        transcription: 'ˈnʌθɪŋ ˈɪntrɪsts hɪm',
        translation: 'Nothing interests him',
      },
      {
        id: 8,
        expression: 'Все люди это знают',
        transcription: 'ɔːl ˈpiːpl nəʊ ɪt',
        translation: 'All people know it',
      },
      {
        id: 9,
        expression: 'Все поддерживают эту идею',
        transcription: 'ˈɛvrɪwʌn (ˈɛvrɪbɒdi) səˈpɔːts ðɪs aɪˈdɪə',
        translation: 'Everyone (everybody) supports this idea',
      },
      {
        id: 10,
        expression: 'Там были все дети',
        transcription: 'ɔːl ðə ˈʧɪldrən wə ðeə',
        translation: 'All the children were there',
      },
      {
        id: 11,
        expression: 'Он ест и мясо, и рыбу',
        transcription: 'hi iːts bəʊθ miːt ənd fɪʃ',
        translation: 'He eats both meat and fish',
      },
      {
        id: 12,
        expression: 'Никто из моих друзей этого не знает',
        transcription:
          'nʌn əv maɪ frɛndz nəʊz ɪt / ˈnaɪðər əv maɪ frɛndz nəʊ (nəʊz) ɪt',
        translation:
          'None of my friends knows it / Neither of my friends know (knows) it',
      },
      {
        id: 13,
        expression: 'Он также очень занят там',
        transcription: 'hiːz ˈɔːlsəʊ ˈvɛri ˈbɪzi ðeə',
        translation: "He's also very busy there",
      },
      {
        id: 14,
        expression: 'Никто этого не хочет',
        transcription: 'nəʊ wʌn (ˈnəʊbədi) wɒnts ɪt',
        translation: 'No one (nobody) wants it',
      },
      {
        id: 15,
        expression: 'Никто из моих друзей не хочет этого',
        transcription: 'nʌn əv maɪ frɛndz wɒnt (wɒnts) ɪt',
        translation: 'None of my friends want (wants) it',
      },
      {
        id: 16,
        expression: 'Многие люди живут в бедности',
        transcription: 'ˈmɛni ˈpiːpl lɪv ɪn ˈpɒvəti',
        translation: 'Many people live in poverty',
      },
      {
        id: 17,
        expression: 'Ни один из них в действительности не заботится об этом',
        transcription: 'nʌn əv ðəm ˈrɪəli keəz əˈbaʊt ɪt',
        translation: 'None of them really cares about it',
      },
      {
        id: 18,
        expression: 'Все были очень заняты',
        transcription: 'ˈɛvrɪwʌn wəz ˈvɛri ˈbɪzi',
        translation: 'Everyone was very busy',
      },
      {
        id: 19,
        expression: 'Все люди поддерживают эту идею',
        transcription: 'ɔːl ˈpiːpl səˈpɔːt ðɪs aɪˈdɪə',
        translation: 'All people support this idea',
      },
      {
        id: 20,
        expression: 'Большинство людей это понимают',
        transcription: 'məʊst ˈpiːpl ˌʌndəˈstænd ɪt',
        translation: 'Most people understand it',
      },
      {
        id: 21,
        expression: 'Все это прекрасно понимают',
        transcription: 'ˈɛvrɪwʌn ˈpɜːfɪktli ˌʌndəˈstændz ɪt',
        translation: 'Everyone perfectly understands it',
      },
      {
        id: 22,
        expression: 'Либо он, либо она это сделали',
        transcription: 'ˈaɪðə hi ɔː ʃi dɪd ɪt',
        translation: 'Either he or she did it',
      },
      {
        id: 23,
        expression: 'Никто не заинтересован в этом',
        transcription: 'nəʊ wʌn z ˈɪntrɪstɪd ɪn ɪt',
        translation: 'No one is interested in it',
      },
      {
        id: 24,
        expression: 'Кто-то ждет тебя',
        transcription: 'ˈsʌmwʌn z ˈweɪtɪŋ fə juː',
        translation: 'Someone is waiting for you',
      },
      {
        id: 25,
        expression: 'Ничто ему не помогает',
        transcription: 'ˈnʌθɪŋ hɛlps hɪm',
        translation: 'Nothing helps him',
      },
      {
        id: 26,
        expression: 'Оба моих друга живут в Германии',
        transcription: 'bəʊθ (ɒv) maɪ frɛndz lɪv ɪn ˈʤɜːməni',
        translation: 'Both (of) my friends live in Germany',
      },
      {
        id: 27,
        expression: 'Ничего действительно не беспокоило меня',
        transcription: 'ˈnʌθɪŋ ˈrɪəli ˈwʌrid miː',
        translation: 'Nothing really worried me',
      },
      {
        id: 28,
        expression: 'Все готовы',
        transcription: 'ˈɛvrɪwʌn z ˈrɛdi',
        translation: 'Everyone is ready',
      },
      {
        id: 29,
        expression: 'Ни одна из этих вещей не интересует меня',
        transcription: 'nʌn əv ðiːz θɪŋz ˈɪntrɪsts miː',
        translation: 'None of these things interests me',
      },
      {
        id: 30,
        expression: 'Большинство из нас думает так',
        transcription: 'məʊst əv əs θɪŋk səʊ',
        translation: 'Most of us think so',
      },
      {
        id: 31,
        expression: 'Им обоим это нравится',
        transcription: 'bəʊθ əv ðəm laɪk ɪt',
        translation: 'Both of them like it',
      },
      {
        id: 32,
        expression: 'Большинство из них хотят этого',
        transcription: 'məʊst əv ðəm wɒnt ɪt',
        translation: 'Most of them want it',
      },
      {
        id: 33,
        expression: 'Каждый из них думает так',
        transcription: 'iːʧ əv ðəm θɪŋk səʊ',
        translation: 'Each of them think so',
      },
      {
        id: 34,
        expression: 'Кто-то это знает',
        transcription: 'ˈsʌmwʌn nəʊz ɪt',
        translation: 'Someone knows it',
      },
      {
        id: 35,
        expression: 'Что-то беспокоит его',
        transcription: 'ˈsʌmθɪŋ ˈwʌriz hɪm',
        translation: 'Something worries him',
      },
      {
        id: 36,
        expression: 'Никто из них не хочет этого',
        transcription: 'nʌn əv ðəm wɒnts ɪt',
        translation: 'None of them wants it',
      },
      {
        id: 37,
        expression: 'Либо он, либо она может сделать это',
        transcription: 'ˈaɪðə hi ɔː ʃi kən dʊ ɪt',
        translation: 'Either he or she can do it',
      },
      {
        id: 38,
        expression: 'Он говорит на обоих этих языках',
        transcription: 'hi spiːks bəʊθ ðiːz ˈlæŋgwɪʤɪz',
        translation: 'He speaks both these languages',
      },
      {
        id: 39,
        expression: 'Это знают все',
        transcription: 'ˈɛvrɪwʌn nəʊz ɪt',
        translation: 'Everyone knows it',
      },
      {
        id: 40,
        expression: 'Я никогда не был заинтересован в этом',
        transcription: 'aɪv ˈnɛvə biːn ˈɪntrɪstɪd ɪn ɪt',
        translation: "I've never been interested in it",
      },
      {
        id: 41,
        expression: 'Не всем это нравится',
        transcription: 'nɒt ˈɛvrɪwʌn laɪks ɪt',
        translation: 'Not everyone likes it',
      },
      {
        id: 42,
        expression: 'Большинство моих друзей поддерживают меня',
        transcription: 'məʊst əv maɪ frɛndz səˈpɔːt miː',
        translation: 'Most of my friends support me',
      },
      {
        id: 43,
        expression: 'Все студенты присутствовали',
        transcription: 'ɔːl ðə ˈstjuːdənts wə ˈprɛznt',
        translation: 'All the students were present',
      },
      {
        id: 44,
        expression: 'Меня это никогда не интересовало',
        transcription: 'ɪts ˈnɛvər ˈɪntrɪstɪd miː',
        translation: "It's never interested me",
      },
      {
        id: 45,
        expression: 'Большинство из нас это понимают',
        transcription: 'məʊst əv əs ˌʌndəˈstænd ɪt',
        translation: 'Most of us understand it',
      },
      {
        id: 46,
        expression: 'Оба эти отеля очень популярны среди туристов',
        transcription: 'bəʊθ ðiːz həʊˈtɛlz ə ˈvɛri ˈpɒpjʊlər əˈmʌŋ ˈtʊərɪsts',
        translation: 'Both these hotels are very popular among tourists',
      },
      {
        id: 47,
        expression: 'Не все понимают важность этой вещи',
        transcription: 'nɒt ˈɛvrɪwʌn ˌʌndəˈstændz ði ɪmˈpɔːtəns əv ðɪs θɪŋ',
        translation: 'Not everyone understands the importance of this thing',
      },
      {
        id: 48,
        expression: 'Ни ему, ни ей не нравится эта идея',
        transcription: 'ˈnaɪðə hi nɔː ʃi laɪk ðɪs aɪˈdɪə',
        translation: 'Neither he nor she like this idea',
      },
      {
        id: 49,
        expression: 'Все мои коллеги были рады этому решению',
        transcription: 'ɔːl maɪ ˈkɒliːgz wə ˈhæpi əˈbaʊt ðɪs dɪˈsɪʒən',
        translation: 'All my colleagues were happy about this decision',
      },
      {
        id: 50,
        expression: 'Большинство из них поддержали эту инициативу',
        transcription: 'məʊst əv ðəm səˈpɔːtɪd ðɪs ɪˈnɪʃɪətɪv',
        translation: 'Most of them supported this initiative',
      },
      {
        id: 51,
        expression: 'Все ошибки будут исправлены скоро',
        transcription: 'ɔːl ðə mɪsˈteɪks wɪl bi kəˈrɛktɪd suːn',
        translation: 'All the mistakes will be corrected soon',
      },
      {
        id: 52,
        expression:
          'Каждый из них хочет что-то сделать, чтобы изменить свою жизнь',
        transcription: 'iːʧ əv ðəm wɒnts tə dʊ ˈsʌmθɪŋ tə ʧeɪnʤ ðeə laɪf',
        translation: 'Each of them wants to do something to change their life',
      },
      {
        id: 53,
        expression: 'Все мои друзья были в восторге от этих новостей',
        transcription: 'ɔːl maɪ frɛndz wər ɪkˈsaɪtɪd əˈbaʊt ðɪs njuːz',
        translation: 'All my friends were excited about this news',
      },
      {
        id: 54,
        expression: 'Большинство студентов в его группе имеют средний уровень',
        transcription: 'məʊst əv ˈstjuːdənts ɪn ɪz gruːp həv ən ˈævərɪʤ ˈlɛvl',
        translation: 'Most of students in his group have an average level',
      },
      {
        id: 55,
        expression: 'Все сотрудники были довольны этим решением',
        transcription: 'ɔːl ði ˌɛmplɔɪˈiːz wə ˈsætɪsfaɪd wɪð ðɪs dɪˈsɪʒən',
        translation: 'All the employees were satisfied with this decision',
      },
      {
        id: 56,
        expression: 'Ни один из них не носит очки',
        transcription: 'ˈnaɪðər əv ðəm weəz ðə ˈglɑːsɪz',
        translation: 'Neither of them wears the glasses',
      },
      {
        id: 57,
        expression: 'Ни моим друзьям, ни мне не понравилась эта идея',
        transcription: 'ˈnɛðə maɪ frɛndz nɔːr aɪ laɪkt ðɪs aɪˈdɪə',
        translation: 'Nether my friends nor I liked this idea',
      },
      {
        id: 58,
        expression: 'У некоторых из них другое мнение',
        transcription: 'sʌm əv ðəm həv əˈnʌðər əˈpɪnjən',
        translation: 'Some of them have another opinion',
      },
      {
        id: 59,
        expression: 'Некоторые из них думают по-другому',
        transcription: 'sʌm əv ðəm θɪŋk ˈdɪfrəntli',
        translation: 'Some of them think differently',
      },
      {
        id: 60,
        expression: 'Многие из этих вещей хорошо известны',
        transcription: 'ˈmɛni əv ðiːz θɪŋz ə wɛl-nəʊn',
        translation: 'Many of these things are well-known',
      },
      {
        id: 61,
        expression: 'Большая часть информации была действительно полезной',
        transcription: 'məʊst əv ði ˌɪnfəˈmeɪʃən wəz ˈrɪəli ˈjuːsfʊl',
        translation: 'Most of the information was really useful',
      },
      {
        id: 62,
        expression: 'Вся эта информация была действительно полезной',
        transcription: 'ɔːl ðɪs ˌɪnfəˈmeɪʃən wəz ˈrɪəli ˈjuːsfʊl',
        translation: 'All this information was really useful',
      },
      {
        id: 63,
        expression: 'Ничто из информации не было полезно',
        transcription: 'nʌn əv ði ˌɪnfəˈmeɪʃən wəz ˈjuːsfʊl',
        translation: 'None of the information was useful',
      },
      {
        id: 64,
        expression: 'Ни одно из предложений не является правильным',
        transcription: 'ˈnaɪðər əv ðə ˈsɛntənsɪz ɪz kəˈrɛkt',
        translation: 'Neither of the sentences is correct',
      },
      {
        id: 65,
        expression: 'Все эти предложения верны',
        transcription: 'ɔːl ðiːz ˈsɛntənsɪz ə kəˈrɛkt',
        translation: 'All these sentences are correct',
      },
      {
        id: 66,
        expression: 'Большинство предложений неверны',
        transcription: 'məʊst əv ðə ˈsɛntənsɪz ər ˌɪnkəˈrɛkt',
        translation: 'Most of the sentences are incorrect',
      },
      {
        id: 67,
        expression: 'Такие вещи никогда не беспокоили меня',
        transcription: 'sʌʧ θɪŋz həv ˈnɛvə ˈwʌrid miː',
        translation: 'Such things have never worried me',
      },
      {
        id: 68,
        expression: 'Эти проблемы меня никогда не беспокоили',
        transcription: 'ðiːz ˈprɒbləmz həv ˈnɛvə ˈwʌrid miː',
        translation: 'These problems have never worried me',
      },
      {
        id: 69,
        expression: 'Я никогда не беспокоился о таких вещах',
        transcription: 'aɪv ˈnɛvə ˈwʌrid əˈbaʊt sʌʧ θɪŋz',
        translation: "I've never worried about such things",
      },
      {
        id: 70,
        expression: 'Многие из моих друзей просто игнорируют это',
        transcription: 'ˈmɛni əv maɪ frɛndz ˈsɪmpli ɪgˈnɔːr ɪt',
        translation: 'Many of my friends simply ignore it',
      },
      {
        id: 71,
        expression: 'Все мои друзья всегда игнорируют это',
        transcription: 'ɔːl maɪ frɛndz ˈɔːlweɪz ɪgˈnɔːr ɪt',
        translation: 'All my friends always ignore it',
      },
      {
        id: 72,
        expression: 'Каждый из моих друзей просто игнорирует это',
        transcription: 'iːʧ əv maɪ frɛndz ˈsɪmpli ɪgˈnɔːz ɪt',
        translation: 'Each of my friends simply ignores it',
      },
      {
        id: 73,
        expression: 'Даже она никогда не слышала об этом',
        transcription: 'ˈiːvən ʃi həz ˈnɛvə hɜːd əˈbaʊt ɪt',
        translation: 'Even she has never heard about it',
      },
      {
        id: 74,
        expression: 'Никто из них еще не слышал об этом',
        transcription: 'ˈnaɪðər əv ðəm həz hɜːd əˈbaʊt ɪt jɛt',
        translation: 'Neither of them has heard about it yet',
      },
      {
        id: 75,
        expression: 'Некоторые из моих друзей уже слышали об этом',
        transcription: 'sʌm əv maɪ frɛndz həv ɔːlˈrɛdi hɜːd əˈbaʊt ɪt',
        translation: 'Some of my friends have already heard about it',
      },
      {
        id: 76,
        expression: 'Он пригласил нас обоих',
        transcription: 'hi ɪnˈvaɪtɪd bəʊθ əv ʌs',
        translation: 'He invited both of us',
      },
      {
        id: 77,
        expression: 'Он пригласил всех моих друзей',
        transcription: 'hi ɪnˈvaɪtɪd ɔːl maɪ frɛndz',
        translation: 'He invited all my friends',
      },
      {
        id: 78,
        expression: 'Он не пригласил никого из нас',
        transcription: 'hi ɪnˈvaɪtɪd ˈnaɪðər əv ʌs',
        translation: 'He invited neither of us',
      },
      {
        id: 79,
        expression: 'Некоторые из студентов отсутствовали',
        transcription: 'sʌm əv ðə ˈstjuːdənts wər ˈæbsənt',
        translation: 'Some of the students were absent',
      },
      {
        id: 80,
        expression: 'Все эти студенты отсутствовали',
        transcription: 'ɔːl ðiːz ˈstjuːdənts wər ˈæbsənt',
        translation: 'All these students were absent',
      },
      {
        id: 81,
        expression: 'Никто не присутствовал',
        transcription: 'nəʊ wʌn wəz ˈprɛznt',
        translation: 'No one was present',
      },
      {
        id: 82,
        expression: 'Многие из моих друзей тоже думают так',
        transcription: 'ˈmɛni əv maɪ frɛndz ˈɔːlsəʊ θɪŋk səʊ',
        translation: 'Many of my friends also think so',
      },
      {
        id: 83,
        expression: 'Никто из моих друзей не думает иначе',
        transcription: 'nʌn əv maɪ frɛndz θɪŋk ˈdɪfrəntli (ˈʌðəwaɪz)',
        translation: 'None of my friends think differently (otherwise)',
      },
      {
        id: 84,
        expression: 'Большинство из них тоже думает так',
        transcription: 'məʊst əv ðəm ˈɔːlsəʊ θɪŋk səʊ',
        translation: 'Most of them also think so',
      },
      {
        id: 85,
        expression: 'Никто из моих друзей не понимает этого',
        transcription: 'nʌn əv maɪ frɛndz ˌʌndəˈstænd(ɛs) ɪt',
        translation: 'None of my friends understand(s) it',
      },
      {
        id: 86,
        expression: 'Большинство моих друзей понимают это',
        transcription: 'məʊst əv maɪ frɛndz ˌʌndəˈstænd ɪt',
        translation: 'Most of my friends understand it',
      },
      {
        id: 87,
        expression: 'Каждый из моих друзей понимает это',
        transcription: 'iːʧ əv maɪ frɛndz ˌʌndəˈstændz ɪt',
        translation: 'Each of my friends understands it',
      },
      {
        id: 88,
        expression: 'Большинство этой информации полезно',
        transcription: 'məʊst əv ðɪs ˌɪnfəˈmeɪʃən z ˈjuːsfʊl',
        translation: 'Most of this information is useful',
      },
      {
        id: 89,
        expression: 'Ничто из этой информации неважно',
        transcription: 'nʌn əv ðɪs ˌɪnfəˈmeɪʃən z ɪmˈpɔːtənt',
        translation: 'None of this information is important',
      },
      {
        id: 90,
        expression: 'Вся эта информация действительно полезна',
        transcription: 'ɔːl ðɪs ˌɪnfəˈmeɪʃən z ˈrɪəli ˈjuːsfʊl',
        translation: 'All this information is really useful',
      },
      {
        id: 91,
        expression: 'Я чувствую, что тебя что-то беспокоит',
        transcription: 'aɪ fiːl ðət ˈsʌmθɪŋ ˈwʌriz juː',
        translation: 'I feel that something worries you',
      },
      {
        id: 92,
        expression: 'С того времени ничего не меняется',
        transcription: 'ˈnʌθɪŋ həz biːn ˈʧeɪnʤɪŋ sɪns ðət taɪm',
        translation: 'Nothing has been changing since that time',
      },
      {
        id: 93,
        expression: 'Кто-то только что постучал в дверь',
        transcription: 'ˈsʌmwʌn həz ʤəst nɒkt ət ðə dɔː',
        translation: 'Someone has just knocked at the door',
      },
      {
        id: 94,
        expression: 'Я живу здесь всю свою жизнь',
        transcription: 'aɪv biːn ˈlɪvɪŋ hɪər ɔːl maɪ laɪf',
        translation: "I've been living here all my life",
      },
      {
        id: 95,
        expression: 'Ни одно из утверждений не является верным',
        transcription: 'ˈnaɪðər əv ðə ˈsteɪtmənts ɪz truː',
        translation: 'Neither of the statements is true',
      },
      {
        id: 96,
        expression: 'Она пригласила их обоих',
        transcription: 'ʃi ɪnˈvaɪtɪd bəʊθ əv ðɛm',
        translation: 'She invited both of them',
      },
      {
        id: 97,
        expression: 'Даже он никогда не слышал об этой вещи',
        transcription: 'ˈiːvən hi həz ˈnɛvə hɜːd əˈbaʊt ðɪs θɪŋ',
        translation: 'Even he has never heard about this thing',
      },
      {
        id: 98,
        expression: 'Все молоко было выпито',
        transcription: 'ɔːl ðə mɪlk wəz drʌŋk',
        translation: 'All the milk was drunk',
      },
      {
        id: 99,
        expression: 'Такого рода вещи никогда не беспокоили меня',
        transcription:
          'ðɪs kaɪnd əv θɪŋz həz ˈnɛvə ˈwʌrid miː / ðiːz kaɪndz əv θɪŋz həv ˈnɛvə ˈwʌrid miː',
        translation:
          'This kind of things has never worried me / These kinds of things have never worried me',
      },
      {
        id: 100,
        expression: 'Я никогда не хотел делать это, когда я жил там',
        transcription: 'aɪv ˈnɛvə wɒnt tə dʊ ɪt wɛn aɪ lɪvd ðeə',
        translation: "I've never want to do it when I lived there",
      },
      {
        id: 101,
        expression: 'Никто из нас не был голоден',
        transcription: 'ˈnaɪðər əv əs wəz ˈhʌŋgri',
        translation: 'Neither of us was hungry',
      },
      {
        id: 102,
        expression: 'Весь хлеб был съеден',
        transcription: 'ɔːl ðə brɛd wəz ˈiːtn',
        translation: 'All the bread was eaten',
      },
      {
        id: 103,
        expression: 'Она приветствовала всех гостей',
        transcription: 'ʃi ˈwɛlkəmd ɔːl ðə gɛsts',
        translation: 'She welcomed all the guests',
      },
      {
        id: 104,
        expression: 'Каждый из нас это понимает',
        transcription: 'iːʧ əv əs ˌʌndəˈstændz ɪt',
        translation: 'Each of us understands it',
      },
      {
        id: 105,
        expression: 'Ничто не может остановить его',
        transcription: 'ˈnʌθɪŋ kən stɒp hɪm',
        translation: 'Nothing can stop him',
      },
    ],
    {
      theory: `<div class="theory-block">
<h3>everyone (каждый), everything (всё), something (что-то), someone (кто-то)</h3>
<p>Нужно запомнить, что эти слова всегда стоят в единственном числе</p>
<p>Somebody does it - Кто-то делает это.</p>
<p>Everything is here - Всё здесь.</p>
<h3>never - никогда не</h3>
<p>С never дополнительного отрицания не требуется</p>
<p>I'll never go there - Я никогда туда не пойду.</p>
</div>`,
    },
  ],
];
