export const contentLesson64 = [
  [
    {
      title: "Урок 64. Present Simple. Глагол to be: Question",
    },
    [
      {
        id: 1,
        expression: "Я хороший специалист?",
        transcription: "əm aɪ ə gʊd ˈspɛʃəlɪst?",
        translation: "Am I a good specialist?",
      },
      {
        id: 2,
        expression: "Они хорошие студенты?",
        transcription: "ɑː ðeɪ gʊd ˈstjuːdənts?",
        translation: "Are they good students?",
      },
      {
        id: 3,
        expression: "Это традиционная еда?",
        transcription: "ɪz ɪt trəˈdɪʃənl fuːd?",
        translation: "Is it traditional food?",
      },
      {
        id: 4,
        expression: "Это дешевая вещь?",
        transcription: "ɪz ɪt ə ʧiːp θɪŋ?",
        translation: "Is it a cheap thing?",
      },
      {
        id: 5,
        expression: "Это официальный документ?",
        transcription: "ɪz ɪt ən əˈfɪʃəl ˈdɒkjʊmənt?",
        translation: "Is it an official document?",
      },
      {
        id: 6,
        expression: "Это шумное место?",
        transcription: "ɪt ɪt ə ˈnɔɪzi pleɪs?",
        translation: "It it a noisy place?",
      },
      {
        id: 7,
        expression: "Это традиционный метод?",
        transcription: "ɪz ɪt ə trəˈdɪʃənl ˈmɛθəd?",
        translation: "Is it a traditional method?",
      },
      {
        id: 8,
        expression: "Ты сейчас в Америке?",
        transcription: "ɑː jʊ ɪn əˈmɛrɪkə naʊ?",
        translation: "Are you in America now?",
      },
      {
        id: 9,
        expression: "Он из Бразилии?",
        transcription: "ɪz hi frəm brəˈzɪl?",
        translation: "Is he from Brazil?",
      },
      {
        id: 10,
        expression: "Они сестры?",
        transcription: "ɑː ðeɪ ˈsɪstəz?",
        translation: "Are they sisters?",
      },
      {
        id: 11,
        expression: "Он твой двоюродный брат?",
        transcription: "ɪz hi jə ˈkʌzn?",
        translation: "Is he your cousin?",
      },
      {
        id: 12,
        expression: "Это лучший ресторан в этой области?",
        transcription: "ɪz ɪt ðə bɛst ˈrɛstrɒnt ɪn ðɪs ˈeərɪə?",
        translation: "Is it the best restaurant in this area?",
      },
      {
        id: 13,
        expression: "Он британец?",
        transcription: "ɪz hi ˈbrɪtɪʃ?",
        translation: "Is he British?",
      },
      {
        id: 14,
        expression: "Это голубая ручка?",
        transcription: "ɪz ɪt ə bluː pɛn?",
        translation: "Is it a blue pen?",
      },
      {
        id: 15,
        expression: "Они американцы?",
        transcription: "ɑː ðeɪ əˈmɛrɪkənz?",
        translation: "Are they Americans?",
      },
      {
        id: 16,
        expression: "Это его родный язык?",
        transcription: "ɪz ɪt ɪz ˈmʌðə tʌŋ?",
        translation: "Is it his mother tongue?",
      },
      {
        id: 17,
        expression: "Они хорошие специалисты?",
        transcription: "ɑː ðeɪ gʊd ˈspɛʃəlɪsts?",
        translation: "Are they good specialists?",
      },
      {
        id: 18,
        expression: "Это старое здание?",
        transcription: "ɪz ɪt ən əʊld ˈbɪldɪŋ?",
        translation: "Is it an old building?",
      },
      {
        id: 19,
        expression: "Ты действительно серьезно?",
        transcription: "ɑː jʊ ˈrɪəli ˈsɪərɪəs?",
        translation: "Are you really serious?",
      },
      {
        id: 20,
        expression: "Это твое любимое блюдо?",
        transcription: "ɪz ɪt jə ˈfeɪvərɪt dɪʃ?",
        translation: "Is it your favourite dish?",
      },
      {
        id: 21,
        expression: "Это важная вещь?",
        transcription: "ɪz ɪt ən ɪmˈpɔːtənt θɪŋ?",
        translation: "Is it an important thing?",
      },
      {
        id: 22,
        expression: "Он хороший специалист?",
        transcription: "ɪz hi ə gʊd ˈspɛʃəlɪst?",
        translation: "Is he a good specialist?",
      },
      {
        id: 23,
        expression: "Это бесплатно или нет?",
        transcription: "ɪz ɪt friː ɔː nɒt?",
        translation: "Is it free or not?",
      },
      {
        id: 24,
        expression: "Они высокие мальчики?",
        transcription: "ɑː ðeɪ tɔːl bɔɪz?",
        translation: "Are they tall boys?",
      },
      {
        id: 25,
        expression: "Это хороший результат для тебя?",
        transcription: "ɪz ɪt ə gʊd rɪˈzʌlt fə juː?",
        translation: "Is it a good result for you?",
      },
      {
        id: 26,
        expression: "Это высокий уровень?",
        transcription: "ɪz ɪt ə haɪ ˈlɛvl?",
        translation: "Is it a high level?",
      },
      {
        id: 27,
        expression: "Он твой любимый певец?",
        transcription: "ɪz hi jə ˈfeɪvərɪt ˈsɪŋə?",
        translation: "Is he your favorite singer?",
      },
      {
        id: 28,
        expression: "Это твой родной язык?",
        transcription: "ɪz ɪt jə ˈmʌðə tʌŋ?",
        translation: "Is it your mother tongue?",
      },
      {
        id: 29,
        expression: "Это длинная история?",
        transcription: "ɪz ɪt ə lɒŋ ˈstɔːri?",
        translation: "Is it a long story?",
      },
      {
        id: 30,
        expression: "Он твой брат?",
        transcription: "ɪz hi jə ˈbrʌðə?",
        translation: "Is he your brother?",
      },
      {
        id: 31,
        expression: "Это хорошая идея?",
        transcription: "ɪz ɪt ə gʊd aɪˈdɪə?",
        translation: "Is it a good idea?",
      },
      {
        id: 32,
        expression: "Ты из Испании?",
        transcription: "ɑː jʊ frəm speɪn?",
        translation: "Are you from Spain?",
      },
      {
        id: 33,
        expression: "Он холост?",
        transcription: "ɪz hi ˈsɪŋgl?",
        translation: "Is he single?",
      },
      {
        id: 34,
        expression: "Это тихое место?",
        transcription: "ɪz ɪt ə ˈkwaɪət pleɪs?",
        translation: "Is it a quiet place?",
      },
      {
        id: 35,
        expression: "Они братья?",
        transcription: "ɑː ðeɪ ˈbrʌðəz?",
        translation: "Are they brothers?",
      },
      {
        id: 36,
        expression: "Это твой любимый фильм?",
        transcription: "ɪz ɪt jə ˈfeɪvərɪt ˈmuːvi?",
        translation: "Is it your favourite movie?",
      },
      {
        id: 37,
        expression: "Он испанец?",
        transcription: "ɪz hi ˈspænɪʃ?",
        translation: "Is he Spanish?",
      },
      {
        id: 38,
        expression: "Это другой пример?",
        transcription: "ɪz ɪt ən əˈnʌðər ɪgˈzɑːmpl?",
        translation: "Is it an another example?",
      },
      {
        id: 39,
        expression: "Это тяжелая коробка?",
        transcription: "ɪz ɪt ə ˈhɛvi bɒks?",
        translation: "Is it a heavy box?",
      },
      {
        id: 40,
        expression: "Ты офлайн сейчас?",
        transcription: "ɑː jʊ ˌɒfˈlaɪn naʊ?",
        translation: "Are you offline now?",
      },
      {
        id: 41,
        expression: "Они твои двоюродные братья?",
        transcription: "ɑː ðeɪ jə ˈkʌznz?",
        translation: "Are they your cousins?",
      },
      {
        id: 42,
        expression: "Ты онлайн сейчас?",
        transcription: "ɑː jʊ ˈɒnˌlaɪn naʊ?",
        translation: "Are you online now?",
      },
      {
        id: 43,
        expression: "Это черный карандаш?",
        transcription: "ɪz ɪt ə blæk ˈpɛnsl?",
        translation: "Is it a black pencil?",
      },
      {
        id: 44,
        expression: "Это неважная вещь?",
        transcription: "ɪz ɪt ən ˌʌnɪmˈpɒtənt θɪŋ?",
        translation: "Is it an unimportant thing?",
      },
      {
        id: 45,
        expression: "Ты интересуешься иностранными языками?",
        transcription: "ɑː jʊ ˈɪntrɪstɪd ɪn ˈfɒrɪn ˈlæŋgwɪʤɪz?",
        translation: "Are you interested in foreign languages?",
      },
      {
        id: 46,
        expression: "Ты действительно шокирован?",
        transcription: "ɑː jʊ ˈrɪəli ʃɒkt?",
        translation: "Are you really shocked?",
      },
      {
        id: 47,
        expression: "Это для тебя большое достижение?",
        transcription: "ɪz ɪt ə bɪg əˈʧiːvmənt fə juː?",
        translation: "Is it a big achievement for you?",
      },
      {
        id: 48,
        expression: "Ты действительно уверен в этом?",
        transcription: "ɑː jʊ ˈrɪəli ʃʊər əˈbaʊt ɪt?",
        translation: "Are you really sure about it?",
      },
      {
        id: 49,
        expression: "Это далеко или близко?",
        transcription: "ɪz ɪt fɑːr ɔː nɪə?",
        translation: "Is it far or near?",
      },
      {
        id: 50,
        expression: "Ты действительно удивлен?",
        transcription: "ɑː jʊ ˈrɪəli səˈpraɪzd?",
        translation: "Are you really surprised?",
      },
      {
        id: 51,
        expression: "Это недорогие часы?",
        transcription: "ɪz ɪt ən ˌɪnɪksˈpɛnsɪv wɒʧ?",
        translation: "Is it an inexpensive watch?",
      },
      {
        id: 52,
        expression: "Ты гордишься своими достижениями?",
        transcription: "ɑː jʊ praʊd əv jər əˈʧiːvmənts?",
        translation: "Are you proud of your achievements?",
      },
      {
        id: 53,
        expression: "Это действительно необходимо сделать завтра?",
        transcription: "ɪz ɪt ˈrɪəli ˈnɛsɪsəri tə dʊ ɪt təˈmɒrəʊ?",
        translation: "Is it really necessary to do it tomorrow?",
      },
      {
        id: 54,
        expression: "Он действительно устал от этого?",
        transcription: "ɪz hi ˈrɪəli ˈtaɪəd əv ɪt?",
        translation: "Is he really tired of it?",
      },
      {
        id: 55,
        expression: "Это полезное приложение?",
        transcription: "ɪz ɪt ə ˈjuːsfʊl æp?",
        translation: "Is it a useful app?",
      },
      {
        id: 56,
        expression: "Они рядом с этим местом?",
        transcription: "ɑː ðeɪ nɪə ðɪs pleɪs?",
        translation: "Are they near this place?",
      },
      {
        id: 57,
        expression: "Это необходимо сделать?",
        transcription: "ɪz ɪt ˈnɛsɪsəri tə dʊ ɪt?",
        translation: "Is it necessary to do it?",
      },
      {
        id: 58,
        expression: "Это рядом с тем местом?",
        transcription: "ɪz ɪt nɪə ðət pleɪs?",
        translation: "Is it near that place?",
      },
      {
        id: 59,
        expression: "Ты действительно устал?",
        transcription: "ɑː jʊ ˈrɪəli ˈtaɪəd?",
        translation: "Are you really tired?",
      },
      {
        id: 60,
        expression: "Ты устал?",
        transcription: "ɑː jʊ ˈtaɪəd?",
        translation: "Are you tired?",
      },
      {
        id: 61,
        expression: "Он действительно устал?",
        transcription: "ɪz hi ˈrɪəli ˈtaɪəd?",
        translation: "Is he really tired?",
      },
      {
        id: 62,
        expression: "Это слева?",
        transcription: "ɪz ɪt ɒn ðə lɛft?",
        translation: "Is it on the left?",
      },
      {
        id: 63,
        expression: "Это справа?",
        transcription: "ɪz ɪt ɒn ðə raɪt?",
        translation: "Is it on the right?",
      },
      {
        id: 64,
        expression: "Это с левой стороны стола?",
        transcription: "ɪz ɪt ɒn ðə lɛft saɪd əv ðə ˈteɪbl?",
        translation: "Is it on the left side of the table?",
      },
      {
        id: 65,
        expression: "Он заинтересован в этом проекте?",
        transcription: "ɪz hi ˈɪntrɪstɪd ɪn ðɪs ˈprɒʤɛkt?",
        translation: "Is he interested in this project?",
      },
      {
        id: 66,
        expression: "Они заинтересованы в этом проекте?",
        transcription: "ɑː ðeɪ ˈɪntrɪstɪd ɪn ðɪs ˈprɒʤɛkt?",
        translation: "Are they interested in this project?",
      },
      {
        id: 67,
        expression: "Ты заинтересован в этой работе?",
        transcription: "ɑː jʊ ˈɪntrɪstɪd ɪn ðɪs ʤɒb?",
        translation: "Are you interested in this job?",
      },
      {
        id: 68,
        expression: "Это неверно?",
        transcription: "ɪz ɪt rɒŋ? / ɪz ɪt ˌɪnkəˈrɛkt?",
        translation: "Is it wrong? / Is it incorrect?",
      },
      {
        id: 69,
        expression: "Этот ответ неверный?",
        transcription: "ɪz ðɪs ˈɑːnsə rɒŋ? / ɪz ðɪs ˈɑːnsər ˌɪnkəˈrɛkt?",
        translation: "Is this answer wrong? / Is this answer incorrect?",
      },
      {
        id: 70,
        expression: "Это действительно верно?",
        transcription: "ɪz ɪt ˈrɪəli kəˈrɛkt?",
        translation: "Is it really correct?",
      },
      {
        id: 71,
        expression: "Он носитель английского языка?",
        transcription: "ɪz hi ə ˈneɪtɪv ˈspiːkər əv ˈɪŋglɪʃ?",
        translation: "Is he a native speaker of English?",
      },
      {
        id: 72,
        expression: "Они носители английского языка?",
        transcription: "ɑː ðeɪ ˈneɪtɪv ˈspiːkəz əv ˈɪŋglɪʃ?",
        translation: "Are they native speakers of English?",
      },
      {
        id: 73,
        expression: "Ты носитель английского языка?",
        transcription: "ɑː jʊ ə ˈneɪtɪv ˈspiːkər əv ˈɪŋglɪʃ?",
        translation: "Are you a native speaker of English?",
      },
      {
        id: 74,
        expression: "Это верно или нет?",
        transcription: "ɪz ɪt kəˈrɛkt ɔː nɒt?",
        translation: "Is it correct or not?",
      },
      {
        id: 75,
        expression: "Это верно?",
        transcription: "ɪz ɪt kəˈrɛkt?",
        translation: "Is it correct?",
      },
      {
        id: 76,
        expression: "Он очень осторожный водитель?",
        transcription: "ɪz hi ə ˈvɛri ˈkeəfʊl ˈdraɪvə?",
        translation: "Is he a very careful driver?",
      },
      {
        id: 77,
        expression: "Ты осторожный водитель?",
        transcription: "ɑː jʊ ə ˈkeəfʊl ˈdraɪvə?",
        translation: "Are you a careful driver?",
      },
      {
        id: 78,
        expression: "Они очень осторожные водители?",
        transcription: "ɑː ðeɪ ˈvɛri ˈkeəfʊl ˈdraɪvəz?",
        translation: "Are they very careful drivers?",
      },
      {
        id: 79,
        expression: "Это полезная вещь?",
        transcription: "ɪz ɪt ə ˈjuːsfʊl θɪŋ?",
        translation: "Is it a useful thing?",
      },
      {
        id: 80,
        expression: "Это хорошая вещь?",
        transcription: "ɪz ɪt ə gʊd θɪŋ?",
        translation: "Is it a good thing?",
      },
      {
        id: 81,
        expression: "Он гордится этим успехом?",
        transcription: "ɪz hi praʊd əv ðɪs səkˈsɛs?",
        translation: "Is he proud of this success?",
      },
      {
        id: 82,
        expression: "Ты гордишься своим успехом?",
        transcription: "ɑː jʊ praʊd əv jə səkˈsɛs?",
        translation: "Are you proud of your success?",
      },
      {
        id: 83,
        expression: "Ты гордишься своей матерью?",
        transcription: "ɑː jʊ praʊd əv jə ˈmʌðə?",
        translation: "Are you proud of your mother?",
      },
      {
        id: 84,
        expression: "Ты также заинтересован в этом?",
        transcription: "ɑː jʊ ˈɔːlsəʊ ˈɪntrɪstɪd ɪn ɪt?",
        translation: "Are you also interested in it?",
      },
      {
        id: 85,
        expression: "Они также заинтересованы в этом?",
        transcription: "ɑː ðeɪ ˈɔːlsəʊ ˈɪntrɪstɪd ɪn ɪt?",
        translation: "Are they also interested in it?",
      },
      {
        id: 86,
        expression: "Она также заинтересована в этом?",
        transcription: "ɪz ʃi ˈɔːlsəʊ ˈɪntrɪstɪd ɪn ɪt?",
        translation: "Is she also interested in it?",
      },
      {
        id: 87,
        expression: "Он женат на ней?",
        transcription: "ɪz hi ˈmærɪd tə hɜː?",
        translation: "Is he married to her?",
      },
      {
        id: 88,
        expression: "Она интересуется музыкой?",
        transcription: "ɪz ʃi ˈɪntrɪstɪd ɪn ˈmjuːzɪk?",
        translation: "Is she interested in music?",
      },
      {
        id: 89,
        expression: "Ты действительно удивлен слышать это?",
        transcription: "ɑː jʊ ˈrɪəli səˈpraɪzd tə hɪər ɪt?",
        translation: "Are you really surprised to hear it?",
      },
      {
        id: 90,
        expression: "Она замужем за ним?",
        transcription: "ɪz ʃi ˈmærɪd tə hɪm?",
        translation: "Is she married to him?",
      },
      {
        id: 91,
        expression: "Это очень дорогая вещь?",
        transcription: "ɪz ɪt ə ˈvɛri ɪksˈpɛnsɪv θɪŋ?",
        translation: "Is it a very expensive thing?",
      },
      {
        id: 92,
        expression: "Она носитель английского языка?",
        transcription: "ɪz ʃi ə ˈneɪtɪv ˈspiːkər əv ˈɪŋglɪʃ?",
        translation: "Is she a native speaker of English?",
      },
      {
        id: 93,
        expression: "Это необходимый шаг?",
        transcription: "ɪz ɪt ə ˈnɛsɪsəri stɛp?",
        translation: "Is it a necessary step?",
      },
      {
        id: 94,
        expression: "Ты гордишься своими результатами?",
        transcription: "ɑː jʊ praʊd əv jə rɪˈzʌlts?",
        translation: "Are you proud of your results?",
      },
      {
        id: 95,
        expression: "Она действительно устала от этой рутины?",
        transcription: "ɪz ʃi ˈrɪəli ˈtaɪəd əv ðɪs ruːˈtiːn?",
        translation: "Is she really tired of this routine?",
      },
      {
        id: 96,
        expression: "Это важное правило или нет?",
        transcription: "ɪz ɪt ən ɪmˈpɔːtənt ruːl ɔː nɒt?",
        translation: "Is it an important rule or not?",
      },
      {
        id: 97,
        expression: "Он гордится своими достижениями?",
        transcription: "ɪz hi praʊd əv ɪz əˈʧiːvmənts?",
        translation: "Is he proud of his achievements?",
      },
      {
        id: 98,
        expression: "Это недорогая вещь?",
        transcription: "ɪz ɪt ˌɪnɪksˈpɛnsɪv θɪŋ?",
        translation: "Is it inexpensive thing?",
      },
      {
        id: 99,
        expression: "Это действительно необходимо?",
        transcription: "ɪz ɪt ˈrɪəli ˈnɛsɪsəri?",
        translation: "Is it really necessary?",
      },
      {
        id: 100,
        expression: "Это полезное устройство?",
        transcription: "ɪz ɪt ə ˈjuːsfʊl dɪˈvaɪs?",
        translation: "Is it a useful device?",
      },
    ],
    {
      theory: `<div class="theory-block">
<h3>Закрепление пройденного материала</h3>
</div>`,
    },
  ],
];
