export const contentLesson66 = [
  [
    {
      title: "Урок 66. Present Simple: сложные подлежащие + Question",
    },
    [
      {
        id: 1,
        expression: "Много людей посещают эту страну?",
        transcription: "dʊ ˈmɛni ˈpiːpl ˈvɪzɪt ðɪs ˈkʌntri?",
        translation: "Do many people visit this country?",
      },
      {
        id: 2,
        expression: "Твой друг верит тебе?",
        transcription: "dəz jə frɛnd bɪˈliːv juː?",
        translation: "Does your friend believe you?",
      },
      {
        id: 3,
        expression: "Твое образование помогает тебе?",
        transcription: "dəz jər ˌɛdju(ː)ˈkeɪʃən hɛlp juː?",
        translation: "Does your education help you?",
      },
      {
        id: 4,
        expression: "Дети часто остаются дома?",
        transcription: "dʊ ðə ˈʧɪldrən ˈɒf(ə)n steɪ ət həʊm?",
        translation: "Do the children often stay at home?",
      },
      {
        id: 5,
        expression: "Твой учитель проверяет твою домашнюю работу?",
        transcription: "dəz jə ˈtiːʧə ʧɛk jə ˈhəʊmˌwɜːk?",
        translation: "Does your teacher check your homework?",
      },
      {
        id: 6,
        expression: "Твой брат занимается плаванием дважды в неделю?",
        transcription: "dəz jə ˈbrʌðə gəʊ ˈswɪmɪŋ twaɪs ə wiːk?",
        translation: "Does your brother go swimming twice a week?",
      },
      {
        id: 7,
        expression: "Твои друзья верят тебе?",
        transcription: "dʊ jə frɛndz bɪˈliːv juː?",
        translation: "Do your friends believe you?",
      },
      {
        id: 8,
        expression: "Эта вещь действительно так сильно тебя интересует?",
        transcription: "dəz ðɪs θɪŋ ˈrɪəli ˈɪntrɪst jʊ səʊ mʌʧ?",
        translation: "Does this thing really interest you so much?",
      },
      {
        id: 9,
        expression: "Дети в этой группе показывают очень хорошие результаты?",
        transcription: "dʊ ðə ˈʧɪldrən ɪn ðɪs gruːp ʃəʊ ˈvɛri gʊd rɪˈzʌlts?",
        translation: "Do the children in this group show very good results?",
      },
      {
        id: 10,
        expression: "Много людей выбирают этот отель?",
        transcription: "dʊ ˈmɛni ˈpiːpl ʧuːz ðɪs həʊˈtɛl?",
        translation: "Do many people choose this hotel?",
      },
      {
        id: 11,
        expression: "Образование играет важную роль в нашей жизни?",
        transcription:
          "dəz ˌɛdju(ː)ˈkeɪʃən pleɪ ən ɪmˈpɔːtənt rəʊl ɪn ˈaʊə laɪf?",
        translation: "Does education play an important role in our life?",
      },
      {
        id: 12,
        expression: "Ее дочь ходит в колледж?",
        transcription: "dəz hə ˈdɔːtə gəʊ tə ˈkɒlɪʤ?",
        translation: "Does her daughter go to college?",
      },
      {
        id: 13,
        expression: "Много людей читают книги?",
        transcription: "dʊ ˈmɛni ˈpiːpl riːd bʊks?",
        translation: "Do many people read books?",
      },
      {
        id: 14,
        expression: "Эти вещи тебя интересуют?",
        transcription: "dʊ ðiːz θɪŋz ˈɪntrɪst juː?",
        translation: "Do these things interest you?",
      },
      {
        id: 15,
        expression: "Твой учитель дает тебе слишком много домашней работы?",
        transcription: "dəz jə ˈtiːʧə gɪv jʊ tuː mʌʧ ˈhəʊmˌwɜːk?",
        translation: "Does your teacher give you too much homework?",
      },
      {
        id: 16,
        expression: "Твои родители это понимают?",
        transcription: "dʊ jə ˈpeərənts ˌʌndəˈstænd ɪt?",
        translation: "Do your parents understand it?",
      },
      {
        id: 17,
        expression: "Твой друг это знает?",
        transcription: "dəz jə frɛnd nəʊ ɪt?",
        translation: "Does your friend know it?",
      },
      {
        id: 18,
        expression: "Твой друг ходит в университет?",
        transcription: "dəz jə frɛnd gəʊ tə ˌjuːnɪˈvɜːsɪti?",
        translation: "Does your friend go to university?",
      },
      {
        id: 19,
        expression: "Кейт понимает этот урок?",
        transcription: "dəz keɪt ˌʌndəˈstænd ðɪs ˈlɛsn?",
        translation: "Does Kate understand this lesson?",
      },
      {
        id: 20,
        expression: "Много людей посещают эту страну?",
        transcription: "dʊ ˈmɛni ˈpiːpl ˈvɪzɪt ðɪs ˈkʌntri?",
        translation: "Do many people visit this country?",
      },
      {
        id: 21,
        expression: "Тебя интересует музыка?",
        transcription: "dəz ˈmjuːzɪk ˈɪntrɪst juː?",
        translation: "Does music interest you?",
      },
      {
        id: 22,
        expression: "Полиция контролирует это?",
        transcription: "dʊ ðə pəˈliːs kənˈtrəʊl ɪt?",
        translation: "Do the police control it?",
      },
      {
        id: 23,
        expression: "Твоему другу нравится футбол?",
        transcription: "dəz jə frɛnd laɪk ˈfʊtbɔːl?",
        translation: "Does your friend like football?",
      },
      {
        id: 24,
        expression: "Эти билеты стоят меньше?",
        transcription: "dʊ ðiːz ˈtɪkɪts kɒst lɛs?",
        translation: "Do these tickets cost less?",
      },
      {
        id: 25,
        expression: "Его родители верят ему?",
        transcription: "dʊ ɪz ˈpeərənts bɪˈliːv hɪm?",
        translation: "Do his parents believe him?",
      },
      {
        id: 26,
        expression: "Ник часто играет в компьютерные игры?",
        transcription: "dəz nɪk ˈɒf(ə)n pleɪ kəmˈpjuːtə geɪmz?",
        translation: "Does Nick often play computer games?",
      },
      {
        id: 27,
        expression: "То приложение кажется очень полезным?",
        transcription: "dəz ðət ˌæplɪˈkeɪʃ(ə)n siːm ˈvɛri ˈjuːsfʊl?",
        translation: "Does that application seem very useful?",
      },
      {
        id: 28,
        expression: "Его сын работает или учится?",
        transcription: "dəz ɪz sʌn wɜːk ɔː ˈstʌdi?",
        translation: "Does his son work or study?",
      },
      {
        id: 29,
        expression: "Тот курс кажется хуже?",
        transcription: "dəz ðət kɔːs siːm wɜːs?",
        translation: "Does that course seem worse?",
      },
      {
        id: 30,
        expression: "Приложение действительно помогает?",
        transcription: "dəz ði ˌæplɪˈkeɪʃ(ə)n ˈrɪəli hɛlp?",
        translation: "Does the application really help?",
      },
      {
        id: 31,
        expression: "Эти вещи кажутся очень важными?",
        transcription: "dʊ ðiːz θɪŋz siːm ˈvɛri ɪmˈpɔːtənt?",
        translation: "Do these things seem very important?",
      },
      {
        id: 32,
        expression: "Этот курс кажется лучше?",
        transcription: "dəz ðɪs kɔːs siːm ˈbɛtə?",
        translation: "Does this course seem better?",
      },
      {
        id: 33,
        expression: "Твои родители работают?",
        transcription: "dʊ jə ˈpeərənts wɜːk?",
        translation: "Do your parents work?",
      },
      {
        id: 34,
        expression: "Твой босс приходит на работу каждый день?",
        transcription: "dəz jə bɒs kʌm tə wɜːk ˈɛvri deɪ?",
        translation: "Does your boss come to work every day?",
      },
      {
        id: 35,
        expression: "Твой брат всегда так рано встает?",
        transcription: "dəz jə ˈbrʌðər ˈɔːlweɪz gɛt ʌp səʊ ˈɜːli?",
        translation: "Does your brother always get up so early?",
      },
      {
        id: 36,
        expression: "Полиция все контролирует?",
        transcription: "dʊ ðə pəˈliːs kənˈtrəʊl ˈɛvrɪθɪŋ?",
        translation: "Do the police control everything?",
      },
      {
        id: 37,
        expression: "Ребенок кажется очень талантливым?",
        transcription: "dəz ðə ʧaɪld siːm ˈvɛri ˈtæləntɪd?",
        translation: "Does the child seem very talented?",
      },
      {
        id: 38,
        expression: "Эта вещь интересует его?",
        transcription: "dəz ðɪs θɪŋ ˈɪntrɪst hɪm?",
        translation: "Does this thing interest him?",
      },
      {
        id: 39,
        expression: "Курс кажется эффективным?",
        transcription: "dəz ðə kɔːs siːm ɪˈfɛktɪv?",
        translation: "Does the course seem effective?",
      },
      {
        id: 40,
        expression: "Эта история кажется очень смешной?",
        transcription: "dəz ðɪs ˈstɔːri siːm ˈvɛri ˈfʌni?",
        translation: "Does this story seem very funny?",
      },
      {
        id: 41,
        expression: "Твоя сестра ходит в колледж?",
        transcription: "dəz jə ˈsɪstə gəʊ tə ˈkɒlɪʤ?",
        translation: "Does your sister go to college?",
      },
      {
        id: 42,
        expression: "Это интересует тебя?",
        transcription: "dəz ɪt ˈɪntrɪst juː?",
        translation: "Does it interest you?",
      },
      {
        id: 43,
        expression:
          "Тот университет предоставляет отличные условия для обучения?",
        transcription:
          "dəz ðət ˌjuːnɪˈvɜːsɪti prəˈvaɪd ˈɛksələnt kənˈdɪʃənz fər ˌɛdju(ː)ˈkeɪʃən?",
        translation:
          "Does that university provide excellent conditions for education?",
      },
      {
        id: 44,
        expression: "Этот мужчина работает водителем такси?",
        transcription: "dəz ðɪs mæn wɜːk əz ə ˈtæksi ˈdraɪvə?",
        translation: "Does this man work as a taxi driver?",
      },
      {
        id: 45,
        expression: "Эта школа предоставляет очень хорошие условия?",
        transcription: "dəz ðɪs skuːl prəˈvaɪd ˈvɛri gʊd kənˈdɪʃənz?",
        translation: "Does this school provide very good conditions?",
      },
      {
        id: 46,
        expression: "Твой учитель указывает на твои ошибки?",
        transcription: "dəz jə ˈtiːʧə pɔɪnt aʊt jə mɪsˈteɪks?",
        translation: "Does your teacher point out your mistakes?",
      },
      {
        id: 47,
        expression: "Твой знакомый работает инструктором по фитнесу?",
        transcription: "dəz jər əˈkweɪntəns wɜːk əz ə ˈfɪtnɪs ɪnˈstrʌktə?",
        translation: "Does your acquaintance work as a fitness instructor?",
      },
      {
        id: 48,
        expression: "Большинство иммигрантов адаптируются к этим условиям?",
        transcription: "dʊ məʊst ˈɪmɪgrənts əˈdæpt tə ðiːz kənˈdɪʃənz?",
        translation: "Do most immigrants adapt to these conditions?",
      },
      {
        id: 49,
        expression: "Твой лучший друг разделяет твою точку зрения?",
        transcription: "dəz jə bɛst frɛnd ʃeə jə pɔɪnt əv vjuː?",
        translation: "Does your best friend share your point of view?",
      },
      {
        id: 50,
        expression: "Этот мужчина страдает от депрессии?",
        transcription: "dəz ðɪs mæn ˈsʌfə frəm dɪˈprɛʃən?",
        translation: "Does this man suffer from depression?",
      },
      {
        id: 51,
        expression:
          "Ты думаешь, что деньги играют очень важную роль в нашей жизни?",
        transcription:
          "dʊ jʊ θɪŋk ðət ˈmʌni pleɪ ə ˈvɛri ɪmˈpɔːtənt rəʊl ɪn ˈaʊə laɪf?",
        translation:
          "Do you think that money play a very important role in our life?",
      },
      {
        id: 52,
        expression: "Много людей страдают от депрессии?",
        transcription: "dʊ ˈmɛni ˈpiːpl ˈsʌfə frəm dɪˈprɛʃən?",
        translation: "Do many people suffer from depression?",
      },
      {
        id: 53,
        expression: "То сообщество растет очень медленно?",
        transcription: "dəz ðət kəˈmjuːnɪti grəʊ ˈvɛri ˈsləʊli?",
        translation: "Does that community grow very slowly?",
      },
      {
        id: 54,
        expression: "Твоим одноклассникам нравятся объяснения твоего учителя?",
        transcription: "dʊ jə ˈklɑːsmeɪts laɪk jə ˈtiːʧəz ˌɛkspləˈneɪʃənz?",
        translation: "Do your classmates like your teacher's explanations?",
      },
      {
        id: 55,
        expression: "Твоя мама работает бухгалтером?",
        transcription: "dəz jə ˈmʌðə wɜːk əz ən əˈkaʊntənt?",
        translation: "Does your mother work as an accountant?",
      },
      {
        id: 56,
        expression: "У этой фирмы очень плохие продажи?",
        transcription: "dəz ðɪs fɜːm həv ˈvɛri bæd seɪlz?",
        translation: "Does this firm have very bad sales?",
      },
      {
        id: 57,
        expression: "Твой друг работает экономистом?",
        transcription: "dəz jə frɛnd wɜːk əz ən i(ː)ˈkɒnəmɪst?",
        translation: "Does your friend work as an economist?",
      },
      {
        id: 58,
        expression: "Эта компания испытывает очень серьезные трудности?",
        transcription:
          "dəz ðɪs ˈkʌmpəni ɪksˈpɪərɪəns ˈvɛri ˈsɪərɪəs ˈdɪfɪkəltiz?",
        translation: "Does this company experience very serious difficulties?",
      },
      {
        id: 59,
        expression: "Эти компании испытывают очень серьезные трудности?",
        transcription:
          "dʊ ðiːz ˈkʌmpəniz ɪksˈpɪərɪəns ˈvɛri ˈsɪərɪəs ˈdɪfɪkəltiz?",
        translation: "Do these companies experience very serious difficulties?",
      },
      {
        id: 60,
        expression: "У этой компании очень серьезные проблемы?",
        transcription: "dəz ðɪs ˈkʌmpəni həv ˈvɛri ˈsɪərɪəs ˈprɒbləmz?",
        translation: "Does this company have very serious problems?",
      },
      {
        id: 61,
        expression: "Его брат работает журналистом?",
        transcription: "dəz ɪz ˈbrʌðə wɜːk əz ə ˈʤɜːnəlɪst?",
        translation: "Does his brother work as a journalist?",
      },
      {
        id: 62,
        expression: "Твоя сестра работает тренером?",
        transcription: "dəz jə ˈsɪstə wɜːk əz ə ˈtreɪnə?",
        translation: "Does your sister work as a trainer?",
      },
      {
        id: 63,
        expression: "Ты работаешь учителем?",
        transcription: "dʊ jʊ wɜːk əz ə ˈtiːʧə?",
        translation: "Do you work as a teacher?",
      },
      {
        id: 64,
        expression: "Эти иммигранты живут в Соединенных Штатах?",
        transcription: "dʊ ðiːz ˈɪmɪgrənts lɪv ɪn ðə jʊˈnaɪtɪd steɪts?",
        translation: "Do these immigrants live in the United States?",
      },
      {
        id: 65,
        expression: "Этот иммигрант живет в Соединенных Штатах?",
        transcription: "dəz ðɪs ˈɪmɪgrənt lɪv ɪn ðə jʊˈnaɪtɪd steɪts?",
        translation: "Does this immigrant live in the United States?",
      },
      {
        id: 66,
        expression: "Эти иммигранты живут в Америке?",
        transcription: "dʊ ðiːz ˈɪmɪgrənts lɪv ɪn əˈmɛrɪkə?",
        translation: "Do these immigrants live in America?",
      },
      {
        id: 67,
        expression: "Деньги интересуют его?",
        transcription: "dəz ˈmʌni ˈɪntrɪst hɪm?",
        translation: "Does money interest him?",
      },
      {
        id: 68,
        expression: "Эти деньги интересуют его?",
        transcription: "dəz ðɪs ˈmʌni ˈɪntrɪst hɪm?",
        translation: "Does this money interest him?",
      },
      {
        id: 69,
        expression: "Эти новости интересуют его?",
        transcription: "dəz ðɪs njuːz ˈɪntrɪst hɪm?",
        translation: "Does this news interest him?",
      },
      {
        id: 70,
        expression: "Студенты часто копируют ошибки других студентов?",
        transcription:
          "dʊ ˈstjuːdənts ˈɒf(ə)n ˈkɒpi ˈʌðə ˈstjuːdənts mɪsˈteɪks?",
        translation: "Do students often copy other students' mistakes?",
      },
      {
        id: 71,
        expression: "Этот студент копирует ошибки другого студента?",
        transcription: "dəz ðɪs ˈstjuːdənt ˈkɒpi əˈnʌðə ˈstjuːdənts mɪsˈteɪks?",
        translation: "Does this student copy another student's mistakes?",
      },
      {
        id: 72,
        expression: "Студенты обычно копируют ошибки других студентов?",
        transcription:
          "dʊ ˈstjuːdənts ˈjuːʒʊəli ˈkɒpi ˈʌðə ˈstjuːdənts mɪsˈteɪks?",
        translation: "Do students usually copy other students' mistakes?",
      },
      {
        id: 73,
        expression: "Эти мужчины чувствуют себя подавленными?",
        transcription: "dʊ ðiːz mɛn fiːl dɪˈprɛst?",
        translation: "Do these men feel depressed?",
      },
      {
        id: 74,
        expression: "Эти люди чувствуют себя подавленными?",
        transcription: "dʊ ðiːz ˈpiːpl fiːl dɪˈprɛst?",
        translation: "Do these people feel depressed?",
      },
      {
        id: 75,
        expression: "Этот мужчина чувствует себя подавленным?",
        transcription: "dəz ðɪs mæn fiːl dɪˈprɛst?",
        translation: "Does this man feel depressed?",
      },
      {
        id: 76,
        expression: "Деньги делают людей счастливыми?",
        transcription: "dəz ˈmʌni meɪk ˈpiːpl ˈhæpi?",
        translation: "Does money make people happy?",
      },
      {
        id: 77,
        expression: "Деньги делают людей счастливее?",
        transcription: "dəz ˈmʌni meɪk ˈpiːpl ˈhæpɪə?",
        translation: "Does money make people happier?",
      },
      {
        id: 78,
        expression: "Деньги делают тебя счастливым?",
        transcription: "dəz ˈmʌni meɪk jʊ ˈhæpi?",
        translation: "Does money make you happy?",
      },
      {
        id: 79,
        expression: "Твой отец работает архитектором?",
        transcription: "dəz jə ˈfɑːðə wɜːk əz ən ˈɑːkɪtɛkt?",
        translation: "Does your father work as an architect?",
      },
      {
        id: 80,
        expression: "Твой брат работает инженером?",
        transcription: "dəz jə ˈbrʌðə wɜːk əz ən ˌɛnʤɪˈnɪə?",
        translation: "Does your brother work as an engineer?",
      },
      {
        id: 81,
        expression: "Ты работаешь менеджером?",
        transcription: "dʊ jʊ wɜːk əz ə ˈmænɪʤə?",
        translation: "Do you work as a manager?",
      },
      {
        id: 82,
        expression: "Тот человек чувствует себя подавленным?",
        transcription: "dəz ðət mæn fiːl dɪˈprɛst?",
        translation: "Does that man feel depressed?",
      },
      {
        id: 83,
        expression: "Эта проблема кажется неважной?",
        transcription: "dəz ðɪs ˈprɒbləm siːm ˌʌnɪmˈpɒtənt?",
        translation: "Does this problem seem unimportant?",
      },
      {
        id: 84,
        expression: "Те проблемы кажутся неважными?",
        transcription: "dʊ ðəʊz ˈprɒbləmz siːm ˌʌnɪmˈpɒtənt?",
        translation: "Do those problems seem unimportant?",
      },
      {
        id: 85,
        expression: "Твои друзья разделяют твое мнение?",
        transcription: "dʊ jə frɛndz ʃeə jər əˈpɪnjən?",
        translation: "Do your friends share your opinion?",
      },
      {
        id: 86,
        expression: "Эти новости часто шокируют людей?",
        transcription: "dəz ðɪs njuːz ˈɒf(ə)n ʃɒk ˈpiːpl?",
        translation: "Does this news often shock people?",
      },
      {
        id: 87,
        expression: "Твоим одногруппникам нравятся уроки этого учителя?",
        transcription: "dʊ jə gruːpmeɪts laɪk ðɪs ˈtiːʧəz ˈlɛsnz?",
        translation: "Do your groupmates like this teacher's lessons?",
      },
      {
        id: 88,
        expression: "Это сообщество растет очень быстро?",
        transcription: "dəz ðɪs kəˈmjuːnɪti grəʊ ˈvɛri ˈkwɪkli?",
        translation: "Does this community grow very quickly?",
      },
      {
        id: 89,
        expression: "Один из твоих друзей работает музыкантом?",
        transcription: "dəz wʌn əv jə frɛndz wɜːk əz ə mju(ː)ˈzɪʃən?",
        translation: "Does one of your friends work as a musician?",
      },
      {
        id: 90,
        expression: "Этих знаний кажется достаточно?",
        transcription: "dəz ðɪs ˈnɒlɪʤ siːm ɪˈnʌf?",
        translation: "Does this knowledge seem enough?",
      },
      {
        id: 91,
        expression: "Твой знакомый работает программистом?",
        transcription: "dəz jər əˈkweɪntəns wɜːk əz ə ˈprəʊgræmə?",
        translation: "Does your acquaintance work as a programmer?",
      },
      {
        id: 92,
        expression: "Учитель указывает на ошибки других студентов?",
        transcription: "dəz ðə ˈtiːʧə pɔɪnt aʊt ˈʌðə ˈstjuːdənts mɪsˈteɪks?",
        translation: "Does the teacher point out other students' mistakes?",
      },
      {
        id: 93,
        expression: "Эта женщина чувствует себя очень удивленной?",
        transcription: "dəz ðɪs ˈwʊmən fiːl ˈvɛri səˈpraɪzd?",
        translation: "Does this woman feel very surprised?",
      },
      {
        id: 94,
        expression: "Твой учитель указывает на твои ошибки?",
        transcription: "dəz jə ˈtiːʧə pɔɪnt aʊt jə mɪsˈteɪks?",
        translation: "Does your teacher point out your mistakes?",
      },
      {
        id: 95,
        expression: "Твоему другу нравится идея твоего брата?",
        transcription: "dəz jə frɛnd laɪk jə ˈbrʌðəz aɪˈdɪə?",
        translation: "Does your friend like your brother's idea?",
      },
      {
        id: 96,
        expression: "Этот пример действительно вдохновляет тебя?",
        transcription: "dəz ðɪs ɪgˈzɑːmpl ˈrɪəli ɪnˈspaɪə juː?",
        translation: "Does this example really inspire you?",
      },
      {
        id: 97,
        expression: "Деньги играют очень важную роль?",
        transcription: "dəz ˈmʌni pleɪ ə ˈvɛri ɪmˈpɔːtənt rəʊl?",
        translation: "Does money play a very important role?",
      },
      {
        id: 98,
        expression: "Твой знакомый рекомендует это?",
        transcription: "dəz jər əˈkweɪntəns ˌrɛkəˈmɛnd ɪt?",
        translation: "Does your acquaintance recommend it?",
      },
      {
        id: 99,
        expression: "Эти женщины очень удивлены?",
        transcription:
          "dʊ ðiːz ˈwɪmɪn fiːl ˈvɛri səˈpraɪzd? / ɑː ðiːz ˈwɪmɪn ˈvɛri səˈpraɪzd?",
        translation:
          "Do these women feel very surprised? / Are these women very surprised?",
      },
    ],
    {
      theory: `<div class="theory-block">
<h3>Закрепление пройденного материала</h3>
</div>`,
    },
  ],
];
