export const contentLesson36 = [
  [
    {
      title: "Урок 36. Past Simple. Regular verbs. Part 3",
    },
    [
      {
        id: 1,
        expression: "Я много учился",
        transcription: "aɪ ˈstʌdɪd ə lɒt",
        translation: "I studied a lot",
      },
      {
        id: 2,
        expression: "Я закончил свою работу",
        transcription: "aɪ ˈfɪnɪʃt maɪ wɜːk",
        translation: "I finished my work",
      },
      {
        id: 3,
        expression: "Я закрыл дверь",
        transcription: "aɪ kləʊzd ðə dɔː",
        translation: "I closed the door",
      },
      {
        id: 4,
        expression: "Он много учился",
        transcription: "hi ˈstʌdɪd ə lɒt",
        translation: "He studied a lot",
      },
      {
        id: 5,
        expression: "Она училась очень мало",
        transcription: "ʃi ˈstʌdɪd ˈvɛri ˈlɪtl",
        translation: "She studied very little",
      },
      {
        id: 6,
        expression: "Я сравнил эти цены",
        transcription: "aɪ kəmˈpeəd ðiːz ˈpraɪsɪz",
        translation: "I compared these prices",
      },
      {
        id: 7,
        expression: "Я остановился возле того окна",
        transcription: "aɪ stɒpt nɪə ðət ˈwɪndəʊ",
        translation: "I stopped near that window",
      },
      {
        id: 8,
        expression: "Он действительно любил ее",
        transcription: "hi ˈrɪəli lʌvd hɜː",
        translation: "He really loved her",
      },
      {
        id: 9,
        expression: "Она закончила свою работу очень рано",
        transcription: "ʃi ˈfɪnɪʃt hə wɜːk ˈvɛri ˈɜːli",
        translation: "She finished her work very early",
      },
      {
        id: 10,
        expression: "Я согласился с этим",
        transcription: "aɪ əˈgriːd wɪð ɪt",
        translation: "I agreed with it",
      },
      {
        id: 11,
        expression: "Тебе понравилась эта идея?",
        transcription: "dɪd jʊ laɪk ðɪs aɪˈdɪə?",
        translation: "Did you like this idea?",
      },
      {
        id: 12,
        expression: "Эта вещь мотивировала меня так сильно",
        transcription: "ðɪs θɪŋ ˈməʊtɪveɪtɪd mi səʊ mʌʧ",
        translation: "This thing motivated me so much",
      },
      {
        id: 13,
        expression: "Тебе понравилось его предложение?",
        transcription: "dɪd jʊ laɪk ɪz ˈɒfə?",
        translation: "Did you like his offer?",
      },
      {
        id: 14,
        expression: "Мы остановились там",
        transcription: "wi stɒpt ðeə",
        translation: "We stopped there",
      },
      {
        id: 15,
        expression: "Я учился очень усердно",
        transcription: "aɪ ˈstʌdɪd ˈvɛri hɑːd",
        translation: "I studied very hard",
      },
      {
        id: 16,
        expression: "Я сдал тот тест",
        transcription: "aɪ pɑːst ðət tɛst",
        translation: "I passed that test",
      },
      {
        id: 17,
        expression: "Все хотели продолжить",
        transcription: "ˈɛvrɪwʌn ˈwɒntɪd tə kənˈtɪnju(ː)",
        translation: "Everyone wanted to continue",
      },
      {
        id: 18,
        expression: "Он так много учился",
        transcription: "hi ˈstʌdɪd səʊ mʌʧ",
        translation: "He studied so much",
      },
      {
        id: 19,
        expression: "Мои друзья рекомендовали этот курс",
        transcription: "maɪ frɛndz ˌrɛkəˈmɛndɪd ðɪs kɔːs",
        translation: "My friends recommended this course",
      },
      {
        id: 20,
        expression: "Она любила танцевать",
        transcription: "ʃi lʌvd ˈdɑːnsɪŋ",
        translation: "She loved dancing",
      },
      {
        id: 21,
        expression: "Ты закрыл окно?",
        transcription: "dɪd jʊ kləʊs ðə ˈwɪndəʊ?",
        translation: "Did you close the window?",
      },
      {
        id: 22,
        expression: "Мы продолжили",
        transcription: "wi kənˈtɪnju(ː)d",
        translation: "We continued",
      },
      {
        id: 23,
        expression: "Что тебе понравилось больше?",
        transcription: "wɒt dɪd jʊ laɪk mɔː?",
        translation: "What did you like more?",
      },
      {
        id: 24,
        expression: "Ты открыл этот сайт?",
        transcription: "dɪd jʊ ˈəʊpən ðɪs ˈwɛbˌsaɪt?",
        translation: "Did you open this website?",
      },
      {
        id: 25,
        expression: "Это действительно мотивировало меня",
        transcription: "ɪt ˈrɪəli ˈməʊtɪveɪtɪd miː",
        translation: "It really motivated me",
      },
      {
        id: 26,
        expression: "Когда ты закончил свою работу?",
        transcription: "wɛn dɪd jʊ ˈfɪnɪʃ jə wɜːk?",
        translation: "When did you finish your work?",
      },
      {
        id: 27,
        expression: "Он умер очень старым",
        transcription: "hi daɪd ˈvɛri əʊld",
        translation: "He died very old",
      },
      {
        id: 28,
        expression: "Я сдал этот экзамен",
        transcription: "aɪ pɑːst ðɪs ɪgˈzæm",
        translation: "I passed this exam",
      },
      {
        id: 29,
        expression: "Он рекомендовал тот отель",
        transcription: "hi ˌrɛkəˈmɛndɪd ðət həʊˈtɛl",
        translation: "He recommended that hotel",
      },
      {
        id: 30,
        expression: "Он прыгнул так высоко",
        transcription: "hi ʤʌmpt səʊ haɪ",
        translation: "He jumped so high",
      },
      {
        id: 31,
        expression: "Он часто пользовался интернетом",
        transcription: "hi ˈɒf(ə)n juːzd ði ˈɪntəˌnɛt",
        translation: "He often used the Internet",
      },
      {
        id: 32,
        expression: "Эта машина остановилась здесь",
        transcription: "ðɪs kɑː stɒpt hɪə",
        translation: "This car stopped here",
      },
      {
        id: 33,
        expression: "Я также хотел продолжить",
        transcription: "aɪ ˈɔːlsəʊ ˈwɒntɪd tə kənˈtɪnju(ː)",
        translation: "I also wanted to continue",
      },
      {
        id: 34,
        expression: "Мне нужно было больше практики",
        transcription: "aɪ ˈniːdɪd mɔː ˈpræktɪs",
        translation: "I needed more practice",
      },
      {
        id: 35,
        expression: "Он закончил свою работу очень поздно",
        transcription: "hi ˈfɪnɪʃt ɪz wɜːk ˈvɛri leɪt",
        translation: "He finished his work very late",
      },
      {
        id: 36,
        expression: "Я открыл дверь",
        transcription: "aɪ ˈəʊpənd ðə dɔː",
        translation: "I opened the door",
      },
      {
        id: 37,
        expression: "Он не хотел прыгать",
        transcription: "hi dɪdnt wɒnt tə ʤʌmp",
        translation: "He didn't want to jump",
      },
      {
        id: 38,
        expression: "Она умерла четыре месяца назад",
        transcription: "ʃi daɪd fɔː mʌnθs əˈgəʊ",
        translation: "She died four months ago",
      },
      {
        id: 39,
        expression: "Я действительно ненавидел это",
        transcription: "aɪ ˈrɪəli ˈheɪtɪd ɪt",
        translation: "I really hated it",
      },
      {
        id: 40,
        expression: "Мы сравнили те курсы",
        transcription: "wi kəmˈpeəd ðəʊz ˈkɔːsɪz",
        translation: "We compared those courses",
      },
      {
        id: 41,
        expression: "Я всегда верил ей",
        transcription: "aɪ ˈɔːlweɪz bɪˈliːvd hɜː",
        translation: "I always believed her",
      },
      {
        id: 42,
        expression: "Как ты скачал это?",
        transcription: "haʊ dɪd jʊ ˌdaʊnˈləʊd ɪt?",
        translation: "How did you download it?",
      },
      {
        id: 43,
        expression: "Он пытался найти работу",
        transcription: "hi traɪd tə faɪnd ə ʤɒb",
        translation: "He tried to find a job",
      },
      {
        id: 44,
        expression: "Я не понимал, почему он ненавидел это так сильно",
        transcription: "aɪ dɪdnt ˌʌndəˈstænd waɪ hi ˈheɪtɪd ɪt səʊ mʌʧ",
        translation: "I didn't understand why he hated it so much",
      },
      {
        id: 45,
        expression: "Как долго длился один урок",
        transcription: "haʊ lɒŋ dɪd wʌn ˈlɛsn lɑːst?",
        translation: "How long did one lesson last?",
      },
      {
        id: 46,
        expression: "Я пользовался тем сервисом раньше",
        transcription: "aɪ juːzd ðət ˈsɜːvɪs ˈɜːlɪə",
        translation: "I used that service earlier",
      },
      {
        id: 47,
        expression: "Я скачал эти файлы",
        transcription: "aɪ ˌdaʊnˈləʊdɪd ðiːz faɪlz",
        translation: "I downloaded these files",
      },
      {
        id: 48,
        expression: "Ты изучал английский в университете?",
        transcription: "dɪd jʊ ˈstʌdi ˈɪŋglɪʃ ət ˌjuːnɪˈvɜːsɪti",
        translation: "Did you study English at university?",
      },
      {
        id: 49,
        expression: "Мне нужно было сделать это немедленно",
        transcription: "aɪ ˈniːdɪd tə dʊ ɪt ɪˈmiːdiətli",
        translation: "I needed to do it immediately",
      },
      {
        id: 50,
        expression: "Я пытался понять это",
        transcription: "aɪ traɪd tʊ ˌʌndəˈstænd ɪt",
        translation: "I tried to understand it",
      },
      {
        id: 51,
        expression: "Она вернулась раньше",
        transcription: "ʃi rɪˈtɜːnd ˈɜːlɪə",
        translation: "She returned earlier",
      },
      {
        id: 52,
        expression: "Я не думаю, что это действительно помогло мне",
        transcription: "aɪ dəʊnt θɪŋk ðət ɪt ˈrɪəli hɛlpt miː",
        translation: "I don't think that it really helped me",
      },
      {
        id: 53,
        expression: "Я решил использовать этот сервис",
        transcription: "aɪ dɪˈsaɪdɪd tə juːz ðɪs ˈsɜːvɪs",
        translation: "I decided to use this service",
      },
      {
        id: 54,
        expression: "Ты исправил эти ошибки?",
        transcription: "dɪd jʊ kəˈrɛkt ðiːz mɪsˈteɪks?",
        translation: "Did you correct these mistakes?",
      },
      {
        id: 55,
        expression: "Я хотел достичь этой цели",
        transcription: "aɪ ˈwɒntɪd tʊ əˈʧiːv ðɪs eɪm",
        translation: "I wanted to achieve this aim",
      },
      {
        id: 56,
        expression: "Я не отмечал этот праздник",
        transcription: "aɪ dɪdnt ˈsɛlɪbreɪt ðɪs ˈhɒlədeɪ",
        translation: "I didn't celebrate this holiday",
      },
      {
        id: 57,
        expression: "Что ты заказал в этом ресторане?",
        transcription: "wɒt dɪd jʊ ˈɔːdər ɪn ðɪs ˈrɛstrɒnt?",
        translation: "What did you order in this restaurant?",
      },
      {
        id: 58,
        expression: "Что ты ел в этом ресторане?",
        transcription: "wɒt dɪd jʊ iːt ɪn ðɪs ˈrɛstrɒnt?",
        translation: "What did you eat in this restaurant?",
      },
      {
        id: 59,
        expression: "Что ты заказал в этом магазине?",
        transcription: "wɒt dɪd jʊ ˈɔːdər ɪn ðɪs ʃɒp?",
        translation: "What did you order in this shop?",
      },
      {
        id: 60,
        expression: "Я вернулся домой позже",
        transcription: "aɪ rɪˈtɜːnd həʊm ˈleɪtə",
        translation: "I returned home later",
      },
      {
        id: 61,
        expression: "Он вернулся в школу позже",
        transcription: "hi rɪˈtɜːnd tə skuːl ˈleɪtə",
        translation: "He returned to school later",
      },
      {
        id: 62,
        expression: "Они вернулись туда позже",
        transcription: "ðeɪ rɪˈtɜːnd ðeə ˈleɪtə",
        translation: "They returned there later",
      },
      {
        id: 63,
        expression: "Я не знаю, почему это случилось с нами",
        transcription: "aɪ dəʊnt nəʊ waɪ ɪt ˈhæpənd tʊ ʌs",
        translation: "I don't know why it happened to us",
      },
      {
        id: 64,
        expression: "Она не знает, почему это случилось с ней",
        transcription: "ʃi dʌznt nəʊ waɪ ɪt ˈhæpənd tə hɜː",
        translation: "She doesn't know why it happened to her",
      },
      {
        id: 65,
        expression: "Я не знал, почему это случилось со мной",
        transcription: "aɪ dɪdnt nəʊ waɪ ɪt ˈhæpənd tə miː",
        translation: "I didn't know why it happened to me",
      },
      {
        id: 66,
        expression: "Она не думает, что это ей помогло так сильно",
        transcription: "ʃi dʌznt θɪŋk ðət ɪt hɛlpt hə səʊ mʌʧ",
        translation: "She doesn't think that it helped her so much",
      },
      {
        id: 67,
        expression: "Он не думает, что это так сильно ему помогло",
        transcription: "hi dʌznt θɪŋk ðət ɪt hɛlpt ɪm səʊ mʌʧ",
        translation: "He doesn't think that it helped him so much",
      },
      {
        id: 68,
        expression: "Я не думаю, что это помогло мне",
        transcription: "aɪ dəʊnt θɪŋk ðət ɪt hɛlpt miː",
        translation: "I don't think that it helped me",
      },
      {
        id: 69,
        expression: "Как долго длился один урок английского?",
        transcription: "haʊ lɒŋ dɪd wʌn ˈɪŋglɪʃ ˈlɛsn lɑːst?",
        translation: "How long did one English lesson last?",
      },
      {
        id: 70,
        expression: "Как долго длился этот урок английского?",
        transcription: "haʊ lɒŋ dɪd ðɪs ˈɪŋglɪʃ ˈlɛsn lɑːst?",
        translation: "How long did this English lesson last?",
      },
      {
        id: 71,
        expression: "Как долго длились эти уроки английского?",
        transcription: "haʊ lɒŋ dɪd ðiːz ˈɪŋglɪʃ ˈlɛsnz lɑːst?",
        translation: "How long did these English lessons last?",
      },
      {
        id: 72,
        expression: "Ты добился своей цели?",
        transcription: "dɪd jʊ əˈʧiːv jər eɪm?",
        translation: "Did you achieve your aim?",
      },
      {
        id: 73,
        expression: "Ты добился этой цели?",
        transcription: "dɪd jʊ əˈʧiːv ðɪs eɪm?",
        translation: "Did you achieve this aim?",
      },
      {
        id: 74,
        expression: "Она добилась своей цели?",
        transcription: "dɪd ʃi əˈʧiːv hər eɪm?",
        translation: "Did she achieve her aim?",
      },
      {
        id: 75,
        expression: "Я скачал все вчера",
        transcription: "aɪ ˌdaʊnˈləʊdɪd ˈɛvrɪθɪŋ ˈjɛstədeɪ",
        translation: "I downloaded everything yesterday",
      },
      {
        id: 76,
        expression: "Я скачал все",
        transcription: "aɪ ˌdaʊnˈləʊdɪd ˈɛvrɪθɪŋ",
        translation: "I downloaded everything",
      },
      {
        id: 77,
        expression: "Я скачал это",
        transcription: "aɪ ˌdaʊnˈləʊdɪd ɪt",
        translation: "I downloaded it",
      },
      {
        id: 78,
        expression: "Она обычно покупала одежду онлайн",
        transcription: "ʃi ˈjuːʒʊəli bɔːt kləʊðz ˈɒnˌlaɪn",
        translation: "She usually bought clothes online",
      },
      {
        id: 79,
        expression: "Она обычно заказывала все онлайн",
        transcription: "ʃi ˈjuːʒʊəli ˈɔːdəd ˈɛvrɪθɪŋ ˈɒnˌlaɪn",
        translation: "She usually ordered everything online",
      },
      {
        id: 80,
        expression: "Мы всегда помогали друг другу",
        transcription: "wi ˈɔːlweɪz hɛlpt iːʧ ˈʌðə",
        translation: "We always helped each other",
      },
      {
        id: 81,
        expression: "Они всегда помогали друг другу",
        transcription: "ðeɪ ˈɔːlweɪz hɛlpt iːʧ ˈʌðə",
        translation: "They always helped each other",
      },
      {
        id: 82,
        expression: "Они всегда помогали нам",
        transcription: "ðeɪ ˈɔːlweɪz hɛlpt ʌs",
        translation: "They always helped us",
      },
      {
        id: 83,
        expression: "Это случилось со мной",
        transcription: "ɪt ˈhæpənd tə miː",
        translation: "It happened to me",
      },
      {
        id: 84,
        expression: "Это случилось со мной однажды",
        transcription: "ɪt ˈhæpənd tə mi wʌn deɪ",
        translation: "It happened to me one day",
      },
      {
        id: 85,
        expression: "Это случилось со мной вчера",
        transcription: "ɪt ˈhæpənd tə mi ˈjɛstədeɪ",
        translation: "It happened to me yesterday",
      },
      {
        id: 86,
        expression: "Как ты отпраздновал свой день рождения?",
        transcription: "haʊ dɪd jʊ ˈsɛlɪbreɪt jə ˈbɜːθdeɪ?",
        translation: "How did you celebrate your birthday?",
      },
      {
        id: 87,
        expression: "Я исправил свои ошибки",
        transcription: "aɪ kəˈrɛktɪd maɪ mɪsˈteɪks",
        translation: "I corrected my mistakes",
      },
      {
        id: 88,
        expression: "Я изучал английский в школе",
        transcription: "aɪ ˈstʌdɪd ˈɪŋglɪʃ ət skuːl",
        translation: "I studied English at school",
      },
      {
        id: 89,
        expression: "Ты согласился или нет?",
        transcription: "dɪd jʊ əˈgriː ɔː nɒt?",
        translation: "Did you agree or not?",
      },
      {
        id: 90,
        expression: "Он праздновал свой день рождения со своей семьей",
        transcription: "hi ˈsɛlɪbreɪtɪd ɪz ˈbɜːθdeɪ wɪð ɪz ˈfæmɪli",
        translation: "He celebrated his birthday with his family",
      },
      {
        id: 91,
        expression: "Я достиг своей цели",
        transcription: "aɪ əˈʧiːvd maɪ eɪm",
        translation: "I achieved my aim",
      },
      {
        id: 92,
        expression: "Этот урок длился дольше",
        transcription: "ðɪs ˈlɛsn ˈlɑːstɪd ˈlɒŋgə",
        translation: "This lesson lasted longer",
      },
      {
        id: 93,
        expression: "Как ты отметил этот праздник?",
        transcription: "haʊ dɪd jʊ ˈsɛlɪbreɪt ðɪs ˈhɒlədeɪ?",
        translation: "How did you celebrate this holiday?",
      },
      {
        id: 94,
        expression: "Я все исправил",
        transcription: "aɪ kəˈrɛktɪd ˈɛvrɪθɪŋ",
        translation: "I corrected everything",
      },
      {
        id: 95,
        expression: "Ты согласился сделать это?",
        transcription: "dɪd jʊ əˈgriː tə dʊ ɪt?",
        translation: "Did you agree to do it?",
      },
      {
        id: 96,
        expression: "Мне нужно было сделать это срочно",
        transcription: "aɪ ˈniːdɪd tə dʊ ɪt ˈɜːʤəntli",
        translation: "I needed to do it urgently",
      },
      {
        id: 97,
        expression: "Ты скачал эту программу?",
        transcription: "dɪd jʊ ˌdaʊnˈləʊd ðɪs ˈprəʊgræm?",
        translation: "Did you download this program?",
      },
      {
        id: 98,
        expression: "Я праздновал свой день рождения со своими друзьями",
        transcription: "aɪ ˈsɛlɪbreɪtɪd maɪ ˈbɜːθdeɪ wɪð maɪ frɛndz",
        translation: "I celebrated my birthday with my friends",
      },
      {
        id: 99,
        expression: "Я часто пользовался интернетом, когда жил там",
        transcription: "aɪ ˈɒf(ə)n ˈjuːzd ði ˈɪntəˌnɛt wɛn aɪ lɪvd ðeə",
        translation: "I often used the Internet when I lived there",
      },
      {
        id: 100,
        expression: "Он согласился помочь тебе?",
        transcription: "dɪd hi əˈgriː tə hɛlp juː?",
        translation: "Did he agree to help you?",
      },
    ],
    {
      theory: `<div class="theory-block">
<p>Устойчивое выражение:</p>
<h3>a lot / lots of</h3>
<p>- много / куча (неформ.)</p>
<p>He had a lot of friends - У него было много друзей.</p>
<p>I did lots of deal - Я переделал кучу дел.</p>
</div>`,
    },
  ],
];
