export const contentLesson54 = [
  [
    {
      title: "Урок 54. Present Simple: verb + to be",
    },
    [
      {
        id: 1,
        expression: "Они работают в другом месте",
        transcription: "ðeɪ wɜːk ɪn əˈnʌðə pleɪs",
        translation: "They work in another place",
      },
      {
        id: 2,
        expression: "Он думает о своей семье",
        transcription: "hi θɪŋks əˈbaʊt ɪz ˈfæmɪli",
        translation: "He thinks about his family",
      },
      {
        id: 3,
        expression: "Я счастлив быть здесь",
        transcription: "aɪm ˈhæpi tə bi hɪə",
        translation: "I'm happy to be here",
      },
      {
        id: 4,
        expression: "Они из разных стран",
        transcription: "ðeə frəm ˈdɪfrənt ˈkʌntriz",
        translation: "They're from different countries",
      },
      {
        id: 5,
        expression: "Он очень стар",
        transcription: "hiːz ˈvɛri əʊld",
        translation: "He's very old",
      },
      {
        id: 6,
        expression: "Она из Лондона",
        transcription: "ʃiːz frəm ˈlʌndən",
        translation: "She's from London",
      },
      {
        id: 7,
        expression: "Это очень популярная песня",
        transcription: "ɪts ə ˈvɛri ˈpɒpjʊlə sɒŋ",
        translation: "It's a very popular song",
      },
      {
        id: 8,
        expression: "Она боится их",
        transcription: "ʃiːz əˈfreɪd əv ðɛm",
        translation: "She's afraid of them",
      },
      {
        id: 9,
        expression: "Это проблема для них",
        transcription: "ɪts ə ˈprɒbləm fə ðɛm",
        translation: "It's a problem for them",
      },
      {
        id: 10,
        expression: "У тебя хорошая работа",
        transcription: "jʊ həv ə gʊd ʤɒb",
        translation: "You have a good job",
      },
      {
        id: 11,
        expression: "Это новый компьютер",
        transcription: "ɪts ə njuː kəmˈpjuːtə",
        translation: "It's a new computer",
      },
      {
        id: 12,
        expression: "Они в разных странах",
        transcription: "ðeər ɪn ˈdɪfrənt ˈkʌntriz",
        translation: "They're in different countries",
      },
      {
        id: 13,
        expression: "Мне нужен новый компьютер",
        transcription: "aɪ niːd ə njuː kəmˈpjuːtə",
        translation: "I need a new computer",
      },
      {
        id: 14,
        expression: "Он боится этого",
        transcription: "hiːz əˈfreɪd əv ɪt",
        translation: "He's afraid of it",
      },
      {
        id: 15,
        expression: "Это действительно так",
        transcription: "ɪts ˈrɪəli səʊ",
        translation: "It's really so",
      },
      {
        id: 16,
        expression: "У него одна проблема",
        transcription: "hi həz wʌn ˈprɒbləm",
        translation: "He has one problem",
      },
      {
        id: 17,
        expression: "Она родом из Лос-Анджелеса",
        transcription: "ʃi kʌmz frəm Los ˈeɪnʤəlz",
        translation: "She comes from Los Angeles",
      },
      {
        id: 18,
        expression: "Это интересует меня",
        transcription: "ɪt ˈɪntrɪsts miː",
        translation: "It interests me",
      },
      {
        id: 19,
        expression: "Они чувствуют себя такими счастливыми",
        transcription: "ðeɪ fiːl səʊ ˈhæpi",
        translation: "They feel so happy",
      },
      {
        id: 20,
        expression: "Мы думаем так",
        transcription: "wi θɪŋk səʊ",
        translation: "We think so",
      },
      {
        id: 21,
        expression: "Он согласен с этим утверждением",
        transcription: "hi əˈgriːz wɪð ðɪs ˈsteɪtmənt",
        translation: "He agrees with this statement",
      },
      {
        id: 22,
        expression: "Они очень счастливы",
        transcription: "ðeə ˈvɛri ˈhæpi",
        translation: "They're very happy",
      },
      {
        id: 23,
        expression: "Он работает в другом месте",
        transcription: "hi wɜːks ɪn əˈnʌðə pleɪs",
        translation: "He works in another place",
      },
      {
        id: 24,
        expression: "Она такая уставшая",
        transcription: "ʃiːz səʊ ˈtaɪəd",
        translation: "She's so tired",
      },
      {
        id: 25,
        expression: "Это новое платье для нее",
        transcription: "ɪts ə njuː drɛs fə hə",
        translation: "It's a new dress for her",
      },
      {
        id: 26,
        expression: "Я здесь в данный момент",
        transcription: "aɪm hɪər ət ðə ˈməʊmənt",
        translation: "I'm here at the moment",
      },
      {
        id: 27,
        expression: "Это кажется фантастическим",
        transcription: "ɪt siːmz fænˈtæstɪk",
        translation: "It seems fantastic",
      },
      {
        id: 28,
        expression: "Она хочет новое платье",
        transcription: "ʃi wɒnts ə njuː drɛs",
        translation: "She wants a new dress",
      },
      {
        id: 29,
        expression: "Мы согласны с тобой",
        transcription: "wi əˈgriː wɪð juː",
        translation: "We agree with you",
      },
      {
        id: 30,
        expression: "Она очень молодая",
        transcription: "ʃiːz ˈvɛri jʌŋ",
        translation: "She's very young",
      },
      {
        id: 31,
        expression: "Это выглядит очень эффективно",
        transcription: "ɪt lʊks ˈvɛri ɪˈfɛktɪv",
        translation: "It looks very effective",
      },
      {
        id: 32,
        expression: "Он чувствует себя таким уставшим",
        transcription: "hi fiːlz səʊ ˈtaɪəd",
        translation: "He feels so tired",
      },
      {
        id: 33,
        expression: "Он думает иначе",
        transcription: "hi θɪŋks ˈdɪfrəntli",
        translation: "He thinks differently",
      },
      {
        id: 34,
        expression: "Он родом из Нью-Йорка",
        transcription: "hi kʌmz frəm njuː jɔːk",
        translation: "He comes from New York",
      },
      {
        id: 35,
        expression: "Это хорошая работа",
        transcription: "ɪts ə gʊd ʤɒb",
        translation: "It's a good job",
      },
      {
        id: 36,
        expression: "Она выглядит очень молодо",
        transcription: "ʃi lʊks ˈvɛri jʌŋ",
        translation: "She looks very young",
      },
      {
        id: 37,
        expression: "Я согласен с этим утверждением",
        transcription: "aɪ əˈgriː wɪð ðɪs ˈsteɪtmənt",
        translation: "I agree with this statement",
      },
      {
        id: 38,
        expression: "Это фантастически",
        transcription: "ɪts fænˈtæstɪk",
        translation: "It's fantastic",
      },
      {
        id: 39,
        expression: "Она живет в прекрасном месте",
        transcription: "ʃi lɪvz ɪn ə ˈlʌvli (ˈwʌndəfʊl) pleɪs",
        translation: "She lives in a lovely (wonderful) place",
      },
      {
        id: 40,
        expression: "Он из Соединенных Штатов",
        transcription: "hiːz frəm ðə jʊˈnaɪtɪd steɪts",
        translation: "He's from the United States",
      },
      {
        id: 41,
        expression: "Это прекрасное место",
        transcription: "ɪts ə ˈlʌvli pleɪs",
        translation: "It's a lovely place",
      },
      {
        id: 42,
        expression: "Они живут в очень большом доме",
        transcription: "ðeɪ lɪv ɪn ə ˈvɛri bɪg haʊs",
        translation: "They live in a very big house",
      },
      {
        id: 43,
        expression: "Я очень устал",
        transcription: "aɪm ˈvɛri ˈtaɪəd",
        translation: "I'm very tired",
      },
      {
        id: 44,
        expression: "Это маленький дом",
        transcription: "ɪts ə smɔːl haʊs",
        translation: "It's a small house",
      },
      {
        id: 45,
        expression: "Это интересно мне",
        transcription: "ɪts ˈɪntrɪstɪŋ fə miː",
        translation: "It's interesting for me",
      },
      {
        id: 46,
        expression: "Это чрезвычайно важная вещь",
        transcription: "ɪts ən ɪksˈtriːmli ɪmˈpɔːtənt θɪŋ",
        translation: "It's an extremely important thing",
      },
      {
        id: 47,
        expression: "Это большой успех",
        transcription: "ɪts ə bɪg səkˈsɛs",
        translation: "It's a big success",
      },
      {
        id: 48,
        expression: "Он выглядит шокированным",
        transcription: "hi lʊks ʃɒkt",
        translation: "He looks shocked",
      },
      {
        id: 49,
        expression: "Это кажется лучшим решением этой проблемы",
        transcription: "ɪt siːmz ðə bɛst səˈluːʃən tə ðɪs ˈprɒbləm",
        translation: "It seems the best solution to this problem",
      },
      {
        id: 50,
        expression: "Ты выглядишь очень удивленным",
        transcription: "jʊ lʊk ˈvɛri səˈpraɪzd",
        translation: "You look very surprised",
      },
      {
        id: 51,
        expression:
          "Наши учителя часто говорят, что это типичная ошибка для изучающих английский язык",
        transcription:
          "ˈaʊə ˈtiːʧəz ˈɒf(ə)n seɪ ðət ɪts ə ˈtɪpɪk(ə)l mɪsˈteɪk əv ˈɪŋglɪʃ ˈlɜːnəz",
        translation:
          "Our teachers often say that it's a typical mistake of English learners",
      },
      {
        id: 52,
        expression: "У них очень интересные обычаи и традиции",
        transcription: "ðeɪ həv ˈɪntrɪstɪŋ ˈkʌstəmz ənd trəˈdɪʃənz",
        translation: "They have interesting customs and traditions",
      },
      {
        id: 53,
        expression: "Это лучшее решение этой проблемы",
        transcription: "ɪts ðə bɛst səˈluːʃən tə ðɪs ˈprɒbləm",
        translation: "It's the best solution to this problem",
      },
      {
        id: 54,
        expression: "Это кажется лучшим решением",
        transcription: "ɪt siːmz ðə bɛst dɪˈsɪʒən",
        translation: "It seems the best decision",
      },
      {
        id: 55,
        expression: "Я так удивлен",
        transcription: "aɪm səʊ səˈpraɪzd",
        translation: "I'm so surprised",
      },
      {
        id: 56,
        expression: "Я думаю, это огромный успех",
        transcription: "aɪ θɪŋk ɪts ə hjuːʤ səkˈsɛs",
        translation: "I think it's a huge success",
      },
      {
        id: 57,
        expression: "Они часто лежат на пляже",
        transcription: "ðeɪ ˈɒf(ə)n laɪ ɒn ðə biːʧ",
        translation: "They often lie on the beach",
      },
      {
        id: 58,
        expression: "Это также мне очень интересно",
        transcription: "ɪts ˈɔːlsəʊ ˈvɛri ˈɪntrɪstɪŋ fə miː",
        translation: "It's also very interesting for me",
      },
      {
        id: 59,
        expression:
          "У меня есть уникальная возможность выучить английский язык здесь",
        transcription: "aɪ həv ə juːˈniːk ˌɒpəˈtjuːnɪti tə lɜːn ˈɪŋglɪʃ hɪə",
        translation: "I have a unique opportunity to learn English here",
      },
      {
        id: 60,
        expression: "Это чрезвычайно важная деталь",
        transcription: "ɪts ən ɪksˈtriːmli ɪmˈpɔːtənt ˈdiːteɪl",
        translation: "It's an extremely important detail",
      },
      {
        id: 61,
        expression: "Это типичная ошибка изучающих английский язык",
        transcription: "ɪts ə ˈtɪpɪk(ə)l mɪsˈteɪk əv ˈɪŋglɪʃ ˈlɜːnəz",
        translation: "It's a typical mistake of English learners",
      },
      {
        id: 62,
        expression: "Это самая типичная ошибка изучающих английский язык",
        transcription: "ɪts ðə məʊst ˈtɪpɪk(ə)l mɪsˈteɪk əv ˈɪŋglɪʃ ˈlɜːnəz",
        translation: "It's the most typical mistake of English learners",
      },
      {
        id: 63,
        expression:
          "Это самая распространенная ошибка изучающих английский язык",
        transcription: "ɪts ðə məʊst ˈkɒmən mɪsˈteɪk əv ˈɪŋglɪʃ ˈlɜːnəz",
        translation: "It's the most common mistake of English learners",
      },
      {
        id: 64,
        expression: "Это огромный успех",
        transcription: "ɪts ə hjuːʤ səkˈsɛs",
        translation: "It's a huge success",
      },
      {
        id: 65,
        expression: "Это действительно огромный успех",
        transcription: "ɪts ə ˈrɪəli hjuːʤ səkˈsɛs",
        translation: "It's a really huge success",
      },
      {
        id: 66,
        expression: "Это действительно большой успех",
        transcription: "ɪts ə ˈrɪəli bɪg səkˈsɛs",
        translation: "It's a really big success",
      },
      {
        id: 67,
        expression: "Это кажется очень необычным выбором",
        transcription: "ɪt siːmz ə ˈvɛri ʌnˈjuːʒʊəl ʧɔɪs",
        translation: "It seems a very unusual choice",
      },
      {
        id: 68,
        expression: "Это кажется очень типичным выбором",
        transcription: "ɪt siːmz ə ˈvɛri ˈtɪpɪk(ə)l ʧɔɪs",
        translation: "It seems a very typical choice",
      },
      {
        id: 69,
        expression: "Это кажется очень хорошим выбором",
        transcription: "ɪt siːmz ə ˈvɛri gʊd ʧɔɪs",
        translation: "It seems a very good choice",
      },
      {
        id: 70,
        expression: "Я действительно шокирован",
        transcription: "aɪm ˈrɪəli ʃɒkt",
        translation: "I'm really shocked",
      },
      {
        id: 71,
        expression: "Она действительно шокирована",
        transcription: "ʃiːz ˈrɪəli ʃɒkt",
        translation: "She's really shocked",
      },
      {
        id: 72,
        expression: "Мы действительно шокированы",
        transcription: "wɪə ˈrɪəli ʃɒkt",
        translation: "We're really shocked",
      },
      {
        id: 73,
        expression: "Это официальный документ",
        transcription: "ɪts ən əˈfɪʃəl ˈdɒkjʊmənt",
        translation: "It's an official document",
      },
      {
        id: 74,
        expression: "Это новый документ",
        transcription: "ɪts ə njuː ˈdɒkjʊmənt",
        translation: "It's a new document",
      },
      {
        id: 75,
        expression: "Это важный документ",
        transcription: "ɪts ən ɪmˈpɔːtənt ˈdɒkjʊmənt",
        translation: "It's an important document",
      },
      {
        id: 76,
        expression: "Это кажется уникальной возможностью",
        transcription: "ɪt siːmz ən juːˈniːk ˌɒpəˈtjuːnɪti",
        translation: "It seems an unique opportunity",
      },
      {
        id: 77,
        expression: "Это кажется уникальным шансом",
        transcription: "ɪt siːmz ən juːˈniːk ʧɑːns",
        translation: "It seems an unique chance",
      },
      {
        id: 78,
        expression: "Это кажется отличной возможностью",
        transcription: "ɪt siːmz ə greɪt ˌɒpəˈtjuːnɪti",
        translation: "It seems a great opportunity",
      },
      {
        id: 79,
        expression: "Это чрезвычайно важно",
        transcription: "ɪts ɪksˈtriːmli ɪmˈpɔːtənt",
        translation: "It's extremely important",
      },
      {
        id: 80,
        expression: "Это действительно важно",
        transcription: "ɪts ˈrɪəli ɪmˈpɔːtənt",
        translation: "It's really important",
      },
      {
        id: 81,
        expression: "Это очень важно",
        transcription: "ɪts ˈvɛri ɪmˈpɔːtənt",
        translation: "It's very important",
      },
      {
        id: 82,
        expression: "Это уникальная возможность",
        transcription: "ɪts ən juːˈniːk ˌɒpəˈtjuːnɪti",
        translation: "It's an unique opportunity",
      },
      {
        id: 83,
        expression: "Это хорошая возможность",
        transcription: "ɪts ə gʊd ˌɒpəˈtjuːnɪti",
        translation: "It's a good opportunity",
      },
      {
        id: 84,
        expression: "Это действительно большая возможность",
        transcription: "ɪts ə ˈrɪəli bɪg ˌɒpəˈtjuːnɪti",
        translation: "It's a really big opportunity",
      },
      {
        id: 85,
        expression:
          "Я так счастлив, что у меня есть эта уникальная возможность",
        transcription: "aɪm səʊ ˈhæpi ðət aɪ həv ðɪs juːˈniːk ˌɒpəˈtjuːnɪti",
        translation: "I'm so happy that I have this unique opportunity",
      },
      {
        id: 86,
        expression:
          "Она так счастлива, что у нее есть эта уникальная возможность",
        transcription: "ʃiːz səʊ ˈhæpi ðət ʃi həz ðɪs juːˈniːk ˌɒpəˈtjuːnɪti",
        translation: "She's so happy that she has this unique opportunity",
      },
      {
        id: 87,
        expression:
          "Они так счастливы, что у них есть эта уникальная возможность",
        transcription: "ðeə səʊ ˈhæpi ðət ðeɪ həv ðɪs juːˈniːk ˌɒpəˈtjuːnɪti",
        translation: "They're so happy that they have this unique opportunity",
      },
      {
        id: 88,
        expression: "Я думаю, это большой успех",
        transcription: "aɪ θɪŋk ɪts ə bɪg səkˈsɛs",
        translation: "I think it's a big success",
      },
      {
        id: 89,
        expression: "Мы думаем, это большой успех",
        transcription: "wi θɪŋk ɪts ə bɪg səkˈsɛs",
        translation: "We think it's a big success",
      },
      {
        id: 90,
        expression: "Она думает, это большой успех",
        transcription: "ʃi θɪŋks ɪts ə bɪg səkˈsɛs",
        translation: "She thinks it's a big success",
      },
      {
        id: 91,
        expression: "Это кажется таким важным",
        transcription: "ɪt siːmz səʊ ɪmˈpɔːtənt",
        translation: "It seems so important",
      },
      {
        id: 92,
        expression: "Ты выглядишь таким удивленным",
        transcription: "jʊ lʊk səʊ səˈpraɪzd",
        translation: "You look so surprised",
      },
      {
        id: 93,
        expression: "Это очень необычный выбор",
        transcription: "ɪts ə ˈvɛri ʌnˈjuːʒʊəl ʧɔɪs",
        translation: "It's a very unusual choice",
      },
      {
        id: 94,
        expression: "Это лежит на крыше",
        transcription: "ɪt laɪz ɒn ðə ruːf",
        translation: "It lies on the roof",
      },
      {
        id: 95,
        expression: "Это на крыше",
        transcription: "ɪts ɒn ðə ruːf",
        translation: "It's on the roof",
      },
      {
        id: 96,
        expression: "Я думаю, это пустая трата времени",
        transcription: "aɪ θɪŋk ɪts ə weɪst əv taɪm",
        translation: "I think it's a waste of time",
      },
      {
        id: 97,
        expression: "Это кажется пустой тратой времени для меня",
        transcription: "ɪt siːmz ə weɪst əv taɪm fə miː",
        translation: "It seems a waste of time for me",
      },
      {
        id: 98,
        expression: "Я думаю, это действительно ужасно",
        transcription: "aɪ θɪŋk ɪts ˈrɪəli ˈtɛrəbl",
        translation: "I think it's really terrible",
      },
      {
        id: 99,
        expression: "Это пустая трата времени",
        transcription: "ɪts ə weɪst əv taɪm",
        translation: "It's a waste of time",
      },
      {
        id: 100,
        expression: "Я чрезвычайно устал",
        transcription: "aɪm ɪksˈtriːmli ˈtaɪəd",
        translation: "I'm extremely tired",
      },
      {
        id: 101,
        expression: "Мне нужно найти решение этой проблемы",
        transcription: "aɪ niːd tə faɪnd ə səˈluːʃən tə ðɪs ˈprɒbləm",
        translation: "I need to find a solution to this problem",
      },
      {
        id: 102,
        expression: "Он говорит, что это чрезвычайно важно для всех нас",
        transcription: "hi sɛz ðət ɪts ɪksˈtriːmli ɪmˈpɔːtənt fər ɔːl əv ʌs",
        translation: "He says that it's extremely important for all of us",
      },
      {
        id: 103,
        expression: "Мы можем видеть это в официальном документе",
        transcription: "wi kən siː ɪt ɪn ði əˈfɪʃəl ˈdɒkjʊmənt",
        translation: "We can see it in the official document",
      },
      {
        id: 104,
        expression: "Они на пляже",
        transcription: "ðeər ɒn ðə biːʧ",
        translation: "They're on the beach",
      },
      {
        id: 105,
        expression: "Это очень интересная традиция",
        transcription: "ɪts ə ˈvɛri ˈɪntrɪstɪŋ trəˈdɪʃən",
        translation: "It's a very interesting tradition",
      },
    ],
    {
      theory: `<div class="theory-block">
<h3>Закрепление пройденного материала</h3>
</div>`,
    },
  ],
];
