export const contentLesson218 = [
  [
    {
      title: 'Урок 218. 320 Dependent Prepositions. Part 11',
    },
    [
      {
        id: 1,
        expression: 'Он всмотрелся в фотографию',
        transcription: 'hiː pɪəd æt ðə ˈfəʊtəʊ',
        translation: 'He peered at the photo',
      },
      {
        id: 2,
        expression: 'Она была одета в белое',
        transcription: 'ʃiː wɒz drɛst ɪn waɪt',
        translation: 'She was dressed in white',
      },
      {
        id: 3,
        expression: 'Я подписан на эти каналы',
        transcription: 'aɪm səbˈskraɪbd tuː ðiːz ˈʧænlz',
        translation: "I'm subscribed to these channels",
      },
      {
        id: 4,
        expression: 'Он боится ранить ее чувства',
        transcription: 'hiː ɪz əˈfreɪd ɒv ˈhɜːtɪŋ hɜː ˈfiːlɪŋz',
        translation: 'He is afraid of hurting her feelings',
      },
      {
        id: 5,
        expression: 'Я поглощен выполнением этого',
        transcription: 'aɪm ɪnˈtɛnt ɒn ˈduːɪŋ ɪt',
        translation: "I'm intent on doing it",
      },
      {
        id: 6,
        expression: 'Это только частичное решение этой проблемы',
        transcription: 'ɪts ˈəʊnli ə ˈpɑːʃəl səˈluːʃᵊn tuː ðɪs ˈprɒbləm',
        translation: "It's only a partial solution to this problem",
      },
      {
        id: 7,
        expression: 'Я уже подписался на тот канал',
        transcription: 'aɪv ɔːlˈrɛdi səbˈskraɪbd tuː ðæt ˈʧænl',
        translation: "I've already subscribed to that channel",
      },
      {
        id: 8,
        expression: 'С ним очень легко иметь дело',
        transcription: 'ɪt ɪz ˈvɛri ˈiːzi tuː diːl wɪð hɪm',
        translation: 'It is very easy to deal with him',
      },
      {
        id: 9,
        expression: 'Мы так благодарны тебе за твою поддержку',
        transcription: 'wiː ɑː səʊ ˈθæŋkfʊl tuː juː fɔː jɔː səˈpɔːt',
        translation: 'We are so thankful to you for your support',
      },
      {
        id: 10,
        expression: 'Она не одобряет такого поведения',
        transcription: 'ʃiː ˌdɪsəˈpruːvz ɒv sʌʧ bɪˈheɪvjə',
        translation: 'She disapproves of such behavior',
      },
      {
        id: 11,
        expression: 'На твоем месте я бы не стал над ним смеяться',
        transcription: 'ɪf aɪ wɜː juː, aɪ ˈwʊdnt lɑːf æt hɪm',
        translation: "If I were you, I wouldn't laugh at him",
      },
      {
        id: 12,
        expression: 'Его оштрафовали за неосторожное вождение',
        transcription: 'hiː wɒz faɪnd fɔː ˈkeəlɪs ˈdraɪvɪŋ',
        translation: 'He was fined for careless driving',
      },
      {
        id: 13,
        expression: 'Она всмотрелась в это изображение',
        transcription: 'ʃiː pɪəd æt ðɪs ˈɪmɪʤ',
        translation: 'She peered at this image',
      },
      {
        id: 14,
        expression: 'Ее глаза были полны слез',
        transcription: 'hɜːr aɪz wɜː fɪld wɪð teəz',
        translation: 'Her eyes were filled with tears',
      },
      {
        id: 15,
        expression: 'Я действительно серьезно к этому отношусь',
        transcription: 'aɪm ˈrɪəli ˈsɪərɪəs əˈbaʊt ɪt',
        translation: "I'm really serious about it",
      },
      {
        id: 16,
        expression: 'Он очень увлечен своей работой',
        transcription: 'hiː ɪz ˈvɛri ɪnˌθjuːzɪˈæstɪk əˈbaʊt hɪz ʤɒb',
        translation: 'He is very enthusiastic about his job',
      },
      {
        id: 17,
        expression: 'Я подписан на несколько каналов',
        transcription: 'aɪm səbˈskraɪbd tuː ˈsɛvrəl ˈʧænlz',
        translation: "I'm subscribed to several channels",
      },
      {
        id: 18,
        expression: 'Он умер от этой болезни в прошлом году',
        transcription: 'hiː daɪd ɒv ðɪs dɪˈziːz lɑːst jɪə',
        translation: 'He died of this disease last year',
      },
      {
        id: 19,
        expression: 'Он был оштрафован за это',
        transcription: 'hiː wɒz faɪnd fɔːr ɪt',
        translation: 'He was fined for it',
      },
      {
        id: 20,
        expression: 'Он также вовлечен в этот проект',
        transcription: 'hiː ɪz ˈɔːlsəʊ ɪnˈvɒlvd ɪn ðɪs ˈprɒʤɛkt',
        translation: 'He is also involved in this project',
      },
      {
        id: 21,
        expression: 'Меня предупреждали об этих возможных рисках',
        transcription: 'aɪ wɒz wɔːnd əˈbaʊt ðiːz ˈpɒsəbᵊl rɪsks',
        translation: 'I was warned about these possible risks',
      },
      {
        id: 22,
        expression: 'Он был одет в черное',
        transcription: 'hiː wɒz drɛst ɪn blæk',
        translation: 'He was dressed in black',
      },
      {
        id: 23,
        expression: 'Я был действительно озадачен этим',
        transcription: 'aɪ wɒz ˈrɪəli ˈpʌzld baɪ (əˈbaʊt, æt) ɪt',
        translation: 'I was really puzzled by (about, at) it',
      },
      {
        id: 24,
        expression: 'Я хотел бы предупредить тебя об этом',
        transcription: 'aɪd laɪk tuː wɔːn juː əˈbaʊt ɪt',
        translation: "I'd like to warn you about it",
      },
      {
        id: 25,
        expression: 'Она очень успешна в этой сфере',
        transcription: 'ʃiː ɪz ˈvɛri səkˈsɛsfʊl ɪn ðɪs sfɪə',
        translation: 'She is very successful in this sphere',
      },
      {
        id: 26,
        expression: 'Меня предупреждали об этой опасности',
        transcription: 'aɪ wɒz wɔːnd əˈbaʊt ðɪs ˈdeɪnʤə',
        translation: 'I was warned about this danger',
      },
      {
        id: 27,
        expression: 'Я вовлечен в этот проект',
        transcription: 'aɪm ɪnˈvɒlvd ɪn ðɪs ˈprɒʤɛkt',
        translation: "I'm involved in this project",
      },
      {
        id: 28,
        expression: 'Он был одет в серый костюм',
        transcription: 'hiː wɒz drɛst ɪn ə ɡreɪ sjuːt',
        translation: 'He was dressed in a grey suit',
      },
      {
        id: 29,
        expression: 'Она действительно боялась этого',
        transcription: 'ʃiː wɒz ˈrɪəli skeəd ɒv ɪt',
        translation: 'She was really scared of it',
      },
      {
        id: 30,
        expression: 'Никто не предупреждал меня об этих возможных рисках',
        transcription: 'nəʊ wʌn wɔːnd miː əˈbaʊt ðiːz ˈpɒsəbᵊl rɪsks',
        translation: 'No one warned me about these possible risks',
      },
      {
        id: 31,
        expression: 'Он всмотрелся в экран',
        transcription: 'hiː pɪəd æt ðə skriːn',
        translation: 'He peered at the screen',
      },
      {
        id: 32,
        expression: 'Я так озадачен всем этим',
        transcription: 'aɪm səʊ ˈpʌzld baɪ ɔːl ðɪs',
        translation: "I'm so puzzled by all this",
      },
      {
        id: 33,
        expression: 'Большинство людей не одобряют такое решение',
        transcription: 'məʊst ˈpiːpl ˌdɪsəˈpruːv ɒv sʌʧ ə dɪˈsɪʒən',
        translation: 'Most people disapprove of such a decision',
      },
      {
        id: 34,
        expression: 'Я действительно благодарен тебе за это',
        transcription: 'aɪm ˈrɪəli ˈθæŋkfʊl tuː juː fɔːr ɪt',
        translation: "I'm really thankful to you for it",
      },
      {
        id: 35,
        expression: 'Я был очень сосредоточен на своей работе',
        transcription: 'aɪ wɒz ˈvɛri ɪnˈtɛnt ɒn maɪ wɜːk',
        translation: 'I was very intent on my work',
      },
      {
        id: 36,
        expression: 'Она была замешана в этом скандале',
        transcription: 'ʃiː wɒz ɪnˈvɒlvd ɪn ðɪs ˈskændl',
        translation: 'She was involved in this scandal',
      },
      {
        id: 37,
        expression: 'Он никогда не смеется над этими шутками',
        transcription: 'hiː ˈnɛvə lɑːfs æt ðiːz ʤəʊks',
        translation: 'He never laughs at these jokes',
      },
      {
        id: 38,
        expression: 'Я очень благодарен тебе за твой совет',
        transcription: 'aɪm ˈvɛri ˈθæŋkfʊl tuː juː fɔː jɔːr ədˈvaɪs',
        translation: "I'm very thankful to you for your advice",
      },
      {
        id: 39,
        expression: 'Это единственно правильное решение этой проблемы',
        transcription: 'ɪts ði ˈəʊnli raɪt səˈluːʃᵊn tuː ðɪs ˈprɒbləm',
        translation: "It's the only right solution to this problem",
      },
      {
        id: 40,
        expression: 'Мы ищем эту информацию',
        transcription: 'wɪə ˈsɜːʧɪŋ fɔː ðɪs ˌɪnfəˈmeɪʃᵊn',
        translation: "We're searching for this information",
      },
      {
        id: 41,
        expression:
          'Я абсолютно уверен, что это единственно правильное решение этой проблемы',
        transcription:
          'aɪm ˈæbsəluːtli ʃʊə ðæt ɪts ði ˈəʊnli raɪt səˈluːʃᵊn tuː ðɪs ˈprɒbləm',
        translation:
          "I'm absolutely sure that it's the only right solution to this problem",
      },
      {
        id: 42,
        expression:
          'Студенты, которые действительно серьезно относятся к изучению английского, делают очень хорошие успехи',
        transcription:
          'ˈstjuːdənts, huː ɑː ˈrɪəli ˈsɪərɪəs əˈbaʊt ˈlɜːnɪŋ ˈɪŋɡlɪʃ, meɪk ˈvɛri ɡʊd ˈprəʊɡrəs',
        translation:
          'Students, who are really serious about learning English, make very good progress',
      },
      {
        id: 43,
        expression:
          'Я часто имею дело с людьми, у которых есть такого рода проблема',
        transcription: 'aɪ ˈɒfᵊn diːl wɪð ˈpiːpl huː hæv ðɪs kaɪnd ɒv ˈprɒbləm',
        translation: 'I often deal with people who have this kind of problem',
      },
      {
        id: 44,
        expression: 'Я вижу, ты полон энтузиазма по этому поводу',
        transcription: 'aɪ siː jʊə fɪld wɪð lɒts ɒv ɪnˈθjuːzɪæzm əˈbaʊt ɪt',
        translation: "I see you're filled with lots of enthusiasm about it",
      },
      {
        id: 45,
        expression: 'На какие каналы ты уже подписался?',
        transcription: 'wɒt ˈʧænlz hæv juː ɔːlˈrɛdi juː səbˈskraɪbd tuː?',
        translation: 'What channels have you already you subscribed to?',
      },
      {
        id: 46,
        expression:
          'Его родители пытались отговорить его от того, чтобы он становился профессиональным музыкантом',
        transcription:
          'hɪz ˈpeərənts traɪd tuː dɪsˈkʌrɪʤ hɪm frɒm bɪˈkʌmɪŋ ə prəˈfɛʃənl mjuːˈzɪʃᵊn',
        translation:
          'His parents tryed to discourage him from becoming a professional musician',
      },
      {
        id: 47,
        expression: 'Нам нужно помешать этому произойти',
        transcription: 'wiː niːd tuː prɪˈvɛnt ɪt frɒm ˈhæpnɪŋ',
        translation: 'We need to prevent it from happening',
      },
      {
        id: 48,
        expression: 'Эта компания очень успешна в мире бизнеса',
        transcription: 'ðɪs ˈkʌmpəni ɪz ˈvɛri səkˈsɛsfʊl ɪn ðə ˈbɪznɪs wɜːld',
        translation: 'This company is very successful in the business world',
      },
      {
        id: 49,
        expression: 'Меня переполняет радость и волнение при мысли об этом',
        transcription: 'aɪm fɪld wɪð ʤɔɪ ænd ɪkˈsaɪtmənt æt ðə θɔːt ɒv ɪt',
        translation: "I'm filled with joy and excitement at the thought of it",
      },
      {
        id: 50,
        expression:
          'Я неудовлетворен этим решением, потому что это только частичное решение этой проблемы',
        transcription:
          'aɪm nɒt ˈsætɪsfaɪd wɪð ðɪs dɪˈsɪʒən bɪˈkɒz ɪts ˈəʊnli ˈpɑːʃəl səˈluːʃᵊn tuː ðɪs ˈprɒbləm',
        translation:
          "I'm not satisfied with this decision because it's only partial solution to this problem",
      },
      {
        id: 51,
        expression: 'Они не позволили толпе войти в здание',
        transcription: 'ðeɪ prɪˈvɛntɪd ðə kraʊd frɒm ˈɛntərɪŋ ðə ˈbɪldɪŋ',
        translation: 'They prevented the crowd from entering the building',
      },
      {
        id: 52,
        expression: 'Сколько человек подписаны на этот канал?',
        transcription: 'haʊ ˈmɛni ˈpiːpl ɑː səbˈskraɪbd tuː ðɪs ˈʧænl?',
        translation: 'How many people are subscribed to this channel?',
      },
      {
        id: 53,
        expression: 'На какие каналы ты подписан?',
        transcription: 'wɒt ˈʧænlz ɑː juː səbˈskraɪbd tuː?',
        translation: 'What channels are you subscribed to?',
      },
      {
        id: 54,
        expression: 'Полиция признала его виновным в краже',
        transcription: 'ðə pəˈliːs faʊnd hɪm ˈɡɪlti ɒv θɛft',
        translation: 'The police found him guilty of theft',
      },
      {
        id: 55,
        expression: 'Мой друг отговорил меня от этого',
        transcription: 'ə frɛnd ɒv maɪn dɪsˈkʌrɪʤd miː frɒm ˈduːɪŋ ɪt',
        translation: 'A friend of mine discouraged me from doing it',
      },
      {
        id: 56,
        expression: 'От чего он умер?',
        transcription: 'wɒt dɪd hiː daɪ ɒv?',
        translation: 'What did he die of?',
      },
      {
        id: 57,
        expression: 'Он умер от той болезни?',
        transcription: 'dɪd hiː daɪ ɒv ðæt dɪˈziːz?',
        translation: 'Did he die of that disease?',
      },
      {
        id: 58,
        expression: 'Она умерла от этой болезни в возрасте шестидесяти лет',
        transcription: 'ʃiː daɪd ɒv ðɪs dɪˈziːz æt ði eɪʤ ɒv ˈsɪksti',
        translation: 'She died of this disease at the age of sixty',
      },
      {
        id: 59,
        expression: 'Я стремлюсь делать все возможное',
        transcription: 'aɪ æm ɪnˈtɛnt ɒn ˈduːɪŋ maɪ bɛst',
        translation: 'I am intent on doing my best',
      },
      {
        id: 60,
        expression: 'Она сосредоточена на выполнении этого задания',
        transcription: 'ʃiː ɪz ɪnˈtɛnt ɒn ˈduːɪŋ ðɪs tɑːsk',
        translation: 'She is intent on doing this task',
      },
      {
        id: 61,
        expression: 'Он поглощен чтением',
        transcription: 'hiː ɪz ɪnˈtɛnt ɒn ˈriːdɪŋ',
        translation: 'He is intent on reading',
      },
      {
        id: 62,
        expression: 'Я боюсь ее расстроить',
        transcription: 'aɪm əˈfreɪd ɒv ʌpˈsɛtɪŋ hɜː',
        translation: "I'm afraid of upseting her",
      },
      {
        id: 63,
        expression: 'Он боится быть один',
        transcription: 'hiː ɪz əˈfreɪd ɒv ˈbiːɪŋ əˈləʊn',
        translation: 'He is afraid of being alone',
      },
      {
        id: 64,
        expression: 'Они боятся потерять свою работу',
        transcription: 'ðeɪ ɑːr əˈfreɪd ɒv ˈluːzɪŋ ðeə ʤɒb',
        translation: 'They are afraid of losing their job',
      },
      {
        id: 65,
        expression: 'Как мы можем помешать этому произойти?',
        transcription: 'haʊ kæn wiː prɪˈvɛnt ɪt frɒm ˈhæpnɪŋ?',
        translation: 'How can we prevent it from happening?',
      },
      {
        id: 66,
        expression: 'Тебе нужно помешать этому произойти',
        transcription: 'juː niːd tuː prɪˈvɛnt ɪt frɒm ˈhæpnɪŋ',
        translation: 'You need to prevent it from happening',
      },
      {
        id: 67,
        expression: 'Он помешал нам войти в здание',
        transcription: 'hiː prɪˈvɛntɪd ʌs frɒm ˈɛntərɪŋ ðə ˈbɪldɪŋ',
        translation: 'He prevented us from entering the building',
      },
      {
        id: 68,
        expression: 'Я действительно благодарен тебе за твою помощь',
        transcription: 'aɪm ˈrɪəli ˈθæŋkfʊl tuː juː fɔː jɔː hɛlp',
        translation: "I'm really thankful to you for your help",
      },
      {
        id: 69,
        expression: 'Он действительно благодарен тебе за это',
        transcription: 'hiː ɪz ˈrɪəli ˈθæŋkfʊl tuː juː fɔːr ɪt',
        translation: 'He is really thankful to you for it',
      },
      {
        id: 70,
        expression: 'Я очень благодарен ему за его рекомендацию',
        transcription: 'aɪm ˈvɛri ˈθæŋkfʊl tuː hɪm fɔː hɪz ˌrɛkəmɛnˈdeɪʃᵊn',
        translation: "I'm very thankful to him for his recommendation",
      },
      {
        id: 71,
        expression: 'На какой канал ты подписался?',
        transcription: 'wɒt ˈʧænl dɪd juː səbˈskraɪb tuː?',
        translation: 'What channel did you subscribe to?',
      },
      {
        id: 72,
        expression: 'На сколько каналов ты подписан?',
        transcription: 'haʊ ˈmɛni ˈʧænlz ɑː juː səbˈskraɪbd tuː?',
        translation: 'How many channels are you subscribed to?',
      },
      {
        id: 73,
        expression: 'Я еще не подписался ни на какие каналы',
        transcription: 'aɪ hævnt səbˈskraɪbd tuː ˈɛni ˈʧænlz jɛt',
        translation: "I haven't subscribed to any channels yet",
      },
      {
        id: 74,
        expression: 'Никто не был предупрежден об этом',
        transcription: 'nəʊ wʌn wɒz wɔːnd əˈbaʊt ɪt',
        translation: 'No one was warned about it',
      },
      {
        id: 75,
        expression: 'Он был предупрежден об этих проблемах',
        transcription: 'hiː wɒz wɔːnd əˈbaʊt ɪt',
        translation: 'He was warned about it',
      },
      {
        id: 76,
        expression: 'Я должен предупредить его об этом',
        transcription: 'aɪ mʌst wɔːn hɪm əˈbaʊt ɪt',
        translation: 'I must warn him about it',
      },
      {
        id: 77,
        expression: 'Я увидел даму, одетую в красное',
        transcription: 'aɪ sɔː ə ˈleɪdi drɛst ɪn rɛd',
        translation: 'I saw a lady dressed in red',
      },
      {
        id: 78,
        expression: 'Она была одета в красное',
        transcription: 'ʃiː wɒz drɛst ɪn rɛd',
        translation: 'She was dressed in red',
      },
      {
        id: 79,
        expression: 'Он был одет в черное пальто',
        transcription: 'hiː wɒz drɛst ɪn ə blæk kəʊt',
        translation: 'He was dressed in a black coat',
      },
      {
        id: 80,
        expression: 'Что он ищет?',
        transcription: 'wɒt ɪz hiː ˈsɜːʧɪŋ fɔː?',
        translation: 'What is he searching for?',
      },
      {
        id: 81,
        expression: 'Ты искал эту информацию?',
        transcription: 'wɜː juː ˈsɜːʧɪŋ fɔː ðɪs ˌɪnfəˈmeɪʃᵊn?',
        translation: 'Were you searching for this information?',
      },
      {
        id: 82,
        expression: 'Я ищу это сейчас',
        transcription: 'aɪm ˈsɜːʧɪŋ fɔːr ɪt naʊ',
        translation: "I'm searching for it now",
      },
      {
        id: 83,
        expression: 'Она очень увлечена этой идеей',
        transcription: 'ʃiː fiːlz ˈvɛri ɪnˌθjuːzɪˈæstɪk əˈbaʊt ðɪs aɪˈdɪə',
        translation: 'She feels very enthusiastic about this idea',
      },
      {
        id: 84,
        expression: 'Я знаю, что он очень увлечен этим проектом',
        transcription:
          'aɪ nəʊ ðæt hiː ɪz ˈvɛri ɪnˌθjuːzɪˈæstɪk əˈbaʊt ðɪs ˈprɒʤɛkt',
        translation: 'I know that he is very enthusiastic about this project',
      },
      {
        id: 85,
        expression: 'Она очень увлечена своей новой работой',
        transcription: 'ʃiː ɪz ˈvɛri ɪnˌθjuːzɪˈæstɪk əˈbaʊt hɜː njuː ʤɒb',
        translation: 'She is very enthusiastic about her new job',
      },
      {
        id: 86,
        expression: 'Он был оштрафован за превышение скорости',
        transcription: 'hiː wɒz faɪnd fɔːr ɪkˈsiːdɪŋ ðə spiːd ˈlɪmɪt',
        translation: 'He was fined for exceeding the speed limit',
      },
      {
        id: 87,
        expression: 'Я действительно озадачен его реакцией на этот вопрос',
        transcription: 'aɪm ˈrɪəli ˈpʌzld baɪ hɪz riˈækʃᵊn tuː ðɪs ˈkwɛsʧən',
        translation: "I'm really puzzled by his reaction to this question",
      },
      {
        id: 88,
        expression: 'Решение этой проблемы еще не найдено',
        transcription: 'ðə səˈluːʃᵊn tuː ðɪs ˈprɒbləm ˈhæznt biːn faʊnd jɛt',
        translation: "The solution to this problem hasn't been found yet",
      },
      {
        id: 89,
        expression: 'В чем он был виноват?',
        transcription: 'wɒt wɒz hiː ˈɡɪlti ɒv?',
        translation: 'What was he guilty of?',
      },
      {
        id: 90,
        expression: 'Мой друг отговаривает меня от поездки туда',
        transcription: 'maɪ frɛnd dɪsˈkʌrɪʤɪz miː frɒm ˈɡəʊɪŋ ðeə',
        translation: 'My friend discourages me from going there',
      },
      {
        id: 91,
        expression: 'Я вижу, что ты очень увлечен этим проектом',
        transcription:
          'aɪ siː ðæt jʊə ˈvɛri ɪnˌθjuːzɪˈæstɪk əˈbaʊt ðɪs ˈprɒʤɛkt',
        translation: "I see that you're very enthusiastic about this project",
      },
      {
        id: 92,
        expression: 'Он говорит, что он намерен читать',
        transcription: 'hiː sɛz ðæt hiː ɪz ɪnˈtɛnt ɒn ˈriːdɪŋ',
        translation: 'He says that he is intent on reading',
      },
      {
        id: 93,
        expression: 'Он боится быть один',
        transcription: 'hiː ɪz skeəd ɒv ˈbiːɪŋ əˈlɒŋ',
        translation: 'He is scared of being along',
      },
      {
        id: 94,
        expression: 'Насколько я знаю, он очень успешен в бизнесе',
        transcription: 'æz fɑːr æz aɪ nəʊ hiː ɪz ˈvɛri səkˈsɛsfʊl ɪn ˈbɪznɪs',
        translation: 'As far as I know he is very successful in business',
      },
      {
        id: 95,
        expression: 'Они признали его виновным во взяточничестве',
        transcription: 'ðeɪ faʊnd hɪm ˈɡɪlti ɒv ˈbraɪbəri',
        translation: 'They found him guilty of bribery',
      },
      {
        id: 96,
        expression: 'Многие люди боятся потерять свою работу',
        transcription: 'ˈmɛni ˈpiːpl ɑːr əˈfreɪd ɒv ˈluːzɪŋ ðeə ʤɒb',
        translation: 'Many people are afraid of losing their job',
      },
      {
        id: 97,
        expression: 'Он стремится сделать все возможное',
        transcription: 'hiː ɪz ɪnˈtɛnt ɒn ˈduːɪŋ hɪz bɛst',
        translation: 'He is intent on doing his best',
      },
      {
        id: 98,
        expression: 'За что его оштрафовали?',
        transcription: 'wɒt wɒz hiː faɪnd fɔː?',
        translation: 'What was he fined for?',
      },
      {
        id: 99,
        expression: 'На этот канал подписано десять миллионов человек',
        transcription: 'tɛn ˈmɪljən ˈpiːpl ɑː səbˈskraɪbd tuː ðɪs ˈʧænl',
        translation: 'Ten million people are subscribed to this channel',
      },
      {
        id: 100,
        expression: 'Чем ты так озадачен?',
        transcription: 'wɒt ɑː juː səʊ ˈpʌzld baɪ?',
        translation: 'What are you so puzzled by?',
      },
    ],
    {
      theory: `<div class="theory-block">
<h3>Изучаем следующую группу зависимых предлогов</h3>
</div>`,
    },
  ],
];
