export const contentLesson81 = [
  [
    {
      title: "Урок 81. Past Simple",
    },
    [
      {
        id: 1,
        expression: "Это была долгая история",
        transcription: "ɪt wɒz ə lɒŋ ˈstɔːri",
        translation: "It was a long story",
      },
      {
        id: 2,
        expression: "Они были великими людьми",
        transcription: "ðeɪ wɜː greɪt ˈpiːpl",
        translation: "They were great people",
      },
      {
        id: 3,
        expression: "Еда была очень вкусной",
        transcription: "ðə fuːd wɒz ˈvɛri ˈteɪsti",
        translation: "The food was very tasty",
      },
      {
        id: 4,
        expression: "Многие люди были очень голодные",
        transcription: "ˈmɛni ˈpiːpl wɜː ˈvɛri ˈhʌŋgri",
        translation: "Many people were very hungry",
      },
      {
        id: 5,
        expression: "Я играл в футбол",
        transcription: "aɪ pleɪd ˈfʊtbɔːl",
        translation: "I played football",
      },
      {
        id: 6,
        expression: "Он пошел домой",
        transcription: "hiː wɛnt həʊm",
        translation: "He went home",
      },
      {
        id: 7,
        expression: "Он жил в этом старом доме",
        transcription: "hiː lɪvd ɪn ðɪs əʊld haʊs",
        translation: "He lived in this old house",
      },
      {
        id: 8,
        expression: "Те меры привели к новым конфликтам",
        transcription: "ðəʊz ˈmɛʒəz lɛd tuː njuː ˈkɒnflɪkts",
        translation: "Those measures led to new conflicts",
      },
      {
        id: 9,
        expression: "Это привело к новым протестам",
        transcription: "ɪt lɛd tuː njuː ˈprəʊtɛsts",
        translation: "It led to new protests",
      },
      {
        id: 10,
        expression: "Это было очевидно для меня",
        transcription: "ɪt wɒz ˈɒbvɪəs tuː miː",
        translation: "It was obvious to me",
      },
      {
        id: 11,
        expression: "Они были действительно шокированы",
        transcription: "ðeɪ wɜː ˈrɪəli ʃɒkt",
        translation: "They were really shocked",
      },
      {
        id: 12,
        expression: "У меня был небольшой перерыв между уроками",
        transcription: "aɪ hæd ə ʃɔːt breɪk bɪˈtwiːn ðə ˈlɛsnz",
        translation: "I had a short break between the lessons",
      },
      {
        id: 13,
        expression: "Это была очень популярная песня несколько лет назад",
        transcription: "ɪt wɒz ə ˈvɛri ˈpɒpjʊlə sɒŋ ˈsɛvrəl jɪəz əˈgəʊ",
        translation: "It was a very popular song several years ago",
      },
      {
        id: 14,
        expression: "Тренировки были очень интенсивными",
        transcription: "ðə ˈtreɪnɪŋz wɜː ˈvɛri ɪnˈtɛnsɪv",
        translation: "The trainings were very intensive",
      },
      {
        id: 15,
        expression: "Та работа требовала большого опыта работы",
        transcription: "ðæt ʤɒb rɪˈkwaɪəd mɔː wɜːk ɪksˈpɪərɪəns",
        translation: "That job required more work experience",
      },
      {
        id: 16,
        expression: "Тяжелая работа привела его к успеху",
        transcription: "hɑːd wɜːk lɛd hɪm tuː səkˈsɛs",
        translation: "Hard work led him to success",
      },
      {
        id: 17,
        expression: "Это было очень мудрое решение",
        transcription: "ɪt wɒz ə ˈvɛri waɪz dɪˈsɪʒən",
        translation: "It was a very wise decision",
      },
      {
        id: 18,
        expression: "Она действительно боялась этого",
        transcription: "ʃiː wɒz ˈrɪəli əˈfreɪd ɒv ɪt",
        translation: "She was really afraid of it",
      },
      {
        id: 19,
        expression: "Я отдыхал вечером",
        transcription:
          "aɪ hæd ə rɛst ɪn ði ˈiːvnɪŋ / aɪ rɪˈlækst ɪn ði ˈiːvnɪŋ",
        translation: "I had a rest in the evening / I relaxed in the evening",
      },
      {
        id: 20,
        expression: "Еда была очень вкусной",
        transcription: "ðə fuːd wɒz ˈvɛri ˈteɪsti",
        translation: "The food was very tasty",
      },
      {
        id: 21,
        expression: "Я написал короткое эссе",
        transcription: "aɪ rəʊt ə ʃɔːt ˈɛseɪ",
        translation: "I wrote a short essay",
      },
      {
        id: 22,
        expression: "Он написал сочинение",
        transcription: "hiː rəʊt ə ˌkɒmpəˈzɪʃən",
        translation: "He wrote a composition",
      },
      {
        id: 23,
        expression: "Тренировка была очень интенсивной",
        transcription: "ðə ˈtreɪnɪŋ wɒz ˈvɛri ɪnˈtɛnsɪv",
        translation: "The training was very intensive",
      },
      {
        id: 24,
        expression: "Это была долгая история",
        transcription: "ɪt wɒz ə lɒŋ ˈstɔːri",
        translation: "It was a long story",
      },
      {
        id: 25,
        expression: "Забор был коричневый",
        transcription: "ðə fɛns wɒz braʊn",
        translation: "The fence was brown",
      },
      {
        id: 26,
        expression: "Это была правдивая история",
        transcription: "ɪt wɒz ə truː ˈstɔːri",
        translation: "It was a true story",
      },
      {
        id: 27,
        expression: "Я положил это в свою сумку",
        transcription: "aɪ pʊt ɪt ɪn maɪ bæg",
        translation: "I put it in my bag",
      },
      {
        id: 28,
        expression: "Это было великое открытие",
        transcription: "ɪt wɒz ə greɪt dɪsˈkʌvəri",
        translation: "It was a great discovery",
      },
      {
        id: 29,
        expression: "Ее решение было очень мудрым",
        transcription: "hɜː dɪˈsɪʒən wɒz ˈvɛri waɪz",
        translation: "Her decision was very wise",
      },
      {
        id: 30,
        expression: "Я был так удивлен",
        transcription: "aɪ wɒz səʊ səˈpraɪzd",
        translation: "I was so surprised",
      },
      {
        id: 31,
        expression: "Клиника была действительно хорошая",
        transcription: "ðə ˈklɪnɪk wɒz ˈrɪəli gʊd",
        translation: "The clinic was really good",
      },
      {
        id: 32,
        expression: "Еда была действительно восхитительной",
        transcription: "ðə fuːd wɒz ˈrɪəli əˈmeɪzɪŋ",
        translation: "The food was really amazing",
      },
      {
        id: 33,
        expression: "Многие люди были очень голодные",
        transcription: "ˈmɛni ˈpiːpl wɜː ˈvɛri ˈhʌŋgri",
        translation: "Many people were very hungry",
      },
      {
        id: 34,
        expression: "Мальчики были во дворе",
        transcription: "ðə bɔɪz wɜːr ɪn ðə jɑːd",
        translation: "The boys were in the yard",
      },
      {
        id: 35,
        expression: "Он сделал великое открытие",
        transcription: "hiː meɪd ə greɪt dɪsˈkʌvəri",
        translation: "He made a great discovery",
      },
      {
        id: 36,
        expression: "Это была удивительная история",
        transcription: "ɪt wɒz ən əˈmeɪzɪŋ ˈstɔːri",
        translation: "It was an amazing story",
      },
      {
        id: 37,
        expression: "Качество было очень хорошее",
        transcription: "ðə ˈkwɒlɪti wɒz ˈvɛri gʊd",
        translation: "The quality was very good",
      },
      {
        id: 38,
        expression: "Еда была вкусная",
        transcription: "ðə fuːd wɒz ˈteɪsti (dɪˈlɪʃəs)",
        translation: "The food was tasty (delicious)",
      },
      {
        id: 39,
        expression: "Кризис был очень серьезный",
        transcription: "ðə ˈkraɪsɪs wɒz ˈvɛri ˈsɪərɪəs",
        translation: "The crisis was very serious",
      },
      {
        id: 40,
        expression: "Это была настоящая революция в технике",
        transcription: "ɪt wɒz ə rɪəl ˌriːvəʊˈlɪʃən ɪn tɛkˈnɒləʤi",
        translation: "It was a real revolition in technology",
      },
      {
        id: 41,
        expression: "У нас был короткий перерыв после урока",
        transcription: "wiː hæd ə ʃɔːt breɪk ˈɑːftə ðə ˈlɛsn",
        translation: "We had a short break after the lesson",
      },
      {
        id: 42,
        expression: "Он сделал маленькую ошибку",
        transcription: "hiː meɪd ə ˈlɪtl mɪsˈteɪk",
        translation: "He made a little mistake",
      },
      {
        id: 43,
        expression: "Многие люди жили в очень плохих условиях",
        transcription: "ˈmɛni ˈpiːpl lɪvd ɪn ˈvɛri bæd kənˈdɪʃənz",
        translation: "Many people lived in very bad conditions",
      },
      {
        id: 44,
        expression: "Я сделал все правильно",
        transcription: "aɪ dɪd ˈɛvrɪθɪŋ kəˈrɛktli",
        translation: "I did everything correctly",
      },
      {
        id: 45,
        expression: "Мы согласились сделать это",
        transcription: "wiː əˈgriːd tuː duː ɪt",
        translation: "We agreed to do it",
      },
      {
        id: 46,
        expression: "Эта работа требовала больше навыков",
        transcription: "ðɪs ʤɒb rɪˈkwaɪəd mɔː skɪlz",
        translation: "This job required more skills",
      },
      {
        id: 47,
        expression: "Эти меры привели к новым протестам",
        transcription: "ðiːz ˈmɛʒəz lɛd tuː njuː ˈprəʊtɛsts",
        translation: "These measures led to new protests",
      },
      {
        id: 48,
        expression: "Коттедж был слишком мал для их семьи",
        transcription: "ðə ˈkɒtɪʤ wɒz tuː smɔːl fɔː ðeə ˈfæmɪli",
        translation: "The cottage was too small for their family",
      },
      {
        id: 49,
        expression:
          "Я могу сказать, что я чувствовал себя очень комфортно среди носителей языка",
        transcription:
          "aɪ kæn seɪ ðæt aɪ fɛlt ˈvɛri ˈkʌmf(ə)təbl əˈmʌŋ ˈneɪtɪv ˈspiːkəz",
        translation:
          "I can say that I felt very comfortable among native speakers",
      },
      {
        id: 50,
        expression:
          "Эта работа требовала также больше опыта работы и профессиональных навыков",
        transcription:
          "ðɪs ʤɒb rɪˈkwaɪəd mɔː wɜːk ɪksˈpɪərɪəns ænd prəˈfɛʃənl skɪlz æz wɛl",
        translation:
          "This job required more work experience and professional skills as well",
      },
      {
        id: 51,
        expression: "Это было чрезвычайно сложное упражнение",
        transcription: "ɪt wɒz ən ɪksˈtriːmli ˈdɪfɪkəlt ˈɛksəsaɪz",
        translation: "It was an extremely difficult exercise",
      },
      {
        id: 52,
        expression: "Для нас все было очевидно",
        transcription: "ˈɛvrɪθɪŋ wɒz ˈɒbvɪəs tuː ʌs",
        translation: "Everything was obvious to us",
      },
      {
        id: 53,
        expression: "Я был полностью удовлетворен своими результатами",
        transcription: "aɪ wɒz ˈfʊli ˈsætɪsfaɪd wɪð maɪ rɪˈzʌlts",
        translation: "I was fully satisfied with my results",
      },
      {
        id: 54,
        expression: "Его друг стал американским гражданином в прошлом году",
        transcription: "hɪz frɛnd bɪˈkeɪm ən əˈmɛrɪkən ˈsɪtɪzn lɑːst jɪə",
        translation: "His friend became an American citizen last year",
      },
      {
        id: 55,
        expression: "Мой отец собирал монеты, когда он был молодым",
        transcription: "maɪ ˈfɑːðə kəˈlɛktɪd kɔɪnz wɛn hiː wɒz jʌŋ",
        translation: "My father collected coins when he was young",
      },
      {
        id: 56,
        expression: "Те меры привели к новым конфликтам и протестам",
        transcription: "ðəʊz ˈmɛʒəz lɛd tuː njuː ˈkɒnflɪkts ænd ˈprəʊtɛsts",
        translation: "Those measures led to new conflicts and protests",
      },
      {
        id: 57,
        expression: "Мне удалось сдать тот экзамен",
        transcription: "aɪ ˈmænɪʤd tuː pɑːs ðæt ɪgˈzæm",
        translation: "I managed to pass that exam",
      },
      {
        id: 58,
        expression:
          "Я могу сказать, что я был полностью удовлетворен качеством этих уроков",
        transcription:
          "aɪ kæn seɪ ðæt aɪ wɒz ˈfʊli ˈsætɪsfaɪd wɪð ðə ˈkwɒlɪti ɒv ðiːz ˈlɛsnz",
        translation:
          "I can say that I was fully satisfied with the quality of these lessons",
      },
      {
        id: 59,
        expression: "Качество этих продуктов было очень хорошим",
        transcription: "ðə ˈkwɒlɪti ɒv ðiːz ˈprɒdʌkts wɒz ˈvɛri gʊd",
        translation: "The quality of these products was very good",
      },
      {
        id: 60,
        expression: "Мне удалось сдать тот тест",
        transcription: "aɪ ˈmænɪʤd tuː pɑːs ðæt tɛst",
        translation: "I managed to pass that test",
      },
      {
        id: 61,
        expression: "Это была очень неприятная вещь",
        transcription: "ɪt wɒz ə ˈvɛri ʌnˈplɛznt θɪŋ",
        translation: "It was a very unpleasant thing",
      },
      {
        id: 62,
        expression: "Он часто опаздывал, и мне это не нравилось",
        transcription: "hiː wɒz ˈɒf(ə)n leɪt ænd aɪ dɪdnt laɪk ɪt",
        translation: "He was often late and I didn't like it",
      },
      {
        id: 63,
        expression: "Я хотел увидеть мир",
        transcription: "aɪ ˈwɒntɪd tuː siː ðə wɜːld",
        translation: "I wanted to see the world",
      },
      {
        id: 64,
        expression: "Все было чрезвычайно сложно",
        transcription: "ˈɛvrɪθɪŋ wɒz ɪksˈtriːmli ˈdɪfɪkəlt",
        translation: "Everything was extremely difficult",
      },
      {
        id: 65,
        expression: "Эти экзамены были чрезвычайно сложными",
        transcription: "ðiːz ɪgˈzæmz wɜːr ɪksˈtriːmli ˈdɪfɪkəlt",
        translation: "These exams were extremely difficult",
      },
      {
        id: 66,
        expression: "Все было действительно сложно",
        transcription: "ˈɛvrɪθɪŋ wɒz ˈrɪəli ˈdɪfɪkəlt",
        translation: "Everything was really difficult",
      },
      {
        id: 67,
        expression: "Я знаю, что принял правильное решение",
        transcription: "aɪ nəʊ ðæt aɪ meɪd ðə raɪt dɪˈsɪʒən",
        translation: "I know that I made the right decision",
      },
      {
        id: 68,
        expression: "Она знает, что приняла правильное решение",
        transcription: "ʃiː nəʊz ðæt ʃiː meɪd (tʊk) ðə raɪt dɪˈsɪʒən",
        translation: "She knows that she made (took) the right decision",
      },
      {
        id: 69,
        expression: "Я знаю, что он нашел лучшее решение",
        transcription: "aɪ nəʊ ðæt hiː faʊnd ðə bɛst səˈluːʃən",
        translation: "I know that he found the best solution",
      },
      {
        id: 70,
        expression: "Это был чрезвычайно полезный урок",
        transcription: "ɪt wɒz ən ɪksˈtriːmli ˈjuːsfʊl ˈlɛsn",
        translation: "It was an extremely useful lesson",
      },
      {
        id: 71,
        expression: "Это был очень полезный урок",
        transcription: "ɪt wɒz ə ˈvɛri ˈjuːsfʊl ˈlɛsn",
        translation: "It was a very useful lesson",
      },
      {
        id: 72,
        expression: "Это был очень полезный курс",
        transcription: "ɪt wɒz ə ˈvɛri ˈjuːsfʊl kɔːs",
        translation: "It was a very useful course",
      },
      {
        id: 73,
        expression: "Все было так необычно",
        transcription: "ˈɛvrɪθɪŋ wɒz səʊ ʌnˈjuːʒʊəl",
        translation: "Everything was so unusual",
      },
      {
        id: 74,
        expression: "Все было так обычно",
        transcription: "ˈɛvrɪθɪŋ wɒz səʊ ˈjuːʒʊəl",
        translation: "Everything was so usual",
      },
      {
        id: 75,
        expression: "Все было необычно",
        transcription: "ˈɛvrɪθɪŋ wɒz ʌnˈjuːʒʊəl",
        translation: "Everything was unusual",
      },
      {
        id: 76,
        expression: "Я знаю, что мне действительно повезло",
        transcription: "aɪ nəʊ ðæt aɪ wɒz ˈrɪəli ˈlʌki",
        translation: "I know that I was really lucky",
      },
      {
        id: 77,
        expression: "Я знаю, что мне очень повезло",
        transcription: "aɪ nəʊ ðæt aɪ wɒz ˈvɛri ˈlʌki",
        translation: "I know that I was very lucky",
      },
      {
        id: 78,
        expression: "Я знаю, что им очень повезло",
        transcription: "aɪ nəʊ ðæt ðeɪ wɜː ˈvɛri ˈlʌki",
        translation: "I know that they were very lucky",
      },
      {
        id: 79,
        expression: "Это был чрезвычайно длинный курс",
        transcription: "ɪt wɒz ɪksˈtriːmli lɒŋ kɔːs",
        translation: "It was extremely long course",
      },
      {
        id: 80,
        expression: "Это был чрезвычайно сложный курс",
        transcription: "ɪt wɒz ən ɪksˈtriːmli ˈdɪfɪkəlt kɔːs",
        translation: "It was an extremely difficult course",
      },
      {
        id: 81,
        expression: "Это был очень длинный курс",
        transcription: "ɪt wɒz ə ˈvɛri lɒŋ kɔːs",
        translation: "It was a very long course",
      },
      {
        id: 82,
        expression: "Это было очень приятное чувство",
        transcription: "ɪt wɒz ə ˈvɛri ˈplɛznt ˈfiːlɪŋ",
        translation: "It was a very pleasant feeling",
      },
      {
        id: 83,
        expression: "Это очень приятное чувство",
        transcription: "ɪts ə ˈvɛri ˈplɛznt ˈfiːlɪŋ",
        translation: "It's a very pleasant feeling",
      },
      {
        id: 84,
        expression: "Это было очень хорошее чувство",
        transcription: "ɪt wɒz ə ˈvɛri gʊd ˈfiːlɪŋ",
        translation: "It was a very good feeling",
      },
      {
        id: 85,
        expression: "Коттедж был достаточно большим",
        transcription: "ðə ˈkɒtɪʤ wɒz bɪg ɪˈnʌf",
        translation: "The cottage was big enough",
      },
      {
        id: 86,
        expression: "Дом был достаточно большим",
        transcription: "ðə haʊs wɒz bɪg ɪˈnʌf",
        translation: "The house was big enough",
      },
      {
        id: 87,
        expression: "Это здание было достаточно большим",
        transcription: "ðɪs ˈbɪldɪŋ wɒz bɪg ɪˈnʌf",
        translation: "This building was big enough",
      },
      {
        id: 88,
        expression: "Я не думаю, что я сделал большую ошибку",
        transcription: "aɪ dəʊnt θɪŋk ðæt aɪ meɪd ə bɪg mɪsˈteɪk",
        translation: "I don't think that I made a big mistake",
      },
      {
        id: 89,
        expression: "Она не думает, что сделала большую ошибку",
        transcription: "ʃiː dʌznt θɪŋk ðæt ʃiː meɪd ə bɪg mɪsˈteɪk",
        translation: "She doesn't think that she made a big mistake",
      },
      {
        id: 90,
        expression: "Я не думаю, что я сделал много ошибок",
        transcription: "aɪ dəʊnt θɪŋk ðæt aɪ meɪd ˈmɛni mɪsˈteɪks",
        translation: "I don't think that I made many mistakes",
      },
      {
        id: 91,
        expression: "Все люди в том городе были очень дружелюбные",
        transcription: "ɔːl ðə ˈpiːpl ɪn ðæt ˈsɪti wɜː ˈvɛri ˈfrɛndli",
        translation: "All the people in that city were very friendly",
      },
      {
        id: 92,
        expression: "Все люди в этом городе были очень дружелюбные",
        transcription: "ɔːl ðə ˈpiːpl ɪn ðɪs ˈsɪti wɜː ˈvɛri ˈfrɛndli",
        translation: "All the people in this city were very friendly",
      },
      {
        id: 93,
        expression: "Многие люди в том городе были очень дружелюбные",
        transcription: "ˈmɛni ˈpiːpl ɪn ðæt ˈsɪti wɜː ˈvɛri ˈfrɛndli",
        translation: "Many people in that city were very friendly",
      },
      {
        id: 94,
        expression: "Одно из этих мест действительно впечатлило меня",
        transcription: "wʌn ɒv ðiːz ˈpleɪsɪz ˈrɪəli ɪmˈprɛst miː",
        translation: "One of these places really impressed me",
      },
      {
        id: 95,
        expression: "Комната была достаточно большая",
        transcription: "ðə ruːm wɒz bɪg ɪˈnʌf",
        translation: "The room was big enough",
      },
      {
        id: 96,
        expression: "Это был чрезвычайно важный урок",
        transcription: "ɪt wɒz ən ɪksˈtriːmli ɪmˈpɔːtənt ˈlɛsn",
        translation: "It was an extremely important lesson",
      },
      {
        id: 97,
        expression: "Один из моих друзей работал в банке",
        transcription: "wʌn ɒv maɪ frɛndz wɜːkt ɪn ə bæŋk",
        translation: "One of my friends worked in a bank",
      },
      {
        id: 98,
        expression: "Он согласился сделать это в конце",
        transcription: "hiː əˈgriːd tuː duː ɪt ɪn ði ɛnd",
        translation: "He agreed to do it in the end",
      },
      {
        id: 99,
        expression: "Люди в этом городе были очень дружелюбные",
        transcription: "ˈpiːpl ɪn ðɪs ˈsɪti wɜː ˈvɛri ˈfrɛndli",
        translation: "People in this city were very friendly",
      },
      {
        id: 100,
        expression: "Я старался не показывать это",
        transcription: "aɪ traɪd nɒt tuː ʃəʊ ɪt",
        translation: "I tried not to show it",
      },
      {
        id: 101,
        expression: "Я был полностью удовлетворен качеством этих продуктов",
        transcription: "aɪ wɒz ˈfʊli ˈsætɪsfaɪd ðə ˈkwɒlɪti ɒv ðiːz ˈprɒdʌkts",
        translation: "I was fully satisfied the quality of these products",
      },
      {
        id: 102,
        expression: "Я хотел общаться с иностранцами",
        transcription: "aɪ ˈwɒntɪd tuː kəˈmjuːnɪkeɪt wɪð ˈfɒrɪnəz",
        translation: "I wanted to communicate with foreigners",
      },
      {
        id: 103,
        expression: "Мне удалось сделать все вовремя",
        transcription: "aɪ ˈmænɪʤd tuː duː ˈɛvrɪθɪŋ ɒn taɪm",
        translation: "I managed to do everything on time",
      },
      {
        id: 104,
        expression: "Я часто опаздывал",
        transcription: "aɪ wɒz ˈɒf(ə)n leɪt",
        translation: "I was often late",
      },
      {
        id: 105,
        expression: "Я верил, что это была правда",
        transcription:
          "aɪ bɪˈliːvd ðæt ɪt wɒz truː / aɪ bɪˈliːvd ðæt ɪt wɒz ðə truːθ",
        translation:
          "I believed that it was true / I believed that it was the truth",
      },
      {
        id: 106,
        expression: "Это было необходимо сделать",
        transcription: "ɪt wɒz ˈnɛsɪsəri tuː duː",
        translation: "It was necessary to do",
      },
      {
        id: 107,
        expression: "Он стал американским гражданином",
        transcription: "hiː bɪˈkeɪm ən əˈmɛrɪkən ˈsɪtɪzn",
        translation: "He became an American citizen",
      },
      {
        id: 108,
        expression: "Вам действительно повезло",
        transcription: "juː wɜː ˈrɪəli ˈlʌki",
        translation: "You were really lucky",
      },
    ],
    {
      theory: `<div class="theory-block">
<h3>Закрепление пройденного материала</h3>
</div>`,
    },
  ],
];
