export const contentLesson68 = [
  [
    {
      title:
        "Урок 68. Present Simple: сложные подлежащие + verb + глагол to be: Question",
    },
    [
      {
        id: 1,
        expression: "Эти джинсы стоят восемьдесят долларов?",
        transcription: "dʊ ðiːz ʤiːnz kɒst ˈeɪti ˈdɒləz?",
        translation: "Do these jeans cost eighty dollars?",
      },
      {
        id: 2,
        expression: "Еда плохо пахнет?",
        transcription: "dəz ðə fuːd smɛl bæd?",
        translation: "Does the food smell bad?",
      },
      {
        id: 3,
        expression: "Торт вкусный?",
        transcription: "ɪz ðə keɪk ˈteɪsti?",
        translation: "Is the cake tasty?",
      },
      {
        id: 4,
        expression: "Твои родители правы?",
        transcription: "ɑː jə ˈpeərənts raɪt?",
        translation: "Are your parents right?",
      },
      {
        id: 5,
        expression: "Эта вещь действительно интересна тебе?",
        transcription:
          "ɪz ðɪs θɪŋ ˈrɪəli ˈɪntrɪstɪŋ fə juː? / dəz ðɪs θɪŋ ˈrɪəli ˈɪntrɪst juː? / ɑː jʊ ˈrɪəli ˈɪntrɪstɪd ɪn ðɪs θɪŋ?",
        translation:
          "Is this thing really interesting for you? / Does this thing really interest you? / Are you really interested in this thing?",
      },
      {
        id: 6,
        expression: "Твои бабушка с дедушкой часто приходят к тебе?",
        transcription: "dʊ jə ˈgrænˌpeərənts ˈɒf(ə)n kʌm tə juː?",
        translation: "Do your grandparents often come to you?",
      },
      {
        id: 7,
        expression: "Этот певец очень популярен в Америке?",
        transcription: "ɪz ðɪs ˈsɪŋə ˈvɛri ˈpɒpjʊlər ɪn əˈmɛrɪkə?",
        translation: "Is this singer very popular in America?",
      },
      {
        id: 8,
        expression: "Те мальчики очень умные?",
        transcription: "ɑː ðiːz bɔɪz ˈvɛri smɑːt?",
        translation: "Are these boys very smart?",
      },
      {
        id: 9,
        expression: "Твоя бабушка помогает тебе?",
        transcription: "dəz jə ˈgrænˌmʌðə (ˈgræni) hɛlp juː?",
        translation: "Does your grandmother (granny) help you?",
      },
      {
        id: 10,
        expression: "Этот уровень слишком сложный для них?",
        transcription: "ɪz ðɪs ˈlɛvl tuː ˈdɪfɪkəlt fə ðɛm?",
        translation: "Is this level too difficult for them?",
      },
      {
        id: 11,
        expression: "Пациент чувствует себя лучше?",
        transcription: "dəz ðə ˈpeɪʃənt fiːl ˈbɛtə?",
        translation: "Does the patient feel better?",
      },
      {
        id: 12,
        expression: "Этот текст кажется очень сложным?",
        transcription: "dəz ðɪs tɛkst siːm ˈvɛri ˈdɪfɪkəlt?",
        translation: "Does this text seem very difficult?",
      },
      {
        id: 13,
        expression: "Этот путь намного короче?",
        transcription: "ɪz ðɪs weɪ mʌʧ ˈʃɔːtə?",
        translation: "Is this way much shorter?",
      },
      {
        id: 14,
        expression: "Та вещь интересует тебя?",
        transcription:
          "dəz ðət θɪŋ ˈɪntrɪst juː? / ɪz ðət θɪŋ ˈɪntrɪstɪŋ fə juː?",
        translation:
          "Does that thing interest you? / Is that thing interesting for you?",
      },
      {
        id: 15,
        expression: "Дети дома?",
        transcription: "ɑː ðə kɪdz ət həʊm?",
        translation: "Are the kids at home?",
      },
      {
        id: 16,
        expression: "Мальчик очень высокий для своего возраста?",
        transcription: "ɪz ðə bɔɪ ˈvɛri tɔːl fə hɪz eɪʤ?",
        translation: "Is the boy very tall for his age?",
      },
      {
        id: 17,
        expression: "Гора очень высокая?",
        transcription: "ɪz ðə ˈmaʊntɪn ˈvɛri haɪ?",
        translation: "Is the mountain very high?",
      },
      {
        id: 18,
        expression: "Компания очень богатая?",
        transcription: "ɪz ðə ˈkʌmpəni ˈvɛri rɪʧ?",
        translation: "Is the company very rich?",
      },
      {
        id: 19,
        expression: "Этой практики достаточно?",
        transcription: "ɪz ðɪs ˈpræktɪs ɪˈnʌf?",
        translation: "Is this practice enough?",
      },
      {
        id: 20,
        expression: "Этому пациенту хуже?",
        transcription: "ɪz ðɪs ˈpeɪʃənt wɜːs?",
        translation: "Is this patient worse?",
      },
      {
        id: 21,
        expression: "Торт вкусный?",
        transcription: "ɪz ðə keɪk ˈteɪsti?",
        translation: "Is the cake tasty?",
      },
      {
        id: 22,
        expression: "Горы очень высокие?",
        transcription: "ɑː ðə ˈmaʊntɪnz ˈvɛri haɪ?",
        translation: "Are the mountains very high?",
      },
      {
        id: 23,
        expression: "Этот мальчик выглядит очень умным?",
        transcription: "dəz ðɪs bɔɪ lʊk ˈvɛri smɑːt?",
        translation: "Does this boy look very smart?",
      },
      {
        id: 24,
        expression: "Этот канал очень полезный?",
        transcription: "ɪz ðɪs ˈʧænl ˈvɛri ˈjuːsfʊl?",
        translation: "Is this channel very useful?",
      },
      {
        id: 25,
        expression: "Стол круглый?",
        transcription: "ɪz ðə ˈteɪbl raʊnd?",
        translation: "Is the table round?",
      },
      {
        id: 26,
        expression: "Билеты стоят больше?",
        transcription: "dʊ ðə ˈtɪkɪts kɒst mɔː?",
        translation: "Do the tickets cost more?",
      },
      {
        id: 27,
        expression: "Этот уровень элементарный?",
        transcription: "ɪz ðɪs ˈlɛvl ˌɛlɪˈmɛntəri?",
        translation: "Is this level elementary?",
      },
      {
        id: 28,
        expression: "Река очень красивая?",
        transcription: "ɪz ðə ˈrɪvə ˈvɛri ˈbjuːtəfʊl?",
        translation: "Is the river very beautiful?",
      },
      {
        id: 29,
        expression: "Тест очень сложный для тебя?",
        transcription: "ɪz ðə tɛst ˈvɛri ˈdɪfɪkəlt fə juː?",
        translation: "Is the test very difficult for you?",
      },
      {
        id: 30,
        expression: "Компания выглядит очень успешной?",
        transcription: "dəz ðə ˈkʌmpəni lʊk ˈvɛri səkˈsɛsfʊl?",
        translation: "Does the company look very successful?",
      },
      {
        id: 31,
        expression: "Этой практики кажется достаточно?",
        transcription: "dəz ðɪs ˈpræktɪs siːm ɪˈnʌf?",
        translation: "Does this practice seem enough?",
      },
      {
        id: 32,
        expression: "Этот музыкант очень талантливый?",
        transcription: "ɪz ðɪs mju(ː)ˈzɪʃən ˈvɛri ˈtæləntɪd?",
        translation: "Is this musician very talented?",
      },
      {
        id: 33,
        expression: "Это средний уровень?",
        transcription: "ɪz ɪt ən ˌɪntəˈmiːdiət ˈlɛvl?",
        translation: "Is it an intermediate level?",
      },
      {
        id: 34,
        expression: "Тот средний уровень?",
        transcription: "ɪz ðət ən ˌɪntəˈmiːdiət ˈlɛvl?",
        translation: "Is that an intermediate level?",
      },
      {
        id: 35,
        expression: "Этот путь кажется гораздо короче?",
        transcription: "dəz ðɪs weɪ siːm mʌʧ ˈʃɔːtə?",
        translation: "Does this way seem much shorter?",
      },
      {
        id: 36,
        expression: "Это элементарный уровень?",
        transcription: "ɪz ɪt ən ˌɛlɪˈmɛntəri ˈlɛvl?",
        translation: "Is it an elementary level?",
      },
      {
        id: 37,
        expression: "Еда очень вкусная?",
        transcription: "ɪz ðə fuːd ˈteɪsti?",
        translation: "Is the food tasty?",
      },
      {
        id: 38,
        expression: "Билет стоит больше?",
        transcription: "dʊ ðə ˈtɪkɪts kɒst mɔː?",
        translation: "Do the tickets cost more?",
      },
      {
        id: 39,
        expression: "Эти мальчики кажутся очень талантливыми?",
        transcription: "dʊ ðiːz bɔɪz siːm ˈvɛri ˈtæləntɪd?",
        translation: "Do these boys seem very talented?",
      },
      {
        id: 40,
        expression: "Тебе подходит время нашей встречи?",
        transcription: "dəz ðə taɪm əv ˈaʊə ˈmiːtɪŋ sjuːt juː?",
        translation: "Does the time of our meeting suit you?",
      },
      {
        id: 41,
        expression:
          "Твой друг чувствует себя достаточно уверенно, когда говорит на иностранном языке?",
        transcription:
          "dəz jə frɛnd fiːl ˈkɒnfɪdənt ɪˈnʌf wɛn hi spiːks ˈfɒrɪn ˈlæŋgwɪʤ?",
        translation:
          "Does your friend feel confident enough when he speaks foreign language?",
      },
      {
        id: 42,
        expression: "Этот дом стоит свыше двух миллионов долларов?",
        transcription: "dəz ðɪs haʊs kɒst ˈəʊvə tuː ˈmɪljən ˈdɒləz?",
        translation: "Does this house cost over two million dollars?",
      },
      {
        id: 43,
        expression: "Твоя жена часто делает покупки?",
        transcription: "dəz jə waɪf ˈɒf(ə)n dʊ ðə ˈʃɒpɪŋ?",
        translation: "Does your wife often do the shopping?",
      },
      {
        id: 44,
        expression: "То время для них удобно?",
        transcription: "ɪz ðət taɪm kənˈviːniənt fə ðɛm?",
        translation: "Is that time convenient for them?",
      },
      {
        id: 45,
        expression:
          "Этот студент чувствует себя достаточно уверенно, когда говорит по-английски?",
        transcription:
          "dəz ðɪs ˈstjuːdənt fiːl ˈkɒnfɪdənt ɪˈnʌf (kwaɪt ˈkɒnfɪdənt) wɛn hi spiːks ˈɪŋglɪʃ?",
        translation:
          "Does this student feel confident enough (quite confident) when he speaks English?",
      },
      {
        id: 46,
        expression: "Эти новости действительно странные?",
        transcription: "ɪz ðɪs njuːz ˈrɪəli streɪnʤ?",
        translation: "Is this news really strange?",
      },
      {
        id: 47,
        expression: "Эта вещь зависит от меня?",
        transcription: "dəz ðɪs θɪŋ dɪˈpɛnd ɒn miː?",
        translation: "Does this thing depend on me?",
      },
      {
        id: 48,
        expression: "Твой друг уверен в этом?",
        transcription: "ɪz jə frɛnd ʃʊər əˈbaʊt ɪt?",
        translation: "Is your friend sure about it?",
      },
      {
        id: 49,
        expression: "Этих знаний достаточно?",
        transcription: "ɪz ðɪs ˈnɒlɪʤ ɪˈnʌf?",
        translation: "Is this knowledge enough?",
      },
      {
        id: 50,
        expression: "Эта работа очень стрессовая?",
        transcription: "ɪz ðɪs ʤɒb ˈrɪəli ˈstrɛsf(ə)l?",
        translation: "Is this job really stressful?",
      },
      {
        id: 51,
        expression: "У мальчика действительно выдающиеся результаты?",
        transcription: "dəz ðə bɔɪ ˈrɪəli həv aʊtˈstændɪŋ rɪˈzʌlts?",
        translation: "Does the boy really have outstanding results?",
      },
      {
        id: 52,
        expression: "Твои родители устали?",
        transcription: "ɑː jə ˈpeərənts ˈtaɪəd?",
        translation: "Are your parents tired?",
      },
      {
        id: 53,
        expression: "Мальчик чувствует себя очень уставшим?",
        transcription: "dəz ðə bɔɪ fiːl ˈvɛri ˈtaɪəd?",
        translation: "Does the boy feel very tired?",
      },
      {
        id: 54,
        expression: "Тест чрезвычайно сложный?",
        transcription: "ɪz ðə tɛst ɪksˈtriːmli ˈdɪfɪkəlt?",
        translation: "Is the test extremely difficult?",
      },
      {
        id: 55,
        expression: "Твоя работа очень стрессовая?",
        transcription: "ɪz jə ʤɒb ˈrɪəli ˈstrɛsf(ə)l?",
        translation: "Is your job really stressful?",
      },
      {
        id: 56,
        expression: "Твоя работа очень тяжелая?",
        transcription: "ɪz jə ʤɒb ˈvɛri hɑːd?",
        translation: "Is your job very hard?",
      },
      {
        id: 57,
        expression: "Их работа действительно стрессовая?",
        transcription: "ɪz ðeə ʤɒb ˈrɪəli ˈstrɛsf(ə)l?",
        translation: "Is their job really stressful?",
      },
      {
        id: 58,
        expression: "У твоего друга стабильный доход?",
        transcription: "dəz jə frɛnd həv ə ˈsteɪbl ˈɪnkʌm?",
        translation: "Does your friend have a stable income?",
      },
      {
        id: 59,
        expression: "У твоих друзей стабильный доход?",
        transcription: "dʊ jə frɛndz həv ə ˈsteɪbl ˈɪnkʌm?",
        translation: "Do your friends have a stable income?",
      },
      {
        id: 60,
        expression: "У тебя стабильный доход?",
        transcription: "dʊ jʊ həv ə ˈsteɪbl ˈɪnkʌm?",
        translation: "Do you have a stable income?",
      },
      {
        id: 61,
        expression: "У ее мужа хорошо оплачиваемая работа?",
        transcription: "dəz hə ˈhʌzbənd həv ə wɛl-peɪd ʤɒb?",
        translation: "Does her husband have a well-paid job?",
      },
      {
        id: 62,
        expression: "У них хорошая работа?",
        transcription: "dʊ ðeɪ həv ə gʊd ʤɒb?",
        translation: "Do they have a good job?",
      },
      {
        id: 63,
        expression: "У твоей жены стрессовая работа?",
        transcription: "dəz jə waɪf həv ə ˈstrɛsf(ə)l ʤɒb?",
        translation: "Does your wife have a stressful job?",
      },
      {
        id: 64,
        expression: "Еда хорошо пахнет?",
        transcription: "dəz ðə fuːd smɛl gʊd?",
        translation: "Does the food smell good?",
      },
      {
        id: 65,
        expression: "Моя еда хорошо пахнет?",
        transcription: "dəz maɪ fuːd smɛl gʊd?",
        translation: "Does my food smell good?",
      },
      {
        id: 66,
        expression: "Эта еда хорошо пахнет?",
        transcription: "dəz ðɪs fuːd smɛl gʊd?",
        translation: "Does this food smell good?",
      },
      {
        id: 67,
        expression: "Это время удобно для тебя?",
        transcription: "ɪz ðɪs taɪm kənˈviːniənt fə juː?",
        translation: "Is this time convenient for you?",
      },
      {
        id: 68,
        expression: "Время удобно для него?",
        transcription: "ɪz ðə taɪm kənˈviːniənt fə hɪm?",
        translation: "Is the time convenient for him?",
      },
      {
        id: 69,
        expression: "Его друг действительно уверен в этом?",
        transcription: "ɪz ɪz frɛnd ˈrɪəli ʃʊər əˈbaʊt ɪt?",
        translation: "Is his friend really sure about it?",
      },
      {
        id: 70,
        expression: "Ты действительно уверен в этом?",
        transcription: "ɑː jʊ ˈrɪəli ʃʊər əˈbaʊt ɪt?",
        translation: "Are you really sure about it?",
      },
      {
        id: 71,
        expression: "Его друзья действительно уверены в этом?",
        transcription: "ɑː hɪz frɛndz ˈrɪəli ʃʊər əˈbaʊt ɪt?",
        translation: "Are his friends really sure about it?",
      },
      {
        id: 72,
        expression: "Этот певец поет очень красиво?",
        transcription: "dəz ðɪs ˈsɪŋə sɪŋ ˈvɛri ˈbjuːtəfʊli?",
        translation: "Does this singer sing very beautifully?",
      },
      {
        id: 73,
        expression: "Эти певцы поют очень красиво?",
        transcription: "dʊ ðiːz ˈsɪŋəz sɪŋ ˈvɛri ˈbjuːtəfʊli?",
        translation: "Do these singers sing very beautifully?",
      },
      {
        id: 74,
        expression: "Эти мужчины поют очень красиво?",
        transcription: "dʊ ðiːz mɛn sɪŋ ˈvɛri ˈbjuːtəfʊli?",
        translation: "Do these men sing very beautifully?",
      },
      {
        id: 75,
        expression: "Этот урок длится дольше?",
        transcription: "ɪz ðɪs ˈlɛsn lɑːst ˈlɒŋgə?",
        translation: "Is this lesson last longer?",
      },
      {
        id: 76,
        expression: "Эта программа длится дольше?",
        transcription: "dəz ðɪs ˈprəʊgræm lɑːst ˈlɒŋgə?",
        translation: "Does this program last longer?",
      },
      {
        id: 77,
        expression: "Эти уроки длятся дольше?",
        transcription: "dʊ ðiːz ˈlɛsnz lɑːst ˈlɒŋgə?",
        translation: "Do these lessons last longer?",
      },
      {
        id: 78,
        expression: "Женщина беременна?",
        transcription: "ɪz ðə ˈwʊmən ˈprɛgnənt?",
        translation: "Is the woman pregnant?",
      },
      {
        id: 79,
        expression: "Твоя жена беременна?",
        transcription: "ɪz jə waɪf ˈprɛgnənt?",
        translation: "Is your wife pregnant?",
      },
      {
        id: 80,
        expression: "Эта женщина беременна?",
        transcription: "ɪz ðɪs ˈwʊmən ˈprɛgnənt?",
        translation: "Is this woman pregnant?",
      },
      {
        id: 81,
        expression: "Эта еда пахнет очень хорошо?",
        transcription: "dəz ðɪs fuːd smɛl ˈvɛri gʊd?",
        translation: "Does this food smell very good?",
      },
      {
        id: 82,
        expression: "Еда пахнет очень плохо?",
        transcription: "dəz ðə fuːd smɛl ˈvɛri bæd?",
        translation: "Does the food smell very bad?",
      },
      {
        id: 83,
        expression: "Эти апельсины пахнут действительно хорошо?",
        transcription: "dʊ ðiːz ˈɒrɪnʤɪz smɛl ˈrɪəli gʊd?",
        translation: "Do these oranges smell really good?",
      },
      {
        id: 84,
        expression: "Эта пара джинсов стоит шестьдесят долларов?",
        transcription: "dəz ðiːz peər əv ʤiːnz kɒst ˈsɪksti ˈdɒləz?",
        translation: "Does these pair of jeans cost sixty dollars?",
      },
      {
        id: 85,
        expression: "Эти брюки стоят меньше денег?",
        transcription: "dʊ ðiːz ˈtraʊzəz kɒst lɛs ˈmʌni?",
        translation: "Do these trousers cost less money?",
      },
      {
        id: 86,
        expression: "Эта вещь - пустая трата времени?",
        transcription: "ɪz ðɪs θɪŋ ə weɪst əv taɪm?",
        translation: "Is this thing a waste of time?",
      },
      {
        id: 87,
        expression: "Твоя жена часто ходит за покупками?",
        transcription: "dəz jə waɪf ˈɒf(ə)n gəʊ ðə ˈʃɒpɪŋ?",
        translation: "Does your wife often go the shopping?",
      },
      {
        id: 88,
        expression: "Эти новости звучат действительно странно?",
        transcription: "dəz ðɪs njuːz saʊnd ˈrɪəli streɪnʤ?",
        translation: "Does this news sound really strange?",
      },
      {
        id: 89,
        expression: "Эти вещи зависят от нас?",
        transcription: "dʊ ðiːz θɪŋz dɪˈpɛnd ɒn ʌs?",
        translation: "Do these things depend on us?",
      },
      {
        id: 90,
        expression: "Те мальчики часто тратят время впустую?",
        transcription: "dʊ ðəʊz bɔɪz ˈɒf(ə)n weɪst əv taɪm?",
        translation: "Do those boys often waste of time?",
      },
      {
        id: 91,
        expression: "Эти джинсы подходят тебе?",
        transcription: "dʊ ðiːz ʤiːnz sjuːt juː?",
        translation: "Do these jeans suit you?",
      },
      {
        id: 92,
        expression: "Стул удобен для тебя?",
        transcription: "ɪz ðə ʧeə ˈkʌmf(ə)təbl fə juː?",
        translation: "Is the chair comfortable for you?",
      },
      {
        id: 93,
        expression: "Этот свитер подходит тебе?",
        transcription: "dəz ðɪs ˈswɛtə sjuːt juː?",
        translation: "Does this sweater suit you?",
      },
      {
        id: 94,
        expression: "Эта пара брюк стоит двадцать три доллара?",
        transcription: "dəz ðɪs peər əv ˈtraʊzəz kɒst ˈtwɛnti θriː ˈdɒləz?",
        translation: "Does this pair of trousers cost twenty three dollars?",
      },
      {
        id: 95,
        expression: "Та женщина беременна?",
        transcription: "ɪz ðət ˈwʊmən ˈprɛgnənt?",
        translation: "Is that woman pregnant?",
      },
      {
        id: 96,
        expression: "Девочка показывает выдающиеся результаты?",
        transcription: "dəz ðə gɜːl ʃəʊ aʊtˈstændɪŋ rɪˈzʌlts?",
        translation: "Does the girl show outstanding results?",
      },
      {
        id: 97,
        expression: "Эти джинсы стоят восемьдесят долларов?",
        transcription: "dʊ ðiːz ʤiːnz kɒst ˈeɪti ˈdɒləz?",
        translation: "Do these jeans cost eighty dollars?",
      },
      {
        id: 98,
        expression: "Еда пахнет плохо?",
        transcription: "dəz ðə fuːd smɛl bæd?",
        translation: "Does the food smell bad?",
      },
    ],
    {
      theory: `<div class="theory-block">
<h3>Закрепление пройденного материала</h3>
</div>`,
    },
  ],
];
