export const contentLesson134 = [
  [
    {
      title: 'Урок 134. 360 Verbs. Part 8',
    },
    [
      {
        id: 1,
        expression: 'Он побежал в лес',
        transcription: 'hi ræn tə ðə ˈfɒrɪst',
        translation: 'He ran to the forest',
      },
      {
        id: 2,
        expression: 'Он отверг все обвинения',
        transcription: 'hi dɪˈnaɪd ɔːl ði ˌækju(ː)ˈzeɪʃ(ə)nz',
        translation: 'He denied all the accusations',
      },
      {
        id: 3,
        expression: 'Которая команда побеждает?',
        transcription: 'wɪʧ tiːm z ˈwɪnɪŋ?',
        translation: 'Which team is winning?',
      },
      {
        id: 4,
        expression: 'Он вступил в спортивный клуб',
        transcription: 'hi ʤɔɪn ə spɔːts klʌb',
        translation: 'He join a sports club',
      },
      {
        id: 5,
        expression: 'Они пели и танцевали',
        transcription: 'ðeɪ wə ˈsɪŋɪŋ ənd ˈdɑːnsɪŋ',
        translation: 'They were singing and dancing',
      },
      {
        id: 6,
        expression: 'Эта страна поставляет нефть и газ',
        transcription: 'ðɪs ˈkʌntri səˈplaɪz ɔɪl ənd gæs',
        translation: 'This country supplies oil and gas',
      },
      {
        id: 7,
        expression: 'Мне нужно улучшить и речь, и грамматику',
        transcription: 'aɪ niːd tʊ ɪmˈpruːv bəʊθ ˈspiːkɪŋ ənd ˈgræmə',
        translation: 'I need to improve both speaking and grammar',
      },
      {
        id: 8,
        expression: 'Как мы пишем это?',
        transcription: 'haʊ dʊ wi spɛl ɪt?',
        translation: 'How do we spell it?',
      },
      {
        id: 9,
        expression: 'Мне не понравился этот формат образования',
        transcription: 'aɪ dɪsˈlaɪkt ðɪs ˈfɔːmæt əv ˌɛdju(ː)ˈkeɪʃən',
        translation: 'I disliked this format of education',
      },
      {
        id: 10,
        expression: 'Он предупредил нас еще раз',
        transcription: 'hi wɔːnd əs wʌn mɔː taɪm',
        translation: 'He warned us one more time',
      },
      {
        id: 11,
        expression:
          'Я значительно улучшил свой английский благодаря этому курсу',
        transcription:
          'aɪ ɪmˈpruːvd maɪ ˈɪŋglɪʃ sɪgˈnɪfɪkəntli θæŋks tə ðɪs kɔːs',
        translation:
          'I improved my English significantly thanks to this course',
      },
      {
        id: 12,
        expression: 'Он поцеловал ее первым',
        transcription: 'hi kɪst hə fɜːst',
        translation: 'He kissed her first',
      },
      {
        id: 13,
        expression: 'Она кричала на него очень сердито',
        transcription: 'ʃi wəz ˈʃaʊtɪŋ ət ɪm ˈvɛri ˈæŋgrɪli',
        translation: 'She was shouting at him very angrily',
      },
      {
        id: 14,
        expression: 'Затем он поцеловал ее',
        transcription: 'ðɛn hi kɪst hɜː',
        translation: 'Then he kissed her',
      },
      {
        id: 15,
        expression: 'Кто повлиял на тебя больше всего?',
        transcription: 'huː ˈɪnflʊənst jʊ məʊst əv ɔːl?',
        translation: 'Who influenced you most of all?',
      },
      {
        id: 16,
        expression: 'Я собираюсь записать эту речь',
        transcription: 'aɪm ˈgəʊɪŋ tə ˈrɛkɔːd ðɪs spiːʧ',
        translation: "I'm going to record this speech",
      },
      {
        id: 17,
        expression: 'Мы не можем игнорировать эти вещи',
        transcription: 'wi kɑːnt ɪgˈnɔː ðiːz θɪŋz',
        translation: "We can't ignore these things",
      },
      {
        id: 18,
        expression: 'Она отрицает свою вину',
        transcription: 'ʃi dɪˈnaɪz hə gɪlt',
        translation: 'She denies her guilt',
      },
      {
        id: 19,
        expression: 'Они поставляют эти товары',
        transcription: 'ðeɪ səˈplaɪ ðiːz gʊdz',
        translation: 'They supply these goods',
      },
      {
        id: 20,
        expression: 'Кто-то разбил окно',
        transcription: 'ˈsʌmwʌn brəʊk ðə ˈwɪndəʊ',
        translation: 'Someone broke the window',
      },
      {
        id: 21,
        expression: 'Мне нужно улучшить свои речевые навыки',
        transcription: 'aɪ niːd tʊ ɪmˈpruːv maɪ ˈspiːkɪŋ skɪlz',
        translation: 'I need to improve my speaking skills',
      },
      {
        id: 22,
        expression: 'Я положил эту книгу на полку',
        transcription: 'aɪ pʊt ðɪs bʊk ɒn ðə ʃɛlf',
        translation: 'I put this book on the shelf',
      },
      {
        id: 23,
        expression: 'Он сбрил свои усы',
        transcription: 'hi ʃeɪvd ɪz məsˈtɑːʃ',
        translation: 'He shaved his moustache',
      },
      {
        id: 24,
        expression: 'Почему ты так быстро бежишь?',
        transcription: 'waɪ ə jʊ ˈrʌnɪŋ səʊ fɑːst?',
        translation: 'Why are you running so fast?',
      },
      {
        id: 25,
        expression: 'Какая команда выиграла?',
        transcription: 'wɪʧ tiːm wʌn?',
        translation: 'Which team won?',
      },
      {
        id: 26,
        expression: 'Это событие очень сильно повлияло на меня',
        transcription: 'ðɪs ɪˈvɛnt ˈɪnflʊənst mi ˈgreɪtli',
        translation: 'This event influenced me greatly',
      },
      {
        id: 27,
        expression: 'Она умеет плавать?',
        transcription: 'kən ʃi swɪm?',
        translation: 'Can she swim?',
      },
      {
        id: 28,
        expression: 'Это действительно помогло мне улучшить мою речь',
        transcription: 'ɪt ˈrɪəli hɛlpt miː (tuː) ɪmˈpruːv maɪ ˈspiːkɪŋ',
        translation: 'It really helped me (to) improve my speaking',
      },
      {
        id: 29,
        expression: 'Не трогай эти провода!',
        transcription: 'dəʊnt tʌʧ ðiːz ˈwaɪəz!',
        translation: "Don't touch these wires!",
      },
      {
        id: 30,
        expression: 'Он коснулся ее руки',
        transcription: 'hi tʌʧt hər ɑːm',
        translation: 'He touched her arm',
      },
      {
        id: 31,
        expression: 'Такие вещи касаются каждого из нас',
        transcription: 'sʌʧ θɪŋz kənˈsɜːn iːʧ əv ʌs',
        translation: 'Such things concern each of us',
      },
      {
        id: 32,
        expression: 'Мне не нравится такого рода еда',
        transcription: 'aɪ dɪsˈlaɪk ðɪs kaɪnd əv fuːd',
        translation: 'I dislike this kind of food',
      },
      {
        id: 33,
        expression: 'Это развивает наши аналитические способности',
        transcription: 'ɪt dɪˈvɛləps ˈaʊər ˌænəˈlɪtɪkəl əˈbɪlɪtiz',
        translation: 'It develops our analytical abilities',
      },
      {
        id: 34,
        expression: 'Я присоединюсь к тебе с большим удовольствием',
        transcription: 'aɪl ʤɔɪn jʊ wɪð greɪt ˈplɛʒə',
        translation: "I'll join you with great pleasure",
      },
      {
        id: 35,
        expression: 'Он сбрил свою бороду',
        transcription: 'hi ʃeɪvd ɪz bɪəd',
        translation: 'He shaved his beard',
      },
      {
        id: 36,
        expression: 'Его новый проект провалился',
        transcription: 'hɪz njuː ˈprɒʤɛkt feɪld',
        translation: 'His new project failed',
      },
      {
        id: 37,
        expression: 'Это касается каждого из нас',
        transcription: 'ɪt kənˈsɜːnz iːʧ əv ʌs',
        translation: 'It concerns each of us',
      },
      {
        id: 38,
        expression: 'Мне следует предупредить тебя',
        transcription: 'aɪ ʃəd wɔːn juː',
        translation: 'I should warn you',
      },
      {
        id: 39,
        expression: 'Мы ели и говорили об этом',
        transcription: 'wi wər ˈiːtɪŋ ənd ˈtɔːkɪŋ əˈbaʊt ɪt',
        translation: 'We were eating and talking about it',
      },
      {
        id: 40,
        expression: 'Он не может представить свою жизнь без этого',
        transcription: 'hi kɑːnt ɪˈmæʤɪn ɪz laɪf wɪˈðaʊt ɪt',
        translation: "He can't imagine his life without it",
      },
      {
        id: 41,
        expression: 'Меня это всегда интересовало, когда я был ребенком',
        transcription:
          'ɪt ˈɔːlweɪz ˈɪntrɪstɪd mi wɛn aɪ wəz ə ʧaɪld / aɪ wəz ˈɔːlweɪz ˈɪntrɪstɪd ɪn ɪt wɛn aɪ wəz ə ʧaɪld',
        translation:
          'It always interested me when I was a child / I was always interested in it when I was a child',
      },
      {
        id: 42,
        expression: 'Он сказал, что он последовал ее совету',
        transcription: 'hi sɛd ðət hiːd ˈfɒləʊd hər ədˈvaɪs',
        translation: "He said that he'd followed her advice",
      },
      {
        id: 43,
        expression:
          'Большинство людей понимают, что курение может нанести вред нашему здоровью',
        transcription:
          'məʊst ˈpiːpl ˌʌndəˈstænd ðət ˈsməʊkɪŋ kən ˈdæmɪʤ ˈaʊə hɛlθ / məʊst ˈpiːpl ˌʌndəˈstænd ðət ˈsməʊkɪŋ kən dʊ hɑːm ˈaʊə hɛlθ',
        translation:
          'Most people understand that smoking can damage our health / Most people understand that smoking can do harm our health',
      },
      {
        id: 44,
        expression:
          'Они сделали очень интересное предложение, и я не мог отказаться',
        transcription:
          'ðeɪ meɪd ə ˈvɛri ˈɪntrɪstɪŋ ˈɒfər ənd aɪ ˈkʊdnt ˌriːˈfjuːz',
        translation: "They made a very interesting offer and I couldn't refuse",
      },
      {
        id: 45,
        expression: 'Когда мы гуляли, веер дул очень сильно',
        transcription: 'wɛn wi wə ˈwɔːkɪŋ, ðə wɪnd wəz ˈbləʊɪŋ ˈvɛri ˈstrɒŋli',
        translation: 'When we were walking, the wind was blowing very strongly',
      },
      {
        id: 46,
        expression: 'Он должен был уйти с работы раньше',
        transcription: 'hi həd tə liːv wɜːk ˈɜːlɪə',
        translation: 'He had to leave work earlier',
      },
      {
        id: 47,
        expression: 'Трудно представить нашу жизнь без этого в наши дни',
        transcription:
          'ɪts ˈdɪfɪkəlt tʊ ɪˈmæʤɪn ˈaʊə laɪf wɪˈðaʊt ɪt ˈnaʊədeɪz',
        translation: "It's difficult to imagine our life without it nowadays",
      },
      {
        id: 48,
        expression: 'Она появилась на телевидении в первый раз',
        transcription: 'ʃi əˈpɪəd ɒn ˌtiːˈviː fə ðə fɜːst taɪm',
        translation: 'She appeared on TV for the first time',
      },
      {
        id: 49,
        expression: 'Он забыл, куда он положил свои очки',
        transcription: 'hi fəˈgɒt weə hiːd pʊt ɪz ˈglɑːsɪz',
        translation: "He forgot where he'd put his glasses",
      },
      {
        id: 50,
        expression: 'Я боюсь, ты написал это неправильно',
        transcription: 'aɪm əˈfreɪd jʊ spɛlt ɪt ˈrɒŋli',
        translation: "I'm afraid you spelt it wrongly",
      },
      {
        id: 51,
        expression: 'Мы уже ушли к тому времени, как она появилась',
        transcription: 'wi həd ɔːlˈrɛdi lɛft baɪ ðə taɪm ʃi əˈpɪəd',
        translation: 'We had already left by the time she appeared',
      },
      {
        id: 52,
        expression: 'Он попросил ее потанцевать с ним',
        transcription: 'hi ɑːskt hə tə dɑːns wɪð hɪm',
        translation: 'He asked her to dance with him',
      },
      {
        id: 53,
        expression:
          'Он не может позволить себе купить новую квартиру в настоящее время',
        transcription: 'hi kɑːnt əˈfɔːd tə baɪ ə njuː əˈpɑːtmənt ət ˈprɛznt',
        translation: "He can't afford to buy a new apartment at present",
      },
      {
        id: 54,
        expression: 'Новое видео будет записано завтра',
        transcription: 'ə njuː ˈvɪdɪəʊ wɪl bi rɪˈkɔːdɪd təˈmɒrəʊ',
        translation: 'A new video will be recorded tomorrow',
      },
      {
        id: 55,
        expression: 'Здание было серьезно повреждено',
        transcription: 'ðə ˈbɪldɪŋ wəz ˈsɪərɪəsli ˈdæmɪʤd',
        translation: 'The building was seriously damaged',
      },
      {
        id: 56,
        expression: 'Это всегда меня интересовало',
        transcription: 'ɪt ˈɔːlweɪz ˈɪntrɪstɪd miː',
        translation: 'It always interested me',
      },
      {
        id: 57,
        expression: 'Это когда-нибудь интересовало его?',
        transcription: 'həz ɪt ˈɛvər ˈɪntrɪstɪd hɪm?',
        translation: 'Has it ever interested him?',
      },
      {
        id: 58,
        expression: 'Это никогда меня не интересовало',
        transcription: 'ɪts ˈnɛvər ˈɪntrɪstɪd miː',
        translation: "It's never interested me",
      },
      {
        id: 59,
        expression: 'Это канал был создан два года назад',
        transcription: 'ðɪs ˈʧænl wəz kri(ː)ˈeɪtɪd tuː jɪəz əˈgəʊ',
        translation: 'This channel was created two years ago',
      },
      {
        id: 60,
        expression: 'Этот канал был создан им',
        transcription: 'ðɪs ˈʧænl wəz kri(ː)ˈeɪtɪd baɪ hɪm',
        translation: 'This channel was created by him',
      },
      {
        id: 61,
        expression: 'Это приложение было создано один год назад',
        transcription: 'ðɪs ˌæplɪˈkeɪʃ(ə)n wəz kri(ː)ˈeɪtɪd wʌn jɪər əˈgəʊ',
        translation: 'This application was created one year ago',
      },
      {
        id: 62,
        expression: 'Сильный ветер дует весь день',
        transcription: 'ə strɒŋ wɪnd həz biːn ˈbləʊɪŋ ɔːl deɪ',
        translation: 'A strong wind has been blowing all day',
      },
      {
        id: 63,
        expression: 'Солнце светит весь день',
        transcription: 'ðə sʌn həz biːn ˈʃaɪnɪŋ ɔːl deɪ',
        translation: 'The sun has been shining all day',
      },
      {
        id: 64,
        expression: 'Сильный ветер подул внезапно',
        transcription: 'ə strɒŋ wɪnd bluː ˈsʌdnli',
        translation: 'A strong wind blew suddenly',
      },
      {
        id: 65,
        expression: 'Он всегда помогал мне',
        transcription: 'hiːz ˈɔːlweɪz hɛlpt miː',
        translation: "He's always helped me",
      },
      {
        id: 66,
        expression: 'Он помогает мне весь день',
        transcription: 'hiːz ˈhɛlpɪŋ mi ɔːl deɪ',
        translation: "He's helping me all day",
      },
      {
        id: 67,
        expression: 'Он никогда не помогал своей матери',
        transcription: 'hiːz ˈnɛvə hɛlpt ɪz ˈmʌðə',
        translation: "He's never helped his mother",
      },
      {
        id: 68,
        expression: 'Эта проблема будет решена скоро',
        transcription: 'ðɪs ˈprɒbləm wɪl bi sɒlvd suːn',
        translation: 'This problem will be solved soon',
      },
      {
        id: 69,
        expression: 'Эта проблема решена',
        transcription: 'ðɪs ˈprɒbləm z sɒlvd',
        translation: 'This problem is solved',
      },
      {
        id: 70,
        expression: 'Эта проблема не была решена',
        transcription: 'ðɪs ˈprɒbləm wɒznt sɒlvd',
        translation: "This problem wasn't solved",
      },
      {
        id: 71,
        expression: 'К сожалению, она провалила экзамен',
        transcription: 'ʌnˈfɔːʧnɪtli, ʃi feɪld ði ɪgˈzæm',
        translation: 'Unfortunately, she failed the exam',
      },
      {
        id: 72,
        expression: 'К счастью, она сдала этот экзамен',
        transcription: 'ˈlʌkɪli, ʃi pɑːst ðɪs ɪgˈzæm',
        translation: 'Luckily, she passed this exam',
      },
      {
        id: 73,
        expression: 'К сожалению, она провалила свой последний экзамен',
        transcription: 'ʌnˈfɔːʧnɪtli, ʃi feɪld (lɑːst) hə ˈfaɪnl ɪgˈzæm',
        translation: 'Unfortunately, she failed her final (last) exam',
      },
      {
        id: 74,
        expression: 'Я вижу, что ты так усердно работаешь последнее время',
        transcription: 'aɪ siː ðət juːv biːn ˈwɜːkɪŋ səʊ hɑːd ˈleɪtli',
        translation: "I see that you've been working so hard lately",
      },
      {
        id: 75,
        expression: 'Я вижу, что ты делаешь это весь день',
        transcription: 'aɪ siː ðət juːv biːn ˈdu(ː)ɪŋ ɪt ɔːl deɪ',
        translation: "I see that you've been doing it all day",
      },
      {
        id: 76,
        expression:
          'Я знаю, что ты готовишься к этому экзамену в течение двух дней',
        transcription:
          'aɪ nəʊ ðət juːv biːn prɪˈpeərɪŋ fə ðɪs ɪgˈzæm fə tuː deɪz',
        translation:
          "I know that you've been preparing for this exam for two days",
      },
      {
        id: 77,
        expression: 'Во сколько ты обычно уходишь на работу?',
        transcription: 'wɒt taɪm dʊ jʊ ˈjuːʒʊəli liːv fə wɜːk?',
        translation: 'What time do you usually leave for work?',
      },
      {
        id: 78,
        expression: 'Во сколько ты обычно просыпаешься?',
        transcription: 'wɒt taɪm dʊ jʊ ˈjuːʒʊəli weɪk ʌp?',
        translation: 'What time do you usually wake up?',
      },
      {
        id: 79,
        expression: 'Во сколько ты обычно возвращаешься домой?',
        transcription: 'wɒt taɪm dʊ jʊ ˈjuːʒʊəli rɪˈtɜːn həʊm?',
        translation: 'What time do you usually return home?',
      },
      {
        id: 80,
        expression: 'Как долго ты живешь в этом городе?',
        transcription: 'haʊ lɒŋ həv jʊ biːn ˈlɪvɪŋ ɪn ðɪs ˈsɪti?',
        translation: 'How long have you been living in this city?',
      },
      {
        id: 81,
        expression: 'Как долго ты работаешь в этой компании?',
        transcription: 'haʊ lɒŋ həv jʊ biːn ˈwɜːkɪŋ fɔː (ɪn) ðɪs ˈkʌmpəni?',
        translation: 'How long have you been working for (in) this company?',
      },
      {
        id: 82,
        expression: 'Как долго ты замужем за ним?',
        transcription: 'haʊ lɒŋ həv jʊ biːn ˈmærɪd tə hɪm?',
        translation: 'How long have you been married to him?',
      },
      {
        id: 83,
        expression: 'Мальчик прыгнул в воду',
        transcription: 'ðə bɔɪ ʤʌmpt ˈɪntə ðə ˈwɔːtə',
        translation: 'The boy jumped into the water',
      },
      {
        id: 84,
        expression:
          'Нам также необходимо развивать наши аналитические способности',
        transcription:
          'wi ˈɔːlsəʊ niːd tə dɪˈvɛləp ˈaʊər ˌænəˈlɪtɪkəl əˈbɪlɪtiz',
        translation: 'We also need to develop our analytical abilities',
      },
      {
        id: 85,
        expression: 'Они живут в пригороде',
        transcription: 'ðeɪ lɪvd ɪn ðə ˈsʌbɜːbz',
        translation: 'They lived in the suburbs',
      },
      {
        id: 86,
        expression: 'Эти вещи часто игнорируются',
        transcription: 'ðiːz θɪŋz ər ˈɒf(ə)n ɪgˈnɔːd',
        translation: 'These things are often ignored',
      },
      {
        id: 87,
        expression: 'Я сказал ему, что я уже решил эту проблему',
        transcription: 'aɪ təʊld ɪm ðət aɪd ɔːlˈrɛdi sɒlvd ðɪs ˈprɒbləm',
        translation: "I told him that I'd already solved this problem",
      },
      {
        id: 88,
        expression: 'Он сказал, что никогда не любил охоту',
        transcription: 'hi sɛd ðət hiːd ˈnɛvə lʌvd ˈhʌntɪŋ',
        translation: "He said that he'd never loved hunting",
      },
      {
        id: 89,
        expression: 'Она всегда помогала мне, когда я был в беде',
        transcription: 'ʃiːz ˈɔːlweɪz hɛlpt mi wɛn aɪ wəz ɪn ˈtrʌbl',
        translation: "She's always helped me when I was in trouble",
      },
      {
        id: 90,
        expression: 'Я жил в пригороде',
        transcription: 'aɪ lɪvd ɪn ðə ˈsʌbɜːbz',
        translation: 'I lived in the suburbs',
      },
      {
        id: 91,
        expression: 'Я буду работать завтра в семь',
        transcription: 'aɪl bi ˈwɜːkɪŋ təˈmɒrəʊ ət ˈsɛvn',
        translation: "I'll be working tomorrow at seven",
      },
      {
        id: 92,
        expression: 'Мужчина прыгнул в море',
        transcription: 'ðə mæn ʤʌmpt ˈɪntə ðə siː',
        translation: 'The man jumped into the sea',
      },
      {
        id: 93,
        expression: 'Мы плаваем весь день',
        transcription: 'wiːv biːn ˈswɪmɪŋ ɔːl deɪ',
        translation: "We've been swimming all day",
      },
      {
        id: 94,
        expression: 'Я еще не ел',
        transcription: 'aɪ hævnt ˈiːtn jɛt',
        translation: "I haven't eaten yet",
      },
      {
        id: 95,
        expression: 'Кто создал нашу Вселенную?',
        transcription: 'huː kri(ː)ˈeɪtɪd ˈaʊə ˈjuːnɪvɜːs?',
        translation: 'Who created our universe?',
      },
      {
        id: 96,
        expression: 'Он отказался сделать это',
        transcription: 'hi ˌriːˈfjuːzd tə dʊ ɪt',
        translation: 'He refused to do it',
      },
      {
        id: 97,
        expression: 'Я не люблю охотиться',
        transcription: 'aɪ dəʊnt laɪk ˈhʌntɪŋ',
        translation: "I don't like hunting",
      },
      {
        id: 98,
        expression: 'Она перестала кричать на него',
        transcription: 'ʃi stɒpt ˈʃaʊtɪŋ ət hɪm',
        translation: 'She stopped shouting at him',
      },
      {
        id: 99,
        expression: 'Я не могу позволить купить себе это сейчас',
        transcription: 'aɪ kɑːnt əˈfɔːd tə baɪ ɪt naʊ',
        translation: "I can't afford to buy it now",
      },
      {
        id: 100,
        expression: 'Я не могу купить это сейчас',
        transcription: 'aɪ kɑːnt baɪ ɪt naʊ',
        translation: "I can't buy it now",
      },
      {
        id: 101,
        expression: 'Я куплю это завтра',
        transcription: 'aɪl baɪ ɪt təˈmɒrəʊ',
        translation: "I'll buy it tomorrow",
      },
    ],
    {
      theory: `<div class="theory-block">
<h3>Закрепление пройденного материала</h3>
</div>`,
    },
  ],
];
