export const contentLesson123 = [
  [
    {
      title: "Урок 123. Passive Voice + Active Voice",
    },
    [
      {
        id: 1,
        expression: "Моя мама работает в банке",
        transcription: "maɪ ˈmʌðə wɜːks ɪn ə bæŋk",
        translation: "My mother works in a bank",
      },
      {
        id: 2,
        expression: "Кто-то украл его ноутбук",
        transcription: "ˈsʌmbədi stəʊl ɪz ˈlæpˌtɒp",
        translation: "Somebody stole his laptop",
      },
      {
        id: 3,
        expression: "Тебе задают вопрос",
        transcription: "jʊər ɑːskt ðə ˈkwɛsʧən",
        translation: "You're asked the question",
      },
      {
        id: 4,
        expression: "Это решение было принято им",
        transcription: "ðɪs dɪˈsɪʒən wəz meɪd baɪ hɪm",
        translation: "This decision was made by him",
      },
      {
        id: 5,
        expression: "Слишком мало денег заработано им",
        transcription: "tuː ˈlɪtl ˈmʌni z ɜːnd baɪ hɪm",
        translation: "Too little money is earned by him",
      },
      {
        id: 6,
        expression: "Компания произвела эти товары в Китае",
        transcription: "ðə ˈkʌmpəni prəˈdjuːst ðiːz gʊdz ɪn ˈʧaɪnə",
        translation: "The company produced these goods in China",
      },
      {
        id: 7,
        expression: "Эта работа будет закончена скоро",
        transcription: "ðɪs wɜːk wɪl bi ˈfɪnɪʃt suːn",
        translation: "This work will be finished soon",
      },
      {
        id: 8,
        expression: "Ее часто хвалят",
        transcription: "ʃi z ˈɒf(ə)n preɪzd",
        translation: "She is often praised",
      },
      {
        id: 9,
        expression: "Кто-то украл его ноутбук",
        transcription: "ˈsʌmwʌn stəʊl ɪz ˈlæpˌtɒp",
        translation: "Someone stole his laptop",
      },
      {
        id: 10,
        expression: "Новая книга была написана им",
        transcription: "ə njuː bʊk wəz ˈrɪtn baɪ hɪm",
        translation: "A new book was written by him",
      },
      {
        id: 11,
        expression: "Он зарабатывает слишком мало денег",
        transcription: "hi ɜːnz tuː ˈlɪtl ˈmʌni",
        translation: "He earns too little money",
      },
      {
        id: 12,
        expression: "Эти товары производятся в Китае",
        transcription: "ðiːz gʊdz ə prəˈdjuːst ɪn ˈʧaɪnə",
        translation: "These goods are produced in China",
      },
      {
        id: 13,
        expression: "Они скоро это забудут",
        transcription: "ðeɪl fəˈgɛt ɪt suːn",
        translation: "They'll forget it soon",
      },
      {
        id: 14,
        expression: "Канал был создан год назад",
        transcription: "ðə ˈʧænl wəz kri(ː)ˈeɪtɪd ə jɪər əˈgəʊ",
        translation: "The channel was created a year ago",
      },
      {
        id: 15,
        expression: "Его ноутбук был украден",
        transcription: "hɪz ˈlæpˌtɒp wəz ˈstəʊlən",
        translation: "His laptop was stolen",
      },
      {
        id: 16,
        expression: "Он неожиданно отменил встречу",
        transcription: "hi ˈkænsəld ðə ˈmiːtɪŋ ˌʌnɪksˈpɛktɪdli",
        translation: "He cancelled the meeting unexpectedly",
      },
      {
        id: 17,
        expression: "Мы приняли их предложение",
        transcription: "wi əkˈsɛptɪd ðeər ˈɒfə",
        translation: "We accepted their offer",
      },
      {
        id: 18,
        expression: "Они часто показывали это по телевизору",
        transcription: "ðeɪ ˈɒf(ə)n ʃəʊd ɪt ɒn ˌtiːˈviː",
        translation: "They often showed it on TV",
      },
      {
        id: 19,
        expression: "Я скоро закончу эту работу",
        transcription: "aɪl ˈfɪnɪʃ ðɪs wɜːk suːn",
        translation: "I'll finish this work soon",
      },
      {
        id: 20,
        expression: "Ее часто критикуют",
        transcription: "ʃiːz ˈɒf(ə)n ˈkrɪtɪsaɪzd",
        translation: "She's often criticized",
      },
      {
        id: 21,
        expression: "Они нашли его живым",
        transcription: "ðeɪ faʊnd ɪm əˈlaɪv",
        translation: "They found him alive",
      },
      {
        id: 22,
        expression: "Он создал канал два года назад",
        transcription: "hi kri(ː)ˈeɪtɪd ðə ˈʧænl tuː jɪəz əˈgəʊ",
        translation: "He created the channel two years ago",
      },
      {
        id: 23,
        expression: "Он был найден живым",
        transcription: "hi wəz faʊnd əˈlaɪv",
        translation: "He was found alive",
      },
      {
        id: 24,
        expression: "Это скоро будет забыто",
        transcription: "ˈɪtl bi fəˈgɒtn suːn",
        translation: "It'll be forgotten soon",
      },
      {
        id: 25,
        expression: "Другие уважают его",
        transcription: "ˈʌðəz rɪsˈpɛkt hɪm",
        translation: "Others respect him",
      },
      {
        id: 26,
        expression: "Они часто критикуют ее",
        transcription: "ðeɪ ˈɒf(ə)n ˈkrɪtɪsaɪz hɜː",
        translation: "They often criticize her",
      },
      {
        id: 27,
        expression: "Они сказали это очень громко",
        transcription: "ðeɪ sɛd ɪt ˈvɛri ˈlaʊdli",
        translation: "They said it very loudly",
      },
      {
        id: 28,
        expression: "Эти вещи производятся в Японии",
        transcription: "ðiːz θɪŋz ə prəˈdjuːst ɪn ʤəˈpæn",
        translation: "These things are produced in Japan",
      },
      {
        id: 29,
        expression: "Они укради эти деньги",
        transcription: "ðeɪ stəʊl ðɪs ˈmʌni",
        translation: "They stole this money",
      },
      {
        id: 30,
        expression: "Другие люди часто хвалят ее",
        transcription: "ˈʌðə ˈpiːpl ˈɒf(ə)n preɪz hɜː",
        translation: "Other people often praise her",
      },
      {
        id: 31,
        expression: "Эти деньги были украдены ими",
        transcription: "ðɪs ˈmʌni wəz ˈstəʊlən baɪ ðɛm",
        translation: "This money was stolen by them",
      },
      {
        id: 32,
        expression: "Он написал новую книгу",
        transcription: "hi rəʊt ə njuː bʊk",
        translation: "He wrote a new book",
      },
      {
        id: 33,
        expression: "Его уважают",
        transcription: "hiːz rɪsˈpɛktɪd",
        translation: "He's respected",
      },
      {
        id: 34,
        expression: "Это было сказано очень громко",
        transcription: "ɪt wəz sɛd ˈvɛri ˈlaʊdli",
        translation: "It was said very loudly",
      },
      {
        id: 35,
        expression: "Он скоро выполнит задачу",
        transcription: "hiːl kəmˈpliːt ðə tɑːsk suːn",
        translation: "He'll complete the task soon",
      },
      {
        id: 36,
        expression: "Это часто показывали по телевизору",
        transcription: "ɪt wəz ˈɒf(ə)n ʃəʊn ɒn ˌtiːˈviː",
        translation: "It was often shown on TV",
      },
      {
        id: 37,
        expression: "Их предложение было принято",
        transcription: "ðeər ˈɒfə wəz əkˈsɛptɪd",
        translation: "Their offer was accepted",
      },
      {
        id: 38,
        expression: "Они производят эти вещи в Японии",
        transcription: "ðeɪ ˈprɒdjuːs ðiːz θɪŋ ɪn ʤəˈpæn",
        translation: "They produce these thing in Japan",
      },
      {
        id: 39,
        expression: "Задание скоро будет выполнено",
        transcription: "ðə tɑːsk wɪl bi kəmˈpliːtɪd suːn",
        translation: "The task will be completed soon",
      },
      {
        id: 40,
        expression: "Все контролируется ими",
        transcription: "ˈɛvrɪθɪŋ z kənˈtrəʊld baɪ ðɛm",
        translation: "Everything is controlled by them",
      },
      {
        id: 41,
        expression: "Они контролируют все",
        transcription: "ðeɪ kənˈtrəʊl ˈɛvrɪθɪŋ",
        translation: "They control everything",
      },
      {
        id: 42,
        expression: "Встреча неожиданно была отменена",
        transcription: "ðə ˈmiːtɪŋ wəz ˈkænsəld ˌʌnɪksˈpɛktɪdli",
        translation: "The meeting was cancelled unexpectedly",
      },
      {
        id: 43,
        expression: "Он часто видит ее там",
        transcription: "hi ˈɒf(ə)n siːz hə ðeə",
        translation: "He often sees her there",
      },
      {
        id: 44,
        expression: "Его часто видят там",
        transcription: "hi ˈɒf(ə)n siːn ðeə",
        translation: "He often seen there",
      },
      {
        id: 45,
        expression: "Они выращивают фрукты и овощи в своем собственном саду",
        transcription: "ðeɪ grəʊ fruːt ənd ˈvɛʤtəb(ə)lz ɪn ðeər əʊn ˈgɑːdn",
        translation: "They grow fruit and vegetables in their own garden",
      },
      {
        id: 46,
        expression: "С ним обращались очень грубо",
        transcription: "hi wəz ˈtriːtɪd ˈvɛri ˈruːdli",
        translation: "He was treated very rudely",
      },
      {
        id: 47,
        expression: "Я родился двадцать пять лет назад",
        transcription: "aɪ wəz bɔːn ˈtwɛnti faɪv jɪəz əˈgəʊ",
        translation: "I was born twenty five years ago",
      },
      {
        id: 48,
        expression: "Это производится в Китае?",
        transcription: "ɪz ɪt prəˈdjuːst ɪn ˈʧaɪnə?",
        translation: "Is it produced in China?",
      },
      {
        id: 49,
        expression: "Эти деньги были возвращены им",
        transcription: "ðɪs ˈmʌni wəz rɪˈtɜːnd baɪ hɪm",
        translation: "This money was returned by him",
      },
      {
        id: 50,
        expression: "Мне кажется, он не сможет достичь этой цели",
        transcription: "ɪt siːmz tə mi hi wəʊnt bi ˈeɪbl tʊ əˈʧiːv ðɪs eɪm",
        translation: "It seems to me he won't be able to achieve this aim",
      },
      {
        id: 51,
        expression: "Фрукты и овощи выращиваются в их собственном саду",
        transcription: "fruːt ənd ˈvɛʤtəb(ə)lz ə grəʊn ɪn ðeər əʊn ˈgɑːdn",
        translation: "Fruit and vegetables are grown in their own garden",
      },
      {
        id: 52,
        expression: "Я перевел этот текст очень легко",
        transcription: "aɪ trænsˈleɪtɪd ðɪs tɛkst ˈvɛri ˈiːzɪli",
        translation: "I translated this text very easily",
      },
      {
        id: 53,
        expression: "Я вижу, что эти вещи тесно связаны друг с другом",
        transcription: "aɪ siː ðət ðiːz θɪŋz ə ˈkləʊsli kəˈnɛktɪd wɪð iːʧ ˈʌðə",
        translation:
          "I see that these things are closely connected with each other",
      },
      {
        id: 54,
        expression: "Он не тратит на это достаточно времени",
        transcription: "hi dʌznt spɛnd ɪˈnʌf taɪm ɒn ɪt",
        translation: "He doesn't spend enough time on it",
      },
      {
        id: 55,
        expression: "Они ничего не делают, чтобы изменить эту ситуацию",
        transcription:
          "ðeɪ dəʊnt dʊ ˈɛnɪθɪŋ tə ʧeɪnʤ ðɪs ˌsɪtjʊˈeɪʃən / ðeɪ dʊ ˈnʌθɪŋ tə ʧeɪnʤ ðɪs ˌsɪtjʊˈeɪʃən",
        translation:
          "They don't do anything to change this situation / They do nothing to change this situation",
      },
      {
        id: 56,
        expression: "Ничего не делается, чтобы улучшить эти условия",
        transcription: "ˈnʌθɪŋ z dʌn tʊ ɪmˈpruːv ðiːz kənˈdɪʃənz",
        translation: "Nothing is done to improve these conditions",
      },
      {
        id: 57,
        expression: "Это сделано за границей?",
        transcription: "ɪz ɪt meɪd əˈbrɔːd?",
        translation: "Is it made abroad?",
      },
      {
        id: 58,
        expression: "Люди рождаются и умирают каждый день",
        transcription: "ˈpiːpl ə bɔːn ənd daɪ ˈɛvri deɪ",
        translation: "People are born and die every day",
      },
      {
        id: 59,
        expression: "Он родился в 1986 году",
        transcription: "hi wəz bɔːn ɪn 1986",
        translation: "He was born in 1986",
      },
      {
        id: 60,
        expression:
          "Я действительно не понимаю, почему он игнорирует эти проблемы",
        transcription:
          "aɪ dəʊnt ˈrɪəli ˌʌndəˈstænd waɪ hi ɪgˈnɔːz ðiːz ˈprɒbləmz",
        translation: "I don't really understand why he ignores these problems",
      },
      {
        id: 61,
        expression: "Я не понимаю, почему у него так много проблем",
        transcription: "aɪ dəʊnt ˌʌndəˈstænd waɪ hi həz səʊ ˈmɛni ˈprɒbləmz",
        translation: "I don't understand why he has so many problems",
      },
      {
        id: 62,
        expression: "Я не знаю, почему она игнорирует эту проблему",
        transcription: "aɪ dəʊnt nəʊ waɪ ʃi ɪgˈnɔːz ðɪs ˈprɒbləm",
        translation: "I don't know why she ignores this problem",
      },
      {
        id: 63,
        expression: "С ней обращаются очень несправедливо",
        transcription: "ʃi z ˈtriːtɪd ˈvɛri ʌnˈfeəli",
        translation: "She is treated very unfairly",
      },
      {
        id: 64,
        expression: "С ней обращаются очень хорошо",
        transcription: "ʃi z ˈtriːtɪd ˈvɛri wɛl",
        translation: "She is treated very well",
      },
      {
        id: 65,
        expression: "С ней обошлись так несправедливо",
        transcription: "ʃi wəz ˈtriːtɪd səʊ ʌnˈfeəli",
        translation: "She was treated so unfairly",
      },
      {
        id: 66,
        expression: "Я знаю, что на испанском языке говорят во многих странах",
        transcription: "aɪ nəʊ ðət ˈspænɪʃ ɪz ˈspəʊkən ɪn ˈmɛni ˈkʌntriz",
        translation: "I know that Spanish is spoken in many countries",
      },
      {
        id: 67,
        expression: "Я знаю, что на английском языке говорят во всем мире",
        transcription: "aɪ nəʊ ðət ˈɪŋglɪʃ ɪz ˈspəʊkən ɔːl ˈəʊvə ðə wɜːld",
        translation: "I know that English is spoken all over the world",
      },
      {
        id: 68,
        expression: "Я знаю, что на английском языке говорят во многих странах",
        transcription: "aɪ nəʊ ðət ˈɪŋglɪʃ ɪz ˈspəʊkən ɪn ˈmɛni ˈkʌntriz",
        translation: "I know that English is spoken in many countries",
      },
      {
        id: 69,
        expression: "Его укусила собака",
        transcription: "hɪz wəz ˈbɪtn baɪ ə dɒg",
        translation: "His was bitten by a dog",
      },
      {
        id: 70,
        expression: "Их укусила собака",
        transcription: "ðeɪ wəz ˈbɪtn baɪ ə dɒg",
        translation: "They was bitten by a dog",
      },
      {
        id: 71,
        expression: "Его укусила очень злая собака",
        transcription: "hi wəz ˈbɪtn baɪ ə ˈvɛri ˈæŋgri dɒg",
        translation: "He was bitten by a very angry dog",
      },
      {
        id: 72,
        expression: "Люди говорят по-английски во всем мире",
        transcription: "ˈpiːpl spiːk ˈɪŋglɪʃ ɔːl ˈəʊvə ðə wɜːld",
        translation: "People speak English all over the world",
      },
      {
        id: 73,
        expression: "Эти люди не говорят по-испански",
        transcription: "ðiːz ˈpiːpl dəʊnt spiːk ˈspænɪʃ",
        translation: "These people don't speak Spanish",
      },
      {
        id: 74,
        expression: "Эти люди говорят по-английски?",
        transcription: "dʊ ðiːz ˈpiːpl spiːk ˈɪŋglɪʃ?",
        translation: "Do these people speak English?",
      },
      {
        id: 75,
        expression: "На это тратится недостаточно времени",
        transcription: "nɒt ɪˈnʌf taɪm z spɛnt ɒn ɪt",
        translation: "Not enough time is spent on it",
      },
      {
        id: 76,
        expression: "На это тратится много времени",
        transcription: "ə lɒt əv taɪm z spɛnt ɒn ɪt",
        translation: "A lot of time is spent on it",
      },
      {
        id: 77,
        expression: "Сколько времени на это тратится?",
        transcription: "haʊ mʌʧ taɪm z spɛnt ɒn ɪt?",
        translation: "How much time is spent on it?",
      },
      {
        id: 78,
        expression: "Они ничего не заметили",
        transcription: "ðeɪ ˈnəʊtɪst ˈnʌθɪŋ / ðeɪ dɪdnt ˈnəʊtɪst ˈɛnɪθɪŋ",
        translation: "They noticed nothing / They didn't noticed anything",
      },
      {
        id: 79,
        expression: "Они что-то заметили",
        transcription: "ðeɪ ˈnəʊtɪst ˈsʌmθɪŋ",
        translation: "They noticed something",
      },
      {
        id: 80,
        expression: "Они не заметили самых важных вещей",
        transcription: "ðeɪ dɪdnt ˈnəʊtɪs ðə məʊst ɪmˈpɔːtənt θɪŋz",
        translation: "They didn't notice the most important things",
      },
      {
        id: 81,
        expression: "Они не делают ничего, чтобы улучшить эти условия",
        transcription: "ðeɪ dəʊnt dʊ ˈɛnɪθɪŋ tʊ ɪmˈpruːv ðiːz kənˈdɪʃənz",
        translation: "They don't do anything to improve these conditions",
      },
      {
        id: 82,
        expression: "Мы делаем все, чтобы улучшить эти условия",
        transcription: "wi dʊ ˈɛvrɪθɪŋ tʊ ɪmˈpruːv ðiːz kənˈdɪʃənz",
        translation: "We do everything to improve these conditions",
      },
      {
        id: 83,
        expression: "Что они сделали, чтобы улучшить эти условия?",
        transcription: "wɒt dɪd ðeɪ dʊ tʊ ɪmˈpruːv ðiːz kənˈdɪʃənz?",
        translation: "What did they do to improve these conditions?",
      },
      {
        id: 84,
        expression:
          "Мы все видим, что на английском языке говорят во всем мире",
        transcription: "wi ɔːl siː ðət ˈɪŋglɪʃ ɪz ˈspəʊkən ɔːl ˈəʊvə ðə wɜːld",
        translation: "We all see that English is spoken all over the world",
      },
      {
        id: 85,
        expression: "Ты знаешь, что на английском языке говорят во всем мире?",
        transcription: "dʊ jʊ nəʊ ðət ˈɪŋglɪʃ ɪz ˈspəʊkən ɔːl ˈəʊvə ðə wɜːld?",
        translation: "Do you know that English is spoken all over the world?",
      },
      {
        id: 86,
        expression: "Я не понимаю, почему эти проблемы игнорируются",
        transcription: "aɪ dəʊnt ˌʌndəˈstænd waɪ ðiːz ˈprɒbləmz ər ɪgˈnɔːd",
        translation: "I don't understand why these problems are ignored",
      },
      {
        id: 87,
        expression: "Я не могу понять, почему он игнорирует эти проблемы",
        transcription: "aɪ kɑːnt ˌʌndəˈstænd waɪ hi ɪgˈnɔːz ðiːz ˈprɒbləmz",
        translation: "I can't understand why he ignores these problems",
      },
      {
        id: 88,
        expression: "Я не понимаю, почему эта проблема была проигнорирована",
        transcription: "aɪ dəʊnt ˌʌndəˈstænd waɪ ðɪs ˈprɒbləm wəz ɪgˈnɔːd",
        translation: "I don't understand why this problem was ignored",
      },
      {
        id: 89,
        expression: "Они анализируют это очень тщательно",
        transcription: "ðeɪ ˈænəlaɪz ɪt ˈvɛri ˈθʌrəli",
        translation: "They analyse it very thoroughly",
      },
      {
        id: 90,
        expression: "Эти вещи тесно связаны друг с другом",
        transcription: "ðiːz θɪŋz ə ˈkləʊsli kəˈnɛktɪd wɪð iːʧ ˈʌðə",
        translation: "These things are closely connected with each other",
      },
      {
        id: 91,
        expression: "Они относятся к ней очень несправедливо",
        transcription: "ðeɪ triːt hə ˈvɛri ʌnˈfeəli",
        translation: "They treat her very unfairly",
      },
      {
        id: 92,
        expression: "Этот текст был переведен очень легко",
        transcription: "ðɪs tɛkst wəz trænsˈleɪtɪd ˈvɛri ˈiːzɪli",
        translation: "This text was translated very easily",
      },
      {
        id: 93,
        expression: "Они делают это в Китае?",
        transcription: "dʊ ðeɪ dʊ ɪt ɪn ˈʧaɪnə?",
        translation: "Do they do it in China?",
      },
      {
        id: 94,
        expression: "Я думаю, эта цель не будет достигнута",
        transcription: "aɪ θɪŋk ðɪs eɪm wəʊnt bi əˈʧiːvd",
        translation: "I think this aim won't be achieved",
      },
      {
        id: 95,
        expression: "Они относились к нему очень грубо",
        transcription: "ðeɪ ˈtriːtɪd ɪm ˈvɛri ˈruːdli",
        translation: "They treated him very rudely",
      },
      {
        id: 96,
        expression: "Все очень тщательно анализируется",
        transcription: "ˈɛvrɪθɪŋ z ˈænəlaɪzd ˈvɛri ˈθʌrəli",
        translation: "Everything is analysed very thoroughly",
      },
      {
        id: 97,
        expression: "Люди говорят по-испански во многих странах",
        transcription: "ˈpiːpl spiːk ˈspænɪʃ ɪn ˈmɛni ˈkʌntriz",
        translation: "People speak Spanish in many countries",
      },
      {
        id: 98,
        expression: "Некоторые ошибки были исправлены",
        transcription: "sʌm mɪsˈteɪks wə kəˈrɛktɪd",
        translation: "Some mistakes were corrected",
      },
      {
        id: 99,
        expression: "Злая собака укусила его",
        transcription: "ən ˈæŋgri dɒg bɪt hɪm",
        translation: "An angry dog bit him",
      },
      {
        id: 100,
        expression: "Я постараюсь исправить все эти ошибки",
        transcription: "aɪl traɪ tə kəˈrɛkt ɔːl ðiːz mɪsˈteɪks",
        translation: "I'll try to correct all these mistakes",
      },
      {
        id: 101,
        expression: "Он не вернул эти деньги",
        transcription: "hi dɪdnt rɪˈtɜːn ðɪs ˈmʌni",
        translation: "He didn't return this money",
      },
      {
        id: 102,
        expression: "Ничего не было замечено",
        transcription: "ˈnʌθɪŋ wəz ˈnəʊtɪst",
        translation: "Nothing was noticed",
      },
      {
        id: 103,
        expression: "Она родилась в 2015 году",
        transcription: "ʃi wəz bɔːn ɪn 2015",
        translation: "She was born in 2015",
      },
    ],
    {
      theory: `<div class="theory-block">
<h3>Закрепление пройденного материала</h3>
</div>`,
    },
  ],
];
