export const contentLesson31 = [
  [
    {
      title: "Урок 31. Past Simple. Negative Form",
    },
    [
      {
        id: 1,
        expression: "У него не было денег",
        transcription: "hi dɪdnt həv ˈmʌni",
        translation: "He didn't have money",
      },
      {
        id: 2,
        expression: "Я не закрыл дверь",
        transcription: "aɪ dɪdnt kləʊs ðə dɔː",
        translation: "I didn't close the door",
      },
      {
        id: 3,
        expression: "Я не делал эти физические упражнения",
        transcription: "aɪ dɪdnt dʊ ðiːz ˈfɪzɪkəl ˈɛksəsaɪzɪz",
        translation: "I didn't do these physical exercises",
      },
      {
        id: 4,
        expression: "Я не поехал в свой загородный дом в воскресенье",
        transcription: "aɪ dɪdnt gəʊ tə maɪ ˈkʌntri haʊs ɒn ˈsʌndeɪ",
        translation: "I didn't go to my country house on Sunday",
      },
      {
        id: 5,
        expression: "У нее не было денег",
        transcription: "ʃi dɪdnt həv ˈmʌni",
        translation: "She didn't have money",
      },
      {
        id: 6,
        expression: "Мы не играли в теннис",
        transcription: "wi dɪdnt pleɪ ˈtɛnɪs",
        translation: "We didn't play tennis",
      },
      {
        id: 7,
        expression: "Это не принесло ему достаточно денег",
        transcription: "ɪt dɪdnt brɪŋ ɪm ɪˈnʌf ˈmʌni",
        translation: "It didn't bring him enough money",
      },
      {
        id: 8,
        expression: "Он не купил машину",
        transcription: "hi dɪdnt baɪ ə kɑː",
        translation: "He didn't buy a car",
      },
      {
        id: 9,
        expression: "Она не чувствовала себя счастливой с ним",
        transcription: "ʃi dɪdnt fiːl ˈhæpi wɪð hɪm",
        translation: "She didn't feel happy with him",
      },
      {
        id: 10,
        expression: "Она не послушала моего совета",
        transcription: "ʃi dɪdnt ˈlɪsn tə maɪ ədˈvaɪs",
        translation: "She didn't listen to my advice",
      },
      {
        id: 11,
        expression: "Я не закрыл дверь",
        transcription: "aɪ dɪdnt kləʊs ðə dɔː",
        translation: "I didn't close the door",
      },
      {
        id: 12,
        expression: "Это не стоило много",
        transcription: "ɪt dɪdnt kɒst mʌʧ",
        translation: "It didn't cost much",
      },
      {
        id: 13,
        expression: "Он не хотел этого",
        transcription: "hi dɪdnt wɒnt ɪt",
        translation: "He didn't want it",
      },
      {
        id: 14,
        expression: "Они не получили это письмо",
        transcription: "ðeɪ dɪdnt gɛt ðɪs ˈlɛtə",
        translation: "They didn't get this letter",
      },
      {
        id: 15,
        expression: "Я не хотел говорить об этом",
        transcription: "aɪ dɪdnt wɒnt tə tɔːk əˈbaʊt ɪt",
        translation: "I didn't want to talk about it",
      },
      {
        id: 16,
        expression: "Я не заплатил за это",
        transcription: "aɪ dɪdnt peɪ fər ɪt",
        translation: "I didn't pay for it",
      },
      {
        id: 17,
        expression: "Я не пошел на ту вечеринку",
        transcription: "aɪ dɪdnt gəʊ tə ðɪs ˈpɑːti",
        translation: "I didn't go to this party",
      },
      {
        id: 18,
        expression: "Она не заперла дверь",
        transcription: "ʃi dɪdnt lɒk ðə dɔː",
        translation: "She didn't lock the door",
      },
      {
        id: 19,
        expression: "Он не сделал ошибку",
        transcription: "hi dɪdnt meɪk ə mɪsˈteɪk",
        translation: "He didn't make a mistake",
      },
      {
        id: 20,
        expression: "Он не учил английский в школе",
        transcription: "hi dɪdnt ˈstʌdi ˈɪŋglɪʃ ət skuːl",
        translation: "He didn't study English at school",
      },
      {
        id: 21,
        expression: "Мы этого не знали",
        transcription: "wi dɪdnt nəʊ ɪt",
        translation: "We didn't know it",
      },
      {
        id: 22,
        expression: "Мне не понравилось это место",
        transcription: "aɪ dɪdnt laɪk ðɪs pleɪs",
        translation: "I didn't like this place",
      },
      {
        id: 23,
        expression: "Я ему не поверил",
        transcription: "aɪ dɪdnt bɪˈliːv hɪm",
        translation: "I didn't believe him",
      },
      {
        id: 24,
        expression: "Это не помогло нам",
        transcription: "ɪt dɪdnt hɛlp ʌs",
        translation: "It didn't help us",
      },
      {
        id: 25,
        expression: "Они не играли в бадминтон",
        transcription: "ðeɪ dɪdnt pleɪ ˈbædmɪntən",
        translation: "They didn't play badminton",
      },
      {
        id: 26,
        expression: "Я не купил компьютер вчера",
        transcription: "aɪ dɪdnt baɪ ə kəmˈpjuːtə ˈjɛstədeɪ",
        translation: "I didn't buy a computer yesterday",
      },
      {
        id: 27,
        expression: "Это не выглядело так смешно",
        transcription: "ɪt dɪdnt lʊk səʊ ˈfʌni",
        translation: "It didn't look so funny",
      },
      {
        id: 28,
        expression: "Она не сдала этот тест",
        transcription: "ʃi dɪdnt pɑːs ðɪs tɛst",
        translation: "She didn't pass this test",
      },
      {
        id: 29,
        expression: "Она не видела ее вчера",
        transcription: "ʃi dɪdnt sɔː hə ˈjɛstədeɪ",
        translation: "She didn't saw her yesterday",
      },
      {
        id: 30,
        expression: "Я не делал эти физические упражнения",
        transcription: "aɪ dɪdnt dʊ ðiːz ˈfɪzɪkəl ˈɛksəsaɪzɪz",
        translation: "I didn't do these physical exercises",
      },
      {
        id: 31,
        expression: "Ее слова не удивили меня",
        transcription: "hə wɜːdz dɪdnt səˈpraɪz miː",
        translation: "Her words didn't surprise me",
      },
      {
        id: 32,
        expression: "Это не произошло",
        transcription: "ɪt dɪdnt ˈhæpən",
        translation: "It didn't happen",
      },
      {
        id: 33,
        expression: "Я думаю, ты не понял это",
        transcription: "aɪ θɪŋk jʊ dɪdnt ˌʌndəˈstænd ɪt",
        translation: "I think you didn't understand it",
      },
      {
        id: 34,
        expression: "Я не ходил туда вчера",
        transcription: "aɪ dɪdnt gəʊ ðeə ˈjɛstədeɪ",
        translation: "I didn't go there yesterday",
      },
      {
        id: 35,
        expression: "Мы не хотели этого",
        transcription: "wi dɪdnt wɒnt ɪt",
        translation: "We didn't want it",
      },
      {
        id: 36,
        expression: "Он не запер дверь",
        transcription: "hi dɪdnt lɒk ðə dɔː",
        translation: "He didn't lock the door",
      },
      {
        id: 37,
        expression: "Она не подписала этот документ",
        transcription: "ʃi dɪdnt saɪn ðɪs ˈdɒkjʊmənt",
        translation: "She didn't sign this document",
      },
      {
        id: 38,
        expression: "Это не казалось странным",
        transcription: "ɪt dɪdnt siːm streɪnʤ",
        translation: "It didn't seem strange",
      },
      {
        id: 39,
        expression: "Он не делал физические упражнения",
        transcription: "hi dɪdnt dʊ ˈfɪzɪkəl ˈɛksəsaɪzɪz",
        translation: "He didn't do physical exercises",
      },
      {
        id: 40,
        expression: "Ты не показывал мне эти фото",
        transcription: "jʊ dɪdnt ʃəʊ mi ðiːz ˈfəʊtəʊz",
        translation: "You didn't show me these photos",
      },
      {
        id: 41,
        expression: "Он не слушал это",
        transcription: "hi dɪdnt ˈlɪsn tʊ ɪt",
        translation: "He didn't listen to it",
      },
      {
        id: 42,
        expression: "Я не видел ее в том месте",
        transcription: "aɪ dɪdnt siː hər ɪn ðət pleɪs",
        translation: "I didn't see her in that place",
      },
      {
        id: 43,
        expression: "Я не ездил в Испанию в прошлом году",
        transcription: "aɪ dɪdnt gəʊ tə speɪn lɑːst jɪə",
        translation: "I didn't go to Spain last year",
      },
      {
        id: 44,
        expression: "Эта вещь не интересовала меня",
        transcription:
          "ðɪs θɪŋ dɪdnt ˈɪntrɪst miː / ðɪs θɪŋ wɒznt ˈɪntrɪstɪŋ fə miː",
        translation:
          "This thing didn't interest me / This thing wasn't interesting for me",
      },
      {
        id: 45,
        expression: "Я не поехал в свой загородный дом в воскресенье",
        transcription: "aɪ dɪdnt gəʊ tə maɪ ˈkʌntri haʊs ɒn ˈsʌndeɪ",
        translation: "I didn't go to my country house on Sunday",
      },
      {
        id: 46,
        expression: "Я не хотел говорить это",
        transcription: "aɪ dɪdnt wɒnt tə seɪ ɪt",
        translation: "I didn't want to say it",
      },
      {
        id: 47,
        expression: "Я не хотел ждать этого",
        transcription: "aɪ dɪdnt wɒnt tə weɪt fər ɪt",
        translation: "I didn't want to wait for it",
      },
      {
        id: 48,
        expression: "Я не понял, как это лучше сделать",
        transcription: "aɪ dɪdnt ˌʌndəˈstænd haʊ tə dʊ ɪt ˈbɛtə",
        translation: "I didn't understand how to do it better",
      },
      {
        id: 49,
        expression: "Я не ходил на вечеринку",
        transcription: "aɪ dɪdnt gəʊ tə ðə ˈpɑːti",
        translation: "I didn't go to the party",
      },
      {
        id: 50,
        expression: "Он не ходил в университет во вторник",
        transcription: "hi dɪdnt gəʊ tə ˌjuːnɪˈvɜːsɪti ɒn ˈtjuːzdeɪ",
        translation: "He didn't go to university on Tuesday",
      },
      {
        id: 51,
        expression: "Она не согласилась с этим",
        transcription: "ʃi dɪdnt əˈgriː wɪð ɪt",
        translation: "She didn't agree with it",
      },
      {
        id: 52,
        expression: "Я не ходил туда в прошлые выходные",
        transcription: "aɪ dɪdnt gəʊ ðeə lɑːst ˈwiːkˈɛnd",
        translation: "I didn't go there last weekend",
      },
      {
        id: 53,
        expression: "Я ничего не сказал",
        transcription: "aɪ dɪdnt seɪ ˈɛnɪθɪŋ",
        translation: "I didn't say anything",
      },
      {
        id: 54,
        expression: "Я не ходил на работу в четверг",
        transcription: "aɪ dɪdnt gəʊ tə wɜːk ɒn ˈθɜːzdeɪ",
        translation: "I didn't go to work on Thursday",
      },
      {
        id: 55,
        expression: "Он не объяснил свое решение",
        transcription: "hi dɪdnt ɪksˈpleɪn ɪz dɪˈsɪʒən",
        translation: "He didn't explain his decision",
      },
      {
        id: 56,
        expression: "Я не знал, что сказать",
        transcription: "aɪ dɪdnt nəʊ wɒt tə seɪ",
        translation: "I didn't know what to say",
      },
      {
        id: 57,
        expression: "Я не сделал какие-либо ошибки",
        transcription: "aɪ dɪdnt meɪk ˈɛni mɪsˈteɪks",
        translation: "I didn't make any mistakes",
      },
      {
        id: 58,
        expression: "Мы не обсуждали это в пятницу",
        transcription: "wi dɪdnt dɪsˈkʌs ɪt ɒn ˈfraɪdeɪ",
        translation: "We didn't discuss it on Friday",
      },
      {
        id: 59,
        expression: "Я не знал, что делать",
        transcription: "aɪ dɪdnt nəʊ wɒt tə duː",
        translation: "I didn't know what to do",
      },
      {
        id: 60,
        expression: "Я не изучал этого в школе",
        transcription: "aɪ dɪdnt ˈstʌdi ɪt ət skuːl",
        translation: "I didn't study it at school",
      },
      {
        id: 61,
        expression: "Я не изучал испанский в школе",
        transcription: "aɪ dɪdnt ˈstʌdi ˈspænɪʃ ət skuːl",
        translation: "I didn't study Spanish at school",
      },
      {
        id: 62,
        expression: "Они не знали друг друга",
        transcription: "ðeɪ dɪdnt nəʊ iːʧ ˈʌðə",
        translation: "They didn't know each other",
      },
      {
        id: 63,
        expression: "Мы не знали друг друга",
        transcription: "wi dɪdnt nəʊ iːʧ ˈʌðə",
        translation: "We didn't know each other",
      },
      {
        id: 64,
        expression: "Они не знали друг друга в прошлом году",
        transcription: "ðeɪ dɪdnt nəʊ iːʧ ˈʌðə lɑːst jɪə",
        translation: "They didn't know each other last year",
      },
      {
        id: 65,
        expression: "Я не видел ее в среду",
        transcription: "aɪ dɪdnt siː hər ɒn ˈwɛnzdeɪ",
        translation: "I didn't see her on Wednesday",
      },
      {
        id: 66,
        expression: "Он не видел ее в понедельник",
        transcription: "hi dɪdnt siː hər ɒn ˈmʌndeɪ",
        translation: "He didn't see her on Monday",
      },
      {
        id: 67,
        expression: "Она не видела его вчера",
        transcription: "ʃi dɪdnt siː ɪm ˈjɛstədeɪ",
        translation: "She didn't see him yesterday",
      },
      {
        id: 68,
        expression: "Она не говорила этого",
        transcription: "ʃi dɪdnt seɪ ɪt",
        translation: "She didn't say it",
      },
      {
        id: 69,
        expression: "Он не сказал мне это",
        transcription: "hi dɪdnt tɛl mi ɪt",
        translation: "He didn't tell me it",
      },
      {
        id: 70,
        expression: "Он не ходил на вечеринку прошлой ночью",
        transcription: "hi dɪdnt gəʊ tə ðə ˈpɑːti lɑːst naɪt",
        translation: "He didn't go to the party last night",
      },
      {
        id: 71,
        expression: "Они не ходили на вечеринку прошлой ночью",
        transcription: "ðeɪ dɪdnt gəʊ tə ðə ˈpɑːti lɑːst naɪt",
        translation: "They didn't go to the party last night",
      },
      {
        id: 72,
        expression: "Он не ходил туда вчера",
        transcription: "hi dɪdnt gəʊ ðeə ˈjɛstədeɪ",
        translation: "He didn't go there yesterday",
      },
      {
        id: 73,
        expression: "Они не хотели ждать этого",
        transcription: "ðeɪ dɪdnt wɒnt tə weɪt fər ɪt",
        translation: "They didn't want to wait for it",
      },
      {
        id: 74,
        expression: "Мы не хотели ждать тебя",
        transcription: "wi dɪdnt wɒnt tə weɪt fə juː",
        translation: "We didn't want to wait for you",
      },
      {
        id: 75,
        expression: "Они не хотели ждать ее",
        transcription: "ðeɪ dɪdnt wɒnt tə weɪt fə hə",
        translation: "They didn't want to wait for her",
      },
      {
        id: 76,
        expression: "Я не изучал эту вещь в университете",
        transcription: "aɪ dɪdnt ˈstʌdi ðɪs θɪŋ ət ˌjuːnɪˈvɜːsɪti",
        translation: "I didn't study this thing at university",
      },
      {
        id: 77,
        expression: "Он не изучал этих вещей в школе",
        transcription: "hi dɪdnt ˈstʌdi ðiːz θɪŋz ət skuːl",
        translation: "He didn't study these things at school",
      },
      {
        id: 78,
        expression: "Я не изучал эти проблемы там",
        transcription: "aɪ dɪdnt ˈstʌdi ðiːz ˈprɒbləmz ðeə",
        translation: "I didn't study these problems there",
      },
      {
        id: 79,
        expression: "У них не было никаких вопросов",
        transcription: "ðeɪ dɪdnt həv ˈɛni ˈkwɛsʧənz",
        translation: "They didn't have any questions",
      },
      {
        id: 80,
        expression: "У нас не было никаких идей",
        transcription: "wi dɪdnt həv ˈɛni aɪˈdɪəz",
        translation: "We didn't have any ideas",
      },
      {
        id: 81,
        expression: "У нее не было никаких проблем",
        transcription: "ʃi dɪdnt həv ˈɛni ˈprɒbləmz",
        translation: "She didn't have any problems",
      },
      {
        id: 82,
        expression: "Я не пытался сделать это",
        transcription: "aɪ dɪdnt traɪ tə dʊ ɪt",
        translation: "I didn't try to do it",
      },
      {
        id: 83,
        expression: "Он не пытался сделать это еще раз",
        transcription: "hi dɪdnt traɪ tə dʊ wʌn mɔː taɪm",
        translation: "He didn't try to do one more time",
      },
      {
        id: 84,
        expression: "Мы не пробовали сделать это снова",
        transcription: "wi dɪdnt traɪ tə dʊ ɪt əˈgɛn",
        translation: "We didn't try to do it again",
      },
      {
        id: 85,
        expression: "У меня не было никаких серьезных проблем",
        transcription: "aɪ dɪdnt həv ˈɛni ˈsɪərɪəs ˈprɒbləmz",
        translation: "I didn't have any serious problems",
      },
      {
        id: 86,
        expression: "У него не было никаких проблем",
        transcription: "hi dɪdnt həv ˈɛni ˈprɒbləmz",
        translation: "He didn't have any problems",
      },
      {
        id: 87,
        expression: "У нас не было никаких вопросов",
        transcription: "wi dɪdnt həv ˈɛni ˈkwɛsʧənz",
        translation: "We didn't have any questions",
      },
      {
        id: 88,
        expression: "Мы не обсуждали это в прошлый вторник",
        transcription: "wi dɪdnt dɪsˈkʌs ɪt lɑːst ˈtjuːzdeɪ",
        translation: "We didn't discuss it last Tuesday",
      },
      {
        id: 89,
        expression: "Они не ходили в зоопарк в субботу",
        transcription: "ðeɪ dɪdnt gəʊ tə ðə zuː ɒn ˈsætədeɪ",
        translation: "They didn't go to the zoo on Saturday",
      },
      {
        id: 90,
        expression: "Она не ходила в школу в понедельник",
        transcription: "ʃi dɪdnt gəʊ tə skuːl ɒn ˈmʌndeɪ",
        translation: "She didn't go to school on Monday",
      },
      {
        id: 91,
        expression: "Я не знал, что сказать ему",
        transcription: "aɪ dɪdnt nəʊ wɒt tə tɛl hɪm",
        translation: "I didn't know what to tell him",
      },
      {
        id: 92,
        expression: "Это не звучало странно",
        transcription: "ɪt dɪdnt saʊnd streɪnʤ",
        translation: "It didn't sound strange",
      },
      {
        id: 93,
        expression: "Он не согласился",
        transcription: "hi dɪdnt əˈgriː",
        translation: "He didn't agree",
      },
      {
        id: 94,
        expression: "Он ничего не сделал",
        transcription: "hi dɪdnt dʊ ˈɛnɪθɪŋ",
        translation: "He didn't do anything",
      },
      {
        id: 95,
        expression: "Он не пытался улучшить свои результаты",
        transcription: "hi dɪdnt traɪ tʊ ɪmˈpruːv ɪz rɪˈzʌlts",
        translation: "He didn't try to improve his results",
      },
      {
        id: 96,
        expression: "Я не забыл сказать это",
        transcription: "aɪ dɪdnt fəˈgɛt tə seɪ ɪt",
        translation: "I didn't forget to say it",
      },
      {
        id: 97,
        expression: "Он не работал в банке",
        transcription: "hi dɪdnt wɜːk ɪn ə bæŋk",
        translation: "He didn't work in a bank",
      },
      {
        id: 98,
        expression: "Я не хотел ничего менять",
        transcription: "aɪ dɪdnt wɒnt tə ʧeɪnʤ ˈɛnɪθɪŋ",
        translation: "I didn't want to change anything",
      },
      {
        id: 99,
        expression: "Он не пытался ничего менять",
        transcription: "hi dɪdnt traɪ tə ʧeɪnʤ ˈɛnɪθɪŋ",
        translation: "He didn't try to change anything",
      },
      {
        id: 100,
        expression: "Я не забыл сделать это",
        transcription: "aɪ dɪdnt fəˈgɛt tə dʊ ɪt",
        translation: "I didn't forget to do it",
      },
      {
        id: 101,
        expression: "Они не любили друг друга",
        transcription: "ðeɪ dɪdnt lʌv iːʧ ˈʌðə",
        translation: "They didn't love each other",
      },
      {
        id: 102,
        expression: "Я не хотел жить там",
        transcription: "aɪ dɪdnt wɒnt tə lɪv ðeə",
        translation: "I didn't want to live there",
      },
    ],
    {
      theory: `<div class="theory-block">
<h3>Отрицание в Past Simple</h3>
<p>Происходит по формуле:</p>
<p><span>did not + глагол</span></p>
<p>Сокращенный вариант <span>didn't + глагол</span></p>
<p>I didn't have time - У меня не было времени.</p>
<p>К устойчивым выражениям:</p>
<h3>do exercices</h3>
<p>- делать упражнения</p>
<p>Не "make"!</p>
<p>He didn't do these exercices - Он не делал эти упражнения.</p>
<h3>on Sunday</h3>
<p>- в воскресенье (или любой другой день недели)</p>
<p>I didn't go to work on Sunday - Я не ходил на работу в воскрсенье.</p>
</div>`,
    },
  ],
];
