export const contentLesson44 = [
  [
    {
      title: "Урок 44. Past Simple: verb + was / were",
    },
    [
      {
        id: 1,
        expression: "Она выглядела старой или молодой?",
        transcription: "dɪd ʃiː lʊk əʊld ɔː jʌŋ? ",
        translation: "Did she look old or young?",
      },
      {
        id: 2,
        expression: "Она работала учителем?",
        transcription: "dɪd ʃiː wɜːk æz ə ˈtiːʧə? ",
        translation: "Did she work as a teacher?",
      },
      {
        id: 3,
        expression: "Это вовсе не было эффективно",
        transcription: "ɪt wɒznt ɪˈfɛktɪv æt ɔːl",
        translation: "It wasn't effective at all",
      },
      {
        id: 4,
        expression: "Он не выглядел старым",
        transcription: "hiː dɪdnt lʊk əʊld",
        translation: "He didn't look old",
      },
      {
        id: 5,
        expression: "Это было эффективно?",
        transcription: "wɒz ɪt ɪˈfɛktɪv? ",
        translation: "Was it effective?",
      },
      {
        id: 6,
        expression: "Они жили вместе?",
        transcription: "dɪd ðeɪ lɪv təˈgɛðə? ",
        translation: "Did they live together?",
      },
      {
        id: 7,
        expression: "Я не был там в прошлом месяце",
        transcription: "aɪ wɒznt ðeə lɑːst mʌnθ",
        translation: "I wasn't there last month",
      },
      {
        id: 8,
        expression: "Я учился там",
        transcription: "aɪ ˈstʌdɪd ðeə",
        translation: "I studied there",
      },
      {
        id: 9,
        expression: "Он был студентом?",
        transcription: "wɒz hiː ə ˈstjuːdənt? ",
        translation: "Was he a student?",
      },
      {
        id: 10,
        expression: "Он учился в том месте",
        transcription: "hiː ˈstʌdɪd ɪn ðæt pleɪs",
        translation: "He studied in that place",
      },
      {
        id: 11,
        expression: "Это не было проблемой для нас",
        transcription: "ɪt wɒznt ə ˈprɒbləm fɔːr ʌs",
        translation: "It wasn't a problem for us",
      },
      {
        id: 12,
        expression: "Он учился там?",
        transcription: "dɪd hiː ˈstʌdi ðeə? ",
        translation: "Did he study there?",
      },
      {
        id: 13,
        expression: "Это было совсем не интересно",
        transcription: "ɪt wɒznt ˈɪntrɪstɪŋ æt ɔːl",
        translation: "It wasn't interesting at all",
      },
      {
        id: 14,
        expression: "Он был инженером",
        transcription: "hiː wɒz ən ˌɛnʤɪˈnɪə",
        translation: "He was an engineer",
      },
      {
        id: 15,
        expression: "Она выглядела очень молодой?",
        transcription: "dɪd ʃiː lʊk ˈvɛri jʌŋ? ",
        translation: "Did she look very young?",
      },
      {
        id: 16,
        expression: "Ты был действительно так счастлив?",
        transcription: "wɜː juː ˈrɪəli səʊ ˈhæpi? ",
        translation: "Were you really so happy?",
      },
      {
        id: 17,
        expression: "Это казалось проблемой?",
        transcription: "dɪd ɪt siːm ə ˈprɒbləm? ",
        translation: "Did it seem a problem?",
      },
      {
        id: 18,
        expression: "Он был очень стар",
        transcription: "hiː wɒz ˈvɛri əʊld",
        translation: "He was very old",
      },
      {
        id: 19,
        expression: "Это было важно?",
        transcription: "wɒz ɪt ɪmˈpɔːtənt? ",
        translation: "Was it important?",
      },
      {
        id: 20,
        expression: "Ты был там прошлой ночью?",
        transcription: "wɜː juː ðeə lɑːst naɪt?",
        translation: "Were you there last night?",
      },
      {
        id: 21,
        expression: "Он выглядел очень старым",
        transcription: "hiː lʊkt ˈvɛri əʊld",
        translation: "He looked very old",
      },
      {
        id: 22,
        expression: "Он был очень молод?",
        transcription: "wɒz hiː ˈvɛri jʌŋ? ",
        translation: "Was he very young?",
      },
      {
        id: 23,
        expression: "Меня это совсем не интересовало",
        transcription: "ɪt dɪdnt ˈɪntrɪst miː æt ɔːl",
        translation: "It didn't interest me at all",
      },
      {
        id: 24,
        expression: "Он не был таким старым",
        transcription: "hiː wɒznt səʊ əʊld",
        translation: "He wasn't so old",
      },
      {
        id: 25,
        expression: "Это не мотивировало его",
        transcription: "ɪt dɪdnt ˈməʊtɪveɪt hɪm",
        translation: "It didn't motivate him",
      },
      {
        id: 26,
        expression: "Я был в том месте два дня назад",
        transcription: "aɪ wɒz ɪn ðæt pleɪs tuː deɪz əˈgəʊ",
        translation: "I was in that place two days ago",
      },
      {
        id: 27,
        expression: "Я не ходил туда в прошлом месяце",
        transcription: "aɪ dɪdnt gəʊ ðeə lɑːst mʌnθ",
        translation: "I didn't go there last month",
      },
      {
        id: 28,
        expression: "Это было действительно странно",
        transcription: "ɪt wɒz ˈrɪəli streɪnʤ",
        translation: "It was really strange",
      },
      {
        id: 29,
        expression: "Ты был там вчера днем?",
        transcription: "wɜː juː ðeə ˈjɛstədeɪ ˈɑːftəˈnuːn? ",
        translation: "Were you there yesterday afternoon?",
      },
      {
        id: 30,
        expression: "Она выглядела старой или молодой?",
        transcription: "dɪd ʃiː lʊk əʊld ɔː jʌŋ? ",
        translation: "Did she look old or young?",
      },
      {
        id: 31,
        expression: "Они были вместе?",
        transcription: "wɜː ðeɪ təˈgɛðə? ",
        translation: "Were they together?",
      },
      {
        id: 32,
        expression: "Это не казалось проблемой",
        transcription: "ɪt dɪdnt siːm ə ˈprɒbləm",
        translation: "It didn't seem a problem",
      },
      {
        id: 33,
        expression: "Ты чувствовал себя очень счастливым?",
        transcription: "dɪd juː fiːl ˈvɛri ˈhæpi? ",
        translation: "Did you feel very happy?",
      },
      {
        id: 34,
        expression: "Он был молодым или старым?",
        transcription: "wɒz hiː jʌŋ ɔːr əʊld? ",
        translation: "Was he young or old?",
      },
      {
        id: 35,
        expression: "Это не было мотивирующим",
        transcription: "ɪt wɒznt ˈməʊtɪveɪtɪŋ",
        translation: "It wasn't motivating",
      },
      {
        id: 36,
        expression: "Он профессионально занимался бизнесом",
        transcription: "hiː dɪd ˈbɪznɪs prəˈfɛʃnəli",
        translation: "He did business professionally",
      },
      {
        id: 37,
        expression: "Ты работал в этом месте?",
        transcription: "dɪd juː wɜːk ɪn ðɪs pleɪs?",
        translation: "Did you work in this place?",
      },
      {
        id: 38,
        expression: "Это совсем не мотивировало меня",
        transcription: "ɪt dɪdnt ˈməʊtɪveɪt miː æt ɔːl",
        translation: "It didn't motivate me at all",
      },
      {
        id: 39,
        expression: "Он был зубным врачом?",
        transcription: "wɒz hiː ə ˈdɛntɪst?",
        translation: "Was he a dentist?",
      },
      {
        id: 40,
        expression: "Это казалось важным?",
        transcription: "dɪd ɪt siːm ɪmˈpɔːtənt?",
        translation: "Did it seem important?",
      },
      {
        id: 41,
        expression: "Ты ходил туда прошлой ночью?",
        transcription: "dɪd juː gəʊ ðeə lɑːst naɪt?",
        translation: "Did you go there last night?",
      },
      {
        id: 42,
        expression: "Это казалось таким странным",
        transcription: "ɪt siːmd səʊ streɪnʤ",
        translation: "It seemed so strange",
      },
      {
        id: 43,
        expression: "Это было проблемой для тебя?",
        transcription: "wɒz ɪt ə ˈprɒbləm fɔː juː? ",
        translation: "Was it a problem for you?",
      },
      {
        id: 44,
        expression: "Он не был менеджером",
        transcription: "hiː wɒznt ə ˈmænɪʤə",
        translation: "He wasn't a manager",
      },
      {
        id: 45,
        expression: "Он не был согласен с этим",
        transcription: "hiː dɪdnt əˈgriː wɪð ɪt",
        translation: "He didn't agree with it",
      },
      {
        id: 46,
        expression: "Она работала учителем?",
        transcription: "dɪd ʃiː wɜːk æz ə ˈtiːʧə?",
        translation: "Did she work as a teacher?",
      },
      {
        id: 47,
        expression: "Я видел, что это было так эффективно",
        transcription: "aɪ sɔː ðæt ɪt wɒz səʊ ɪˈfɛktɪv",
        translation: "I saw that it was so effective",
      },
      {
        id: 48,
        expression: "Я знал, что это было правильное решение",
        transcription: "aɪ njuː ðæt ɪt wɒz ðə raɪt dɪˈsɪʒən",
        translation: "I knew that it was the right decision",
      },
      {
        id: 49,
        expression: "Она была одинока?",
        transcription: "wɒz ʃiː ˈləʊnli? ",
        translation: "Was she lonely?",
      },
      {
        id: 50,
        expression: "Это был правильный ответ или нет?",
        transcription: "wɒz ɪt ðə raɪt (kəˈrɛkt) ˈɑːnsər ɔː nɒt? ",
        translation: "Was it the right (correct) answer or not?",
      },
      {
        id: 51,
        expression: "Ты устал очень быстро?",
        transcription: "dɪd juː gɛt ˈtaɪəd ˈvɛri ˈkwɪkli? ",
        translation: "Did you get tired very quickly?",
      },
      {
        id: 52,
        expression: "Он не работал менеджером",
        transcription: "hiː dɪdnt wɜːk æz ə ˈmænɪʤə",
        translation: "He didn't work as a manager",
      },
      {
        id: 53,
        expression: "Это казалось таким эффективным",
        transcription: "ɪt siːmd səʊ ɪˈfɛktɪv",
        translation: "It seemed so effective",
      },
      {
        id: 54,
        expression: "Они поженились?",
        transcription: "dɪd ðeɪ gɛt ˈmærɪd? ",
        translation: "Did they get married?",
      },
      {
        id: 55,
        expression: "Она была учителем?",
        transcription: "wɒz ʃiː ə ˈtiːʧə? ",
        translation: "Was she a teacher?",
      },
      {
        id: 56,
        expression: "Они не поженились в прошлом году",
        transcription: "ðeɪ dɪdnt gɛt ˈmærɪd lɑːst jɪə",
        translation: "They didn't get married last year",
      },
      {
        id: 57,
        expression: "Ты знал верный ответ?",
        transcription: "dɪd juː nəʊ ðə raɪt ˈɑːnsə?",
        translation: "Did you know the right answer?",
      },
      {
        id: 58,
        expression: "Он чувствовал себя так одиноко?",
        transcription: "dɪd hiː fiːl səʊ ˈləʊnli? ",
        translation: "Did he feel so lonely?",
      },
      {
        id: 59,
        expression: "Я знал, что это было невозможно",
        transcription: "aɪ njuː ðæt ɪt wɒz ɪmˈpɒsəbl",
        translation: "I knew that it was impossible",
      },
      {
        id: 60,
        expression: "Она знала, это было невозможно",
        transcription: "ʃiː njuː ɪt wɒz ɪmˈpɒsəbl",
        translation: "She knew it was impossible",
      },
      {
        id: 61,
        expression: "Ты знал, что это было действительно невозможно",
        transcription: "juː njuː ðæt ɪt wɒz ˈrɪəli ɪmˈpɒsəbl",
        translation: "You knew that it was really impossible",
      },
      {
        id: 62,
        expression: "Я не устал",
        transcription: "aɪ wɒznt ˈtaɪəd",
        translation: "I wasn't tired",
      },
      {
        id: 63,
        expression: "Ты действительно был уставшим",
        transcription: "juː wɜː ˈrɪəli ˈtaɪəd",
        translation: "You were really tired",
      },
      {
        id: 64,
        expression: "Я не был очень уставшим",
        transcription: "aɪ wɒznt ˈvɛri ˈtaɪəd",
        translation: "I wasn't very tired",
      },
      {
        id: 65,
        expression: "Она работала секретарем?",
        transcription: "dɪd ʃiː wɜːk æz ə ˈsɛkrətri? ",
        translation: "Did she work as a secretary?",
      },
      {
        id: 66,
        expression: "Она работала менеджером?",
        transcription: "dɪd ʃiː wɜːk æz ə ˈmænɪʤə?",
        translation: "Did she work as a manager?",
      },
      {
        id: 67,
        expression: "Ты работал учителем?",
        transcription: "dɪd juː wɜːk æz ə ˈtiːʧə? ",
        translation: "Did you work as a teacher?",
      },
      {
        id: 68,
        expression: "Это кажется невозможным",
        transcription: "ɪt siːmz ɪmˈpɒsəbl",
        translation: "It seems impossible",
      },
      {
        id: 69,
        expression: "Это казалось невозможным",
        transcription: "ɪt siːmd ɪmˈpɒsəbl",
        translation: "It seemed impossible",
      },
      {
        id: 70,
        expression: "Она была не одна",
        transcription: "ʃiː wɒznt əˈləʊn",
        translation: "She wasn't alone",
      },
      {
        id: 71,
        expression: "Я был не один",
        transcription: "aɪ wɒznt əˈləʊn",
        translation: "I wasn't alone",
      },
      {
        id: 72,
        expression: "Он был женат на ней",
        transcription: "hiː wɒz ˈmærɪd tuː hɜː",
        translation: "He was married to her",
      },
      {
        id: 73,
        expression: "Она вышла замуж",
        transcription: "ʃiː gɒt ˈmærɪd",
        translation: "She got married",
      },
      {
        id: 74,
        expression: "Она вышла за него замуж",
        transcription: "ʃiː ˈmærɪd hɪm",
        translation: "She married him",
      },
      {
        id: 75,
        expression: "Ты быстро устал?",
        transcription: "dɪd juː gɛt ˈtaɪəd ˈkwɪkli? / wɜː juː ˈtaɪəd ˈkwɪkli?",
        translation: "Did you get tired quickly? / Were you tired quickly?",
      },
      {
        id: 76,
        expression: "Она очень быстро устала?",
        transcription:
          "wɒz ʃiː ˈtaɪəd ˈvɛri ˈkwɪkli? / dɪd ʃiː gɛt ˈtaɪəd ˈvɛri ˈkwɪkli?",
        translation:
          "Was she tired very quickly? / Did she get tired very quickly?",
      },
      {
        id: 77,
        expression: "Он был зол?",
        transcription: "wɒz hiː ˈæŋgri?",
        translation: "Was he angry?",
      },
      {
        id: 78,
        expression: "Они были злыми?",
        transcription: "wɜː ðeɪ ˈæŋgri? ",
        translation: "Were they angry?",
      },
      {
        id: 79,
        expression: "Я действительно устал",
        transcription: "aɪ wɒz ˈrɪəli ˈtaɪəd / aɪ gɒt ˌriːˈaɪli ˈtaɪəd",
        translation: "I was really tired / I got reaIly tired",
      },
      {
        id: 80,
        expression: "Они очень устали",
        transcription: "ðeɪ wɜː ˈvɛri ˈtaɪəd / ðeɪ gɒt ˈvɛri ˈtaɪəd",
        translation: "They were very tired / They got very tired",
      },
      {
        id: 81,
        expression: "Он согласился или нет?",
        transcription: "dɪd hiː əˈgriː ɔː nɒt?",
        translation: "Did he agree or not?",
      },
      {
        id: 82,
        expression: "Ты согласился?",
        transcription: "dɪd juː əˈgriː?",
        translation: "Did you agree?",
      },
      {
        id: 83,
        expression: "Я знаю, что они не были женаты",
        transcription: "aɪ nəʊ ðæt ðeɪ wɜːnt ˈmærɪd",
        translation: "I know that they weren't married",
      },
      {
        id: 84,
        expression: "Я не чувствовал себя одиноко",
        transcription: "aɪ dɪdnt fiːl ˈləʊnli",
        translation: "I didn't feel lonely",
      },
      {
        id: 85,
        expression: "Она согласилась",
        transcription: "ʃiː əˈgriːd",
        translation: "She agreed",
      },
      {
        id: 86,
        expression: "Он чувствовал себя таким злым?",
        transcription: "dɪd hiː fiːl səʊ ˈæŋgri?",
        translation: "Did he feel so angry?",
      },
      {
        id: 87,
        expression: "Это не казалось эффективным",
        transcription: "ɪt dɪdnt siːm ɪˈfɛktɪv",
        translation: "It didn't seem effective",
      },
      {
        id: 88,
        expression: "Я не был одинок",
        transcription: "aɪ wɒznt ˈləʊnli",
        translation: "I wasn't lonely",
      },
      {
        id: 89,
        expression: "Он с ней не чувствовал себя счастливым",
        transcription: "hiː dɪdnt fiːl ˈhæpi wɪð hɜː",
        translation: "He didn't feel happy with her",
      },
      {
        id: 90,
        expression: "Он не был зол",
        transcription: "hiː wɒznt ˈæŋgri",
        translation: "He wasn't angry",
      },
      {
        id: 91,
        expression: "Они были женаты?",
        transcription: "wɜː ðeɪ ˈmærɪd?",
        translation: "Were they married?",
      },
      {
        id: 92,
        expression: "Она была замужем",
        transcription: "ʃiː wɒz ˈmærɪd",
        translation: "She was married",
      },
      {
        id: 93,
        expression: "Я не устал",
        transcription: "aɪ wɒznt ˈtaɪəd / aɪ dɪdnt gɛt ˈtaɪəd",
        translation: "I wasn't tired / I didn't get tired",
      },
      {
        id: 94,
        expression: "Это совсем не было эффективно",
        transcription: "ɪt wɒznt ɪˈfɛktɪv æt ɔːl",
        translation: "It wasn't effective at all",
      },
      {
        id: 95,
        expression: "Я был уставшим",
        transcription: "aɪ wɒz ˈtaɪəd / aɪ gɒt ˈvɛri ˈtaɪəd",
        translation: "I was tired / I got very tired",
      },
      {
        id: 96,
        expression: "Это казалось эффективным?",
        transcription: "dɪd ɪt siːm ɪˈfɛktɪv?",
        translation: "Did it seem effective?",
      },
      {
        id: 97,
        expression: "Я был уверен, что это был верный ответ",
        transcription: "aɪ wɒz ʃʊə ðæt ɪt wɒz ðə raɪt (kəˈrɛkt) ˈɑːnsə",
        translation: "I was sure that it was the right (correct) answer",
      },
    ],
    {
      theory: `<div class="theory-block">
<p>Устойчивые выражения:</p>
<h3>look old / young</h3>
<p>- выглядеть старым / молодым</p>
<p>Did she look old or young? - Она выглядела старой или молодой?</p>
<h3>work as a / an</h3>
<p>- работать кем-то</p>
<p>Did you work as a teacher? - Ты работал учителем?</p>
<p>Наличие неопределенного артикля обязательно!</p>
<h3>at all / an</h3>
<p>- вовсе, совсем</p>
<p>It wasn't funny at all - Это было совсем не смешно</p>
</div>`,
    },
  ],
];
