export const contentLesson32 = [
  [
    {
      title: "Урок 32. Past Simple. Question",
    },
    [
      {
        id: 1,
        expression: "Ты видел это в начале?",
        transcription: "dɪd jʊ siː ɪt ɪn ðə bɪˈgɪnɪŋ?",
        translation: "Did you see it in the beginning?",
      },
      {
        id: 2,
        expression: "Ты читал об этом в конце?",
        transcription: "dɪd jʊ riːd əˈbaʊt ɪt ɪn ði ɛnd?",
        translation: "Did you read about it in the end?",
      },
      {
        id: 3,
        expression: "Тебе нужно было больше денег?",
        transcription: "dɪd jʊ niːd mɔː ˈmʌni?",
        translation: "Did you need more money?",
      },
      {
        id: 4,
        expression: "Она тебе ответила?",
        transcription: "dɪd ʃi ˈɑːnsə juː?",
        translation: "Did she answer you?",
      },
      {
        id: 5,
        expression: "Ты написал письмо?",
        transcription: "dɪd jʊ raɪt ə ˈlɛtə?",
        translation: "Did you write a letter?",
      },
      {
        id: 6,
        expression: "Ты согласился?",
        transcription: "dɪd jʊ əˈgriː?",
        translation: "Did you agree?",
      },
      {
        id: 7,
        expression: "Ты вернулся домой позже?",
        transcription: "dɪd jʊ kʌm bæk həʊm ˈleɪtə?",
        translation: "Did you come back home later?",
      },
      {
        id: 8,
        expression: "Ты говорил о нашем обществе?",
        transcription: "dɪd jʊ tɔːk əˈbaʊt ˈaʊə səˈsaɪəti?",
        translation: "Did you talk about our society?",
      },
      {
        id: 9,
        expression: "Ты написал письмо?",
        transcription: "dɪd jʊ raɪt ə ˈlɛtə?",
        translation: "Did you write a letter?",
      },
      {
        id: 10,
        expression: "Ты помнил ее фамилию?",
        transcription:
          "dɪd jʊ rɪˈmɛmbə hə ˈsɜːneɪm? / dɪd jʊ rɪˈmɛmbə hə lɑːst neɪm? / dɪd jʊ rɪˈmɛmbə hə ˈfæmɪli neɪm?",
        translation:
          "Did you remember her surname? / Did you remember her last name? / Did you remember her family name?",
      },
      {
        id: 11,
        expression: "Ты получил мое сообщение?",
        transcription: "dɪd jʊ gɛt maɪ ˈmɛsɪʤ?",
        translation: "Did you get my message?",
      },
      {
        id: 12,
        expression: "Они говорили о социальных проблемах?",
        transcription: "dɪd ðeɪ tɔːk əˈbaʊt ˈsəʊʃəl ˈprɒbləmz?",
        translation: "Did they talk about social problems?",
      },
      {
        id: 13,
        expression: "Ты закончил свою работу?",
        transcription: "dɪd jʊ ˈfɪnɪʃ jə wɜːk?",
        translation: "Did you finish your work?",
      },
      {
        id: 14,
        expression: "Ты купил квартиру?",
        transcription: "dɪd jʊ baɪ ən əˈpɑːtmənt?",
        translation: "Did you buy an apartment?",
      },
      {
        id: 15,
        expression: "Она тебе ответила?",
        transcription: "dɪd ʃi ˈɑːnsə juː?",
        translation: "Did she answer you?",
      },
      {
        id: 16,
        expression: "Они производили дешевые товары?",
        transcription: "dɪd ðeɪ ˈprɒdjuːs ʧiːp gʊdz?",
        translation: "Did they produce cheap goods?",
      },
      {
        id: 17,
        expression: "Ты ходил на работу вчера?",
        transcription: "dɪd jʊ gəʊ tə wɜːk ˈjɛstədeɪ?",
        translation: "Did you go to work yesterday?",
      },
      {
        id: 18,
        expression: "Ты сохранил этот документ?",
        transcription: "dɪd jʊ seɪv ðɪs ˈdɒkjʊmənt?",
        translation: "Did you save this document?",
      },
      {
        id: 19,
        expression: "Ты пригласил своих друзей?",
        transcription: "dɪd jʊ ɪnˈvaɪt jə frɛndz?",
        translation: "Did you invite your friends?",
      },
      {
        id: 20,
        expression: "Ты посетил Германию на прошлой неделе?",
        transcription: "dɪd jʊ ˈvɪzɪt ˈʤɜːməni lɑːst wiːk?",
        translation: "Did you visit Germany last week?",
      },
      {
        id: 21,
        expression: "Ты понял это?",
        transcription: "dɪd jʊ ˌʌndəˈstænd ɪt?",
        translation: "Did you understand it?",
      },
      {
        id: 22,
        expression: "Ты вспомнил его фамилию?",
        transcription: "dɪd jʊ rɪˈmɛmbə hɪz ˈsɜːneɪm?",
        translation: "Did you remember his surname?",
      },
      {
        id: 23,
        expression: "Он ходил в школу позавчера?",
        transcription: "dɪd hi gəʊ tə skuːl ðə deɪ bɪˈfɔː ˈjɛstədeɪ?",
        translation: "Did he go to school the day before yesterday?",
      },
      {
        id: 24,
        expression: "Ты сдал этот экзамен?",
        transcription: "dɪd jʊ pɑːs ðɪs ɪgˈzæm?",
        translation: "Did you pass this exam?",
      },
      {
        id: 25,
        expression: "Ты ездил в Англию в прошлом месяце?",
        transcription: "dɪd jʊ gəʊ tʊ ˈɪŋglənd lɑːst wiːk?",
        translation: "Did you go to England last week?",
      },
      {
        id: 26,
        expression: "Ты видел ее на прошлой неделе?",
        transcription: "dɪd jʊ siː hə lɑːst wiːk?",
        translation: "Did you see her last week?",
      },
      {
        id: 27,
        expression: "Они говорили по-английски?",
        transcription: "dɪd ðeɪ spiːk ˈɪŋglɪʃ?",
        translation: "Did they speak English?",
      },
      {
        id: 28,
        expression: "Она потратила слишком много денег?",
        transcription: "dɪd ʃi spɛnd tuː mʌʧ ˈmʌni?",
        translation: "Did she spend too much money?",
      },
      {
        id: 29,
        expression: "Ты водил машину вчера?",
        transcription: "dɪd jʊ draɪv ə kɑː ˈjɛstədeɪ?",
        translation: "Did you drive a car yesterday?",
      },
      {
        id: 30,
        expression: "Это принесло тебе хорошие деньги?",
        transcription: "dɪd ɪt brɪŋ jʊ gʊd ˈmʌni?",
        translation: "Did it bring you good money?",
      },
      {
        id: 31,
        expression: "Вы все обсудили?",
        transcription: "dɪd jʊ dɪsˈkʌs ˈɛvrɪθɪŋ?",
        translation: "Did you discuss everything?",
      },
      {
        id: 32,
        expression: "Ты снимал квартиру?",
        transcription: "dɪd jʊ rɛnt ən əˈpɑːtmənt?",
        translation: "Did you rent an apartment?",
      },
      {
        id: 33,
        expression: "Ты отправил ей сообщение?",
        transcription: "dɪd jʊ sɛnd hər ə ˈmɛsɪʤ?",
        translation: "Did you send her a message?",
      },
      {
        id: 34,
        expression: "Ты учился вчера?",
        transcription: "dɪd jʊ ˈstʌdi ˈjɛstədeɪ?",
        translation: "Did you study yesterday?",
      },
      {
        id: 35,
        expression: "Это казалось очень странным?",
        transcription: "dɪd ɪt siːm ˈvɛri streɪnʤ?",
        translation: "Did it seem very strange?",
      },
      {
        id: 36,
        expression: "Тебе нужно было больше времени?",
        transcription: "dɪd jʊ niːd mɔː taɪm?",
        translation: "Did you need more time?",
      },
      {
        id: 37,
        expression: "Ты думал о той вещи?",
        transcription: "dɪd jʊ θɪŋk əˈbaʊt ðɪs θɪŋ?",
        translation: "Did you think about this thing?",
      },
      {
        id: 38,
        expression: "Вы говорили о современных технологиях?",
        transcription: "dɪd jʊ tɔːk əˈbaʊt ˈmɒdən tɛkˈnɒləʤi?",
        translation: "Did you talk about modern technology?",
      },
      {
        id: 39,
        expression: "Ты работал вчера?",
        transcription: "dɪd jʊ wɜːk ˈjɛstədeɪ?",
        translation: "Did you work yesterday?",
      },
      {
        id: 40,
        expression: "Они говорили о нашем современном обществе?",
        transcription: "dɪd ðeɪ tɔːk əˈbaʊt ˈaʊə ˈmɒdən səˈsaɪəti?",
        translation: "Did they talk about our modern society?",
      },
      {
        id: 41,
        expression: "Это случилось вчера?",
        transcription: "dɪd ɪt ˈhæpən ˈjɛstədeɪ?",
        translation: "Did it happen yesterday?",
      },
      {
        id: 42,
        expression: "Они производили очень дорогие товары?",
        transcription: "dɪd ðeɪ ˈprɒdjuːs ˈvɛri ɪksˈpɛnsɪv gʊdz?",
        translation: "Did they produce very expensive goods?",
      },
      {
        id: 43,
        expression: "Он купил большой дом?",
        transcription: "dɪd hi baɪ ə bɪg haʊs? / dɪd hi baɪ ə lɑːʤ haʊs?",
        translation: "Did he buy a big house? / Did he buy a large house? ",
      },
      {
        id: 44,
        expression: "Тебе понравился этот фильм?",
        transcription: "dɪd jʊ laɪk ðɪs ˈmuːvi?",
        translation: "Did you like this movie?",
      },
      {
        id: 45,
        expression: "Ты ответил на это сообщение?",
        transcription: "dɪd jʊ ˈɑːnsə ðɪs ˈmɛsɪʤ?",
        translation: "Did you answer this message?",
      },
      {
        id: 46,
        expression: "Ты чувствовал себя счастливым, когда ты жил там?",
        transcription: "dɪd jʊ fiːl ˈhæpi wɛn jʊ lɪvd ðeə?",
        translation: "Did you feel happy when you lived there?",
      },
      {
        id: 47,
        expression: "Ты хотел сменить работу?",
        transcription: "dɪd jʊ wɒnt tə ʧeɪnʤ ə ʤɒb?",
        translation: "Did you want to change a job?",
      },
      {
        id: 48,
        expression: "Он женился на ней?",
        transcription: "dɪd hi ˈmæri hɜː?",
        translation: "Did he marry her?",
      },
      {
        id: 49,
        expression: "Ты переехал в другую страну?",
        transcription: "dɪd jʊ muːv tʊ əˈnʌðə ˈkʌntri?",
        translation: "Did you move to another country?",
      },
      {
        id: 50,
        expression: "Ты знал, что делать в этой ситуации?",
        transcription: "dɪd jʊ nəʊ wɒt tə dʊ ɪn ðɪs ˌsɪtjʊˈeɪʃən?",
        translation: "Did you know what to do in this situation?",
      },
      {
        id: 51,
        expression: "Ты прочел об этом в конце?",
        transcription: "dɪd jʊ riːd əˈbaʊt ɪt ɪn ði ɛnd?",
        translation: "Did you read about it in the end?",
      },
      {
        id: 52,
        expression: "Это стоило намного меньше?",
        transcription: "dɪd ɪt kɒst mʌʧ lɛs?",
        translation: "Did it cost much less?",
      },
      {
        id: 53,
        expression: "Ей была нужна твоя помощь?",
        transcription: "dɪd ʃi niːd jə hɛlp?",
        translation: "Did she need your help?",
      },
      {
        id: 54,
        expression: "Ты ходил туда, когда учился в школе?",
        transcription: "dɪd jʊ gəʊ ðeə wɛn jʊ ˈstʌdɪd ət skuːl?",
        translation: "Did you go there when you studied at school?",
      },
      {
        id: 55,
        expression: "Ты слышал эту новость?",
        transcription: "dɪd jʊ ˈlɪsn tə ðɪs njuːz?",
        translation: "Did you listen to this news?",
      },
      {
        id: 56,
        expression: "Ты купил те билеты?",
        transcription: "dɪd jʊ baɪ ðəʊz ˈtɪkɪts?",
        translation: "Did you buy those tickets?",
      },
      {
        id: 57,
        expression: "Она переехала за границу?",
        transcription: "dɪd ʃi muːv əˈbrɔːd?",
        translation: "Did she move abroad?",
      },
      {
        id: 58,
        expression: "Ты прибыл туда вовремя?",
        transcription: "dɪd jʊ əˈraɪv ðeər ɒn taɪm?",
        translation: "Did you arrive there on time?",
      },
      {
        id: 59,
        expression: "Ей нужно было больше практики?",
        transcription: "dɪd ʃi niːd mɔː ˈpræktɪs?",
        translation: "Did she need more practice?",
      },
      {
        id: 60,
        expression: "Тебе нужно было найти это срочно?",
        transcription: "dɪd jʊ niːd tə faɪnd ɪt ˈɜːʤəntli?",
        translation: "Did you need to find it urgently?",
      },
      {
        id: 61,
        expression: "Ей нужно было сделать это срочно?",
        transcription: "dɪd ʃi niːd tə dʊ ɪt ˈɜːʤəntli?",
        translation: "Did she need to do it urgently?",
      },
      {
        id: 62,
        expression:
          "Ты пригласил своих друзей на празднование своего дня рождения?",
        transcription: "dɪd jʊ ɪnˈvaɪt jə frɛndz tə jə ˈbɜːθdeɪ ˈpɑːti?",
        translation: "Did you invite your friends to your birthday party?",
      },
      {
        id: 63,
        expression:
          "Ты хотел пригласить своих друзей на празднование своего дня рождения?",
        transcription:
          "dɪd jʊ wɒnt tʊ ɪnˈvaɪt jə frɛndz tə jə ˈbɜːθdeɪ ˈpɑːti?",
        translation:
          "Did you want to invite your friends to your birthday party?",
      },
      {
        id: 64,
        expression: "Он выиграл в конце?",
        transcription: "dɪd hi wɪn ɪn ði ɛnd?",
        translation: "Did he win in the end?",
      },
      {
        id: 65,
        expression: "Ты выиграл?",
        transcription: "dɪd jʊ wɪn?",
        translation: "Did you win?",
      },
      {
        id: 66,
        expression: "Это стоило намного больше?",
        transcription: "dɪd ɪt kɒst mʌʧ mɔː?",
        translation: "Did it cost much more?",
      },
      {
        id: 67,
        expression: "Эта вещь стоила намного больше?",
        transcription: "dɪd ðɪs θɪŋ kɒst mʌʧ mɔː?",
        translation: "Did this thing cost much more?",
      },
      {
        id: 68,
        expression: "Это случилось или нет?",
        transcription: "dɪd ɪt ˈhæpən ɔː nɒt?",
        translation: "Did it happen or not?",
      },
      {
        id: 69,
        expression: "Это случилось?",
        transcription: "dɪd ɪt ˈhæpən?",
        translation: "Did it happen?",
      },
      {
        id: 70,
        expression: "Ты хотел найти новую работу?",
        transcription: "dɪd jʊ wɒnt tə faɪnd ə njuː ʤɒb?",
        translation: "Did you want to find a new job?",
      },
      {
        id: 71,
        expression: "Ты хотел найти работу?",
        transcription: "dɪd jʊ wɒnt tə faɪnd ə ʤɒb?",
        translation: "Did you want to find a job?",
      },
      {
        id: 72,
        expression: "Ты пытался найти новую работу?",
        transcription: "dɪd jʊ traɪ tə faɪnd ə njuː ʤɒb?",
        translation: "Did you try to find a new job?",
      },
      {
        id: 73,
        expression: "Ты подготовился к этому экзамену?",
        transcription: "dɪd jʊ prɪˈpeə fə ðɪs ɪgˈzæm?",
        translation: "Did you prepare for this exam?",
      },
      {
        id: 74,
        expression: "Ты подготовился к тому экзамену?",
        transcription: "dɪd jʊ prɪˈpeə fə ðət ɪgˈzæm?",
        translation: "Did you prepare for that exam?",
      },
      {
        id: 75,
        expression: "Он говорил это или нет?",
        transcription: "dɪd hi seɪ ɪt ɔː nɒt?",
        translation: "Did he say it or not?",
      },
      {
        id: 76,
        expression: "Ты говорил это или нет?",
        transcription: "dɪd jʊ seɪ ɪt ɔː nɒt?",
        translation: "Did you say it or not?",
      },
      {
        id: 77,
        expression: "Она хотела это или нет?",
        transcription: "dɪd ʃi wɒnt ɪt ɔː nɒt?",
        translation: "Did she want it or not?",
      },
      {
        id: 78,
        expression: "Это действительно интересовало тебя?",
        transcription: "dɪd ɪt ˈrɪəli ˈɪntrɪst juː?",
        translation: "Did it really interest you?",
      },
      {
        id: 79,
        expression: "Это действительно интересовало его?",
        transcription: "dɪd ɪt ˈrɪəli ˈɪntrɪst hɪm?",
        translation: "Did it really interest him?",
      },
      {
        id: 80,
        expression: "Ему нужны были деньги?",
        transcription: "dɪd hi niːd ˈmʌni?",
        translation: "Did he need money?",
      },
      {
        id: 81,
        expression: "Ему нужно было больше денег?",
        transcription: "dɪd hi niːd mɔː ˈmʌni?",
        translation: "Did he need more money?",
      },
      {
        id: 82,
        expression: "Она вышла за него замуж?",
        transcription: "dɪd ʃi ˈmæri hɪm?",
        translation: "Did she marry him?",
      },
      {
        id: 83,
        expression: "Ты подготовился к этому тесту?",
        transcription: "dɪd jʊ prɪˈpeə fə ðɪs tɛst?",
        translation: "Did you prepare for this test?",
      },
      {
        id: 84,
        expression: "Это произошло в начале?",
        transcription: "dɪd ɪt ˈhæpən ɪn ðə bɪˈgɪnɪŋ?",
        translation: "Did it happen in the beginning?",
      },
      {
        id: 85,
        expression: "Ты прослушал этот урок?",
        transcription: "dɪd jʊ ˈlɪsn tə ðɪs ˈlɛsn?",
        translation: "Did you listen to this lesson?",
      },
      {
        id: 86,
        expression: "Ты пытался изменить это?",
        transcription: "dɪd jʊ traɪ tə ʧeɪnʤ ɪt?",
        translation: "Did you try to change it?",
      },
      {
        id: 87,
        expression: "Он рассказал тебе этот секрет?",
        transcription: "dɪd hi tɛl jʊ ðɪs ˈsiːkrɪt?",
        translation: "Did he tell you this secret?",
      },
      {
        id: 88,
        expression: "У тебя были какие-либо проблемы?",
        transcription: "dɪd jʊ həv ˈɛni ˈprɒbləmz?",
        translation: "Did you have any problems?",
      },
      {
        id: 89,
        expression: "Ты видел это в начале?",
        transcription: "dɪd jʊ siː ɪt ɪn ðə bɪˈgɪnɪŋ?",
        translation: "Did you see it in the beginning?",
      },
      {
        id: 90,
        expression: "Они поженились?",
        transcription: "dɪd ðeɪ gɛt ˈmærɪd?",
        translation: "Did they get married?",
      },
      {
        id: 91,
        expression: "Тебе нужно было пойти туда?",
        transcription: "dɪd jʊ niːd tə gəʊ ðeə?",
        translation: "Did you need to go there?",
      },
      {
        id: 92,
        expression: "Он переехал в Америку?",
        transcription: "dɪd hi muːv tʊ əˈmɛrɪkə?",
        translation: "Did he move to America?",
      },
      {
        id: 93,
        expression: "У тебя были какие-либо вопросы?",
        transcription: "dɪd jʊ həv ˈɛni ˈkwɛsʧənz?",
        translation: "Did you have any questions?",
      },
      {
        id: 94,
        expression: "Ты знал, как сделать это лучше?",
        transcription: "dɪd jʊ nəʊ haʊ tə dʊ ɪt ˈbɛtə?",
        translation: "Did you know how to do it better?",
      },
      {
        id: 95,
        expression: "Она рассказала ему тот секрет?",
        transcription: "dɪd ʃi tɛl ɪm ðət ˈsiːkrɪt?",
        translation: "Did she tell him that secret?",
      },
      {
        id: 96,
        expression: "Ты хотел это увидеть?",
        transcription: "dɪd jʊ wɒnt tə siː ɪt?",
        translation: "Did you want to see it?",
      },
    ],
    {
      theory: `<div class="theory-block">
<h3>Вопросы в Past Simple</h3>
<p>Задаются по формуле:</p>
<p><span>did + подлежащее + глагол в первой форме</span></p>
<p>Did he answer you? - Он тебе ответил?</p>
<p>К устойчивым выражениям:</p>
<h3>in the beginning</h3>
<p>- в начале</p>
<p>I also didn't see it in the beginning - Я также не видел этого в начале.</p>
<h3>in the end</h3>
<p>- в конце</p>
<p>He asked me about it in the end of the meeting - Он стросил меня об этом в конце встречи.</p>
</div>`,
    },
  ],
];
