export const contentLesson51 = [
  [
    {
      title: "Урок 51. Построение предложений",
    },
    [
      {
        id: 1,
        expression: "Я живу в другом городе",
        transcription: "aɪ lɪv ɪn əˈnʌðə ˈsɪti",
        translation: "I live in another city",
      },
      {
        id: 2,
        expression: "Он действительно хочет говорить по-русски",
        transcription: "hi ˈrɪəli wɒnts tə spiːk ˈrʌʃ(ə)n",
        translation: "He really wants to speak Russian",
      },
      {
        id: 3,
        expression: "Я обожаю читать книги вечером",
        transcription: "aɪ ɪnˈʤɔɪ ˈriːdɪŋ bʊks ɪn ði ˈiːvnɪŋ",
        translation: "I enjoy reading books in the evening",
      },
      {
        id: 4,
        expression: "Она обожает играть в теннис",
        transcription: "ʃi ɪnˈʤɔɪz ˈpleɪɪŋ ˈtɛnɪs",
        translation: "She enjoys playing tennis",
      },
      {
        id: 5,
        expression: "Мне нравится есть здоровую пищу",
        transcription:
          "aɪ laɪk tʊ iːt ˈhɛlθi fuːd / aɪ laɪk ˈiːtɪŋ ˈhɛlθi fuːd",
        translation: "I like to eat healthy food / I like eating healthy food",
      },
      {
        id: 6,
        expression: "Ему нравится читать книги на английском",
        transcription: "hi laɪks ˈriːdɪŋ bʊks ɪn ˈɪŋglɪʃ",
        translation: "He likes reading books in English",
      },
      {
        id: 7,
        expression: "Мне действительно нравится кататься на велосипеде",
        transcription: "aɪ ˈrɪəli laɪk ˈsaɪklɪŋ",
        translation: "I really like cycling",
      },
      {
        id: 8,
        expression: "Ты говоришь по-английски прекрасно",
        transcription: "jʊ spiːk ˈɪŋglɪʃ ˈpɜːfɪktli",
        translation: "You speak English perfectly",
      },
      {
        id: 9,
        expression: "Это звучит отлично",
        transcription: "ɪt saʊndz greɪt",
        translation: "It sounds great",
      },
      {
        id: 10,
        expression: "Он платит за это",
        transcription: "hi peɪz fər ɪt",
        translation: "He pays for it",
      },
      {
        id: 11,
        expression: "Это стоит два миллиона фунтов",
        transcription: "ɪt kɒsts tuː ˈmɪljən paʊndz",
        translation: "It costs two million pounds",
      },
      {
        id: 12,
        expression: "Я могу сделать это в начале",
        transcription: "aɪ kən dʊ ɪt ɪn ðə bɪˈgɪnɪŋ",
        translation: "I can do it in the beginning",
      },
      {
        id: 13,
        expression: "Ты слишком много работаешь",
        transcription: "jʊ wɜːk tuː mʌʧ",
        translation: "You work too much",
      },
      {
        id: 14,
        expression: "Она тоже так думает",
        transcription: "ʃi ˈɔːlsəʊ θɪŋks səʊ / ʃi θɪŋks səʊ, tuː",
        translation: "She also thinks so / She thinks so, too",
      },
      {
        id: 15,
        expression: "Он тоже так думает",
        transcription: "hi ˈɔːlsəʊ θɪŋks səʊ / hi θɪŋks səʊ, tuː",
        translation: "He also thinks so / He thinks so, too",
      },
      {
        id: 16,
        expression: "Я предпочитаю делать это в свое свободное время",
        transcription: "aɪ priˈfɜː tə dʊ ɪt ɪn maɪ friː taɪm",
        translation: "I prefer to do it in my free time",
      },
      {
        id: 17,
        expression: "Ты показываешь отличные результаты",
        transcription: "jʊ ʃəʊ ˈɛksələnt rɪˈzʌlts",
        translation: "You show excellent results",
      },
      {
        id: 18,
        expression: "Ей нравятся иностранные языки",
        transcription: "ʃi laɪks ˈfɒrɪn ˈlæŋgwɪʤɪz",
        translation: "She likes foreign languages",
      },
      {
        id: 19,
        expression: "Она прекрасно понимает это",
        transcription: "ʃi ˈpɜːfɪktli ˌʌndəˈstændz ɪt",
        translation: "She perfectly understands it",
      },
      {
        id: 20,
        expression: "У меня отличные результаты",
        transcription: "aɪ həv ˈɛksələnt rɪˈzʌlts",
        translation: "I have excellent results",
      },
      {
        id: 21,
        expression: "Он много знает",
        transcription: "hi nəʊz ə lɒt",
        translation: "He knows a lot",
      },
      {
        id: 22,
        expression: "Это стоит пять тысяч евро",
        transcription: "ɪt kɒsts faɪv ˈθaʊzənd ˈjʊərəʊz",
        translation: "It costs five thousand euros",
      },
      {
        id: 23,
        expression: "Мы учимся в одной группе",
        transcription: "wi ˈstʌdi ɪn wʌn gruːp",
        translation: "We study in one group",
      },
      {
        id: 24,
        expression: "Мы действительно ценим твою помощь",
        transcription: "wi ˈrɪəli əˈpriːʃɪeɪt jə hɛlp",
        translation: "We really appreciate your help",
      },
      {
        id: 25,
        expression: "Это нам очень помогает",
        transcription: "ɪt hɛlps əs ə lɒt",
        translation: "It helps us a lot",
      },
      {
        id: 26,
        expression: "Я тебя прекрасно понимаю",
        transcription: "aɪ ˈpɜːfɪktli ˌʌndəˈstænd juː",
        translation: "I perfectly understand you",
      },
      {
        id: 27,
        expression: "У нее блестящие результаты",
        transcription: "ʃi həz ˈbrɪljənt rɪˈzʌlts",
        translation: "She has brilliant results",
      },
      {
        id: 28,
        expression: "Он часто говорит эти вещи",
        transcription: "hi ˈɒf(ə)n sɛz ðiːz θɪŋz",
        translation: "He often says these things",
      },
      {
        id: 29,
        expression: "Ей действительно нравится кататься на велосипеде",
        transcription: "ʃi ˈrɪəli laɪks ˈsaɪklɪŋ",
        translation: "She really likes cycling",
      },
      {
        id: 30,
        expression: "Я обожаю английский",
        transcription: "aɪ ɪnˈʤɔɪ ˈɪŋglɪʃ",
        translation: "I enjoy English",
      },
      {
        id: 31,
        expression: "Она предпочитает горячий чай",
        transcription: "ʃi priˈfɜːz hɒt tiː",
        translation: "She prefers hot tea",
      },
      {
        id: 32,
        expression: "Ему действительно нравится плавать",
        transcription: "hi ˈrɪəli laɪks ˈswɪmɪŋ",
        translation: "He really likes swimming",
      },
      {
        id: 33,
        expression: "Он живет в другой области",
        transcription: "hi lɪvz ɪn əˈnʌðər ˈeərɪə",
        translation: "He lives in another area",
      },
      {
        id: 34,
        expression: "Мы видим музей",
        transcription: "wi siː ə mju(ː)ˈzɪəm",
        translation: "We see a museum",
      },
      {
        id: 35,
        expression: "Я хочу свободно говорить по-английски",
        transcription: "aɪ wɒnt tə spiːk ˈɪŋglɪʃ ˈflu(ː)əntli",
        translation: "I want to speak English fluently",
      },
      {
        id: 36,
        expression: "Он учится и работает",
        transcription: "hi ˈstʌdiz ənd wɜːks",
        translation: "He studies and works",
      },
      {
        id: 37,
        expression: "Эта вещь стоит двести долларов",
        transcription: "ðɪs θɪŋ kɒsts tuː ˈhʌndrəd ˈdɒləz",
        translation: "This thing costs two hundred dollars",
      },
      {
        id: 38,
        expression: "Мне действительно нравится этот язык",
        transcription: "aɪ ˈrɪəli laɪk ðɪs ˈlæŋgwɪʤ",
        translation: "I really like this language",
      },
      {
        id: 39,
        expression: "Я действительно обожаю спорт",
        transcription: "aɪ ˈrɪəli ɪnˈʤɔɪ spɔːt",
        translation: "I really enjoy sport",
      },
      {
        id: 40,
        expression: "Мне нужно больше опыта",
        transcription: "aɪ niːd mɔːr ɪksˈpɪərɪəns",
        translation: "I need more experience",
      },
      {
        id: 41,
        expression: "Он показывает блестящие результаты",
        transcription: "hi ʃəʊz ˈɛksələnt rɪˈzʌlts",
        translation: "He shows excellent results",
      },
      {
        id: 42,
        expression: "Я действительно ценю твою помощь",
        transcription: "aɪ ˈrɪəli əˈpriːʃɪeɪt jə hɛlp",
        translation: "I really appreciate your help",
      },
      {
        id: 43,
        expression: "Я стараюсь делать это каждый день",
        transcription: "aɪ traɪ tə dʊ ɪt ˈɛvri deɪ",
        translation: "I try to do it every day",
      },
      {
        id: 44,
        expression: "Она живет в квартире",
        transcription: "ʃi lɪvz ɪn ən əˈpɑːtmənt",
        translation: "She lives in an apartment",
      },
      {
        id: 45,
        expression: "Мы живем в доме",
        transcription: "wi lɪv ɪn ə haʊs",
        translation: "We live in a house",
      },
      {
        id: 46,
        expression: "Она профессионально преподает английский",
        transcription: "ʃi ˈtiːʧɪz ˈɪŋglɪʃ prəˈfɛʃnəli",
        translation: "She teaches English professionally",
      },
      {
        id: 47,
        expression: "Я прекрасно понимаю, как это работает",
        transcription: "aɪ ˈpɜːfɪktli ˌʌndəˈstænd haʊ ɪt wɜːks",
        translation: "I perfectly understand how it works",
      },
      {
        id: 48,
        expression: "Она часто слушает музыку, когда занимается другими делами",
        transcription: "ʃi ˈɒf(ə)n ˈlɪsnz tə ˈmjuːzɪk wɛn ʃi dəz ˈʌðə θɪŋz",
        translation: "She often listens to music when she does other things",
      },
      {
        id: 49,
        expression: "Мне нужен опыт работы в начале",
        transcription: "aɪ niːd wɜːk ɪksˈpɪərɪəns ɪn ðə bɪˈgɪnɪŋ",
        translation: "I need work experience in the beginning",
      },
      {
        id: 50,
        expression:
          "Я чувствую, что мне нужно прежде всего улучшить свое аудирование и речь",
        transcription:
          "aɪ fiːl ðət aɪ niːd tʊ ɪmˈpruːv maɪ ˈlɪsnɪŋ ənd ˈspiːkɪŋ fɜːst əv ɔːl",
        translation:
          "I feel that I need to improve my listening and speaking first of all",
      },
      {
        id: 51,
        expression: "Я действительно хочу понимать носителей языка",
        transcription: "aɪ ˈrɪəli wɒnt tʊ ˌʌndəˈstænd ˈneɪtɪv ˈspiːkəz",
        translation: "I really want to understand native speakers",
      },
      {
        id: 52,
        expression: "Я прекрасно понимаю твою точку зрения",
        transcription: "aɪ ˈpɜːfɪktli ˌʌndəˈstænd jə pɔɪnt əv vjuː",
        translation: "I perfectly understand your point of view",
      },
      {
        id: 53,
        expression: "Мне кажется, у тебя отличные результаты",
        transcription: "ɪt siːmz tə mi jʊ həv ən ˈɛksələnt rɪˈzʌlts",
        translation: "It seems to me you have an excellent results",
      },
      {
        id: 54,
        expression:
          "Я действительно хочу говорить по-английски как носитель языка",
        transcription: "aɪ ˈrɪəli wɒnt tə spiːk ˈɪŋglɪʃ laɪk ə ˈneɪtɪv ˈspiːkə",
        translation: "I really want to speak English like a native speaker",
      },
      {
        id: 55,
        expression: "Она работает врачом",
        transcription: "ʃi wɜːks əz ə ˈdɒktə",
        translation: "She works as a doctor",
      },
      {
        id: 56,
        expression: "Она хочет улучшить свой словарный запас в первую очередь",
        transcription: "ʃi wɒnts tʊ ɪmˈpruːv hə vəʊˈkæbjʊləri fɜːst əv ɔːl",
        translation: "She wants to improve her vocabulary first of all",
      },
      {
        id: 57,
        expression: "Ей очень нравится бегать трусцой",
        transcription: "ʃi ˈrɪəli laɪks tə gəʊ ˈʤɒgɪŋ",
        translation: "She really likes to go jogging",
      },
      {
        id: 58,
        expression: "Я работаю менеджером",
        transcription: "aɪ wɜːk əz ə ˈmænɪʤə",
        translation: "I work as a manager",
      },
      {
        id: 59,
        expression: "Я вижу, ты часто ездишь за границу",
        transcription: "aɪ siː jʊ ˈɒf(ə)n gəʊ əˈbrɔːd",
        translation: "I see you often go abroad",
      },
      {
        id: 60,
        expression: "Я хочу поехать в Соединенные Штаты в следующем году",
        transcription: "aɪ wɒnt tə gəʊ tə ðə jʊˈnaɪtɪd steɪts nɛkst jɪə",
        translation: "I want to go to the United States next year",
      },
      {
        id: 61,
        expression: "Он работает учителем",
        transcription: "hi wɜːks əz ə ˈtiːʧə",
        translation: "He works as a teacher",
      },
      {
        id: 62,
        expression: "Она обожает плавать",
        transcription: "ʃi ɪnˈʤɔɪz ˈswɪmɪŋ",
        translation: "She enjoys swimming",
      },
      {
        id: 63,
        expression: "Я люблю бегать трусцой",
        transcription: "aɪ laɪk ˈʤɒgɪŋ",
        translation: "I like jogging",
      },
      {
        id: 64,
        expression: "Я действительно обожаю плавать",
        transcription: "aɪ ˈrɪəli laɪk ˈswɪmɪŋ",
        translation: "I really like swimming",
      },
      {
        id: 65,
        expression: "Он говорит по-английски без акцента",
        transcription: "hi spiːks ˈɪŋglɪʃ wɪˈðaʊt ən ˈæksənt",
        translation: "He speaks English without an accent",
      },
      {
        id: 66,
        expression: "Я говорю по-немецки без акцента",
        transcription: "aɪ spiːk ˈʤɜːmən wɪˈðaʊt ən ˈæksənt",
        translation: "I speak German without an accent",
      },
      {
        id: 67,
        expression: "Она говорит по-русски с акцентом",
        transcription: "ʃi spiːks ˈrʌʃ(ə)n wɪð ən ˈæksənt",
        translation: "She speaks Russian with an accent",
      },
      {
        id: 68,
        expression: "Мне кажется, это действительно стоит много",
        transcription: "ɪt siːmz tə mi ɪt ˈrɪəli kɒsts ə lɒt",
        translation: "It seems to me it really costs a lot",
      },
      {
        id: 69,
        expression: "Ей кажется, это действительно стоит много",
        transcription: "ɪt siːmz tə hər ɪt ˈrɪəli kɒsts ə lɒt",
        translation: "It seems to her it really costs a lot",
      },
      {
        id: 70,
        expression: "Мне кажется, что это действительно стоит много",
        transcription: "ɪt siːmz tə mi ðət ɪt ˈrɪəli kɒsts ə lɒt",
        translation: "It seems to me that it really costs a lot",
      },
      {
        id: 71,
        expression: "Она понимает носителей языка лишь немного",
        transcription: "ʃi ˌʌndəˈstændz ˈneɪtɪv ˈspiːkəz ˈəʊnli ə ˈlɪtl",
        translation: "She understands native speakers only a little",
      },
      {
        id: 72,
        expression: "Он понимает носителей языка лишь немного",
        transcription: "hi ˌʌndəˈstændz ˈneɪtɪv ˈspiːkəz ˈəʊnli ə ˈlɪtl",
        translation: "He understands native speakers only a little",
      },
      {
        id: 73,
        expression: "Они понимают носителей языка лишь немного",
        transcription: "ðeɪ ˌʌndəˈstænd ˈneɪtɪv ˈspiːkəz ˈəʊnli ə ˈlɪtl",
        translation: "They understand native speakers only a little",
      },
      {
        id: 74,
        expression: "Мне нужен некоторый опыт работы в первую очередь",
        transcription: "aɪ niːd səm wɜːk ɪksˈpɪərɪəns fɜːst əv ɔːl",
        translation: "I need some work experience first of all",
      },
      {
        id: 75,
        expression: "Ей нужен некоторый опыт работы в первую очередь",
        transcription: "ʃi niːdz səm wɜːk ɪksˈpɪərɪəns fɜːst əv ɔːl",
        translation: "She needs some work experience first of all",
      },
      {
        id: 76,
        expression: "Тебе нужен некоторый опыт работы в первую очередь",
        transcription: "jʊ niːd səm wɜːk ɪksˈpɪərɪəns fɜːst əv ɔːl",
        translation: "You need some work experience first of all",
      },
      {
        id: 77,
        expression: "Он работает секретарем",
        transcription: "hi wɜːks əz ə ˈsɛkrətri",
        translation: "He works as a secretary",
      },
      {
        id: 78,
        expression: "Я работаю учителем",
        transcription: "aɪ wɜːks əz ə ˈtiːʧə",
        translation: "I works as a teacher",
      },
      {
        id: 79,
        expression: "Она работает менеджером",
        transcription: "ʃi wɜːks əz ə ˈmænɪʤə",
        translation: "She works as a manager",
      },
      {
        id: 80,
        expression: "Я вижу, у тебя есть идея",
        transcription: "aɪ siː jʊ həv ən aɪˈdɪə",
        translation: "I see you have an idea",
      },
      {
        id: 81,
        expression: "Я вижу, у нее есть идея",
        transcription: "aɪ siː ʃi həz ən aɪˈdɪə",
        translation: "I see she has an idea",
      },
      {
        id: 82,
        expression: "Я вижу, у них есть идея",
        transcription: "aɪ siː ðeɪ həv ən aɪˈdɪə",
        translation: "I see they have an idea",
      },
      {
        id: 83,
        expression: "Я думаю, что это звучит великолепно",
        transcription: "aɪ θɪŋk ðət ɪt saʊndz greɪt",
        translation: "I think that it sounds great",
      },
      {
        id: 84,
        expression: "Она думает, что это звучит великолепно",
        transcription: "ʃi θɪŋks ðət ɪt saʊndz greɪt",
        translation: "She thinks that it sounds great",
      },
      {
        id: 85,
        expression: "Я думаю, что это выглядит великолепно",
        transcription: "aɪ θɪŋk ðət ɪt lʊks greɪt",
        translation: "I think that it looks great",
      },
      {
        id: 86,
        expression: "Он много путешествует",
        transcription: "hi ˈtrævlz ə lɒt",
        translation: "He travels a lot",
      },
      {
        id: 87,
        expression: "Она много путешествует",
        transcription: "ʃi ˈtrævlz ə lɒt",
        translation: "She travels a lot",
      },
      {
        id: 88,
        expression: "Я много путешествую",
        transcription: "aɪ ˈtrævl ə lɒt",
        translation: "I travel a lot",
      },
      {
        id: 89,
        expression: "Это случается время от времени",
        transcription: "ɪt ˈhæpənz frəm taɪm tə taɪm",
        translation: "It happens from time to time",
      },
      {
        id: 90,
        expression: "Эта вещь случается время от времени",
        transcription: "ðɪs θɪŋ ˈhæpənz frəm taɪm tə taɪm",
        translation: "This thing happens from time to time",
      },
      {
        id: 91,
        expression: "Это иногда случается",
        transcription: "ɪt ˈsʌmtaɪmz ˈhæpənz",
        translation: "It sometimes happens",
      },
      {
        id: 92,
        expression: "Он ходит в бассейн",
        transcription: "hi gəʊz tə ðə ˈswɪmɪŋ puːl",
        translation: "He goes to the swimming pool",
      },
      {
        id: 93,
        expression: "Я вижу, что она говорит по-английски без акцента",
        transcription: "aɪ siː ðət ʃi spiːks ˈɪŋglɪʃ wɪˈðaʊt ən ˈæksənt",
        translation: "I see that she speaks English without an accent",
      },
      {
        id: 94,
        expression: "Я действительно хочу говорить по-английски как носитель",
        transcription: "aɪ ˈrɪəli wɒnt tə spiːk ˈɪŋglɪʃ əz ə ˈneɪtɪv",
        translation: "I really want to speak English as a native speaker",
      },
      {
        id: 95,
        expression: "Она работает в другом отделе",
        transcription: "ʃi wɜːks ɪn əˈnʌðə dɪˈpɑːtmənt",
        translation: "She works in another department",
      },
      {
        id: 96,
        expression: "Ей очень нравится классическая музыка",
        transcription: "ʃi ˈrɪəli laɪks ˈklæsɪkəl ˈmjuːzɪk",
        translation: "She really likes classical music",
      },
      {
        id: 97,
        expression: "Я вижу, ему действительно нравится эта идея",
        transcription: "aɪ siː hi ˈrɪəli laɪks ðɪs aɪˈdɪə",
        translation: "I see he really likes this idea",
      },
      {
        id: 98,
        expression: "Я занимаюсь плаванием дважды в неделю",
        transcription: "aɪ gəʊ ˈswɪmɪŋ twaɪs ə wiːk",
        translation: "I go swimming twice a week",
      },
      {
        id: 99,
        expression: "Она работала продавцом магазина",
        transcription: "ʃi wɜːkt əz ə ʃɒp əˈsɪstənt",
        translation: "She worked as a shop assistant",
      },
      {
        id: 100,
        expression: "Он часто летает в Англию",
        transcription: "hi ˈɒf(ə)n flaɪz tʊ ˈɪŋglənd",
        translation: "He often flies to England",
      },
      {
        id: 101,
        expression:
          "Я только немного понимаю носителей языка, но я работаю над этим",
        transcription:
          "aɪ ˌʌndəˈstænd ˈneɪtɪv ˈspiːkəz ˈəʊnli ə lɒt bət aɪ wɜːk ɒn ɪt",
        translation: "I understand native speakers only a lot but I work on it",
      },
      {
        id: 102,
        expression: "Я хочу улучшить свою грамматику",
        transcription: "aɪ wɒnt tʊ ɪmˈpruːv maɪ ˈgræmə",
        translation: "I want to improve my grammar",
      },
      {
        id: 103,
        expression: "Я занимаюсь плаванием два или три раза в неделю",
        transcription: "aɪ gəʊ ˈswɪmɪŋ tuː ɔː θriː taɪmz ə wiːk",
        translation: "I go swimming two or three times a week",
      },
      {
        id: 104,
        expression: "Она часто летает в Соединенные Штаты",
        transcription: "ʃi ˈɒf(ə)n flaɪz tə ðə jʊˈnaɪtɪd steɪts",
        translation: "She often flies to the United States",
      },
      {
        id: 105,
        expression: "Она прекрасно понимает нашу точку зрения",
        transcription: "ʃi ˈpɜːfɪktli ˌʌndəˈstændz ˈaʊə pɔɪnt əv vjuː",
        translation: "She perfectly understands our point of view",
      },
      {
        id: 106,
        expression: "Он часто бегает трусцой",
        transcription: "hi ˈɒf(ə)n gəʊz ˈʤɒgɪŋ",
        translation: "He often goes jogging",
      },
    ],
    {
      theory: `<div class="theory-block">
<p>Что ж, на данный момент уровень владения вами английским языком уже такой, что в англоязычной стране вы точно не умрете от полной дезориентации.</p>
<p>Вспомним еще кое-что из пройденного материала и будем двигаться дальше.</p>
<h3>like</h3>
<p>- нравится</p>
<p>После глагола like следующий глагол может ставиться как с окончанием ing, что встречается чаще, так и в инфинитиве</p>
<p>She likes eating out / She likes to eat out- Ей нравится питаться вне дома</p>
<h3>enjoy</h3>
<p>- обожать</p>
<p>То же самое после глагола enjoy: I enjoy drinking coffee in the morning / I enjoy to drink coffee in the mornings- Я обожаю пить кофе по утрам</p>
</div>`,
    },
  ],
];
