export const contentLesson67 = [
  [
    {
      title:
        "Урок 67. Present Simple: сложные подлежащие + глагол to be: Question",
    },
    [
      {
        id: 1,
        expression: "Твоя сестра школьница?",
        transcription: "ɪz jə ˈsɪstər ə ˈskuːlgɜːl?",
        translation: "Is your sister a schoolgirl?",
      },
      {
        id: 2,
        expression: "Дети дома?",
        transcription: "ɑː ðə ˈʧɪldrən (kɪdz) ət həʊm?",
        translation: "Are the children (kids) at home?",
      },
      {
        id: 3,
        expression: "Эта вещь действительно важна для тебя?",
        transcription: "ɪz ðɪs θɪŋ ˈrɪəli ɪmˈpɔːtənt fə juː?",
        translation: "Is this thing really important for you?",
      },
      {
        id: 4,
        expression: "Эти два мальчика в одной и той же группе?",
        transcription: "ɑː ðiːz tuː bɔɪz ɪn ðə seɪm gruːp?",
        translation: "Are these two boys in the same group?",
      },
      {
        id: 5,
        expression: "Билеты слишком дорогие?",
        transcription: "ɑː ðə ˈtɪkɪts tuː ɪksˈpɛnsɪv?",
        translation: "Are the tickets too expensive?",
      },
      {
        id: 6,
        expression: "Этой информации более чем достаточно?",
        transcription: "ɪz ðɪs ˌɪnfəˈmeɪʃən mɔː ðən ɪˈnʌf?",
        translation: "Is this information more than enough?",
      },
      {
        id: 7,
        expression: "История - твой любимый предмет?",
        transcription: "ɪz ˈhɪstəri jə ˈfeɪvərɪt ˈsʌbʤɪkt?",
        translation: "Is history your favourite subject?",
      },
      {
        id: 8,
        expression: "Твой брат школьник?",
        transcription: "ɪz jə ˈbrʌðər ə ˈskuːlbɔɪ?",
        translation: "Is your brother a schoolboy?",
      },
      {
        id: 9,
        expression: "Твои родственники очень далеко?",
        transcription: "ɑː jə ˈrɛlətɪvz ˈvɛri fɑː?",
        translation: "Are your relatives very far?",
      },
      {
        id: 10,
        expression: "Фильм очень скучный?",
        transcription: "ɪz ðə ˈmuːvi ˈvɛri ˈbɔːrɪŋ?",
        translation: "Is the movie very boring?",
      },
      {
        id: 11,
        expression: "Цена очень низкая?",
        transcription: "ɪz ðə praɪs ˈvɛri ləʊ?",
        translation: "Is the price very low?",
      },
      {
        id: 12,
        expression: "Тот проект успешный?",
        transcription: "ɪz ðət ˈprɒʤɛkt səkˈsɛsfʊl?",
        translation: "Is that project successful?",
      },
      {
        id: 13,
        expression: "Эта помощь важна для тебя?",
        transcription: "ɪz ðɪs hɛlp ɪmˈpɔːtənt fə juː?",
        translation: "Is this help important for you?",
      },
      {
        id: 14,
        expression: "Курс действительно эффективный?",
        transcription: "ɪz ðə kɔːs ˈrɪəli ɪˈfɛktɪv?",
        translation: "Is the course really effective?",
      },
      {
        id: 15,
        expression: "Проблема очень серьезная?",
        transcription: "ɪz ðə ˈprɒbləm ˈvɛri ˈsɪərɪəs?",
        translation: "Is the problem very serious?",
      },
      {
        id: 16,
        expression: "Это хороший знак для нас?",
        transcription: "ɪz ðɪs ə gʊd saɪn fər ʌs?",
        translation: "Is this a good sign for us?",
      },
      {
        id: 17,
        expression: "Тот мужчина болен?",
        transcription: "ɪz ðət mæn ɪl?",
        translation: "Is that man ill?",
      },
      {
        id: 18,
        expression: "Твоя сестра школьница?",
        transcription: "ɪz jə ˈsɪstər ə ˈskuːlgɜːl?",
        translation: "Is your sister a schoolgirl?",
      },
      {
        id: 19,
        expression: "Этот ребенок очень талантливый?",
        transcription: "ɪz ðɪs ʧaɪld (kɪd) ˈvɛri ˈtæləntɪd?",
        translation: "Is this child (kid) very talented?",
      },
      {
        id: 20,
        expression: "Этот путь довольно короткий?",
        transcription: "ɪz ðɪs weɪ kwaɪt ʃɔːt?",
        translation: "Is this way quite short?",
      },
      {
        id: 21,
        expression: "Та песня очень красивая?",
        transcription: "ɪz ðət sɒŋ ˈvɛri ˈbjuːtəfʊl?",
        translation: "Is that song very beautiful?",
      },
      {
        id: 22,
        expression: "Это дорожный знак?",
        transcription: "ɪz ɪt ə rəʊd saɪn?",
        translation: "Is it a road sign?",
      },
      {
        id: 23,
        expression: "Это место очень далеко?",
        transcription: "ɪz ðɪs pleɪs ˈvɛri fɑː?",
        translation: "Is this place very far?",
      },
      {
        id: 24,
        expression: "Твой компьютер новый?",
        transcription: "ɪz jə kəmˈpjuːtə njuː?",
        translation: "Is your computer new?",
      },
      {
        id: 25,
        expression: "История очень интересная?",
        transcription: "ɪz ðə ˈstɔːri ˈvɛri ˈɪntrɪstɪŋ?",
        translation: "Is the story very interesting?",
      },
      {
        id: 26,
        expression: "Книга интересная?",
        transcription: "ɪz ðə bʊk ˈɪntrɪstɪŋ?",
        translation: "Is the book interesting?",
      },
      {
        id: 27,
        expression: "Твой начальник против этого решения?",
        transcription: "ɪz jə bɒs əˈgɛnst ðɪs dɪˈsɪʒən?",
        translation: "Is your boss against this decision?",
      },
      {
        id: 28,
        expression: "Этот уровень действительно высокий?",
        transcription: "ɪz ðɪs ˈlɛvl ˈrɪəli haɪ?",
        translation: "Is this level really high?",
      },
      {
        id: 29,
        expression: "Компьютер старый?",
        transcription: "ɪz ðə kəmˈpjuːtər əʊld?",
        translation: "Is the computer old?",
      },
      {
        id: 30,
        expression: "Уроки бесплатные?",
        transcription: "ɑː ðə ˈlɛsnz friː?",
        translation: "Are the lessons free?",
      },
      {
        id: 31,
        expression: "Твои родители счастливы?",
        transcription: "ɑː jə ˈpeərənts ˈhæpi?",
        translation: "Are your parents happy?",
      },
      {
        id: 32,
        expression: "Учитель прав?",
        transcription: "ɪz ðə ˈtiːʧə raɪt?",
        translation: "Is the teacher right?",
      },
      {
        id: 33,
        expression: "Здание очень высокое?",
        transcription: "ɪz ðə ˈbɪldɪŋ ˈvɛri haɪ?",
        translation: "Is the building very high?",
      },
      {
        id: 34,
        expression: "Эта вещь действительно неважная?",
        transcription: "ɪz ðɪs θɪŋ ˈrɪəli ˌʌnɪmˈpɒtənt?",
        translation: "Is this thing really unimportant?",
      },
      {
        id: 35,
        expression: "Школа хорошая?",
        transcription: "ɪz ðə skuːl gʊd?",
        translation: "Is the school good?",
      },
      {
        id: 36,
        expression: "Отель слишком дорогой?",
        transcription: "ɪz ðə həʊˈtɛl tuː ɪksˈpɛnsɪv?",
        translation: "Is the hotel too expensive?",
      },
      {
        id: 37,
        expression: "Цена очень высокая?",
        transcription: "ɪz ðə praɪs ˈvɛri haɪ?",
        translation: "Is the price very high?",
      },
      {
        id: 38,
        expression: "Урок бесплатный?",
        transcription: "ɪz ðə ˈlɛsn friː?",
        translation: "Is the lesson free?",
      },
      {
        id: 39,
        expression: "Эта машина надежная?",
        transcription: "ɪz ðɪs kɑː rɪˈlaɪəbl?",
        translation: "Is this car reliable?",
      },
      {
        id: 40,
        expression: "Мальчики в этой группе действительно ленивые?",
        transcription: "ɑː ðə bɔɪz ɪn ðɪs gruːp ˈrɪəli ˈleɪzi?",
        translation: "Are the boys in this group really lazy?",
      },
      {
        id: 41,
        expression: "Этот метод действительно эффективный?",
        transcription: "ɪz ðɪs ˈmɛθəd ˈrɪəli ɪˈfɛktɪv?",
        translation: "Is this method really effective?",
      },
      {
        id: 42,
        expression: "Дверь открыта?",
        transcription: "ɪz ðə dɔːr ˈəʊpən?",
        translation: "Is the door open?",
      },
      {
        id: 43,
        expression: "Эти изменения очень неожиданные для них?",
        transcription: "ɑː ðiːz ˈʧeɪnʤɪz ˈvɛri ˌʌnɪksˈpɛktɪd fə ðɛm?",
        translation: "Are these changes very unexpected for them?",
      },
      {
        id: 44,
        expression: "Дом просторный для твоей семьи?",
        transcription: "ɪz ðə haʊs ˈspeɪʃəs fə jə ˈfæmɪli?",
        translation: "Is the house spacious for your family?",
      },
      {
        id: 45,
        expression: "Образование бесплатное в твоей стране?",
        transcription: "ɪz ˌɛdju(ː)ˈkeɪʃən friː ɪn jə ˈkʌntri?",
        translation: "Is education free in your country?",
      },
      {
        id: 46,
        expression: "Этих денег действительно достаточно?",
        transcription: "ɪz ðɪs ˈmʌni ˈrɪəli ɪˈnʌf?",
        translation: "Is this money really enough?",
      },
      {
        id: 47,
        expression: "Эти оценки очень хороши для вас?",
        transcription: "ɑː ðiːz mɑːks (greɪdz) ˈvɛri gʊd fə juː?",
        translation: "Are these marks (grades) very good for you?",
      },
      {
        id: 48,
        expression: "Те люди также заинтересованы в этом?",
        transcription: "ɑː ðəʊz ˈpiːpl ˈɔːlsəʊ ˈɪntrɪstɪd ɪn ɪt?",
        translation: "Are those people also interested in it?",
      },
      {
        id: 49,
        expression: "Эти новости очень удивительны для тебя?",
        transcription: "ɪz ðɪs njuːz ˈvɛri səˈpraɪzɪŋ fə juː?",
        translation: "Is this news very surprising for you?",
      },
      {
        id: 50,
        expression: "Та область переполнена туристами?",
        transcription: "ɪz ðət ˈeərɪə ˌəʊvəˈkraʊdɪd wɪð ˈtʊərɪsts?",
        translation: "Is that area overcrowded with tourists?",
      },
      {
        id: 51,
        expression: "Этого опыта достаточно?",
        transcription: "ɪz ðɪs ɪksˈpɪərɪəns ɪˈnʌf?",
        translation: "Is this experience enough?",
      },
      {
        id: 52,
        expression: "Второй урок тоже бесплатный?",
        transcription: "ɪz ðə ˈsɛkənd ˈlɛsn ˈɔːlsəʊ friː?",
        translation: "Is the second lesson also free?",
      },
      {
        id: 53,
        expression: "Эта оценка довольно высокая для тебя?",
        transcription: "ɪz ðɪs mɑːk kwaɪt haɪ fə juː?",
        translation: "Is this mark quite high for you?",
      },
      {
        id: 54,
        expression: "Полицейский в этом районе?",
        transcription: "ɪz ðə pəˈliːsmən ɪn ðɪs ˈdɪstrɪkt?",
        translation: "Is the policeman in this district?",
      },
      {
        id: 55,
        expression: "Эти оценки очень высокие для него?",
        transcription: "ɑː ðiːz mɑːks ˈvɛri haɪ fə hɪm?",
        translation: "Are these marks very high for him?",
      },
      {
        id: 56,
        expression: "Эта машина достаточно надежная?",
        transcription: "ɪz ðɪs kɑː rɪˈlaɪəbl ɪˈnʌf?",
        translation: "Is this car reliable enough?",
      },
      {
        id: 57,
        expression: "Его голос очень мелодичный?",
        transcription: "ɪz ɪz vɔɪs ˈvɛri mɪˈlɒdɪk?",
        translation: "Is his voice very melodic?",
      },
      {
        id: 58,
        expression: "Его родители в отъезде сейчас?",
        transcription: "ɑː hɪz ˈpeərənts əˈweɪ naʊ?",
        translation: "Are his parents away now?",
      },
      {
        id: 59,
        expression: "Твои родители дома сейчас?",
        transcription: "ɑː jə ˈpeərənts ət həʊm naʊ?",
        translation: "Are your parents at home now?",
      },
      {
        id: 60,
        expression: "Твои родители в отъезде?",
        transcription: "ɑː jə ˈpeərənts əˈweɪ?",
        translation: "Are your parents away?",
      },
      {
        id: 61,
        expression: "Этот город переполнен туристами?",
        transcription: "ɪz ðɪs ˈsɪti ˌəʊvəˈkraʊdɪd wɪð ˈtʊərɪsts?",
        translation: "Is this city overcrowded with tourists?",
      },
      {
        id: 62,
        expression: "Эта область переполнена туристами?",
        transcription: "ɪz ðɪs ˈeərɪə ˌəʊvəˈkraʊdɪd wɪð ˈtʊərɪsts?",
        translation: "Is this area overcrowded with tourists?",
      },
      {
        id: 63,
        expression: "Это здание переполнено людьми?",
        transcription: "ɪz ðɪs ˈbɪldɪŋ ˌəʊvəˈkraʊdɪd wɪð ˈpiːpl?",
        translation: "Is this building overcrowded with people?",
      },
      {
        id: 64,
        expression: "Это место часто переполнено?",
        transcription: "ɪz ðɪs pleɪs ˈɒf(ə)n ˌəʊvəˈkraʊdɪd?",
        translation: "Is this place often overcrowded?",
      },
      {
        id: 65,
        expression: "Это место обычно переполнено?",
        transcription: "ɪz ðɪs pleɪs ˈjuːʒʊəli ˌəʊvəˈkraʊdɪd?",
        translation: "Is this place usually overcrowded?",
      },
      {
        id: 66,
        expression: "То место часто переполнено?",
        transcription: "ɪz ðət pleɪs ˈɒf(ə)n ˌəʊvəˈkraʊdɪd?",
        translation: "Is that place often overcrowded?",
      },
      {
        id: 67,
        expression: "Полицейский в этом районе?",
        transcription: "ɪz ðə pəˈliːsmən ɪn ðɪs ˈdɪstrɪkt?",
        translation: "Is the policeman in this district?",
      },
      {
        id: 68,
        expression: "Полицейские в том районе?",
        transcription: "ɑː ðə pəˈliːsmən ɪn ðət ˈdɪstrɪkt?",
        translation: "Are the policemen in that district?",
      },
      {
        id: 69,
        expression: "Это членство бесплатное?",
        transcription: "ɪz ðɪs ˈmɛmbəʃɪp friː?",
        translation: "Is this membership free?",
      },
      {
        id: 70,
        expression: "Членство очень дорогое?",
        transcription: "ɪz ðə ˈmɛmbəʃɪp ˈvɛri ɪksˈpɛnsɪv?",
        translation: "Is the membership very expensive?",
      },
      {
        id: 71,
        expression: "То членство дорогое?",
        transcription: "ɪz ðət ˈmɛmbəʃɪp ɪksˈpɛnsɪv?",
        translation: "Is that membership expensive?",
      },
      {
        id: 72,
        expression: "Эти парни очень легкие в общении?",
        transcription: "ɑː ðiːz gaɪz ˈvɛri ˈiːzɪˌgəʊɪŋ?",
        translation: "Are these guys very easy-going?",
      },
      {
        id: 73,
        expression: "Этот парень очень легкий в общении?",
        transcription: "ɪz ðɪs gaɪ ˈvɛri ˈiːzɪˌgəʊɪŋ?",
        translation: "Is this guy very easy-going?",
      },
      {
        id: 74,
        expression: "Эти мужчины очень легкие в общении?",
        transcription: "ɑː ðiːz mɛn ˈvɛri ˈiːzɪˌgəʊɪŋ?",
        translation: "Are these men very easy-going?",
      },
      {
        id: 75,
        expression: "Первый урок бесплатный?",
        transcription: "ɪz ðə fɜːst ˈlɛsn friː?",
        translation: "Is the first lesson free?",
      },
      {
        id: 76,
        expression: "Этот урок бесплатный?",
        transcription: "ɪz ðɪs ˈlɛsn friː?",
        translation: "Is this lesson free?",
      },
      {
        id: 77,
        expression: "Второй урок интересный?",
        transcription: "ɪz ðə ˈsɛkənd ˈlɛsn ˈɪntrɪstɪŋ?",
        translation: "Is the second lesson interesting?",
      },
      {
        id: 78,
        expression: "Стоимость жизни выше сейчас?",
        transcription: "ɪz ðə kɒst əv ˈlɪvɪŋ ˈhaɪə naʊ?",
        translation: "Is the cost of living higher now?",
      },
      {
        id: 79,
        expression: "Стоимость жизни выше в наши дни?",
        transcription: "ɪz ðə kɒst əv ˈlɪvɪŋ ˈhaɪə ˈnaʊədeɪz?",
        translation: "Is the cost of living higher nowadays?",
      },
      {
        id: 80,
        expression: "Стоимость жизни ниже сейчас?",
        transcription: "ɪz ðə kɒst əv ˈlɪvɪŋ ˈləʊə naʊ?",
        translation: "Is the cost of living lower now?",
      },
      {
        id: 81,
        expression: "Полиция рядом?",
        transcription: "ɑː ðə pəˈliːs nɪə?",
        translation: "Are the police near?",
      },
      {
        id: 82,
        expression: "Полиция там?",
        transcription: "ɑː ðə pəˈliːs ðeə?",
        translation: "Are the police there?",
      },
      {
        id: 83,
        expression: "Еда испорчена?",
        transcription: "ɪz ðə fuːd spɔɪlt?",
        translation: "Is the food spoilt?",
      },
      {
        id: 84,
        expression: "Твоя еда испорчена?",
        transcription: "ɪz jə fuːd spɔɪlt?",
        translation: "Is your food spoilt?",
      },
      {
        id: 85,
        expression: "Та еда испорчена?",
        transcription: "ɪz ðət fuːd spɔɪlt?",
        translation: "Is that food spoilt?",
      },
      {
        id: 86,
        expression: "Те новости такие неожиданные для тебя?",
        transcription: "ɪz ðət njuːz səʊ ˌʌnɪksˈpɛktɪd fə juː?",
        translation: "Is that news so unexpected for you?",
      },
      {
        id: 87,
        expression: "Дети внутри?",
        transcription: "ɑː ðə ˈʧɪldrən ɪnˈsaɪd?",
        translation: "Are the children inside?",
      },
      {
        id: 88,
        expression: "Твой отец отсутствует?",
        transcription: "ɪz jə ˈfɑːðər ˈæbsənt (aʊt)?",
        translation: "Is your father absent (out)?",
      },
      {
        id: 89,
        expression: "Дом достаточно просторный?",
        transcription: "ɪz ðə haʊs ˈspeɪʃəs ɪˈnʌf?",
        translation: "Is the house spacious enough?",
      },
      {
        id: 90,
        expression: "Полиция в том месте?",
        transcription: "ɑː ðə pəˈliːs ɪn ðət pleɪs?",
        translation: "Are the police in that place?",
      },
      {
        id: 91,
        expression: "Стоимость жизни в наши дни намного выше?",
        transcription: "ɪz ðə kɒst əv ˈlɪvɪŋ mʌʧ ˈhaɪə ˈnaʊədeɪz?",
        translation: "Is the cost of living much higher nowadays?",
      },
      {
        id: 92,
        expression: "Цена слишком высокая?",
        transcription: "ɪz ðə praɪs tuː haɪ?",
        translation: "Is the price too high?",
      },
      {
        id: 93,
        expression: "Дети снаружи?",
        transcription: "ɑː ðə ˈʧɪldrən ˌaʊtˈsaɪd?",
        translation: "Are the children outside?",
      },
      {
        id: 94,
        expression: "Этих навыков достаточно для той работы?",
        transcription: "ɑː ðiːz skɪlz ɪˈnʌf fə ðət ʤɒb?",
        translation: "Are these skills enough for that job?",
      },
      {
        id: 95,
        expression: "Эта оценка очень низкая?",
        transcription: "ɪz ðɪs mɑːk ˈvɛri ləʊ?",
        translation: "Is this mark very low?",
      },
      {
        id: 96,
        expression: "Это членство совершенно бесплатно?",
        transcription: "ɪz ðɪs ˈmɛmbəʃɪp ˈæbsəluːtli friː?",
        translation: "Is this membership absolutely free?",
      },
      {
        id: 97,
        expression: "Этот человек также заинтересован в этом?",
        transcription: "ɪz ðɪs ˈpɜːsn ˈɔːlsəʊ ˈɪntrɪstɪd ɪn ɪt?",
        translation: "Is this person also interested in it?",
      },
      {
        id: 98,
        expression: "Квартира достаточно просторная для тебя?",
        transcription: "ɪz ði əˈpɑːtmənt ˈspeɪʃəs ɪˈnʌf fə juː?",
        translation: "Is the apartment spacious enough for you?",
      },
    ],
    {
      theory: `<div class="theory-block">
<h3>Закрепление пройденного материала</h3>
</div>`,
    },
  ],
];
