export const contentLesson158 = [
  [
    {
      title:
        'Урок 158. Comparison of Tenses. Present Simple + Present Continuous',
    },
    [
      {
        id: 1,
        expression: 'Я не думаю об этом в настоящее время',
        transcription: 'aɪm nɒt ˈθɪŋkɪŋ əˈbaʊt ɪt æt ˈprɛznt',
        translation: "I'm not thinking about it at present",
      },
      {
        id: 2,
        expression: 'Дети обычно спят на первом этаже',
        transcription: 'ðə ˈʧɪldrən ˈjuːʒʊəli sliːp ɒn ðə fɜːst flɔː',
        translation: 'The children usually sleep on the first floor',
      },
      {
        id: 3,
        expression: 'Какая длина пути?',
        transcription: 'wɒts ðə lɛŋθ ɒv ðə weɪ? / haʊ lɒŋ ɪz ðə weɪ?',
        translation: "What's the length of the way? / How long is the way?",
      },
      {
        id: 4,
        expression: 'Мой английский становится лучше и лучше',
        transcription: 'maɪ ˈɪŋglɪʃ ɪz ˈgɛtɪŋ ˈbɛtər ænd ˈbɛtə',
        translation: 'My English is getting better and better',
      },
      {
        id: 5,
        expression: 'Послушай! Музыка играет очень громко',
        transcription: 'ˈlɪsn! ðə ˈmjuːzɪk ɪz ˈpleɪɪŋ ˈvɛri ˈlaʊdli',
        translation: 'Listen! The music is playing very loudly',
      },
      {
        id: 6,
        expression: 'Я часто думаю об этом',
        transcription: 'aɪ ˈɒf(ə)n θɪŋk əˈbaʊt ɪt',
        translation: 'I often think about it',
      },
      {
        id: 7,
        expression: 'Ничего из этих вещей не интересует его',
        transcription: 'nʌn ɒv ðiːz θɪŋz ˈɪntrɪsts hɪm',
        translation: 'None of these things interests him',
      },
      {
        id: 8,
        expression: 'Что делает Кейт?',
        transcription: 'wɒt ɪz keɪt ˈdu(ː)ɪŋ?',
        translation: 'What is Kate doing?',
      },
      {
        id: 9,
        expression: 'Насколько эффективен этот метод?',
        transcription: 'haʊ ɪˈfɛktɪv ɪz ðɪs ˈmɛθəd?',
        translation: 'How effective is this method?',
      },
      {
        id: 10,
        expression: 'Он никогда не ходит в это место',
        transcription: 'hiː ˈnɛvə gəʊz tuː ðɪs pleɪs',
        translation: 'He never goes to this place',
      },
      {
        id: 11,
        expression: 'Каждый из нас хочет сделать то же самое',
        transcription: 'iːʧ ɒv ʌs wɒnts tuː duː ðə seɪm',
        translation: 'Each of us wants to do the same',
      },
      {
        id: 12,
        expression: 'Все в порядке',
        transcription: 'ˈɛvrɪθɪŋ ɪz ɔːlˈraɪt',
        translation: 'Everything is alright',
      },
      {
        id: 13,
        expression: 'Насколько длинное это расстояние?',
        transcription: 'haʊ lɒŋ ɪz ðɪs ˈdɪstəns?',
        translation: 'How long is this distance?',
      },
      {
        id: 14,
        expression: 'Что говорит Алекс?',
        transcription: 'wɒt ɪz ˈæləks ˈseɪɪŋ?',
        translation: 'What is Alex saying?',
      },
      {
        id: 15,
        expression: 'Никто не знает этого',
        transcription: 'nəʊ wʌn nəʊz ɪt',
        translation: 'No one knows it',
      },
      {
        id: 16,
        expression: 'Все это понимают сейчас',
        transcription: 'ˈɛvrɪwʌn ˌʌndəˈstændz ɪt naʊ',
        translation: 'Everyone understands it now',
      },
      {
        id: 17,
        expression: 'Этого сейчас никто не понимает',
        transcription: 'nəʊ wʌn ˌʌndəˈstændz ɪt naʊ',
        translation: 'No one understands it now',
      },
      {
        id: 18,
        expression: 'Мне это никогда не помогает',
        transcription: 'ɪt ˈnɛvə hɛlps miː',
        translation: 'It never helps me',
      },
      {
        id: 19,
        expression: 'Кто-то здесь есть',
        transcription: 'ˈsʌmwʌn (ˈsʌmbədi) ɪz hɪə',
        translation: 'Someone (somebody) is here',
      },
      {
        id: 20,
        expression: 'Все это понимают',
        transcription: 'ˈɛvrɪwʌn ˌʌndəˈstændz ɪt',
        translation: 'Everyone understands it',
      },
      {
        id: 21,
        expression: 'Никому из нас это не нравится',
        transcription: 'nʌn ɒv ʌs laɪks ɪt',
        translation: 'None of us likes it',
      },
      {
        id: 22,
        expression: 'Идет дождь',
        transcription: 'ɪts ˈreɪnɪŋ',
        translation: "It's raining",
      },
      {
        id: 23,
        expression: 'Я стараюсь делать это на регулярной основе',
        transcription: 'aɪ traɪ tuː duː ɪt ɒn ə ˈrɛgjʊlə ˈbeɪsɪs',
        translation: 'I try to do it on a regular basis',
      },
      {
        id: 24,
        expression: 'Какая длина комнаты?',
        transcription: 'wɒts ðə lɛŋθ ɒv ðə ruːm?',
        translation: "What's the length of the room?",
      },
      {
        id: 25,
        expression: 'Кажется, все в порядке',
        transcription: 'ˈɛvrɪθɪŋ siːmz ɔːlˈraɪt',
        translation: 'Everything seems alright',
      },
      {
        id: 26,
        expression: 'Идет снег',
        transcription: 'ɪts ˈsnəʊɪŋ',
        translation: "It's snowing",
      },
      {
        id: 27,
        expression: 'Малыш плачет',
        transcription: 'ðə ˈbeɪbi ɪz ˈkraɪɪŋ',
        translation: 'The baby is crying',
      },
      {
        id: 28,
        expression: 'Он делает физические упражнения довольно регулярно',
        transcription: 'hiː dʌz ˈfɪzɪkəl ˈɛksəsaɪzɪz kwaɪt ˈrɛgjʊləli',
        translation: 'He does physical exercises quite regularly',
      },
      {
        id: 29,
        expression: 'Он любит блины',
        transcription: 'hiː laɪks ˈpænkeɪks',
        translation: 'He likes pancakes',
      },
      {
        id: 30,
        expression: 'Малыш часто плачет',
        transcription: 'ðə ˈbeɪbi ˈɒf(ə)n kraɪz',
        translation: 'The baby often cries',
      },
      {
        id: 31,
        expression: 'Каждый из нас прекрасно понимает это сейчас',
        transcription: 'iːʧ ɒv ʌs ˈpɜːfɪktli ˌʌndəˈstændz ɪt naʊ',
        translation: 'Each of us perfectly understands it now',
      },
      {
        id: 32,
        expression: 'Они сейчас едут домой',
        transcription: 'ðeə ˈgəʊɪŋ həʊm naʊ',
        translation: "They're going home now",
      },
      {
        id: 33,
        expression: 'Все кажется очень странным сейчас',
        transcription: 'ˈɛvrɪθɪŋ siːmz ˈvɛri streɪnʤ naʊ',
        translation: 'Everything seems very strange now',
      },
      {
        id: 34,
        expression: 'Никому из них не нравится эта идея сейчас',
        transcription: 'nʌn ɒv ðɛm laɪks ðɪs aɪˈdɪə naʊ',
        translation: 'None of them likes this idea now',
      },
      {
        id: 35,
        expression: 'Он пишет что-то на доске',
        transcription: 'hiːz ˈraɪtɪŋ ˈsʌmθɪŋ ɒn ðə ˈblækbɔːd',
        translation: "He's writing something on the blackboard",
      },
      {
        id: 36,
        expression: 'Никто из них действительно не понимает это сейчас',
        transcription: 'nʌn ɒv ðɛm ˈrɪəli ˌʌndəˈstændz ɪt naʊ',
        translation: 'None of them really understands it now',
      },
      {
        id: 37,
        expression: 'Что делает учитель?',
        transcription: 'wɒts ðə ˈtiːʧə ˈdu(ː)ɪŋ?',
        translation: "What's the teacher doing?",
      },
      {
        id: 38,
        expression: 'Кто-то звонит мне',
        transcription: 'ˈsʌmwʌn ɪz ˈkɔːlɪŋ miː',
        translation: 'Someone is calling me',
      },
      {
        id: 39,
        expression: 'Каждый из нас это осознает',
        transcription: 'iːʧ ɒv ʌs ˈrɪəlaɪzɪz ɪt',
        translation: 'Each of us realises it',
      },
      {
        id: 40,
        expression: 'Я сейчас пишу письмо своему коллеге',
        transcription: 'aɪm ˈraɪtɪŋ ə ˈlɛtə tuː maɪ ˈkɒliːg naʊ',
        translation: "I'm writing a letter to my colleague now",
      },
      {
        id: 41,
        expression:
          'Он постоянно жалуется на что-то совсем без всякой причины [с раздражением]',
        transcription:
          'hiːz ˈkɒnstəntli kəmˈpleɪnɪŋ əˈbaʊt ˈsʌmθɪŋ fɔː nəʊ ˈriːzn',
        translation:
          "He's constantly complaining about something for no reason",
      },
      {
        id: 42,
        expression: 'Мои коллеги и я работаем невероятно усердно в эти дни',
        transcription:
          'maɪ ˈkɒliːgz ænd aɪ ɑː ˈwɜːkɪŋ ɪnˈkrɛdəbli hɑːd ðiːz deɪz',
        translation:
          'My colleagues and I are working incredibly hard these days',
      },
      {
        id: 43,
        expression: 'Врач очень успешно проводит все свои операции',
        transcription:
          'ðə ˈdɒktə ˈkɒndʌkts ɔːl hɪz ˌɒpəˈreɪʃənz ˈvɛri səkˈsɛsfʊli',
        translation: 'The doctor conducts all his operations very successfully',
      },
      {
        id: 44,
        expression: 'О чем они говорят в данный момент?',
        transcription: 'wɒt ɑː ðeɪ ˈtɔːkɪŋ əˈbaʊt æt ðə ˈməʊmənt?',
        translation: 'What are they talking about at the moment?',
      },
      {
        id: 45,
        expression: 'Я полностью не согласен с таким утверждением',
        transcription: 'aɪ ˈtəʊtli ˌdɪsəˈgriː wɪð sʌʧ ə ˈsteɪtmənt',
        translation: 'I totally disagree with such a statement',
      },
      {
        id: 46,
        expression: 'Бензин становится все более и более дорогим',
        transcription: 'ðə ˈpɛtrəl ɪz ˈgɛtɪŋ mɔːr ænd mɔːr ɪksˈpɛnsɪv',
        translation: 'The petrol is getting more and more expensive',
      },
      {
        id: 47,
        expression: 'Я вижу, что твой английский становится все лучше и лучше',
        transcription: 'aɪ siː ðæt jɔːr ˈɪŋglɪʃ ɪz ˈgɛtɪŋ ˈbɛtər ænd ˈbɛtə',
        translation: 'I see that your English is getting better and better',
      },
      {
        id: 48,
        expression: 'Все становится все более и более дорогим',
        transcription: 'ˈɛvrɪθɪŋ ɪz ˈgɛtɪŋ mɔːr ænd mɔːr ɪksˈpɛnsɪv',
        translation: 'Everything is getting more and more expensive',
      },
      {
        id: 49,
        expression: 'Врачи проводят операцию',
        transcription: 'ðə ˈdɒktəz ɑː kənˈdʌktɪŋ ði ˌɒpəˈreɪʃən',
        translation: 'The doctors are conducting the operation',
      },
      {
        id: 50,
        expression: 'Я совершенно не согласен с этим сейчас',
        transcription: 'aɪ ˈtəʊtli ˌdɪsəˈgriː wɪð ɪt naʊ',
        translation: 'I totally disagree with it now',
      },
      {
        id: 51,
        expression: 'Идет сильный дождь',
        transcription: 'ɪts ˈreɪnɪŋ ˈhɛvɪli',
        translation: "It's raining heavily",
      },
      {
        id: 52,
        expression: 'Летом здесь часто идет дождь?',
        transcription: 'dʌz ɪt ˈɒf(ə)n reɪn hɪər ɪn ˈsʌmə?',
        translation: 'Does it often rain here in summer?',
      },
      {
        id: 53,
        expression: 'У нас будет очень важная встреча завтра',
        transcription: 'wɪə ˈhævɪŋ ə ˈvɛri ɪmˈpɔːtənt ˈmiːtɪŋ təˈmɒrəʊ',
        translation: "We're having a very important meeting tomorrow",
      },
      {
        id: 54,
        expression: 'Мы встречаемся завтра в шесть',
        transcription: 'wɪə ˈmiːtɪŋ təˈmɒrəʊ æt sɪks',
        translation: "We're meeting tomorrow at six",
      },
      {
        id: 55,
        expression: 'Я и мой коллега разговариваем по телефону',
        transcription: 'maɪ ˈkɒliːg ænd aɪ ɑː ˈtɔːkɪŋ ɒn ðə fəʊn',
        translation: 'My colleague and I are talking on the phone',
      },
      {
        id: 56,
        expression: 'Мы встречаемся после работы',
        transcription: 'wɪə ˈmiːtɪŋ ˈɑːftə wɜːk',
        translation: "We're meeting after work",
      },
      {
        id: 57,
        expression: 'Они болтают после работы',
        transcription: 'ðeɪ ʧæt ˈɑːftə wɜːk',
        translation: 'They chat after work',
      },
      {
        id: 58,
        expression: 'Я работаю над этим проектом сейчас',
        transcription: 'aɪm ˈwɜːkɪŋ ɒn ðɪs ˈprɒʤɛkt naʊ',
        translation: "I'm working on this project now",
      },
      {
        id: 59,
        expression: 'Сейчас идет дождь?',
        transcription: 'ɪz ɪt ˈreɪnɪŋ naʊ?',
        translation: 'Is it raining now?',
      },
      {
        id: 60,
        expression: 'Сейчас идет снег?',
        transcription: 'ɪz ɪt ˈsnəʊɪŋ naʊ?',
        translation: 'Is it snowing now?',
      },
      {
        id: 61,
        expression: 'Вчера в пять шел дождь?',
        transcription: 'wɒz ɪt ˈreɪnɪŋ ˈjɛstədeɪ æt faɪv?',
        translation: 'Was it raining yesterday at five?',
      },
      {
        id: 62,
        expression: 'Она постоянно жалуется на него [с раздражением]',
        transcription: 'ʃiːz ˈkɒnstəntli kəmˈpleɪnɪŋ əˈbaʊt hɪm',
        translation: "She's constantly complaining about him",
      },
      {
        id: 63,
        expression: 'Она жалуется на него в данный момент',
        transcription: 'ʃiːz kəmˈpleɪnɪŋ əˈbaʊt hɪm æt ðə ˈməʊmənt',
        translation: "She's complaining about him at the moment",
      },
      {
        id: 64,
        expression: 'Они постоянно ведут себя очень плохо [с раздражением]',
        transcription: 'ðeə ˈkɒnstəntli bɪˈheɪvɪŋ ˈvɛri ˈbædli',
        translation: "They're constantly behaving very badly",
      },
      {
        id: 65,
        expression: 'От чего зависит эта вещь?',
        transcription: 'wɒt dʌz ðɪs θɪŋ dɪˈpɛnd ɒn?',
        translation: 'What does this thing depend on?',
      },
      {
        id: 66,
        expression: 'От кого зависят эти вещи?',
        transcription: 'huː dʌz ðiːz θɪŋz dɪˈpɛnd ɒn?',
        translation: 'Who does these things depend on?',
      },
      {
        id: 67,
        expression: 'От чего зависит твое решение?',
        transcription: 'wɒt dʌz jɔː dɪˈsɪʒən dɪˈpɛnd ɒn?',
        translation: 'What does your decision depend on?',
      },
      {
        id: 68,
        expression: 'Эта вещь касается каждого из нас',
        transcription: 'ðɪs θɪŋ kənˈsɜːnz iːʧ ɒv ʌs',
        translation: 'This thing concerns each of us',
      },
      {
        id: 69,
        expression: 'Эти изменения касаются каждого из нас',
        transcription: 'ðiːz ˈʧeɪnʤɪz kənˈsɜːn iːʧ ɒv ʌs',
        translation: 'These changes concern each of us',
      },
      {
        id: 70,
        expression: 'Эти вещи не касаются никого из нас',
        transcription: 'ðiːz θɪŋz kənˈsɜːn nʌn ɒv ʌs',
        translation: 'These things concern none of us',
      },
      {
        id: 71,
        expression: 'Необходимо сделать это сегодня',
        transcription: 'ɪts ˈnɛsɪsəri tuː duː ɪt təˈdeɪ',
        translation: "It's necessary to do it today",
      },
      {
        id: 72,
        expression: 'Необходимо было сделать это вчера',
        transcription: 'ɪt wɒz ˈnɛsɪsəri tuː duː ɪt ˈjɛstədeɪ',
        translation: 'It was necessary to do it yesterday',
      },
      {
        id: 73,
        expression: 'Необходимо будет сделать это завтра',
        transcription: 'ˈɪtl biː ˈnɛsɪsəri tuː duː ɪt təˈmɒrəʊ',
        translation: "It'll be necessary to do it tomorrow",
      },
      {
        id: 74,
        expression: 'Я уезжаю из города завтра',
        transcription: 'aɪm ˈliːvɪŋ ðə ˈsɪti təˈmɒrəʊ',
        translation: "I'm leaving the city tomorrow",
      },
      {
        id: 75,
        expression: 'Я возвращаюсь в город завтра',
        transcription: 'aɪm ˈkʌmɪŋ bæk tuː ðə ˈsɪti təˈmɒrəʊ',
        translation: "I'm coming back to the city tomorrow",
      },
      {
        id: 76,
        expression: 'Я прибываю туда завтра в шесть',
        transcription: 'aɪm əˈraɪvɪŋ ðeə təˈmɒrəʊ æt sɪks',
        translation: "I'm arriving there tomorrow at six",
      },
      {
        id: 77,
        expression: 'Он идет к стоматологу завтра',
        transcription: 'hiːz ˈgəʊɪŋ tuː ðə ˈdɛntɪst təˈmɒrəʊ',
        translation: "He's going to the dentist tomorrow",
      },
      {
        id: 78,
        expression: 'Она идет в школу завтра',
        transcription: 'ʃiːz ˈgəʊɪŋ tuː skuːl təˈmɒrəʊ',
        translation: "She's going to school tomorrow",
      },
      {
        id: 79,
        expression: 'Он не идет туда завтра',
        transcription: 'hiː ˈɪznt ˈgəʊɪŋ ðeə təˈmɒrəʊ',
        translation: "He isn't going there tomorrow",
      },
      {
        id: 80,
        expression: 'Мы иногда встречаемся после работы',
        transcription: 'wiː ˈsʌmtaɪmz miːt ˈɑːftə wɜːk',
        translation: 'We sometimes meet after work',
      },
      {
        id: 81,
        expression: 'Мы обычно встречаемся перед работой',
        transcription: 'wiː ˈjuːʒʊəli miːt bɪˈfɔː wɜːk',
        translation: 'We usually meet before work',
      },
      {
        id: 82,
        expression: 'Они всегда встречают его после работы',
        transcription: 'ðeɪ ˈɔːlweɪz miːt hɪm ˈɑːftə wɜːk',
        translation: 'They always meet him after work',
      },
      {
        id: 83,
        expression: 'Это касается каждого из нас сейчас',
        transcription: 'ɪt kənˈsɜːnz iːʧ ɒv ʌs naʊ',
        translation: 'It concerns each of us now',
      },
      {
        id: 84,
        expression: 'Это касается всех нас сейчас',
        transcription: 'ɪt kənˈsɜːnz ɔːl ɒv ʌs naʊ',
        translation: 'It concerns all of us now',
      },
      {
        id: 85,
        expression: 'Это касалось каждого из них',
        transcription: 'ɪt kənˈsɜːnd iːʧ ɒv ðɛm',
        translation: 'It concerned each of them',
      },
      {
        id: 86,
        expression:
          'Почему она всегда перебивает других людей? [с раздражением]',
        transcription: 'waɪ ɪz ʃiː ˈɔːlweɪz ˌɪntəˈrʌptɪŋ ˈʌðə ˈpiːpl?',
        translation: 'Why is she always interrupting other people?',
      },
      {
        id: 87,
        expression: 'Почему они обычно говорят об этом?',
        transcription: 'waɪ duː ðeɪ ˈjuːʒʊəli tɔːk əˈbaʊt ɪt?',
        translation: 'Why do they usually talk about it?',
      },
      {
        id: 88,
        expression: 'Я лечу в Соединенные Штаты на следующей неделе',
        transcription: 'aɪm ˈflaɪɪŋ tuː ðə jʊˈnaɪtɪd steɪts nɛkst wiːk',
        translation: "I'm flying to the United States next week",
      },
      {
        id: 89,
        expression: 'Такая важная вещь касается каждого из нас',
        transcription: 'sʌʧ ən ɪmˈpɔːtənt θɪŋ kənˈsɜːnz iːʧ ɒv ʌs',
        translation: 'Such an important thing concerns each of us',
      },
      {
        id: 90,
        expression: 'Она часто кричит на него без причины',
        transcription: 'ʃiː ˈɒf(ə)n ʃaʊts æt hɪm fɔː nəʊ ˈriːzn',
        translation: 'She often shouts at him for no reason',
      },
      {
        id: 91,
        expression: 'Я работаю над очень важным проектом в настоящее время',
        transcription: 'aɪm ˈwɜːkɪŋ ɒn ə ˈvɛri ɪmˈpɔːtənt ˈprɒʤɛkt æt ˈprɛznt',
        translation: "I'm working on a very important project at present",
      },
      {
        id: 92,
        expression: 'Это очень легко сказать, но это не так легко сделать',
        transcription:
          'ɪts ˈvɛri ˈiːzi tuː seɪ səʊ bʌt ɪt ˈɪznt səʊ ˈiːzi tuː duː ɪt',
        translation: "It's very easy to say so but it isn't so easy to do it",
      },
      {
        id: 93,
        expression: 'От чего это зависит сейчас?',
        transcription: 'wɒt dʌz ɪt dɪˈpɛnd ɒn naʊ?',
        translation: 'What does it depend on now?',
      },
      {
        id: 94,
        expression: 'Почему он всегда жалуется?',
        transcription: 'waɪ ɪz hiː ˈɔːlweɪz kəmˈpleɪnɪŋ?',
        translation: 'Why is he always complaining?',
      },
      {
        id: 95,
        expression: 'Летом здесь часто идут дожди',
        transcription: 'ɪt ˈɒf(ə)n reɪnz hɪər ɪn ˈsʌmə',
        translation: 'It often rains here in summer',
      },
      {
        id: 96,
        expression: 'Они прибывают в Нью-Йорк сегодня вечером',
        transcription: 'ðeər əˈraɪvɪŋ ɪn njuː jɔːk təˈnaɪt',
        translation: "They're arriving in New York tonight",
      },
      {
        id: 97,
        expression: 'Я ухожу в четыре',
        transcription: 'aɪm ˈliːvɪŋ æt fɔː',
        translation: "I'm leaving at four",
      },
      {
        id: 98,
        expression: 'Идет сильный снег',
        transcription: 'ɪts ˈsnəʊɪŋ ˈhɛvɪli',
        translation: "It's snowing heavily",
      },
      {
        id: 99,
        expression: 'Такая возможность существует',
        transcription: 'sʌʧ ə ˌpɒsəˈbɪlɪti ɪgˈzɪsts',
        translation: 'Such a possibility exists',
      },
      {
        id: 100,
        expression: 'Она всегда кричит на него [с раздражением]',
        transcription: 'ʃiːz ˈɔːlweɪz ˈʃaʊtɪŋ æt hɪm',
        translation: "She's always shouting at him",
      },
    ],
    {
      theory: `<div class="theory-block">
<h3>Закрепление пройденного материала</h3>
<p>Present Simple обычно употребляется для описания действий, которые происходят постоянно. Однако в таких случаях можно использовать и Present Continious, но тогда нужно иметь в виду, что этим самым можно передать раздражение систематически повторяющимся действием другого человека: </p>
<p>Why is he always complaining about something? - Почему он всегда на что-то жалуется?</p>
</div>`,
    },
  ],
];
