export const contentLesson80 = [
  [
    {
      title: "Урок 80. Future Simple. Special Question",
    },
    [
      {
        id: 1,
        expression: "Что ты увидишь там?",
        transcription: "wɒt wɪl jʊ siː ðeə?",
        translation: "What will you see there?",
      },
      {
        id: 2,
        expression: "Когда ты подтвердишь нашу встречу?",
        transcription: "wɛn wɪl jʊ kənˈfɜːm ˈaʊə ˈmiːtɪŋ?",
        translation: "When will you confirm our meeting?",
      },
      {
        id: 3,
        expression: "Почему он будет чувствовать себя там так неудобно?",
        transcription: "waɪ wɪl hi fiːl səʊ ʌnˈkʌmfətəbl ðeə?",
        translation: "Why will he feel so uncomfortable there?",
      },
      {
        id: 4,
        expression: "Когда мы встретимся в аэропорту?",
        transcription: "wɛn wɪl wi miːt ət ði ˈeəpɔːt?",
        translation: "When will we meet at the airport?",
      },
      {
        id: 5,
        expression: "Сколько продлится один урок английского?",
        transcription: "haʊ lɒŋ wɪl wʌn ˈɪŋglɪʃ ˈlɛsn lɑːst?",
        translation: "How long will one English lesson last?",
      },
      {
        id: 6,
        expression: "Когда начнется встреча?",
        transcription: "wɛn wɪl ðə ˈmiːtɪŋ bɪˈgɪn?",
        translation: "When will the meeting begin?",
      },
      {
        id: 7,
        expression: "Когда она выйдет за него замуж?",
        transcription: "wɛn wɪl ʃi ˈmæri hɪm?",
        translation: "When will she marry him?",
      },
      {
        id: 8,
        expression: "Почему ты будешь чувствовать себя там очень неудобно?",
        transcription: "waɪ wɪl jʊ fiːl ˈvɛri ʌnˈkʌmfətəbl ðeə?",
        translation: "Why will you feel very uncomfortable there?",
      },
      {
        id: 9,
        expression: "Почему это случится с ними?",
        transcription: "waɪ wɪl ɪt ˈhæpən tə ðɛm?",
        translation: "Whe will it happen to them?",
      },
      {
        id: 10,
        expression: "Где мы встретимся с ним?",
        transcription: "weə wɪl wi miːt wɪð hɪm?",
        translation: "Where will we meet with him?",
      },
      {
        id: 11,
        expression: "Когда она вернется?",
        transcription: "wɛn wɪl ʃi rɪˈtɜːn (kʌm bæk)?",
        translation: "When will she return (come back)?",
      },
      {
        id: 12,
        expression: "Какой у тебя будет новый номер телефона?",
        transcription: "wɒt wɪl jə njuː fəʊn ˈnʌmbə biː?",
        translation: "What will your new phone number be?",
      },
      {
        id: 13,
        expression: "Когда начнутся экзамены?",
        transcription: "wɛn wɪl ði ɪgˈzæmz bɪˈgɪn (stɑːt)?",
        translation: "When will the exams begin (start)?",
      },
      {
        id: 14,
        expression: "Где он будет завтра?",
        transcription: "weə wɪl hi bi təˈmɒrəʊ?",
        translation: "Where will he be tomorrow?",
      },
      {
        id: 15,
        expression: "Когда ты придешь на работу?",
        transcription: "wɛn wɪl jʊ kʌm tə wɜːk?",
        translation: "When will you come to work?",
      },
      {
        id: 16,
        expression: "Когда ты уйдешь из дома?",
        transcription: "wɛn wɪl jʊ liːv həʊm (gəʊ aʊt)?",
        translation: "When will you leave home (go out)?",
      },
      {
        id: 17,
        expression: "Когда ты увидишь его в следующий раз?",
        transcription: "wɛn wɪl jʊ siː ɪm nɛkst taɪm?",
        translation: "When will you see him next time?",
      },
      {
        id: 18,
        expression: "Когда начнется конференция?",
        transcription: "wɛn wɪl ðə ˈkɒnfərəns stɑːt?",
        translation: "When will the conference start?",
      },
      {
        id: 19,
        expression: "Что ты там увидишь?",
        transcription: "wɒt wɪl jʊ siː ðeə?",
        translation: "What will you see there?",
      },
      {
        id: 20,
        expression: "Почему они будут жить отдельно?",
        transcription: "waɪ wɪl ðeɪ lɪv ˈsɛprɪtli?",
        translation: "Why will they live separately?",
      },
      {
        id: 21,
        expression: "Когда ты подтвердишь нашу встречу?",
        transcription: "wɛn wɪl jʊ kənˈfɜːm ˈaʊə ˈmiːtɪŋ?",
        translation: "When will you confirm our meeting?",
      },
      {
        id: 22,
        expression: "Как ты будешь работать в этих условиях?",
        transcription: "haʊ wɪl jʊ wɜːk ɪn ðiːz kənˈdɪʃənz?",
        translation: "How will you work in these conditions?",
      },
      {
        id: 23,
        expression: "Когда начнется экзамен?",
        transcription: "wɛn wɪl ði ɪgˈzæm stɑːt?",
        translation: "When will the exam start?",
      },
      {
        id: 24,
        expression: "Когда вы поженитесь?",
        transcription: "wɛn wɪl jʊ gɛt ˈmærɪd?",
        translation: "When will you get married?",
      },
      {
        id: 25,
        expression: "Когда он окончит школу?",
        transcription: "wɛn wɪl hi ˈfɪnɪʃ skuːl?",
        translation: "When will he finish school?",
      },
      {
        id: 26,
        expression: "Как долго это будет?",
        transcription: "haʊ lɒŋ wɪl ɪt biː?",
        translation: "How long will it be?",
      },
      {
        id: 27,
        expression: "Какие города ты посетишь?",
        transcription: "wɒt ˈsɪtiz wɪl jʊ ˈvɪzɪt?",
        translation: "What cities will you visit?",
      },
      {
        id: 28,
        expression: "Куда ты пойдешь?",
        transcription: "weə wɪl jʊ gəʊ?",
        translation: "Where will you go?",
      },
      {
        id: 29,
        expression: "Как долго ты там будешь?",
        transcription: "haʊ lɒŋ wɪl jʊ bi ðeə?",
        translation: "How long will you be there?",
      },
      {
        id: 30,
        expression: "Как ты будешь проводить свое свободное время?",
        transcription: "haʊ wɪl jʊ spɛnd jə friː taɪm?",
        translation: "How will you spend your free time?",
      },
      {
        id: 31,
        expression: "Как часто ты будешь пользоваться этим приложением?",
        transcription: "haʊ ˈɒf(ə)n wɪl jʊ juːz ðɪs ˌæplɪˈkeɪʃ(ə)n?",
        translation: "How often will you use this application?",
      },
      {
        id: 32,
        expression: "Что ты будешь делать в этой ситуации?",
        transcription: "wɒt wɪl jʊ dʊ ɪn ðɪs ˌsɪtjʊˈeɪʃən?",
        translation: "What will you do in this situation?",
      },
      {
        id: 33,
        expression: "Что ты скажешь своим родителям?",
        transcription: "wɒt wɪl jʊ tɛl jə ˈpeərənts?",
        translation: "What will you tell your parents?",
      },
      {
        id: 34,
        expression: "Сколько денег будет достаточно?",
        transcription: "haʊ mʌʧ ˈmʌni wɪl bi ɪˈnʌf?",
        translation: "How much money will be enough?",
      },
      {
        id: 35,
        expression: "Что ты будешь делать в этом случае?",
        transcription: "wɒt wɪl jʊ dʊ ɪn ðɪs keɪs?",
        translation: "What will you do in this case?",
      },
      {
        id: 36,
        expression: "Кто тебя там увидит?",
        transcription: "huː wɪl jʊ siː ðeə?",
        translation: "Who will you see there?",
      },
      {
        id: 37,
        expression: "Когда ты пойдешь спать?",
        transcription: "wɛn wɪl jʊ gəʊ tə bɛd?",
        translation: "When will you go to bed?",
      },
      {
        id: 38,
        expression: "Во сколько ты мне позвонишь?",
        transcription: "wɒt taɪm wɪl jʊ kɔːl miː?",
        translation: "What time will you call me?",
      },
      {
        id: 39,
        expression: "Сколько ты за это заплатишь?",
        transcription: "haʊ mʌʧ wɪl jʊ peɪ fər ɪt?",
        translation: "How much will you pay for it?",
      },
      {
        id: 40,
        expression: "Какой у него будет новый адрес?",
        transcription: "wɒt wɪl ɪz njuː əˈdrɛs biː?",
        translation: "What will his new address be?",
      },
      {
        id: 41,
        expression: "Во сколько ты завтра встанешь?",
        transcription: "wɒt taɪm wɪl jʊ gɛt ʌp təˈmɒrəʊ?",
        translation: "What time will you get up tomorrow?",
      },
      {
        id: 42,
        expression: "Когда он женится на ней?",
        transcription: "wɛn wɪl hi ˈmæri hɜː?",
        translation: "When will he marry her?",
      },
      {
        id: 43,
        expression: "Сколько будет стоить учиться в Соединенных Штатах?",
        transcription: "haʊ mʌʧ wɪl ɪt kɒst tə ˈstʌdi ɪn ðə jʊˈnaɪtɪd steɪts?",
        translation: "How much will it cost to study in the United States?",
      },
      {
        id: 44,
        expression: "Почему это будет лучшим решением этой проблемы?",
        transcription: "waɪ wɪl ɪt bi ðə bɛst səˈluːʃən tə ðɪs ˈprɒbləm?",
        translation: "Why will it be the best solution to this problem?",
      },
      {
        id: 45,
        expression: "Сколько будет стоить арендовать такого рода машину?",
        transcription: "haʊ mʌʧ wɪl ɪt bi tə rɛnt ðɪs kaɪnd əv kɑː?",
        translation: "How much will it be to rent this kind of car?",
      },
      {
        id: 46,
        expression:
          "Какие упражнения ты будешь делать, чтобы увеличить свой словарный запас?",
        transcription:
          "wɒt ˈɛksəsaɪzɪz wɪl jʊ dʊ tʊ ˈɪnkriːs jə vəʊˈkæbjʊləri?",
        translation: "What exercises will you do to increase your vocabulary?",
      },
      {
        id: 47,
        expression: "Почему это будет совершенно пустая трата времени?",
        transcription: "waɪ wɪl ɪt bi ə kəmˈpliːt weɪst əv taɪm?",
        translation: "Why will it be a complete waste of time?",
      },
      {
        id: 48,
        expression: "Кого ты пригласишь на свой день рождения?",
        transcription: "huː wɪl jʊ ɪnˈvaɪt tə jə ˈbɜːθdeɪ ˈpɑːti?",
        translation: "Who will you invite to your birthday party?",
      },
      {
        id: 49,
        expression: "Где я смогу купить это?",
        transcription: "weə wɪl aɪ bi ˈeɪbl tə baɪ ɪt?",
        translation: "Where will I be able to buy it?",
      },
      {
        id: 50,
        expression: "Сколько будет стоить арендовать эту квартиру?",
        transcription: "haʊ mʌʧ wɪl ɪt bi tə rɛnt ðɪs əˈpɑːtmənt?",
        translation: "How much will it be to rent this apartment?",
      },
      {
        id: 51,
        expression: "Когда это будет возможно сделать?",
        transcription: "wɛn wɪl ɪt bi ˈpɒsəbl tə dʊ ɪt?",
        translation: "When will it be possible to do it?",
      },
      {
        id: 52,
        expression: "Когда он разведется?",
        transcription: "wɛn wɪl hi gɛt dɪˈvɔːst?",
        translation: "When will he get divorced?",
      },
      {
        id: 53,
        expression: "Сколько ты заплатишь за новую квартиру?",
        transcription: "haʊ mʌʧ wɪl jʊ peɪ fər ə njuː əˈpɑːtmənt?",
        translation: "How much will you pay for a new apartment?",
      },
      {
        id: 54,
        expression:
          "Какие упражнения ты будешь делать, чтобы улучшить свой английский?",
        transcription: "wɒt ˈɛksəsaɪzɪz wɪl jʊ dʊ tʊ ɪmˈpruːv jər ˈɪŋglɪʃ?",
        translation: "What exercises will you do to improve your English?",
      },
      {
        id: 55,
        expression: "Насколько полезным будет урок?",
        transcription: "haʊ ˈjuːsfʊl wɪl ðə ˈlɛsn biː?",
        translation: "How useful will the lesson be?",
      },
      {
        id: 56,
        expression: "Сколько будет стоить арендовать дом?",
        transcription: "haʊ mʌʧ wɪl ɪt kɒst tə rɛnt ə haʊs?",
        translation: "How much will it cost to rent a house?",
      },
      {
        id: 57,
        expression: "Сколько денег мне нужно будет взять с собой?",
        transcription: "haʊ mʌʧ ˈmʌni wɪl aɪ niːd tə teɪk wɪð miː?",
        translation: "How much money will I need to take with me?",
      },
      {
        id: 58,
        expression: "Что ты будешь делать, чтобы улучшить свое произношение?",
        transcription: "wɒt wɪl jʊ dʊ tʊ ɪmˈpruːv jə prəˌnʌnsɪˈeɪʃən?",
        translation: "What will you do to improve your pronunciation?",
      },
      {
        id: 59,
        expression: "Что ты будешь делать, чтобы улучшить свою речь?",
        transcription: "wɒt wɪl jʊ dʊ tʊ ɪmˈpruːv jə ˈspiːkɪŋ?",
        translation: "What will you do to improve your speaking?",
      },
      {
        id: 60,
        expression: "Когда она улучшит свое произношение?",
        transcription: "wɛn wɪl ʃi ɪmˈpruːv hə prəˌnʌnsɪˈeɪʃən?",
        translation: "When will she improve her pronunciation?",
      },
      {
        id: 61,
        expression: "Когда закончится урок?",
        transcription: "wɛn wɪl ðə ˈlɛsn ˈfɪnɪʃ?",
        translation: "When will the lesson finish?",
      },
      {
        id: 62,
        expression: "Когда эти уроки закончатся?",
        transcription: "wɛn wɪl ðiːz ˈlɛsnz ˈfɪnɪʃ?",
        translation: "When will these lessons finish?",
      },
      {
        id: 63,
        expression: "Когда начнется урок?",
        transcription: "wɛn wɪl ðə ˈlɛsn bɪˈgɪn?",
        translation: "When will the lesson begin?",
      },
      {
        id: 64,
        expression: "Как ты сможешь это сделать?",
        transcription: "haʊ wɪl jʊ bi ˈeɪbl tə dʊ ɪt?",
        translation: "How will you be able to do it?",
      },
      {
        id: 65,
        expression: "Как она сможет это сделать?",
        transcription: "haʊ wɪl ʃi bi ˈeɪbl tə dʊ ɪt?",
        translation: "How will she be able to do it?",
      },
      {
        id: 66,
        expression: "Когда они смогут это сделать?",
        transcription: "wɛn wɪl ðeɪ bi ˈeɪbl tə dʊ ɪt?",
        translation: "When will they be able to do it?",
      },
      {
        id: 67,
        expression: "Насколько эффективным будет курс?",
        transcription: "haʊ ɪˈfɛktɪv wɪl ðə kɔːs biː?",
        translation: "How effective will the course be?",
      },
      {
        id: 68,
        expression: "Насколько эффективными будут курсы?",
        transcription: "haʊ ɪˈfɛktɪv wɪl ðə ˈkɔːsɪz biː?",
        translation: "How effective will the courses be?",
      },
      {
        id: 69,
        expression: "Насколько эффективным будет тот курс?",
        transcription: "haʊ ɪˈfɛktɪv wɪl ðət kɔːs biː?",
        translation: "How effective will that course be?",
      },
      {
        id: 70,
        expression: "Сколько будет стоить учиться за границей?",
        transcription: "haʊ mʌʧ wɪl ɪt kɒst tə ˈstʌdi əˈbrɔːd?",
        translation: "How much will it cost to study abroad?",
      },
      {
        id: 71,
        expression: "Сколько будет стоить поехать за границу?",
        transcription: "haʊ mʌʧ wɪl ɪt kɒst tə gəʊ əˈbrɔːd?",
        translation: "How much will it cost to go abroad?",
      },
      {
        id: 72,
        expression: "Когда он подтвердит время нашей встречи?",
        transcription: "wɛn wɪl hi kənˈfɜːm ðə taɪm əv ˈaʊə ˈmiːtɪŋ?",
        translation: "When will he confirm the time of our meeting?",
      },
      {
        id: 73,
        expression: "Когда они подтвердят время этой встречи?",
        transcription: "wɛn wɪl ðeɪ kənˈfɜːm ðə taɪm əv ðɪs ˈmiːtɪŋ?",
        translation: "When will they confirm the time of this meeting?",
      },
      {
        id: 74,
        expression: "Когда она подтвердит нашу встречу?",
        transcription: "wɛn wɪl ʃi kənˈfɜːm ˈaʊə ˈmiːtɪŋ?",
        translation: "When will she confirm our meeting?",
      },
      {
        id: 75,
        expression: "Насколько интересной будет книга?",
        transcription: "haʊ ˈɪntrɪstɪŋ wɪl ðə bʊk biː?",
        translation: "How interesting will the book be?",
      },
      {
        id: 76,
        expression: "Насколько дорогой будет эта книга?",
        transcription: "haʊ ɪksˈpɛnsɪv wɪl ðɪs bʊk biː?",
        translation: "How expensive will this book be?",
      },
      {
        id: 77,
        expression: "Насколько интересным будет фильм?",
        transcription: "haʊ ˈɪntrɪstɪŋ wɪl ðə ˈmuːvi biː?",
        translation: "How interesting will the movie be?",
      },
      {
        id: 78,
        expression: "Что будет необходимо исправить?",
        transcription: "wɒt wɪl bi ˈnɛsɪsəri tə kəˈrɛkt?",
        translation: "What will be necessary to correct?",
      },
      {
        id: 79,
        expression: "Что будет необходимо изменить?",
        transcription: "wɒt wɪl bi ˈnɛsɪsəri tə ʧeɪnʤ?",
        translation: "What will be necessary to change?",
      },
      {
        id: 80,
        expression: "Что будет необходимо улучшить?",
        transcription: "wɒt wɪl bi ˈnɛsɪsəri tʊ ɪmˈpruːv?",
        translation: "What will be necessary to improve?",
      },
      {
        id: 81,
        expression: "Какого рода книги ты будешь читать?",
        transcription: "wɒt kaɪnd əv bʊks wɪl jʊ riːd?",
        translation: "What kind of books will you read?",
      },
      {
        id: 82,
        expression: "Какого рода книги ты будешь покупать?",
        transcription: "wɒt kaɪnd əv bʊks wɪl jʊ baɪ?",
        translation: "What kind of books will you buy?",
      },
      {
        id: 83,
        expression: "Какую книгу ты будешь читать?",
        transcription: "wɒt bʊk wɪl jʊ riːd?",
        translation: "What book will you read?",
      },
      {
        id: 84,
        expression: "Во сколько закончатся занятия?",
        transcription: "wɒt taɪm wɪl ðə ˈklɑːsɪz ɛnd?",
        translation: "What time will the classes end?",
      },
      {
        id: 85,
        expression: "Когда закончатся занятия?",
        transcription: "wɛn wɪl ðə ˈklɑːsɪz ɛnd?",
        translation: "When will the classes end?",
      },
      {
        id: 86,
        expression: "Во сколько начнется урок?",
        transcription: "wɒt taɪm wɪl ðə klɑːs stɑːt?",
        translation: "What time will the class start?",
      },
      {
        id: 87,
        expression: "Когда ты окончишь этот университет?",
        transcription: "wɛn wɪl jʊ ˈgrædjʊət frəm ðɪs ˌjuːnɪˈvɜːsɪti?",
        translation: "When will you graduate from this university?",
      },
      {
        id: 88,
        expression: "Сколько будет стоить жить в Соединенном Королевстве?",
        transcription: "haʊ mʌʧ wɪl ɪt kɒst tə lɪv ɪn ðə jʊˈnaɪtɪd ˈkɪŋdəm?",
        translation: "How much will it cost to live in the United Kingdom?",
      },
      {
        id: 89,
        expression: "Кто сможет сделать это?",
        transcription: "huː wɪl bi ˈeɪbl tə dʊ ɪt?",
        translation: "Who will be able to do it?",
      },
      {
        id: 90,
        expression: "Сколько денег мне нужно будет потратить на это?",
        transcription: "haʊ mʌʧ ˈmʌni wɪl aɪ niːd tə spɛnd ɒn ɪt?",
        translation: "How much money will I need to spend on it?",
      },
      {
        id: 91,
        expression: "Сколько гостей придут на вечеринку?",
        transcription: "haʊ ˈmɛni gɛsts wɪl kʌm tə ðə ˈpɑːti?",
        translation: "How many guests will come to the party?",
      },
      {
        id: 92,
        expression: "Сколько он заплатит за новый дом?",
        transcription: "haʊ mʌʧ wɪl hi peɪ fər ə njuː haʊs?",
        translation: "How much will he pay for a new house?",
      },
      {
        id: 93,
        expression: "Сколько будет стоить жить в этом городе?",
        transcription: "haʊ mʌʧ wɪl ɪt kɒst tə lɪv ɪn ðɪs ˈsɪti?",
        translation: "How much will it cost to live in this city?",
      },
      {
        id: 94,
        expression: "Во сколько закончится фильм?",
        transcription: "wɒt taɪm wɪl ðə ˈmuːvi ˈfɪnɪʃ?",
        translation: "What time will the movie finish?",
      },
      {
        id: 95,
        expression: "Какого рода фильмы ты будешь смотреть?",
        transcription: "wɒt kaɪnd əv ˈmuːviz wɪl jʊ wɒʧ?",
        translation: "What kind of movies will you watch?",
      },
      {
        id: 96,
        expression: "Когда ты подтвердишь дату нашей встречи?",
        transcription: "wɛn wɪl jʊ kənˈfɜːm ðə deɪt əv ˈaʊə ˈmiːtɪŋ?",
        translation: "When will you confirm the date of our meeting?",
      },
      {
        id: 97,
        expression: "Сколько будет стоить арендовать этот автомобиль?",
        transcription: "haʊ mʌʧ wɪl ɪt kɒst tə rɛnt ðɪs kɑː?",
        translation: "How much will it cost to rent this car?",
      },
      {
        id: 98,
        expression: "Что будет необходимо сделать?",
        transcription: "wɒt wɪl bi ˈnɛsɪsəri tə duː?",
        translation: "What will be necessary to do?",
      },
      {
        id: 99,
        expression: "Во сколько закончится занятие?",
        transcription: "wɒt taɪm wɪl ðə klɑːs ɛnd?",
        translation: "What time will the class end?",
      },
      {
        id: 100,
        expression: "Почему они разведутся?",
        transcription: "waɪ wɪl ðeɪ gɛt dɪˈvɔːst?",
        translation: "Why will they get divorced?",
      },
    ],
    {
      theory: `<div class="theory-block">
<h3>Закрепление пройденного материала</h3>
</div>`,
    },
  ],
];
